ministryofjustice/c100-application

- lib/generators/step/templates/controller.rb
- lib/generators/step/templates/controller_spec.rb
- lib/generators/step/templates/edit.html.erb
- lib/generators/step/templates/form.rb
- lib/generators/step/templates/form_spec.rb
- lib/generators/task/USAGE
- lib/generators/task/task_generator.rb
- lib/generators/task/templates/controller.rb
- lib/generators/task/templates/decision_tree.rb
Some changes needed to play nice with Rubocop and mutant.
> Update task and step generators

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/app.scss
- app/assets/stylesheets/local/forms.scss
- app/controllers/miam_controller.rb
- app/views/entrypoint/shared/_start_application.html.erb
- app/views/entrypoint/v1.en.html.erb
- app/views/entrypoint/v2.en.html.erb
- app/views/entrypoint/v3.en.html.erb
- app/views/miam/index.en.html.erb
- app/views/steps/shared/_start_application.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/miam_controller_spec.rb
This acts as a second start page after the entrypoint pages and it is
still not a step page as will be informative only too.
Will be after this page the application will efectively start.
Content as per current prototype, to have something to play with, but
will definetely change in the future.
> Add MIAM Acknowledgement page

- app/assets/stylesheets/local/forms.scss
- app/controllers/steps/applicant/user_type_controller.rb
- app/controllers/steps/applicant_step_controller.rb
- app/forms/steps/applicant/user_type_form.rb
- app/services/base_decision_tree.rb
- app/services/c100_app/applicant_decision_tree.rb
- app/services/c100_app/case_type_decision_tree.rb
- app/value_objects/user_type.rb
- app/views/miam/index.en.html.erb
- app/views/steps/applicant/user_type/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171030142134_add_user_type.rb
- db/schema.rb
- lib/generators/step/templates/form_spec.rb
- lib/generators/task/task_generator.rb
- lib/generators/task/templates/decision_tree_spec.rb
- spec/controllers/steps/applicant/user_type_controller_spec.rb
- spec/controllers/steps/nature_of_application/case_type_controller_spec.rb
- spec/forms/steps/applicant/user_type_form_spec.rb
- spec/services/c100_app/applicant_decision_tree_spec.rb
- spec/services/c100_app/case_type_decision_tree_spec.rb
- spec/support/decision_tree_shared_examples.rb
- spec/support/step_controller_shared_examples.rb
This will create the top level Applicant task, and the first step of
this task, User Type.
Some improvements to the generators to make life a bit easier.
> Create Applicant task with User Type step

- .env.test.example
- README.md
- app/controllers/steps/help_with_fees/help_paying_controller.rb
- app/controllers/steps/help_with_fees_step_controller.rb
- app/forms/steps/help_with_fees/help_paying_form.rb
- app/models/c100_application.rb
- app/services/c100_app/help_with_fees_decision_tree.rb
- app/value_objects/help_paying.rb
- app/views/steps/help_with_fees/help_paying/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171031122708_add_help_paying.rb
- db/schema.rb
- lib/generators/step/templates/form_spec.rb
- lib/generators/task/templates/decision_tree_spec.rb
- spec/controllers/steps/help_with_fees/help_paying_controller_spec.rb
- spec/forms/steps/help_with_fees/help_paying_form_spec.rb
- spec/services/c100_app/help_with_fees_decision_tree_spec.rb
- spec/support/form_validation_shared_examples.rb
Also some amendments to the generators, and updated README.
> Create HelpWithFees task with first step

- app/controllers/steps/help_with_fees/help_paying_controller.rb
- app/forms/steps/help_with_fees/help_paying_form.rb
- app/value_objects/help_paying.rb
- app/views/steps/help_with_fees/help_paying/edit.html.erb
- config/locales/en.yml
- db/migrate/20171031165425_add_hwf_reference_number.rb
- db/schema.rb
- lib/generators/step/templates/form_spec.rb
- spec/forms/steps/help_with_fees/help_paying_form_spec.rb
- spec/services/c100_app/help_with_fees_decision_tree_spec.rb
NOTE: the show/hide is not working yet.
> Update `Help with fees` step to match prototype

- app/controllers/steps/children/personal_details_controller.rb
- app/controllers/steps/children_step_controller.rb
- app/forms/steps/children/personal_details_form.rb
- app/models/c100_application.rb
- app/models/child.rb
- app/services/c100_app/children_decision_tree.rb
- app/views/steps/children/personal_details/_child_row.html.erb
- app/views/steps/children/personal_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171107123012_create_children_table.rb
- db/schema.rb
- spec/controllers/steps/children/personal_details_controller_spec.rb
- spec/forms/steps/children/personal_details_form_spec.rb
- spec/services/c100_app/children_decision_tree_spec.rb
Very similar (fewer attributes) to applicants and respondents.
DRY'ed a bit i18n.
> Children personal details step

- app/services/base_decision_tree.rb
- app/services/c100_app/applicant_decision_tree.rb
- app/services/c100_app/children_decision_tree.rb
- app/services/c100_app/help_with_fees_decision_tree.rb
- app/services/c100_app/respondent_decision_tree.rb
- config/locales/en.yml
- spec/services/c100_app/applicant_decision_tree_spec.rb
- spec/services/c100_app/children_decision_tree_spec.rb
- spec/services/c100_app/help_with_fees_decision_tree_spec.rb
- spec/services/c100_app/respondent_decision_tree_spec.rb
It will create a loop so all steps can be hit and tested.
Some steps are not in the order they should as there are still some
intermediate steps missing.
> Link all currently working steps together

- Gemfile.lock
- app/views/steps/applicant/personal_details/edit.html.erb
- app/views/steps/children/additional_details/edit.html.erb
- app/views/steps/help_with_fees/help_paying/edit.html.erb
- app/views/steps/respondent/personal_details/edit.html.erb
Update the views to use the updated code to reveal linked panels.
> Update revealing panels in all steps

- app/controllers/steps/abuse_concerns/base_abuse_step_controller.rb
- app/controllers/steps/abuse_concerns/details_controller.rb
- app/forms/steps/abuse_concerns/base_abuse_form.rb
- app/forms/steps/abuse_concerns/details_form.rb
- app/forms/steps/abuse_concerns/question_form.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/views/steps/abuse_concerns/details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/steps/abuse_concerns/details_controller_spec.rb
- spec/forms/steps/abuse_concerns/details_form_spec.rb
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
Now each question, when asked `yes` will follow up with a details step. If asked `no` it will just jump to the next question.
> Implement the abuse details step

- app/controllers/steps/court_orders/has_orders_controller.rb
- app/controllers/steps/court_orders_step_controller.rb
- app/forms/steps/court_orders/has_orders_form.rb
- app/models/c100_application.rb
- app/models/court_order.rb
- app/services/c100_app/court_orders_decision_tree.rb
- app/views/steps/court_orders/has_orders/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171115142813_add_has_court_orders_field.rb
- db/migrate/20171115143551_create_court_orders_table.rb
- db/schema.rb
- lib/generators/step/templates/edit/edit.html.erb
- lib/generators/step/templates/edit/form_spec.rb
- lib/generators/task/templates/decision_tree_spec.rb
- spec/controllers/steps/court_orders/has_orders_controller_spec.rb
- spec/forms/steps/court_orders/has_orders_form_spec.rb
- spec/services/c100_app/court_orders_decision_tree_spec.rb
Simple yes/no question step, with follow-up PR implementing the more
complicated orders form.
> Add court orders task and question step

- app/attributes/yes_no.rb
- app/controllers/steps/court_orders/details_controller.rb
- app/forms/steps/court_orders/details_form.rb
- app/models/c100_application.rb
- app/models/court_order.rb
- app/services/c100_app/court_orders_decision_tree.rb
- app/value_objects/generic_yes_no.rb
- app/views/steps/court_orders/details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/steps/court_orders/details_controller_spec.rb
- spec/forms/steps/court_orders/details_form_spec.rb
- spec/services/c100_app/court_orders_decision_tree_spec.rb
- spec/support/step_controller_shared_examples.rb
- spec/value_objects/generic_yes_no_spec.rb
Follow-up to the previous PR.
This decision tree is still not connected to the others, but can be tested going directly to:
http://localhost:3000/steps/court_orders/has_orders
> Court orders details step

- app/controllers/steps/abuse_concerns/contact_controller.rb
- app/forms/steps/abuse_concerns/contact_form.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/services/c100_app/court_orders_decision_tree.rb
- app/value_objects/concerns_contact_type.rb
- app/views/steps/abuse_concerns/contact/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171117152425_add_concerns_contact_fields.rb
- db/schema.rb
- spec/controllers/steps/abuse_concerns/contact_controller_spec.rb
- spec/forms/steps/abuse_concerns/contact_form_spec.rb
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
- spec/services/c100_app/court_orders_decision_tree_spec.rb
New step with controller, view and associated form objects.
Updated decision trees.
> Concerns contact type step

- app/controllers/steps/abuse_concerns/previous_proceedings_controller.rb
- app/forms/steps/abuse_concerns/previous_proceedings_form.rb
- app/models/c100_application.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/views/steps/abuse_concerns/previous_proceedings/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171120101456_add_children_previous_proceedings_field.rb
- db/schema.rb
- spec/controllers/steps/abuse_concerns/previous_proceedings_controller_spec.rb
- spec/forms/steps/abuse_concerns/previous_proceedings_form_spec.rb
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
Belongs to the task `abuse concerns`. Updated decision tree.
> Add `Previous proceedings` step

- app/controllers/steps/abuse_concerns/base_abuse_step_controller.rb
- app/controllers/steps/safety_questions/substance_abuse_controller.rb
- app/controllers/steps/safety_questions/substance_abuse_details_controller.rb
- app/forms/steps/safety_questions/substance_abuse_details_form.rb
- app/forms/steps/safety_questions/substance_abuse_form.rb
- app/services/base_decision_tree.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/services/c100_app/safety_questions_decision_tree.rb
- app/value_objects/abuse_type.rb
- app/views/steps/safety_questions/substance_abuse/edit.html.erb
- app/views/steps/safety_questions/substance_abuse_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171121150905_add_substance_abuse_fields.rb
- db/schema.rb
- spec/controllers/steps/safety_questions/substance_abuse_controller_spec.rb
- spec/controllers/steps/safety_questions/substance_abuse_details_controller_spec.rb
- spec/forms/steps/safety_questions/substance_abuse_details_form_spec.rb
- spec/forms/steps/safety_questions/substance_abuse_form_spec.rb
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
- spec/services/c100_app/safety_questions_decision_tree_spec.rb
This is now in their separate form objects, views and controller as opposite to being part of the bigger `concerns of abuse` journey.
The whole `concerns of abuse` journey will also change soon (reordering mainly).
Separate commits to make this PR more palatable.
> Substance abuse question and details

- .rubocop.yml
- app/controllers/steps/safety_questions/children_abuse_controller.rb
- app/forms/steps/safety_questions/children_abuse_form.rb
- app/services/c100_app/applicant_decision_tree.rb
- app/services/c100_app/safety_questions_decision_tree.rb
- app/views/steps/safety_questions/children_abuse/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171122092951_add_children_abuse_field.rb
- db/schema.rb
- spec/controllers/steps/safety_questions/children_abuse_controller_spec.rb
- spec/forms/steps/safety_questions/children_abuse_form_spec.rb
- spec/services/c100_app/safety_questions_decision_tree_spec.rb
Another boilerplate yes/no question and decision tree updated.
> Add children abuse question step

- app/controllers/steps/abuse_concerns/start_controller.rb
- app/controllers/steps/safety_questions/domestic_abuse_controller.rb
- app/controllers/steps/safety_questions/other_abuse_controller.rb
- app/forms/steps/safety_questions/domestic_abuse_form.rb
- app/forms/steps/safety_questions/other_abuse_form.rb
- app/services/c100_app/safety_questions_decision_tree.rb
- app/views/steps/abuse_concerns/start/show.en.html.erb
- app/views/steps/safety_questions/domestic_abuse/edit.html.erb
- app/views/steps/safety_questions/other_abuse/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171122103100_add_domestic_abuse_field.rb
- db/migrate/20171122104208_add_other_abuse_field.rb
- db/schema.rb
- spec/controllers/steps/abuse_concerns/start_controller_spec.rb
- spec/controllers/steps/safety_questions/domestic_abuse_controller_spec.rb
- spec/controllers/steps/safety_questions/other_abuse_controller_spec.rb
- spec/forms/steps/safety_questions/domestic_abuse_form_spec.rb
- spec/forms/steps/safety_questions/other_abuse_form_spec.rb
- spec/services/c100_app/safety_questions_decision_tree_spec.rb
This adds some more yes/no question steps and adapts the decision tree
to match the logic in the prototype.
> Add `domestic` and `other` abuse steps

- app/controllers/steps/applicant/user_type_controller.rb
- app/controllers/steps/miam/acknowledgement_controller.rb
- app/controllers/steps/miam/attended_controller.rb
- app/controllers/steps/miam/certification_controller.rb
- app/controllers/steps/miam/no_certification_kickout_controller.rb
- app/controllers/steps/miam/not_attended_info_controller.rb
- app/forms/steps/miam/attended_form.rb
- app/forms/steps/miam/certification_form.rb
- app/services/c100_app/miam_decision_tree.rb
- app/views/entrypoint/shared/_start_application.html.erb
- app/views/steps/miam/attended/edit.html.erb
- app/views/steps/miam/certification/edit.html.erb
- app/views/steps/miam/no_certification_kickout/show.en.html.erb
- app/views/steps/miam/not_attended_info/show.en.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171123094803_add_miam_attended_field.rb
- db/migrate/20171123095928_add_miam_certification_field.rb
- db/schema.rb
- spec/controllers/steps/applicant/user_type_controller_spec.rb
- spec/controllers/steps/miam/acknowledgement_controller_spec.rb
- spec/controllers/steps/miam/attended_controller_spec.rb
- spec/controllers/steps/miam/certification_controller_spec.rb
- spec/controllers/steps/miam/no_certification_kickout_controller_spec.rb
- spec/controllers/steps/miam/not_attended_info_controller_spec.rb
- spec/forms/steps/miam/attended_form_spec.rb
- spec/forms/steps/miam/certification_form_spec.rb
- spec/services/c100_app/miam_decision_tree_spec.rb
More MIAM questions, and updated decision trees.
Some of these step views are placeholders awaiting final copy and might change, or be removed.
> Add MIAM attended and certification steps

- app/controllers/steps/petition/orders_controller.rb
- app/controllers/steps/petition/other_issue_controller.rb
- app/controllers/steps/petition_step_controller.rb
- app/forms/steps/petition/orders_form.rb
- app/forms/steps/petition/other_issue_form.rb
- app/models/asking_order.rb
- app/models/c100_application.rb
- app/services/base_decision_tree.rb
- app/services/c100_app/petition_decision_tree.rb
- app/views/steps/petition/orders/edit.html.erb
- app/views/steps/petition/other_issue/edit.html.erb
- config/initializers/extensions.rb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171123125740_create_asking_orders_table.rb
- db/schema.rb
- lib/extensions/string_extension.rb
- spec/controllers/steps/petition/orders_controller_spec.rb
- spec/controllers/steps/petition/other_issue_controller_spec.rb
- spec/forms/steps/petition/orders_form_spec.rb
- spec/forms/steps/petition/other_issue_form_spec.rb
- spec/lib/extensions/string_extension_spec.rb
- spec/services/c100_app/petition_decision_tree_spec.rb
This step let the applicant choose what the court needs to do about
the children. When `other` is selected, it goes to another step to
enter more details.
> Add `asking orders` step

- app/controllers/steps/abduction/international_controller.rb
- app/controllers/steps/abduction/previous_attempt_controller.rb
- app/controllers/steps/abduction/previous_attempt_details_controller.rb
- app/controllers/steps/abduction/risk_details_controller.rb
- app/forms/steps/abduction/previous_attempt_details_form.rb
- app/forms/steps/abduction/previous_attempt_form.rb
- app/forms/steps/abduction/risk_details_form.rb
- app/services/c100_app/abduction_decision_tree.rb
- app/views/steps/abduction/previous_attempt/edit.html.erb
- app/views/steps/abduction/previous_attempt_details/edit.html.erb
- app/views/steps/abduction/risk_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/steps/abduction/previous_attempt_controller_spec.rb
- spec/controllers/steps/abduction/previous_attempt_details_controller_spec.rb
- spec/controllers/steps/abduction/risk_details_controller_spec.rb
- spec/forms/steps/abduction/previous_attempt_details_form_spec.rb
- spec/forms/steps/abduction/previous_attempt_form_spec.rb
- spec/forms/steps/abduction/risk_details_form_spec.rb
- spec/services/c100_app/abduction_decision_tree_spec.rb
This PR finishes the abduction journey as per prototype.
> Add remaining abduction steps

- app/controllers/steps/abuse_concerns/base_abuse_step_controller.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/views/steps/abuse_concerns/start/show.en.html.erb
- app/views/steps/miam/attended/edit.html.erb
- app/views/steps/miam/certification/edit.html.erb
- app/views/steps/miam/not_attended_info/show.en.html.erb
- app/views/steps/safety_questions/children_abuse/edit.html.erb
- app/views/steps/safety_questions/domestic_abuse/edit.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- config/locales/en.yml
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
Some steps were out of sync with the prototype, although there might
be more changes in the future, is better to maintain as much as possible
the app and the prototype in sync.
> Reorder steps and add copy matching prototype

- app/controllers/steps/miam/certification_date_controller.rb
- app/controllers/steps/miam/certification_expired_kickout_controller.rb
- app/controllers/steps/miam/certification_number_controller.rb
- app/forms/steps/miam/certification_date_form.rb
- app/forms/steps/miam/certification_number_form.rb
- app/services/c100_app/miam_decision_tree.rb
- app/views/steps/alternatives/start/show.en.html.erb
- app/views/steps/miam/certification_date/edit.html.erb
- app/views/steps/miam/certification_expired_kickout/show.html.erb
- app/views/steps/miam/certification_number/edit.html.erb
- app/views/steps/miam/no_certification_kickout/show.en.html.erb
- app/views/steps/miam/not_attended_info/show.en.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171129114601_add_miam_certification_date_field.rb
- db/migrate/20171129123803_add_miam_certification_number_field.rb
- db/schema.rb
- lib/generators/step/templates/edit/form_spec.rb
- spec/controllers/steps/miam/certification_date_controller_spec.rb
- spec/controllers/steps/miam/certification_expired_kickout_controller_spec.rb
- spec/controllers/steps/miam/certification_number_controller_spec.rb
- spec/forms/steps/miam/certification_date_form_spec.rb
- spec/forms/steps/miam/certification_number_form_spec.rb
- spec/services/c100_app/miam_decision_tree_spec.rb
Added the certification date, with validation and kickout for expired
dates, and also the certification number, but not validation yet.
Some copy changes and decision tree changes too.
> Add MIAM certification details steps

- app/controllers/steps/children/other_children_controller.rb
- app/forms/steps/children/other_children_form.rb
- app/services/c100_app/children_decision_tree.rb
- app/views/steps/children/other_children/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171204134208_add_other_children_field.rb
- db/schema.rb
- spec/controllers/steps/children/other_children_controller_spec.rb
- spec/forms/steps/children/other_children_form_spec.rb
- spec/services/c100_app/children_decision_tree_spec.rb
This will trigger the `other children` journey which is very similar to
the current `children` journey. A PR for this coming soon.
> Add `other children` question step

- app/models/c100_application.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/services/c100_app/court_orders_decision_tree.rb
- app/services/c100_app/petition_decision_tree.rb
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
- spec/services/c100_app/court_orders_decision_tree_spec.rb
- spec/services/c100_app/petition_decision_tree_spec.rb
Some small changes to adapt the app journeys to the latest version
of the prototype.
> Update decision trees

- app/controllers/steps/applicant/contact_details_controller.rb
- app/forms/steps/applicant/contact_details_form.rb
- app/services/base_decision_tree.rb
- app/services/c100_app/applicant_decision_tree.rb
- app/services/c100_app/children_decision_tree.rb
- app/services/c100_app/other_children_decision_tree.rb
- app/views/steps/applicant/contact_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/steps/applicant/contact_details_controller_spec.rb
- spec/forms/steps/applicant/contact_details_form_spec.rb
- spec/services/c100_app/applicant_decision_tree_spec.rb
And some DRY in the decision trees.
> Applicant contact details step

- app/controllers/concerns/crud_step.rb
- app/controllers/steps/respondent/contact_details_controller.rb
- app/controllers/steps/respondent/names_controller.rb
- app/controllers/steps/respondent/personal_details_controller.rb
- app/forms/steps/respondent/contact_details_form.rb
- app/forms/steps/respondent/names_form.rb
- app/forms/steps/respondent/personal_details_form.rb
- app/models/respondent.rb
- app/services/c100_app/applicant_decision_tree.rb
- app/services/c100_app/respondent_decision_tree.rb
- app/views/steps/respondent/contact_details/edit.html.erb
- app/views/steps/respondent/names/edit.html.erb
- app/views/steps/respondent/personal_details/_respondent_row.html.erb
- app/views/steps/respondent/personal_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171208150846_drop_respondents_table.rb
- db/schema.rb
- spec/controllers/steps/applicant/names_controller_spec.rb
- spec/controllers/steps/children/names_controller_spec.rb
- spec/controllers/steps/other_children/names_controller_spec.rb
- spec/controllers/steps/respondent/contact_details_controller_spec.rb
- spec/controllers/steps/respondent/names_controller_spec.rb
- spec/controllers/steps/respondent/personal_details_controller_spec.rb
- spec/forms/steps/respondent/contact_details_form_spec.rb
- spec/forms/steps/respondent/names_form_spec.rb
- spec/forms/steps/respondent/personal_details_form_spec.rb
- spec/services/c100_app/applicant_decision_tree_spec.rb
- spec/services/c100_app/respondent_decision_tree_spec.rb
- spec/support/step_controller_shared_examples.rb
Same as Applicants really, just minor changes in the contact form fields, and obviously different i18n.
> Add Respondent names and details steps

- app/controllers/concerns/names_crud_step.rb
- app/controllers/crud_step_controller.rb
- app/controllers/steps/applicant/contact_details_controller.rb
- app/controllers/steps/applicant/names_controller.rb
- app/controllers/steps/applicant/personal_details_controller.rb
- app/controllers/steps/applicant_step_controller.rb
- app/controllers/steps/children/names_controller.rb
- app/controllers/steps/children/personal_details_controller.rb
- app/controllers/steps/children_step_controller.rb
- app/controllers/steps/other_children/names_controller.rb
- app/controllers/steps/other_children/personal_details_controller.rb
- app/controllers/steps/other_children_step_controller.rb
- app/controllers/steps/respondent/contact_details_controller.rb
- app/controllers/steps/respondent/names_controller.rb
- app/controllers/steps/respondent/personal_details_controller.rb
- app/controllers/steps/respondent_step_controller.rb
This is easy to follow and understand without having to mess around
with 2 different concerns, one overriding methods of the other one.
Also, a few lines less of code per controller is nice :-)
> Refactor and DRY crud controllers

- app/forms/names_base_form.rb
- app/forms/steps/children/names_form.rb
- app/forms/steps/children/personal_details_form.rb
- app/views/steps/children/names/edit.html.erb
- app/views/steps/children/personal_details/edit.html.erb
- config/locales/en.yml
- spec/forms/steps/children/names_form_spec.rb
- spec/forms/steps/children/personal_details_form_spec.rb
Removing the override and updating views to match prototype.
> Use full name for children

- app/controllers/steps/safety_questions/address_confidentiality_controller.rb
- app/forms/steps/safety_questions/address_confidentiality_form.rb
- app/services/c100_app/safety_questions_decision_tree.rb
- app/views/steps/safety_questions/address_confidentiality/edit.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171212105422_add_address_confidentiality_field.rb
- db/schema.rb
- spec/controllers/steps/safety_questions/address_confidentiality_controller_spec.rb
- spec/forms/steps/safety_questions/address_confidentiality_form_spec.rb
- spec/services/c100_app/safety_questions_decision_tree_spec.rb
Simple yes/no step, we don't actually do anything with the answer for
now other than storing it.
Updated decision tree.
> Add `address_confidentiality` yes/no step

- app/controllers/steps/alternatives/court_controller.rb
- app/forms/steps/alternatives/court_form.rb
- app/services/base_decision_tree.rb
- app/services/c100_app/alternatives_decision_tree.rb
- app/services/c100_app/petition_decision_tree.rb
- app/services/c100_app/safety_questions_decision_tree.rb
- app/views/steps/alternatives/court/edit.en.html.erb
- config/locales/en.yml
- db/migrate/20171212143713_change_alternative_court_field.rb
- db/schema.rb
- spec/forms/steps/alternatives/court_form_spec.rb
- spec/services/c100_app/alternatives_decision_tree_spec.rb
- spec/services/c100_app/petition_decision_tree_spec.rb
- spec/services/c100_app/safety_questions_decision_tree_spec.rb
Following recent changes in the prototype, the previously yes/no
question has been changed to a checkbox, and also the decision tree
has been updated with some logic around the concerns.
A few other changes in other decision trees to change steps order.
> Update `going to court` step and decision trees

- app/controllers/home_controller.rb
- app/views/entrypoint/v1.en.html.erb
- app/views/home/miam_exemptions.en.html.erb
- app/views/steps/miam/not_attended_info/show.en.html.erb
- config/routes.rb
- spec/controllers/home_controller_spec.rb
Simple static page. Added links in a couple of steps. Some other
minor copy changes.
> Add static page with MIAM exemptions list

- app/controllers/steps/application/without_notice_controller.rb
- app/controllers/steps/application/without_notice_details_controller.rb
- app/controllers/steps/application_step_controller.rb
- app/forms/steps/application/without_notice_details_form.rb
- app/forms/steps/application/without_notice_form.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/services/c100_app/application_decision_tree.rb
- app/views/steps/application/without_notice/edit.html.erb
- app/views/steps/application/without_notice_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20171221111510_add_without_notice_fields.rb
- db/schema.rb
- spec/controllers/steps/application/without_notice_controller_spec.rb
- spec/controllers/steps/application/without_notice_details_controller_spec.rb
- spec/forms/steps/application/without_notice_details_form_spec.rb
- spec/forms/steps/application/without_notice_form_spec.rb
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
- spec/services/c100_app/application_decision_tree_spec.rb
A yes/no question step, with further details step if answer was 'yes'.
> Add `WithoutNotice` yes/no and details steps

- app/controllers/steps/application/litigation_capacity_controller.rb
- app/controllers/steps/application/litigation_capacity_details_controller.rb
- app/forms/steps/application/litigation_capacity_details_form.rb
- app/forms/steps/application/litigation_capacity_form.rb
- app/services/c100_app/application_decision_tree.rb
- app/services/c100_app/international_decision_tree.rb
- app/views/steps/application/litigation_capacity/edit.html.erb
- app/views/steps/application/litigation_capacity_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180115104941_add_litigation_capacity_fields.rb
- db/schema.rb
- spec/controllers/steps/application/litigation_capacity_controller_spec.rb
- spec/controllers/steps/application/litigation_capacity_details_controller_spec.rb
- spec/forms/steps/application/litigation_capacity_details_form_spec.rb
- spec/forms/steps/application/litigation_capacity_form_spec.rb
- spec/services/c100_app/application_decision_tree_spec.rb
- spec/services/c100_app/international_decision_tree_spec.rb
Yes/no question, followed by a details step when answer is yes.
> Add `Litigation capacity` steps

- app/controllers/steps/application/special_arrangements_controller.rb
- app/controllers/steps/application/special_assistance_controller.rb
- app/forms/steps/application/special_arrangements_form.rb
- app/forms/steps/application/special_assistance_form.rb
- app/services/c100_app/application_decision_tree.rb
- app/views/steps/application/special_arrangements/edit.html.erb
- app/views/steps/application/special_assistance/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180115121626_add_special_assistance_fields.rb
- db/schema.rb
- spec/controllers/steps/application/special_arrangements_controller_spec.rb
- spec/controllers/steps/application/special_assistance_controller_spec.rb
- spec/forms/steps/application/special_arrangements_form_spec.rb
- spec/forms/steps/application/special_assistance_form_spec.rb
- spec/services/c100_app/application_decision_tree_spec.rb
A couple of yes/no questions with revealing text areas for details.
> Add `Special assistance` steps

- app/controllers/entrypoint_controller.rb
- app/views/entrypoint/how_long.en.html.erb
- app/views/entrypoint/shared/_start_application.html.erb
- app/views/entrypoint/what_is_needed.en.html.erb
- config/routes.rb
- spec/controllers/entrypoint_controller_spec.rb
As per prototype, but not fully styled. Maybe @stephdavid can take a look at these?
> Add a couple of entry pages

- app/controllers/steps/application/details_controller.rb
- app/forms/steps/application/details_form.rb
- app/services/c100_app/application_decision_tree.rb
- app/services/c100_app/international_decision_tree.rb
- app/views/steps/application/details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180118095646_add_application_details_field.rb
- db/schema.rb
- spec/controllers/steps/application/details_controller_spec.rb
- spec/forms/steps/application/details_form_spec.rb
- spec/services/c100_app/application_decision_tree_spec.rb
- spec/services/c100_app/international_decision_tree_spec.rb
>  Add `application details` step

- app/controllers/steps/abduction/passport_details_controller.rb
- app/forms/steps/abduction/international_form.rb
- app/forms/steps/abduction/passport_details_form.rb
- app/forms/steps/abduction/risk_details_form.rb
- app/services/c100_app/abduction_decision_tree.rb
- app/services/c100_app/safety_questions_decision_tree.rb
- app/views/steps/abduction/international/edit.html.erb
- app/views/steps/abduction/passport_details/edit.html.erb
- app/views/steps/abduction/previous_attempt_details/edit.html.erb
- app/views/steps/abduction/risk_details/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180118131931_add_current_location_field.rb
- db/schema.rb
- spec/controllers/steps/abduction/passport_details_controller_spec.rb
- spec/forms/steps/abduction/international_form_spec.rb
- spec/forms/steps/abduction/passport_details_form_spec.rb
- spec/forms/steps/abduction/risk_details_form_spec.rb
- spec/services/c100_app/abduction_decision_tree_spec.rb
- spec/services/c100_app/safety_questions_decision_tree_spec.rb
As per latest prototype, quite a few changes in the abduction journey.
Moved around some attributes from one form to another new one, lots of copy changes, and introduction of a new text area.
> Rework some abduction steps

- app/forms/base_form.rb
- app/forms/steps/miam_exemptions/safety_form.rb
- app/value_objects/safety_exemptions.rb
- app/views/steps/miam_exemptions/safety/edit.html.erb
- config/locales/en.yml
- spec/forms/base_form_spec.rb
- spec/forms/steps/miam_exemptions/safety_form_spec.rb
- spec/value_objects/safety_exemptions_spec.rb
A bit of code refactor and extracting the exemptions to a value-object to make life easier.
More details in the individual commits.
> Finish the safety MIAM exemptions

- app/forms/steps/miam_exemptions/urgency_form.rb
- app/value_objects/urgency_exemptions.rb
- app/views/steps/miam_exemptions/safety/edit.html.erb
- app/views/steps/miam_exemptions/urgency/edit.html.erb
- config/locales/en.yml
- config/locales/exemptions/en.yml
- spec/forms/steps/miam_exemptions/urgency_form_spec.rb
- spec/value_objects/urgency_exemptions_spec.rb
Following the same pattern as before, using the value-object.
> Update UrgencyForm and view

- app/assets/stylesheets/local/pdf_summary.scss
- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/section_presenter.rb
- app/presenters/summary/sections/header_section.rb
- app/views/steps/completion/shared/_header.html.erb
- app/views/steps/completion/shared/_header.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/section_presenter_spec.rb
- spec/presenters/summary/sections/header_section_spec.rb
These are rendered with a different template and also they lack 'show?' logic, as they always show.
> Ability to create PDF headers

- app/presenters/summary/base_answer.rb
- app/presenters/summary/free_text_answer.rb
- app/presenters/summary/multi_answer.rb
- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/help_with_fees.rb
- app/presenters/summary/sections/nature_of_application.rb
- app/views/steps/completion/shared/_multi_answer_row.html.erb
- app/views/steps/completion/shared/_multi_answer_row.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/summary/answer_spec.rb
- spec/presenters/summary/base_answer_spec.rb
- spec/presenters/summary/free_text_answer_spec.rb
- spec/presenters/summary/multi_answer_spec.rb
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/nature_of_application_spec.rb
> Add `Nature of Application` section to PDF

- app/assets/stylesheets/local/pdf_summary.scss
- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/additional_information.rb
- app/views/steps/completion/shared/_risk_concerns.pdf.erb
- app/views/steps/completion/shared/_section.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/additional_information_spec.rb
A couple of questions are still to be decided or lack their
corresponding step, but it is a matter of updating this a bit
when we have them.
> Add `Additional details` section to the PDF

- app/assets/stylesheets/local/pdf_summary.scss
- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/children.rb
- app/presenters/summary/sections/section_header.rb
- app/views/steps/completion/shared/_section_header.html.erb
- app/views/steps/completion/shared/_section_header.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/children_spec.rb
- spec/presenters/summary/sections/section_header_spec.rb
This section is quite big with many questions/answers, so there will be
at least one more PR.
> Add `The Children` section to PDF

- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/base_section_presenter.rb
- app/presenters/summary/sections/miam_requirement.rb
- app/views/steps/completion/shared/_section.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/base_section_presenter_spec.rb
- spec/presenters/summary/sections/miam_requirement_spec.rb
Simple question/answer questions, although there are some unknowns.
> Add MIAM requirements to PDF

- app/views/home/miam_exemptions.en.html.erb
Add embedded ruby code with nested url_for(:back) method in the styled back button used by the c100 app: 
app/views/home/miam_exemptions.en.html.erb
Fixes Issue #142
> Add dynamic back button

- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/application_reasons.rb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/application_reasons_spec.rb
> Add application reasons section to PDF

- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/urgent_hearing.rb
- app/presenters/summary/sections/without_notice_hearing.rb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/urgent_hearing_spec.rb
- spec/presenters/summary/sections/without_notice_hearing_spec.rb
* Add urgent hearing sections to PDF
* Add without notice hearing section to PDF
> Urgent and without notice hearing PDF sections

- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/international_element.rb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/international_element_spec.rb
* Add "8. Cases with an international element" section to the PDF
> add PDF section for "Cases with an international element"

- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/litigation_capacity.rb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/litigation_capacity_spec.rb
> Add `litigation capacity` section to PDF

- app/assets/stylesheets/application.scss
- app/views/steps/abduction/children_have_passport/edit.html.erb
- app/views/steps/abduction/international/edit.html.erb
- app/views/steps/abduction/passport_details/edit.html.erb
- app/views/steps/abduction/previous_attempt/edit.html.erb
- app/views/steps/abduction/previous_attempt_details/edit.html.erb
- app/views/steps/abduction/risk_details/edit.html.erb
- app/views/steps/abuse_concerns/applicant_info/show.en.html.erb
- app/views/steps/abuse_concerns/children_info/show.en.html.erb
- app/views/steps/abuse_concerns/details/edit.html.erb
- app/views/steps/abuse_concerns/question/edit.html.erb
- app/views/steps/abuse_concerns/start/show.en.html.erb
- app/views/steps/miam/child_protection_cases/edit.html.erb
- app/views/steps/safety_questions/address_confidentiality/edit.html.erb
- app/views/steps/safety_questions/children_abuse/edit.html.erb
- app/views/steps/safety_questions/risk_of_abduction/edit.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- app/views/steps/safety_questions/substance_abuse/edit.html.erb
- app/views/steps/safety_questions/substance_abuse_details/edit.html.erb
- config/locales/en.yml
The content and styling of the following rails c100 app pages have been modified to match the updated prototype:
app/assets/stylesheets/application.scss
app/views/steps/abduction/children_have_passport/edit.html.erb
app/views/steps/abduction/international/edit.html.erb
app/views/steps/abduction/passport_details/edit.html.erb
app/views/steps/abduction/previous_attempt/edit.html.erb
app/views/steps/abduction/previous_attempt_details/edit.html.erb
app/views/steps/abduction/risk_details/edit.html.erb
app/views/steps/abuse_concerns/applicant_info/show.en.html.erb
app/views/steps/abuse_concerns/children_info/show.en.html.erb
app/views/steps/abuse_concerns/details/edit.html.erb
app/views/steps/abuse_concerns/question/edit.html.erb
app/views/steps/abuse_concerns/start/show.en.html.erb …
> Content changes to add Safety concerns section

- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/attending_court.rb
- config/locales/summary/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
- spec/presenters/summary/sections/attending_court_spec.rb
A couple of questions are not yet in the app, so marking these as
pending, and next PR or so, will introduce them.
> Add `attending court` section to PDF

- app/controllers/steps/application/language_controller.rb
- app/forms/steps/application/language_form.rb
- app/presenters/summary/sections/additional_information.rb
- app/presenters/summary/sections/attending_court.rb
- app/services/c100_app/application_decision_tree.rb
- app/views/steps/application/language/edit.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
- config/routes.rb
- db/migrate/20180205153804_add_language_help_fields.rb
- db/schema.rb
- spec/controllers/steps/application/language_controller_spec.rb
- spec/forms/steps/application/language_form_spec.rb
- spec/presenters/summary/sections/additional_information_spec.rb
- spec/presenters/summary/sections/attending_court_spec.rb
- spec/services/c100_app/application_decision_tree_spec.rb
Yes/No question with a revealing ‘details’ text area when Yes.
> Add `language help` question step

- app/controllers/steps/application/intermediary_controller.rb
- app/controllers/steps/application/language_controller.rb
- app/forms/steps/application/intermediary_form.rb
- app/presenters/summary/sections/attending_court.rb
- app/services/c100_app/application_decision_tree.rb
- app/views/steps/application/intermediary/edit.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
- config/routes.rb
- db/migrate/20180206101647_add_intermediary_fields.rb
- db/schema.rb
- spec/controllers/steps/application/intermediary_controller_spec.rb
- spec/forms/steps/application/intermediary_form_spec.rb
- spec/presenters/summary/sections/attending_court_spec.rb
- spec/services/c100_app/application_decision_tree_spec.rb
Yes/No question with a revealing ‘details’ text area when Yes.
> Add `intermediary` question step

- app/assets/stylesheets/local/pdf_summary.scss
- app/presenters/relationships_presenter.rb
- app/presenters/summary/sections/miam_requirement.rb
- app/views/steps/completion/shared/_miam_information.en.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/relationships_presenter_spec.rb
- spec/presenters/summary/sections/miam_requirement_spec.rb
Mainly copy changes to bring the PDF in sync with the mockup.
> Copy changes and missing bits in C100 PDF

- app/assets/stylesheets/local/pdf_summary.scss
- app/presenters/summary/sections/base_section_presenter.rb
- app/presenters/summary/sections/other_children_details.rb
- app/presenters/summary/sections/other_court_cases.rb
- app/presenters/summary/sections/other_parties_details.rb
- app/presenters/summary/separator.rb
- spec/presenters/summary/sections/base_section_presenter_spec.rb
- spec/presenters/summary/separator_spec.rb
A few improvements and refinements. Nothing major.
> Some PDF rendering refinements

- Gemfile
- Gemfile.lock
- app/views/steps/children/residence/edit.html.erb
- config/locales/en.yml
The latest version of the gem decorates collections, so we can get rid
of our custom markup.
> Using `govuk_elements_form_builder` 1.2.0

- app/attributes/order_attributes.rb
- app/forms/base_form.rb
- app/forms/form_attribute_methods.rb
- app/forms/steps/children/orders_form.rb
- app/forms/steps/petition/orders_form.rb
- spec/forms/steps/children/orders_form_spec.rb
- spec/support/relationship_step_controller_shared_examples.rb
A bit of refactor, which is going to make a future PR (coming after this) much more pleasant.
Some context and explanation in the separate commits.
> Refactor `BaseForm` and Order forms

- app/controllers/steps/miam_exemptions/protection_controller.rb
- app/forms/steps/miam_exemptions/protection_form.rb
- app/services/c100_app/miam_exemptions_decision_tree.rb
- app/value_objects/protection_exemptions.rb
- app/views/steps/miam_exemptions/protection/edit.html.erb
- config/locales/en.yml
- config/locales/exemptions/en.yml
- config/routes.rb
- spec/controllers/steps/miam_exemptions/protection_controller_spec.rb
- spec/forms/steps/miam_exemptions/protection_form_spec.rb
- spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
- spec/value_objects/protection_exemptions_spec.rb
So nice and easy now, after the refactor :smile:
Although this is the smaller of the 5 exemptions groups.
> Add `protection` MIAM exemptions step

- app/controllers/steps/miam_exemptions/adr_controller.rb
- app/forms/steps/miam_exemptions/adr_form.rb
- app/services/c100_app/miam_exemptions_decision_tree.rb
- app/value_objects/adr_exemptions.rb
- app/views/steps/miam_exemptions/adr/edit.html.erb
- config/locales/en.yml
- config/locales/exemptions/en.yml
- config/routes.rb
- spec/controllers/steps/miam_exemptions/adr_controller_spec.rb
- spec/forms/steps/miam_exemptions/adr_form_spec.rb
- spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
- spec/value_objects/adr_exemptions_spec.rb
One more exemptions step, one less to go…
> Add `adr` MIAM exemptions step

- app/controllers/steps/miam_exemptions/misc_controller.rb
- app/forms/steps/miam_exemptions/misc_form.rb
- app/services/c100_app/miam_exemptions_decision_tree.rb
- app/value_objects/misc_exemptions.rb
- app/views/steps/miam_exemptions/misc/edit.html.erb
- config/locales/en.yml
- config/locales/exemptions/en.yml
- config/routes.rb
- spec/controllers/steps/miam_exemptions/misc_controller_spec.rb
- spec/forms/steps/miam_exemptions/misc_form_spec.rb
- spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
- spec/value_objects/misc_exemptions_spec.rb
Last one of the 5 exemptions groups. Yay!
> Add `misc` MIAM exemptions step

- app/value_objects/domestic_exemptions.rb
- app/value_objects/urgency_exemptions.rb
- app/views/steps/miam_exemptions/domestic/edit.html.erb
- app/views/steps/miam_exemptions/urgency/edit.html.erb
- config/locales/exemptions/en.yml
- spec/value_objects/domestic_exemptions_spec.rb
- spec/value_objects/urgency_exemptions_spec.rb
Some reorganisation and copy changes.
> Amendments to MIAM exemption groups

- app/controllers/steps/miam_exemptions/exit_page_controller.rb
- app/controllers/steps/miam_exemptions/reasons_playback_controller.rb
- app/controllers/steps/miam_exemptions/safety_playback_controller.rb
- app/presenters/miam_exemptions_presenter.rb
- app/services/c100_app/abuse_concerns_decision_tree.rb
- app/services/c100_app/international_decision_tree.rb
- app/services/c100_app/miam_exemptions_decision_tree.rb
- app/services/c100_app/safety_questions_decision_tree.rb
- app/views/steps/miam_exemptions/exit_page/show.en.html.erb
- app/views/steps/miam_exemptions/reasons_playback/show.html.erb
- app/views/steps/miam_exemptions/safety_playback/show.html.erb
- app/views/steps/miam_exemptions/shared/_exemption.html.erb
- config/locales/en.yml
- config/locales/exemptions/en.yml
- config/routes.rb
- spec/controllers/steps/miam_exemptions/exit_page_controller_spec.rb
- spec/controllers/steps/miam_exemptions/reasons_playback_controller_spec.rb
- spec/controllers/steps/miam_exemptions/safety_playback_controller_spec.rb
- spec/presenters/miam_exemptions_presenter_spec.rb
- spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
- spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
- spec/services/c100_app/safety_questions_decision_tree_spec.rb
* MIAM exemptions playback is fully implemented (except the final copy is still TBD).
* Safety concerns playback is WIP.
> Add exemptions playback steps

- app/controllers/steps/screener/urgency_controller.rb
- app/controllers/steps/screener/urgent_exit_controller.rb
- app/forms/steps/screener/urgency_form.rb
- app/models/court.rb
- app/services/base_decision_tree.rb
- app/services/c100_app/screener_decision_tree.rb
- app/views/steps/screener/no_court_found/show.html.erb
- app/views/steps/screener/urgency/edit.html.erb
- app/views/steps/screener/urgent_exit/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180206155341_add_screener_answers_urgent.rb
- db/migrate/20180219114253_add_screener_answers_local_court.rb
- db/schema.rb
- lib/tasks/mutant.rake
- spec/controllers/steps/screener/urgency_controller_spec.rb
- spec/controllers/steps/screener/urgent_exit_controller_spec.rb
- spec/forms/steps/screener/urgency_form_spec.rb
- spec/models/court_spec.rb
- spec/services/c100_app/screener_decision_tree_spec.rb
> Add urgency screener

- app/views/steps/help_with_fees/help_paying/edit.html.erb
- app/views/steps/miam/certification/edit.html.erb
- config/locales/en.yml
If there's some already established convention rather than body_html, happy to switch to that
> Move copy from lede to body #189

- lib/tasks/mutant.rake
Reduce the sample for mutation to try to get the CI build time
under 15 mins.
> Speed up a little bit the CI build

- app/controllers/steps/screener/legal_representation_controller.rb
- app/controllers/steps/screener/legal_representation_exit_controller.rb
- app/forms/steps/screener/legal_representation_form.rb
- app/services/c100_app/screener_decision_tree.rb
- app/views/steps/screener/legal_representation/edit.html.erb
- app/views/steps/screener/legal_representation_exit/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180220152553_add_screener_answers_legal_representation.rb
- db/schema.rb
- spec/controllers/steps/screener/legal_representation_controller_spec.rb
- spec/controllers/steps/screener/legal_representation_exit_controller_spec.rb
- spec/forms/steps/screener/legal_representation_form_spec.rb
- spec/services/c100_app/screener_decision_tree_spec.rb
> add legal representation screener question

- app/presenters/summary/c100_form.rb
- app/presenters/summary/partial.rb
- app/presenters/summary/sections/miam_exemptions.rb
- app/presenters/summary/sections/miam_requirement.rb
- app/views/steps/completion/shared/_miam_exemptions.en.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/summary/c100_form_spec.rb
- spec/presenters/summary/partial_spec.rb
- spec/presenters/summary/sections/miam_exemptions_spec.rb
- spec/presenters/summary/sections/miam_requirement_spec.rb
Now we have the MIAM exemptions we can finish this section in the PDF.
Yay!
> Implement MIAM exemptions section in C100 PDF

- lib/tasks/mutant.rake
on my machine, this brings down a random-sample mutant run from over 5m to about 2m40s
> pass all classes to mutant at once, for big speed-ups

- app/presenters/summary/c1a_form.rb
- app/presenters/summary/sections/c1a_applicant_abuse_details.rb
- app/presenters/summary/sections/c1a_base_abuse_details.rb
- app/presenters/summary/sections/c1a_children_abuse_details.rb
- config/locales/summary/en.yml
- spec/presenters/summary/c1a_form_spec.rb
- spec/presenters/summary/sections/c1a_applicant_abuse_details_spec.rb
- spec/presenters/summary/sections/c1a_children_abuse_details_spec.rb
For both, applicant and children.
> Add `domestic abuse` section to C1A

- app/forms/steps/court_orders/details_form.rb
- app/models/court_order.rb
- app/presenters/summary/c1a_form.rb
- app/presenters/summary/sections/c1a_court_orders.rb
- app/value_objects/court_order_type.rb
- app/views/steps/court_orders/details/edit.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
- spec/presenters/summary/c1a_form_spec.rb
- spec/presenters/summary/sections/c1a_court_orders_spec.rb
Another section. One less to go.
> Add `court orders` section to C1A

- app/controllers/steps/screener/written_agreement_controller.rb
- app/controllers/steps/screener/written_agreement_exit_controller.rb
- app/forms/steps/screener/written_agreement_form.rb
- app/services/c100_app/screener_decision_tree.rb
- app/views/steps/screener/written_agreement/edit.html.erb
- app/views/steps/screener/written_agreement_exit/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180220155926_add_screener_answers_written_agreement.rb
- db/schema.rb
- spec/controllers/steps/screener/written_agreement_controller_spec.rb
- spec/controllers/steps/screener/written_agreement_exit_controller_spec.rb
- spec/forms/steps/screener/written_agreement_form_spec.rb
- spec/services/c100_app/screener_decision_tree_spec.rb
> Add written agreement screener question

- app/assets/stylesheets/application.scss
- app/views/steps/miam/certification_date/edit.html.erb
- config/locales/en.yml
Add missing padding #229
Adjust styling so that child option does not feel separated from the parent option #228
Adjust styling to prevent nested panel overlapping 'or' element #227
> Fix assorted styling problems - #227, #228, #229

- app/controllers/steps/screener/email_consent_controller.rb
- app/forms/steps/screener/email_consent_form.rb
- app/services/c100_app/screener_decision_tree.rb
- app/views/steps/screener/email_consent/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20180226132148_add_screener_email_consent_and_email_address.rb
- db/schema.rb
- spec/controllers/steps/screener/email_consent_controller_spec.rb
- spec/forms/steps/screener/email_consent_form_spec.rb
- spec/services/c100_app/screener_decision_tree_spec.rb
> add email contact screener question

- app/presenters/summary/c1a_form.rb
- app/presenters/summary/sections/c1a_abduction_details.rb
- config/locales/summary/en.yml
- spec/presenters/summary/c1a_form_spec.rb
- spec/presenters/summary/sections/c1a_abduction_details_spec.rb
> Add `abduction` section to C1A

- app/presenters/summary/c1a_form.rb
- config/locales/summary/en.yml
- spec/presenters/summary/c1a_form_spec.rb
> add Statement of Truth to C1A

- config/locales/en.yml
> improve the error message for an invalid email address

- app/presenters/summary/c1a_form.rb
- config/locales/summary/en.yml
- spec/presenters/summary/c1a_form_spec.rb
> add C1A section for Attending the court

- app/assets/javascripts/application.js
- app/assets/javascripts/module_loader.js
- app/assets/javascripts/modules/check-email-address-variables.js.erb
- app/assets/javascripts/modules/check-email-address.js
- app/assets/javascripts/modules/link-alerts.js
- app/assets/javascripts/modules/password-toggle-variables.js.erb
- app/assets/javascripts/modules/password-toggle.js
- app/assets/javascripts/modules/session-timeout-variables.js.erb
- app/assets/javascripts/modules/session-timeout.js
- app/assets/stylesheets/local/inputs.scss
Utility JS modules to show the email confirmation and show/hide the
password in Save&Return, and the session timeout mechanism.
> Bring a few needed JS modules

- app/presenters/summary/sections/litigation_capacity.rb
- app/views/steps/application/litigation_capacity_details/edit.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
- spec/presenters/summary/sections/litigation_capacity_spec.rb
A few copy changes and reorder the text areas.
> Copy changes to Litigation Capacity step

- app/models/c100_application.rb
- app/models/person.rb
- config/application.rb
- lib/tasks/daily_tasks.rake
- spec/models/c100_application_spec.rb
- spec/models/user_spec.rb
Setup the purging of inactive user accounts and old applications.
> Purge users and applications

- app/services/c100_app/miam_exemptions_decision_tree.rb
- app/views/steps/miam/consent_order_sought/show.en.html.erb
- spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
We were missing a couple of exceptions. Added these.
> Fix for MIAM routing

- app/assets/stylesheets/local/lists.scss
- app/assets/stylesheets/local/pdf_summary.scss
- app/presenters/summary/base_pdf_form.rb
- app/presenters/summary/c100_form.rb
- app/presenters/summary/c1a_form.rb
- app/presenters/summary/c8_form.rb
- app/presenters/summary/sections/c1a_concerns_substance.rb
- app/services/c100_app/pdf_generator.rb
- config/locales/summary/en.yml
- spec/presenters/c8_confidentiality_presenter_spec.rb
- spec/presenters/relationships_presenter_spec.rb
- spec/presenters/summary/c100_form_spec.rb
- spec/presenters/summary/c1a_form_spec.rb
- spec/presenters/summary/c8_form_spec.rb
- spec/presenters/summary/sections/c1a_concerns_substance_spec.rb
- spec/services/c100_app/pdf_generator_spec.rb
Minor fixes and copy amendments.
Separate commits for context.
> Assorted amendments

- app/presenters/summary/c1a_form.rb
- app/presenters/summary/sections/c1a_getting_support.rb
- app/presenters/summary/sections/c1a_protection_orders.rb
- app/views/steps/completion/shared/_c1a_getting_support.en.pdf.erb
- config/locales/summary/en.yml
- spec/presenters/summary/c1a_form_spec.rb
- spec/presenters/summary/sections/c1a_getting_support_spec.rb
- spec/presenters/summary/sections/c1a_protection_orders_spec.rb
* Add `protection orders` section
* Add `getting support` section
With these, the C1A can be considered finished, pending copy amendments and any possible oversight.
> Finish remaining C1A PDF sections

- app/controllers/steps/abduction/international_controller.rb
- app/forms/steps/abduction/international_form.rb
- app/services/c100_app/abduction_decision_tree.rb
- app/views/steps/abduction/international/edit.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
- db/migrate/20180312115018_remove_international_risk_field.rb
- db/schema.rb
- spec/forms/steps/abduction/international_form_spec.rb
- spec/presenters/summary/sections/c1a_abduction_details_spec.rb
- spec/services/c100_app/abduction_decision_tree_spec.rb
Some changes to remove a yes/no question (and DB field) and change structure.
> Rework an abduction step

- app/controllers/steps/completion/what_next_controller.rb
- app/models/court.rb
- app/services/c100_app/court_postcode_checker.rb
- app/services/c100_app/courtfinder_api.rb
- app/views/steps/completion/summary/show.html.erb
- app/views/steps/completion/what_next/show.html.erb
- config/locales/en.yml
- config/routes.rb
- lib/tasks/mutant.rake
- spec/controllers/steps/completion/what_next_controller_spec.rb
- spec/models/court_spec.rb
- spec/services/c100_app/courtfinder_api_spec.rb
> Add "What Next" page at the end of the journey

- app/views/steps/screener/done/show.en.html.erb
- app/views/steps/screener/postcode/edit.html.erb
- app/views/steps/screener/start/show.en.html.erb
- app/views/steps/screener/urgency/edit.html.erb
- app/views/steps/screener/urgent_exit/show.html.erb
- config/locales/en.yml
Still we need to remove the labels from the radio fieldsets.
> Add real copy to screener steps

- app/services/c100_app/application_decision_tree.rb
- app/views/steps/completion/what_next/show.html.erb
- config/locales/en.yml
- spec/services/c100_app/application_decision_tree_spec.rb
Update decision tree and some copy changes, to show the `What next` page after the Declaration.
> Wire what next page

- app/views/entrypoint/v1.en.html.erb
- app/views/home/cookies.en.html.erb
- app/views/steps/abuse_concerns/applicant_info/show.en.html.erb
- app/views/steps/abuse_concerns/children_info/show.en.html.erb
- app/views/steps/alternatives/collaborative_law/edit.en.html.erb
- app/views/steps/alternatives/court/edit.en.html.erb
- app/views/steps/alternatives/lawyer_negotiation/edit.en.html.erb
- app/views/steps/alternatives/mediation/edit.en.html.erb
- app/views/steps/alternatives/negotiation_tools/edit.en.html.erb
- app/views/steps/completion/download/show.en.html.erb
- app/views/steps/completion/shared/_c1a_getting_support.en.pdf.erb
- app/views/steps/miam/acknowledgement/edit.en.html.erb
- app/views/steps/miam/certification_expired_info/show.html.erb
- app/views/steps/miam_exemptions/exit_page/show.en.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- config/locales/en.yml
A few copy changes, and replacing target _blank with "external_link" when it is actually external, and also adding the `rel="external"`.
We are missing quite a few links, they will be updated soon.
> Copy amendments and external links

- app/models/court.rb
- lib/tasks/mutant.rake
- spec/models/court_spec.rb
> make mutant tests pass on Court model, and re-include it in rake task

- config/govuk_notify_templates.yml
This correspond with the notify prod env.
> Add production notify template UUIDs

- app/views/steps/screener/urgent_exit/show.html.erb
- app/views/steps/screener/written_agreement_exit/show.html.erb
- app/views/steps/shared/_screener_exit_actions.html.erb
- config/locales/en.yml
Except urgent hearing and consent order.
> Add CAIT link in screener kickouts

- app/assets/javascripts/modules/ga-events.js
It required some modifications to work with multiple radio buttons in the same page, and other fixes, but we can reuse a lot.
> Bring GA events code from Tax Tribs

- app/assets/stylesheets/local/typography.scss
- app/views/steps/screener/legal_representation/edit.html.erb
- app/views/steps/screener/over18/edit.html.erb
- app/views/steps/screener/parent/edit.html.erb
- app/views/steps/screener/start/show.en.html.erb
- config/locales/en.yml
Removing some ledes, and other copy changes.
> More screener copy amendments

- app/views/home/miam_exemptions.en.html.erb
There might be more copy changes, but the layout will be the same.
> Rework MIAM exemptions info page

- app/models/court.rb
- app/views/steps/completion/what_next/show.en.html.erb
- spec/models/court_spec.rb
There was an invalid condition causing a nil exception under certain circumstances.
https://sentry.service.dsd.io/mojds/c100-application-staging/issues/27679/
> Protect from nil exception

- app/assets/stylesheets/local/app.scss
- app/controllers/sessions_controller.rb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/miam/certification_expired_info/show.html.erb
- app/views/steps/miam_exemptions/exit_page/show.en.html.erb
- app/views/steps/shared/_kickout_survey.html.erb
- config/application.rb
- config/routes.rb
- spec/controllers/sessions_controller_spec.rb
Also exposing `/survey` URL to redirect to the survey.
And a few minor styling issues.
> Update survey links

- app/value_objects/gender.rb
- config/locales/en.yml
- config/locales/summary/en.yml
- spec/value_objects/gender_spec.rb
> Change `intersex` to `unspecified`

- app/value_objects/relation.rb
- app/views/steps/shared/_relationship_step.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
- spec/forms/steps/shared/relationship_form_spec.rb
- spec/value_objects/relation_spec.rb
For pilot we narrow down the list.
Also, changing 'party' to 'person' in other parties steps.
> Remove some relation values

- app/value_objects/urgency_exemptions.rb
- app/views/steps/miam_exemptions/urgency/edit.html.erb
- config/locales/en.yml
- config/locales/exemptions/en.yml
- spec/value_objects/urgency_exemptions_spec.rb
And re-organise the Urgency exemptions.
> Copy updates in MIAM exemptions

- app/controllers/sessions_controller.rb
- app/views/application/_developer_tools.html.erb
- config/routes.rb
> Add a bypass to completion

- app/assets/stylesheets/local/pdf_summary.scss
- app/views/home/miam_exemptions.en.html.erb
- app/views/layouts/_footer_links.html.erb
- app/views/steps/abuse_concerns/applicant_info/show.en.html.erb
- app/views/steps/alternatives/court/edit.en.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- config/locales/en.yml
- config/locales/exemptions/en.yml
- config/locales/summary/en.yml
Also:
- reduce margins in PDF document
- hide contact link in the footer
> More copy changes

- app/views/steps/alternatives/collaborative_law/edit.en.html.erb
- app/views/steps/alternatives/court/edit.en.html.erb
- app/views/steps/alternatives/start/show.en.html.erb
- app/views/steps/completion/shared/_c1a_getting_support.en.pdf.erb
- app/views/steps/miam/acknowledgement/edit.en.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- config/locales/en.yml
> Replace `your children` with `the children`

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/local/app.scss
- app/assets/stylesheets/local/app/flash_card.scss
- app/assets/stylesheets/local/buttons.scss
- app/assets/stylesheets/local/forms.scss
- app/assets/stylesheets/local/js_enabled.scss
- app/assets/stylesheets/local/lists.scss
- app/assets/stylesheets/local/panels.scss
- app/assets/stylesheets/local/typography.scss
- app/views/home/miam_exemptions.en.html.erb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/screener/urgency/edit.html.erb
- Tidy up what's next page
- Tidy up exemptions list
- Tweak details styling
- Move styles from app file to appropriate sub-files
> Whats next tidy up

- config/locales/en.yml
as per https://trello.com/c/DeqcCYdw/198-1-review-copy-in-error-pages
> improve error message content

- config/locales/en.yml
- config/locales/summary/en.yml
as per https://trello.com/c/pZs0h1Uj/216-without-notice-hearing-sub-questions
> content changes to without_notice sub-questions

- app/controllers/application_controller.rb
as per https://trello.com/c/Pj8BqFKy/219-add-http-security-headers
> add headers recommended in pentest report to all requests

- app/controllers/application_controller.rb
- config/environments/production.rb
as per [section 4.2 in the pentest report](https://docs.google.com/document/d/1xG5GNKTnBHToawfH00kVOEf_LY2jEZKNlVeORgaMr4A/edit?ts=5ab8e04d#heading=h.cu6m7eukeeg8) and [the Trello card](https://docs.google.com/document/d/1xG5GNKTnBHToawfH00kVOEf_LY2jEZKNlVeORgaMr4A/edit?ts=5ab8e04d#heading=h.cu6m7eukeeg8)
> prevent host header poisoning attack

- app/views/steps/miam/certification_confirmation/show.en.html.erb
as per [the Trello card](https://trello.com/c/5iP5P5ih/228-miam-attendance-confirmation)
> simpler, less intimidating message on miam confirmation page

- app/views/home/miam_exemptions.en.html.erb
as per [the Trello card](https://trello.com/c/iB6fXabK/227-financial-abuse-evidence)
> change evidence header on financial abuse MIAM exemptions list

- app/views/home/miam_exemptions.en.html.erb
- config/locales/en.yml
as per [the Trello card](https://trello.com/c/NHgQ67ge/232-miam-exemptions-pages)
> Miam exemptions wording

- config/locales/en.yml
as per [the Trello card](https://trello.com/c/4n2B2JKL/231-which-or-the-orders-applied-for-relate-to-name)
> minor wording change on orders_applied_for

- app/views/steps/international/resident/edit.html.erb
- config/locales/en.yml
as per [Trello card](https://trello.com/c/p9Zx8065/234-international-element-hidden-text)
> remove reveal panel from international resident question

- config/locales/en.yml
as per [Trello card](https://trello.com/c/WUhZm3LT/235-you-dont-have-to-attend-a-miam-callout-content)
> change callout content on no-miam-needed page

- config/locales/en.yml
According to ticket: https://trello.com/c/E803dbi7
> Update MIAM callout copy

- README.md
- config/locales/en.yml
- features/screener.feature
- features/step_definitions/common.rb
- features/support/env.rb
This is the basic cucumber setup and a complete screener happy path and 2 unhappy paths (for the postcode).
We can continue growing the cukes from here.
Updated the README with a reference to the cukes.
> Initial screener cukes

- app/forms/steps/application/court_proceedings_form.rb
- app/forms/steps/application/help_paying_form.rb
- app/forms/steps/miam/certification_details_form.rb
- app/forms/steps/screener/postcode_form.rb
- app/views/home/miam_exemptions.en.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
* https://trello.com/c/coHbiQYB
* https://trello.com/c/rLIFbLiS
Also trimming spaces from some strings.
> Fix minor copy issues

- app/assets/javascripts/modules/ga-events.js
- app/views/application/_step_header.html.erb
- app/views/entrypoint/v1.en.html.erb
- app/views/layouts/_footer_links.html.erb
- app/views/layouts/application.html.erb
- app/views/steps/alternatives/court/edit.en.html.erb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/miam/acknowledgement/edit.en.html.erb
- app/views/steps/screener/error_but_continue/show.html.erb
- app/views/steps/shared/_screener_exit_actions.html.erb
- app/views/users/drafts/index.html.erb
Code to track some internal links, and all external links.
Added the rel="external" to a few extra links.
> Track links in GA

- app/forms/concerns/single_question_form.rb
- app/forms/steps/abduction/children_have_passport_form.rb
- app/forms/steps/abduction/previous_attempt_form.rb
- app/forms/steps/miam/certification_form.rb
- app/forms/steps/miam/child_protection_cases_form.rb
- spec/forms/steps/abduction/children_have_passport_form_spec.rb
- spec/forms/steps/abduction/previous_attempt_form_spec.rb
- spec/forms/steps/miam/certification_form_spec.rb
- spec/forms/steps/miam/child_protection_cases_form_spec.rb
Only a few, there are many more that we need to consider. This is fundamental work for a future, functional `check your answers`.
- MIAM attributes
- Abduction details
> Reset of some fields when answer changes

- app/assets/javascripts/modules/ga-events.js
- app/views/home/miam_exemptions.en.html.erb
- app/views/steps/children/has_other_children/edit.html.erb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- app/views/steps/screener/urgency/edit.html.erb
- config/locales/en.yml
These are interesting to track too, specially the one to see if users opened the details about printing the application.
> Track revealing details links

- app/views/steps/completion/shared/_free_text_row.pdf.erb
This will output the text in paragraphs if there are new lines in the free text entered by the user.
> Format free text in PDF

- app/views/home/cookies.en.html.erb
- app/views/layouts/application.html.erb
- app/views/steps/abuse_concerns/applicant_info/show.en.html.erb
- app/views/steps/alternatives/court/edit.en.html.erb
- app/views/steps/alternatives/negotiation_tools/edit.en.html.erb
- app/views/steps/completion/shared/_c1a_getting_support.en.pdf.erb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- config/locales/en.yml
Also adding `msapplication-config` meta tag to reduce annoying 404 errors from Internet Explorer browsers hitting the /browserconfig.xml file.
> Ensure all external links are https

- app/forms/steps/children/residence_form.rb
- config/locales/en.yml
- spec/forms/steps/children/residence_form_spec.rb
Enforce at least one checkbox to be selected.
> Add validation to `residence` step

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/nature_of_application.rb
- config/locales/summary/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/nature_of_application_spec.rb
> add Nature of Application section to Check your answers

- app/views/steps/miam/certification_expired_info/show.html.erb
- app/views/steps/miam_exemptions/exit_page/show.en.html.erb
- app/views/users/logins/new.html.erb
- app/views/users/passwords/reset_sent.html.erb
- config/locales/en.yml
- config/locales/summary/en.yml
* A Few more S&R copy changes
* Replace `certificate` with `document` in MIAM steps
> Copy changes

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/safety_concerns.rb
- app/views/steps/completion/shared/_free_text_row.html.erb
- config/locales/summary/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/safety_concerns_spec.rb
This is missing the abduction concerns. Will be done as part of a separate PR.
> Add `safety concerns` section to CYA

- app/assets/stylesheets/local/check_answers.scss
- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/abduction.rb
- config/locales/summary/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/abduction_spec.rb
This section will only show if the answer to `Are the children at risk of being abducted?` was yes.
> Add `abduction` section to CYA

- app/forms/steps/safety_questions/other_abuse_form.rb
- spec/forms/steps/safety_questions/other_abuse_form_spec.rb
This is a bit of an edge case, but once we have the `check your answers`, it could happen.
> Reset abuse concerns when no longer apply

- app/forms/steps/safety_questions/other_abuse_form.rb
- spec/forms/steps/safety_questions/other_abuse_form_spec.rb
There are a few more fields that we need to reset.
> Reset more C1A fields

- app/views/steps/completion/shared/_statement_of_truth.pdf.erb
- config/locales/summary/en.yml
As per ticket:
https://trello.com/c/43VsJX5z
> Add "no signature requirement" copy to PDF

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/safety_contact.rb
- config/locales/summary/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/safety_contact_spec.rb
This safety questions are neverending...
> Add `safety contact` section to CYA

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/people_details.rb
- app/presenters/summary/html_sections/respondents_details.rb
- app/views/steps/completion/shared/_free_text_row.html.erb
- config/locales/summary/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/respondents_details_spec.rb
> Add `respondents` section to CYA

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/applicants_details.rb
- app/presenters/summary/html_sections/other_parties_details.rb
- app/presenters/summary/html_sections/respondents_details.rb
- config/locales/summary/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/other_parties_details_spec.rb
> Add `other parties` section to CYA

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/without_notice_details.rb
- config/locales/cya/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/without_notice_details_spec.rb
> add without notice hearing details to CYA

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/international_element.rb
- config/locales/cya/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/international_element_spec.rb
> add CYA international elements section

- app/views/steps/abuse_concerns/applicant_info/show.en.html.erb
- app/views/steps/abuse_concerns/children_info/show.en.html.erb
- config/locales/en.yml
Some minor copy changes as per ticket:
https://trello.com/c/zGCluKdp
> Copy changes to safety/abuse questions

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/application_reasons.rb
- config/locales/cya/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/application_reasons_spec.rb
> add application details to CYA

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/children_residence.rb
- config/locales/cya/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/children_residence_spec.rb
> Add `children residence` section to CYA

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/help_with_fees.rb
- config/locales/cya/en.yml
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/help_with_fees_spec.rb
Last bit of the Check your answers. Yay!
Still we need to do some TLC, lots of copy changes, etc. in following PRs.
> Add `help with fees` section to CYA

- app/views/entrypoint/v1.en.html.erb
- config/locales/en.yml
As per ticket: https://trello.com/c/i1PPCWby
> Minor copy changes

- app/assets/stylesheets/local/pdf_summary.scss
* Increasing a bit the font size all over the PDF and unifying some other font sizes.
* Reduce a bit the margins.
> Amendments to font sizes in the PDF

- app/views/steps/application/check_your_answers/edit.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
Some copy changes/review still needed in the MIAM exemptions.
> CYA copy changes

- app/views/steps/completion/shared/_answers_group.html.erb
- app/views/steps/completion/shared/_change_link.html.erb
- app/views/steps/completion/shared/_date_row.html.erb
- app/views/steps/completion/shared/_free_text_row.html.erb
- app/views/steps/completion/shared/_multi_answer_row.html.erb
- app/views/steps/completion/shared/_row.html.erb
- config/locales/cya/en.yml
Also, track the `change` links in GA.
> Improve wording of MIAM exemptions in CYA

- app/mailer_previews/submission_mailer_preview.rb
- app/mailers/submission_mailer.rb
- app/views/mailers/receipt_mailer/copy_to_user.en.html.erb
- app/views/mailers/receipt_mailer/copy_to_user.en.text.erb
- app/views/mailers/shared/_court_help.en.html.erb
- app/views/mailers/shared/_court_help.en.text.erb
- app/views/mailers/shared/_feedback.en.html.erb
- app/views/mailers/shared/_feedback.en.text.erb
- app/views/steps/completion/confirmation/show.en.html.erb
- spec/mailers/court_mailer_spec.rb
- spec/mailers/receipt_mailer_spec.rb
- spec/support/submission_mailer_shared_examples.rb
Individual commits with more details.
(Still copy is WIP but we almost certainly want the court contact details so adding it).
> Email submission SES header and copy changes

- app/views/mailers/court_mailer/submission_to_court.en.html.erb
- app/views/mailers/court_mailer/submission_to_court.en.text.erb
- config/locales/en.yml
- spec/mailers/court_mailer_spec.rb
- spec/mailers/receipt_mailer_spec.rb
> Copy changes to court email

- app/presenters/summary/html_presenter.rb
- app/presenters/summary/html_sections/solicitor_details.rb
- config/locales/cya/en.yml
- db/schema.rb
- spec/presenters/summary/html_presenter_spec.rb
- spec/presenters/summary/html_sections/solicitor_details_spec.rb
> add CYA section for solicitors details

- app/views/entrypoint/what_is_needed.en.html.erb
- app/views/mailers/court_mailer/submission_to_court.en.html.erb
- app/views/mailers/court_mailer/submission_to_court.en.text.erb
- app/views/steps/application/submission/edit.html.erb
- app/views/steps/completion/confirmation/show.en.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
For the digital/e-submission.
And adding `You can find their details in the attached PDF application.` to the email sent to court.
> Copy change to read `electronically` instead of `online`

- app/services/c100_app/application_decision_tree.rb
- app/views/steps/completion/what_next/show.en.html.erb
- spec/services/c100_app/application_decision_tree_spec.rb
As we are preparing for release to production, we don't need this anymore.
> Remove some unnecessary feature-flag logic

- app/mailer_previews/submission_mailer_preview.rb
- app/mailers/court_mailer.rb
- app/views/entrypoint/v1.en.html.erb
- app/views/mailers/receipt_mailer/copy_to_user.en.html.erb
- app/views/mailers/receipt_mailer/copy_to_user.en.text.erb
- app/views/steps/application/submission/edit.html.erb
- app/views/steps/shared/_payment_instructions.en.html.erb
- config/locales/en.yml
- spec/mailers/court_mailer_spec.rb
* If the application is an urgent hearing, we append `URGENT` to the subject.
* Other minor copy changes for electronic submission to prepare for release to prod.
> Copy amendments for e-submission

- app/views/steps/screener/start/show.en.html.erb
To include the list of courts taking part on the trial.
> Update copy in the screener start page

- app/views/steps/screener/start/show.en.html.erb
> Copy change for Cardiff

- app/models/completed_applications_audit.rb
- db/migrate/20180711151214_add_urgent_to_applications_audit.rb
- db/schema.rb
- spec/models/completed_applications_audit_spec.rb
Track if it is an urgent hearing application or not.
> Add `urgent_hearing` to the audit table

- app/models/court.rb
- spec/models/court_spec.rb
Primarily to accommodate the needs of Leeds Combined Court Centre under the new Courtfinder admin system
> prioritise emails marked as "Applications" over "Family"

- .travis.yml
- README.md
- lib/tasks/all_tests.rake
- lib/tasks/mutant.rake
- lib/tasks/travis.rake
And some other changes and improvements.
Few updates to the README.
> Do not run mutant on master

- lib/tasks/mutant.rake
`TRAVIS_BRANCH:`
- for push builds, or builds not triggered by a pull request, this is the name of the branch.
- for builds triggered by a pull request this is the name of the branch targeted by the pull request.
> Another attempt at Travis-Mutant discrepancies

- app/assets/javascripts/modules/ga-events.js
- app/views/about/cookies.en.html.erb
- app/views/about/privacy.en.html.erb
- app/views/about/terms_and_conditions.en.html.erb
- app/views/entrypoint/v1.en.html.erb
- app/views/home/miam_exemptions.en.html.erb
- app/views/steps/abuse_concerns/applicant_info/show.en.html.erb
- app/views/steps/abuse_concerns/children_info/show.en.html.erb
- app/views/steps/abuse_concerns/details/edit.html.erb
- app/views/steps/alternatives/collaborative_law/edit.en.html.erb
- app/views/steps/alternatives/court/edit.en.html.erb
- app/views/steps/alternatives/lawyer_negotiation/edit.en.html.erb
- app/views/steps/alternatives/mediation/edit.en.html.erb
- app/views/steps/alternatives/negotiation_tools/edit.en.html.erb
- app/views/steps/completion/confirmation/show.en.html.erb
- app/views/steps/completion/shared/_c1a_getting_support.en.pdf.erb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/miam/acknowledgement/edit.en.html.erb
- app/views/steps/miam/certification_expired_info/show.html.erb
- app/views/steps/miam_exemptions/exit_page/show.en.html.erb
- app/views/steps/safety_questions/start/show.en.html.erb
- app/views/steps/shared/_court_help.en.html.erb
- app/views/steps/shared/_kickout_survey.html.erb
- app/views/steps/shared/_payment_instructions.en.html.erb
- config/locales/en.yml
There seem to be an issue with mobile Safari where external links are not opened in new tabs.
It is working fine in other browsers.
Using a different approach.
> Different approach to open external links

- app/views/steps/applicant/names/edit.html.erb
- config/locales/en.yml
Small copy tweak based on feedback.
> Clarify difference between applicant and respondent

- app/views/steps/screener/postcode/edit.html.erb
- config/locales/en.yml
In the postcode screener step.
> Add information about C4 form

- app/views/mailers/receipt_mailer/copy_to_user.en.html.erb
- app/views/mailers/receipt_mailer/copy_to_user.en.text.erb
- app/views/steps/shared/_payment_instructions.en.html.erb
> Update payment instructions copy

- app/presenters/summary/pdf_presenter.rb
- config/locales/pdf/en.yml
- spec/presenters/summary/pdf_presenter_spec.rb
Same as we did between C1A/C100 and C8.
> Add blank page between C100 and C1A

- app/views/about/privacy.en.html.erb
These ones need to be updated too.
> Change 2 links in privacy notice

- app/views/errors/application_completed.html.erb
- config/locales/en.yml
Small copy change for applications completed electronically.
> Copy amendments to error page

- config/locales/cya/en.yml
- config/locales/en.yml
> Minor copy change to FMC label

- Gemfile
- Gemfile.lock
- config/environments/development.rb
This addresses a known vulnerability in ruby-ffi.
> Cleanup unused dev gems and bump ruby-ffi

- config/locales/en.yml
> Minor copy changes to safety disclaimer

- app/views/layouts/application.html.erb
Making it harder for our site to be flagged as spam or whatever.
> Verify site with google search console

- app/views/steps/application/without_notice/edit.html.erb
- config/locales/en.yml
> Add warning copy to `without notice` step

- app/services/c100_app/court_postcode_checker.rb
- app/views/steps/screener/start/show.en.html.erb
- spec/services/c100_app/court_postcode_checker_spec.rb
The following courts are now taking part in the trial:
- Liverpool
- Plymouth
- Peterborough
> Add three more courts to the pilot

- app/views/steps/applicant/personal_details/edit.html.erb
- app/views/steps/children/personal_details/edit.html.erb
- app/views/steps/court_orders/details/edit.html.erb
- app/views/steps/other_children/personal_details/edit.html.erb
- app/views/steps/other_parties/personal_details/edit.html.erb
- app/views/steps/respondent/personal_details/edit.html.erb
- config/locales/en.yml
Some date fields were missing the hint.
Show a sensible date hint depending on which date we are talking about.
> Add missing date hints

- app/models/completed_applications_audit.rb
- db/migrate/20181114112518_add_reference_code_to_applications_audit.rb
- db/migrate/20181114112915_refactor_applications_audit.rb
- db/schema.rb
- spec/models/completed_applications_audit_spec.rb
- spec/support/step_controller_shared_examples.rb
We need to store some extra bits of information to facilitate in the future debug of old applications that no longer exists in database.
A new JSON type column will store these details and any other we could add in the future.
> Improve the audit DB table

- db/migrate/20181114112915_refactor_applications_audit.rb
`find_each` doesn't perform on staging database, so doing it another way.
> Fix migration

- app/models/completed_applications_audit.rb
- lib/tasks/mutant.rake
- spec/models/completed_applications_audit_spec.rb
* Temporarily do not mutant test ShortUrl
* Get postcode from screener_answers
> Apply some test fixes

- lib/tasks/mutant.rake
- spec/models/short_url_spec.rb
The tests have been refactored so mutant doesn't complain.
> Reintroduce `ShortUrl` mutant testing

- .circleci/config.yml
- .dockerignore
- Gemfile
- Gemfile.lock
- README.md
- lib/tasks/all_tests.rake
This will split the work in jobs and create dependencies between the
jobs in order to progress in the workflow.
It will build a deploy automatically to staging upon successful merge
to master.
> Create a CircleCI workflow with a few jobs

- app/models/abuse_concern.rb
- config/application.rb
- lib/tasks/daily_tasks.rake
* Added more logging to the daily task
* Reduced from 3 to 2 days the orphan cleaning task
* We no longer need to order abuse concerns by kind
> Some maintenance

- app/services/c100_app/pdf_email_submission.rb
- spec/services/c100_app/pdf_email_submission_spec.rb
It may happen Notify fails and we don't get a `govuk_notify_response` object back.
In this case, we must ensure we don't provoke another exception (the first one is already reported).
> Improve `message_id` audit

- app/views/steps/completion/confirmation/show.en.html.erb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/shared/_court_help.en.html.erb
- app/views/steps/shared/_feedback.en.html.erb
This is a proof of concept, and will be updated once we have the final survey snippet code.
>  Embed a survey on completion page

- app/services/c100_app/pdf_email_submission.rb
- spec/services/c100_app/pdf_email_submission_spec.rb
This was failing under certain scenarios.
> Make sure we have an actual govuk response

- app/attributes/normalised_email_type.rb
- app/forms/steps/application/submission_form.rb
- app/forms/steps/screener/email_consent_form.rb
- app/services/c100_app/notify_callback.rb
- spec/attributes/normalised_email_type_spec.rb
- spec/services/c100_app/notify_callback_spec.rb
Making sure it gets transformed at origin.
> Better approach to email lowercase

- Gemfile
- Gemfile.lock
- app.json
- config/puma.rb
Should we give us some interesting metrics to evaluate the performance of the application.
> Enable Heroku metrics

- config/puma.rb
Otherwise metrics don't seem to be gathered.
> Start barnes, outside the fork block

- Gemfile
- Gemfile.lock
- app.json
- config/environments/production.rb
- config/initializers/filter_parameter_logging.rb
- config/puma.rb
And add some more params to the logging filter.
> Remove barnes

- Gemfile
- Gemfile.lock
The new version of the gem has been published to Rubygems and we can start using it.
> Use govuk_elements_form_builder rubygems repo

- docs/pull_request_template.md
This is a PR template that sets out the structure we expect; a description, link to the story and a checklist to help the person raising the PR to remember the things to check before requesting a review.
> Add a PR template including a checklist

- app/assets/stylesheets/local/typography.scss
- app/assets/stylesheets/local/utilities.scss
- app/views/about/privacy.en.html.erb
- app/views/entrypoint/v1.en.html.erb
- app/views/home/miam_exemptions.en.html.erb
- app/views/steps/abuse_concerns/details/edit.html.erb
- app/views/steps/application/check_your_answers/edit.html.erb
- app/views/steps/application/check_your_answers/resume.html.erb
- app/views/steps/completion/confirmation/show.en.html.erb
- app/views/steps/completion/shared/_separator.html.erb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/14030806)
- Replace <BR> tag with css spacing from all ERB templates 
> replace BR tag with css spacing

- app/forms/steps/court_orders/details_form.rb
- config/locales/errors/en.yml
[Link to story](https://mojdigital.teamwork.com/#/tasks/14030547)
A lot more copy changes, and making sure the court orders form doesn't validate twice the `xxx_is_current` attribute (one for presence, another one for inclusion) as that duplicates the error message unnecessarily.
> Refactor and reword error messages - Part 2

- app/views/steps/safety_questions/address_confidentiality/edit.html.erb
- config/locales/en.yml
[Link to story](https://mojdigital.teamwork.com/#/tasks/14490114?c=4961532&)
This updates the text to what is currently needed on the safety_questions/address_confidentiality page.
> Update safety questions - address confidentiality label text

- app/forms/steps/petition/orders_form.rb
- app/views/steps/petition/orders/edit.html.erb
- config/locales/errors/en.yml
- spec/forms/steps/petition/orders_form_spec.rb
[Link to story](https://mojdigital.teamwork.com/#/tasks/14030547)
Final round of error copy changes, and a bit of refactor in the validations of the petition orders so we are able to customise the different error messages.
> Refactor and reword error messages - Part 3

- Gemfile
- Gemfile.lock
[Link to story](https://github.com/ministryofjustice/c100-application/network/alerts)
> update devise gem

- app/views/entrypoint/what_is_needed.en.html.erb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/15131426)
Update the text to match the following [document](https://docs.google.com/presentation/d/1kUKJYwmoL4iPxb4N0G22m5oKNt2NB7yTAcAXnXc7YMA/edit#slide=id.g57d3b6782b_0_206)
> Update wording on front page

- app/views/steps/safety_questions/children_abuse/edit.html.erb
- app/views/steps/safety_questions/domestic_abuse/edit.html.erb
- config/locales/en.yml
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/14427375)
- update Have you ever suffered or are you at risk of suffering domestic violence or abuse? to Have you suffered or are you at risk of suffering domestic violence or abuse?
- update Have the children ever suffered or are they at risk of suffering domestic or child abuse? to  Have the children suffered or are they at risk of suffering domestic or child abuse?
- small layout change on both pages to move the call out to under the question
> update safety concern questions and small layout change

- app/controllers/about_controller.rb
- app/views/about/privacy.en.html.erb
- app/views/about/privacy_consent.en.html.erb
- app/views/steps/screener/email_consent/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/about_controller_spec.rb
[Link to story](https://mojdigital.teamwork.com/#/tasks/14526017)
[Link to story](https://mojdigital.teamwork.com/#/tasks/14427235)
- add privacy consent notice page for email consent.
- update main privacy notice
- update /steps/screener/email_consent  
> add privacy consent notice

- app/presenters/c8_confidentiality_presenter.rb
- spec/presenters/c8_confidentiality_presenter_spec.rb
add full_address to C8ConfidentialityPresenter
> add full_address to C8ConfidentialityPresenter

- app/views/about/privacy.en.html.erb
- app/views/about/privacy_consent.en.html.erb
- config/locales/en.yml
Some copy fixes and markup formatting required as per ticket.
[Link to story](https://mojdigital.teamwork.com/#/tasks/14526017)
> Copy fixes to privacy notice and consent

- app/services/c100_app/address_lookup_service.rb
- spec/services/c100_app/address_lookup_service_spec.rb
Fix typo in  ENV variable ORDNANACE_SURVEY_API_KEY to ORDNANCE_SURVEY_API_KEY
> Fix small typo in ORDNANCE_SURVEY_API_KEY feature flag

- app/views/steps/screener/start/show.en.html.erb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/17298469)
You can find the suggested copy changes [here](https://docs.google.com/document/d/1-DxKL322QgfJzz_KMNUj5XdewP6tqND47kA8MrV0QHI/edit#)
> Update landing page copy

- app/assets/stylesheets/local/app.scss
- app/assets/stylesheets/local/app/backoffice.scss
- app/controllers/backoffice/dashboard_controller.rb
- app/views/backoffice/dashboard/_completion.en.html.erb
- app/views/backoffice/dashboard/index.en.html.erb
- app/views/backoffice/emails/_failure.en.html.erb
- app/views/backoffice/emails/index.en.html.erb
Add some more functionality to the back office.
This will list the last 50 completed applications with some basic details.
> Add list of latest applications to backoffice

- app/views/users/logins/new.html.erb
- app/views/users/passwords/edit.html.erb
- app/views/users/passwords/new.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
After the accessibility audit, these headers are to be changed from h2 to h1.
> Change to h1 some h2 headers

- .circleci/config.yml
Now we've tested this, we can reduce the frequency of this test to run once a day at 6am.
> Change smoke tests frequency to daily

- app/controllers/about_controller.rb
- app/views/about/accessibility.en.html.erb
- app/views/layouts/_footer_links.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/about_controller_spec.rb
This is a new page, linked from the footer, in order to disclosuse the current state of the service with regards to accessibility and any known issues.
> Add an accessibility statement

- app/forms/steps/miam/certification_details_form.rb
- app/services/c100_app/courtfinder_api.rb
- config/locales/en.yml
- config/locales/errors/en.yml
- spec/forms/steps/miam/certification_details_form_spec.rb
Some applicants might not have or know this and it is not really necessary.
> Make the mediator sole trader field optional

- config/locales/en.yml
The question was a bit too long.
Reworded to be shorter, as per content designer recommendations.
> Amend header copy in other children step

- app/assets/stylesheets/local/app/backoffice.scss
- app/views/backoffice/dashboard/_completion.en.html.erb
We can show some more details when making use of the application lookup functionality.
This is mainly metadata details.
> Include more application details in back office table

- app/views/backoffice/dashboard/_completion.en.html.erb
No need for `N/A` here as these are booleans so will just show true/false accordingly.
> Improve back office details

- app/models/completed_applications_audit.rb
- app/views/backoffice/dashboard/_completion.en.html.erb
- app/views/backoffice/dashboard/_results_table.en.html.erb
- spec/models/completed_applications_audit_spec.rb
Reorganise a bit the completed applications table, and add some more details when looking for a particular reference case.
> Add some more details to the back office

- app/views/steps/application/payment/edit.html.erb
- app/views/steps/shared/_payment_instructions.en.html.erb
- config/locales/en.yml
Still pending confirmation but adding the logic around the different payment types.
Reorder the payment types according to prototype.
> Add copy for solicitor fee payment

- app/forms/steps/solicitor/contact_details_form.rb
- app/views/steps/address/lookup/_other_party.html.erb
- app/views/steps/address/lookup/_respondent.html.erb
- app/views/steps/completion/shared/_statement_of_truth.pdf.erb
- config/locales/en.yml
- config/locales/errors/en.yml
- config/locales/pdf/en.yml
- spec/forms/steps/solicitor/contact_details_form_spec.rb
And making the solicitor's phone number a mandatory field.
> Copy amendments for legal representation

- app/views/entrypoint/v1.en.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
- config/locales/errors/en.yml
- config/locales/pdf/en.yml
As per feedback from legal/policy and HMCTS.
Still a few changes to go for the declaration of truth, will be part of a separate PR.
> Minor copy amendments for solicitor's journey

- app/presenters/summary/sections/statement_of_truth.rb
- app/views/entrypoint/what_is_needed.en.html.erb
- app/views/steps/application/check_your_answers/edit.html.erb
- app/views/steps/completion/shared/_statement_of_truth.pdf.erb
- config/locales/en.yml
- config/locales/pdf/en.yml
- spec/presenters/summary/sections/statement_of_truth_spec.rb
As per legal feedback.
Clarifying the declaration when a solicitor has been given authority by the applicant.
> Statement of truth copy changes

- .circleci/config.yml
- sidekiq.sh
The control script will take care of the basic actions (start, stop...) and also a very basic `probe` for now for kuberneted readinessProbe and livenessProbe.
> Add sidekiq control script and CircleCI deploy

- README.md
- config/initializers/sidekiq.rb
- docker-compose.yml
- sidekiq.sh
The probe is now much better and checks not only Redis is up (otherwise nothing will work) but also there is a process with more than 1 thread.
Updated README.
> Minor improvements and fixes to sidekiq script

- app/controllers/steps/attending_court/special_arrangements_controller.rb
- app/forms/concerns/arrangements_check_boxes_form.rb
- app/forms/steps/attending_court/special_arrangements_form.rb
- app/services/c100_app/attending_court_decision_tree.rb
- app/value_objects/special_arrangements.rb
- app/views/steps/attending_court/special_arrangements/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20200213102002_add_special_arrangements_fields.rb
- db/schema.rb
- spec/controllers/steps/attending_court/special_arrangements_controller_spec.rb
- spec/forms/steps/attending_court/special_arrangements_form_spec.rb
- spec/services/c100_app/attending_court_decision_tree_spec.rb
- spec/value_objects/special_arrangements_spec.rb
This is not yet wired to the main journey, and can only be accessed by knowing the URL.
Also, CYA and PDF blocks will be added in the next PR.
> Redesign the special arrangements step with check boxes

- app/presenters/summary/html_sections/attending_court_v2.rb
- app/presenters/summary/sections/attending_court_v2.rb
- app/views/steps/completion/shared/_multi_answer_row.html.erb
- app/views/steps/completion/shared/_multi_answer_row.pdf.erb
- config/locales/cya/en.yml
- config/locales/pdf/en.yml
- spec/presenters/summary/html_sections/attending_court_v2_spec.rb
- spec/presenters/summary/sections/attending_court_v2_spec.rb
> Add new special arrangements block to CYA and PDF

- app/presenters/summary/html_sections/attending_court_v2.rb
- app/presenters/summary/sections/attending_court_v2.rb
- config/locales/cya/en.yml
- config/locales/pdf/en.yml
- spec/presenters/summary/html_sections/attending_court_v2_spec.rb
- spec/presenters/summary/sections/attending_court_v2_spec.rb
Same as we did with special arrangements.
> Add new special assistance block to CYA and PDF

- app/assets/stylesheets/local/check_answers.scss
- app/assets/stylesheets/local/pdf_summary.scss
- app/views/steps/completion/shared/_free_text_row.html.erb
- app/views/steps/completion/shared/_free_text_row.pdf.erb
Improve free text paragraphs and give more space and padding to the `Attending court` PDF section.
> Minor styling tweaks

- app/assets/stylesheets/local/pdf_summary.scss
- config/locales/pdf/en.yml
Making C1A abuse list more clear to read, and unifying some copy in attending to court section.
> Styling tweaks to PDF

- app/lib/audit_helper.rb
- app/presenters/summary/sections/statement_of_truth.rb
- app/services/c100_app/applicant_decision_tree.rb
- spec/lib/audit_helper_spec.rb
- spec/presenters/summary/sections/statement_of_truth_spec.rb
- spec/services/c100_app/applicant_decision_tree_spec.rb
This is no longer needed as all applications are now asked the solicitor question.
> Cleanup feature-flag code for solicitors

- app/services/reports/failed_emails_report.rb
Instead of just a generic 'undelivered' better to just use whatever is the error the callback returned (usually it will be either `permanent-failure` or `temporary-failure`) so we can better diagnose the issue and if we want to retry or not the email submission.
> Refactor the failed emails report to show status error

- db/migrate/20200310151742_add_under_age_to_people.rb
- db/schema.rb
I'm adding the column so that it can be stored over the user journey as we
would like to allow users under 18 to fill the form, trough a slightly different
journey that will show them information that they need a "litigation friend".
The implementation will come in a separate PR.
Story: https://mojdigital.teamwork.com/#/tasks/19603602
> add under_age boolean column on people database table

- app/controllers/steps/applicant/under_age_controller.rb
- app/views/steps/applicant/under_age/edit.html.erb
- config/locales/en.yml
- spec/controllers/steps/applicant/under_age_controller_spec.rb
This pull request depends on https://github.com/ministryofjustice/c100-application/pull/822 to be merged first.
This commit replaces the copy and adds information about which court the person
needs to get in contact with.
> Update under age page copy

- config/court_slugs.yml
Smoke test raised these slug changes overnight.
> Update slugs for two courts

- Gemfile.lock
- app/views/steps/miam/certification_confirmation/show.en.html.erb
- app/views/steps/miam/certification_details/edit.html.erb
- app/views/steps/miam/certification_expired_info/show.html.erb
- app/views/steps/miam/exemption_claim/edit.html.erb
- config/locales/en.yml
This complete the work to migrate all steps in the `/steps/miam/` group.
Gem fork now includes latest upstream changes.
> Migrate remaining MIAM attendance steps

- app/views/steps/solicitor/contact_details/edit.html.erb
- app/views/steps/solicitor/personal_details/edit.html.erb
This commit brings the page up to date with the design system.
- https://design-system.service.gov.uk
- https://govuk-form-builder.netlify.app
Story: https://mojdigital.teamwork.com/#/tasks/20122507
> Update Solicitors page

- app/views/steps/screener/done/show.en.html.erb
- config/locales/en.yml
- features/screener.feature
As per some feedback from solicitors, clarify that the application can be completed by solicitors representing a parent.
Ticket: https://mojdigital.teamwork.com/#/tasks/20136328
> Amend copy on screener to clarify legal representation

- app/views/steps/applicant/relationship/edit.html.erb
- app/views/steps/other_party/relationship/edit.html.erb
- app/views/steps/respondent/relationship/edit.html.erb
- app/views/steps/shared/_relationship_step.html.erb
- config/locales/en.yml
This is a shared partial between the following:
- applicant/relationship
- other_party/relationship
- respondent/relationship
Story: https://mojdigital.teamwork.com/#/tasks/20230253
> Update design system for step: shared/relationship

- app/forms/steps/children/residence_form.rb
- app/views/steps/children/additional_details/edit.html.erb
- app/views/steps/children/has_other_children/edit.html.erb
- app/views/steps/children/residence/edit.html.erb
- config/locales/en.yml
- spec/forms/steps/children/residence_form_spec.rb
> Finish migration of remaining children steps

- app/forms/steps/other_children/personal_details_form.rb
- app/views/steps/children/personal_details/edit.html.erb
- app/views/steps/other_children/personal_details/edit.html.erb
- app/views/steps/shared/_children_personal_details.html.erb
- config/locales/en.yml
Refactor the view to a partial shared between Children and OtherChildren, as they are identical except for the page title.
> Migrate other children personal details

- app/forms/steps/applicant/personal_details_form.rb
- app/views/steps/applicant/address_details/edit.html.erb
- app/views/steps/applicant/contact_details/edit.html.erb
- app/views/steps/applicant/has_solicitor/edit.html.erb
- app/views/steps/applicant/personal_details/edit.html.erb
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/20230244
> Update applicant screens

- app/forms/steps/respondent/personal_details_form.rb
- app/views/steps/respondent/address_details/edit.html.erb
- app/views/steps/respondent/contact_details/edit.html.erb
- app/views/steps/respondent/has_other_parties/edit.html.erb
- app/views/steps/respondent/personal_details/edit.html.erb
- app/views/steps/respondent/under_age/edit.html.erb
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/20230252
> Update respondent screens

- app/assets/stylesheets/local/app.scss
- app/assets/stylesheets/local/app/pending_migration.scss
- app/assets/stylesheets/local/typography.scss
- app/views/entrypoint/v1.en.html.erb
- app/views/steps/completion/confirmation/_under_age_section.html.erb
- app/views/steps/completion/confirmation/show.en.html.erb
- app/views/steps/completion/what_next/show.en.html.erb
- app/views/steps/shared/_court_help.en.html.erb
- app/views/steps/shared/_download_pdf_copy.en.html.erb
- app/views/steps/shared/_feedback.en.html.erb
- app/views/steps/shared/_payment_instructions.en.html.erb
- app/views/steps/shared/_post_instructions.en.html.erb
- app/views/steps/shared/_under_age_section.html.erb
Story: https://mojdigital.teamwork.com/#/tasks/20230248
> Update completion screens

- app/views/errors/application_completed.html.erb
- app/views/errors/application_not_found.html.erb
- app/views/errors/application_screening.html.erb
- app/views/errors/invalid_session.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/shared/_continue_button.html.erb
- app/views/errors/unhandled.html.erb
- app/views/steps/address/results/edit.html.erb
- config/locales/en.yml
Also, replaced a few `govuk-!-font-weight-bold` with `<strong>` tags.
Just an example, as all pages are pretty similar:
> Updated all error pages to the new design system

- app/controllers/step_controller.rb
- app/forms/steps/other_party/personal_details_form.rb
- app/views/steps/other_party/address_details/edit.html.erb
- app/views/steps/other_party/personal_details/edit.html.erb
- app/views/steps/respondent/address_details/edit.html.erb
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/20230250
> Update other parties screens

- app/views/steps/applicant/under_age/edit.html.erb
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/20340358
Follow up PR will remove respondent under age logic
> Update Applicant Under Age

- app/views/steps/application/court_proceedings/edit.html.erb
- app/views/steps/application/previous_proceedings/edit.html.erb
- config/locales/en.yml
This is a yes-no question, if answered yes, a details page is shown.
Nothing complicated here.
--
> Migrate previous proceedings steps

- app/views/steps/application/details/edit.html.erb
- app/views/steps/application/payment/edit.html.erb
- config/locales/en.yml
- config/locales/errors/en.yml
> Migrate application details and payment step

- app/views/steps/application/urgent_hearing/edit.html.erb
- app/views/steps/application/urgent_hearing_details/edit.html.erb
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/20353648
> Update design urgent hearing

- app/views/steps/application/litigation_capacity/edit.html.erb
- app/views/steps/application/litigation_capacity_details/edit.html.erb
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/20353647
> Update litigation screens

- app/views/steps/application/urgent_hearing_details/edit.html.erb
Text area is suppose to open on YES.
Fixes https://github.com/ministryofjustice/c100-application/pull/900/files#r418512802
> Fix urgent hearing screen

- app/views/steps/application/without_notice/edit.html.erb
- app/views/steps/application/without_notice_details/edit.html.erb
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/20353649
> Update without notice screens

- app/views/backoffice/auth0/index.en.html.erb
- app/views/backoffice/dashboard/index.en.html.erb
> Update design system for: backoffice/auth0

- app/assets/stylesheets/local/app/backoffice.scss
- app/views/backoffice/audit/_record.en.html.erb
- app/views/backoffice/audit/index.en.html.erb
> Update design system for: backoffice/audit

- app/assets/stylesheets/local/app/backoffice.scss
- app/views/backoffice/dashboard/_completion.en.html.erb
- app/views/backoffice/dashboard/_lookup_form.en.html.erb
- app/views/backoffice/dashboard/_results_table.en.html.erb
- app/views/backoffice/dashboard/index.en.html.erb
- app/views/backoffice/dashboard/lookup.en.html.erb
> Update design system for: backoffice/dashboard

- app/assets/stylesheets/local/app/backoffice.scss
- app/views/backoffice/dashboard/_completion.en.html.erb
- app/views/backoffice/dashboard/_lookup_form.en.html.erb
- app/views/backoffice/emails/_failure.en.html.erb
- app/views/backoffice/emails/_lookup_form.en.html.erb
- app/views/backoffice/emails/_results_table.en.html.erb
- app/views/backoffice/emails/_submission.en.html.erb
- app/views/backoffice/emails/index.en.html.erb
- app/views/backoffice/emails/lookup.en.html.erb
I have updated the way the rows are displayed, for me was not clear 
where the recipient belonged to, so I made some changes, hopefully it is 
better.
> Update design system for: backoffice/emails

- app/views/backoffice/errors/unhandled.en.html.erb
The last bit on the backoffice
> Update design system for: backoffice/errors

- lib/generators/step/templates/edit/edit.html.erb
- lib/generators/step/templates/question/edit.html.erb
- lib/generators/step/templates/show/show.html.erb
Left over work.
Story: https://mojdigital.teamwork.com/#/tasks/20230255
> Update generators to new design system

- app/views/steps/court_orders/details/edit.html.erb
> Remove h1 heading from repeatable question

- app/views/steps/application/check_your_answers/_fulfilment_errors.html.erb
> Update missing information link font size

- app/views/steps/address/results/edit.html.erb
- config/locales/en.yml
Also update font size from small to medium to be more noticeable.
> Update address results headings

- app/assets/javascripts/application.js
- app/assets/stylesheets/application-ie8.scss
- app/assets/stylesheets/local/check_answers.scss
- app/assets/stylesheets/local/misc.scss
- app/views/layouts/govuk_template.html.erb
- config/initializers/assets.rb
- vendor/assets/javascripts/html5shiv-printshiv.js
As per instructions here:
https://frontend.design-system.service.gov.uk/supporting-ie8
Include custom styling as part of the ie8 stylesheet, and add the shim/shiv.
I'm still doing some more testing and the JS is not totally working on IE with some errors from rails-ujs, but at least the styles now are correct.
> Improve IE8 compatibility

- app/forms/backoffice/lookup_form.rb
- app/models/concerns/application_reference.rb
- app/validators/c100_reference_code_validator.rb
Move the validation to a validator class, and improve it a little bit. Still is high level but the purpose is to check the format makes sense to void silly mistakes.
> Refactor reference code validation

- features/safety_concerns.feature
This is an initial iteration on the Safety Concerns scenario.
I'm trying to cover the simplest path here (mainly choosing "Yes" on most questions)
This is not testing the other side (choosing "No" followed by extra questions)
I should be able to cover more scenarios after this PR, including the safety concerns regarding the Applicant.
> Add feature tests for Children Safety Concerns

- features/safety_concerns.feature
- features/step_definitions/forms.rb
This commit enhances the feature test created during https://github.com/ministryofjustice/c100-application/pull/954
Supporting the sub forms during the journey, and stops at the Applicant Safety Concerns (to be covered in a future commit)
> Feature tests for Children Safety Concers with sub forms

- app/validators/application_fulfilment_validator.rb
- config/locales/errors/en.yml
- spec/validators/application_fulfilment_validator_spec.rb
Story: https://mojdigital.teamwork.com/#/tasks/20765761
> Validates that payment and submission types are fulfilled

- app/controllers/steps/miam/child_protection_cases_controller.rb
- app/controllers/steps/miam/consent_order_controller.rb
- app/forms/steps/miam/child_protection_cases_form.rb
- app/forms/steps/miam/consent_order_form.rb
- app/services/c100_app/miam_decision_tree.rb
- app/views/entrypoint/how_long.en.html.erb
- app/views/steps/miam/consent_order_sought/show.en.html.erb
- features/miam.feature
- features/safety_concerns.feature
- features/screener.feature
- features/step_definitions/common.rb
- spec/controllers/steps/miam/child_protection_cases_controller_spec.rb
- spec/controllers/steps/miam/consent_order_controller_spec.rb
- spec/forms/steps/miam/consent_order_form_spec.rb
- spec/services/c100_app/miam_decision_tree_spec.rb
This PR will surface the already existing (from 2018, how about that!) consent order question.
The copy is TBD, I'm using same copy as originally but there is a separate ticket to amend the copy if needed.
This step is now the first question in the application journey (where previously it was child protection cases), so I've had to tweak a bit some cukes and links.
Note: changes to the Check your Answers and PDF will come as a separate PR.
Parent ticket: https://mojdigital.teamwork.com/#/tasks/19965720
Subtask: https://mojdigital.teamwork.com/#/tasks/21212921
> Show consent order step

- app/views/steps/completion/confirmation/_consent_order_section.html.erb
Story: https://mojdigital.teamwork.com/#/tasks/21212954
Follow up on the previous PR, #1011 
Following these changes, the page will look like this:
> Correcting heading of consent order section.

- app/views/steps/miam/consent_order_sought/show.en.html.erb
Story: https://mojdigital.teamwork.com/#/tasks/21212942
> Update copy on consent order sought

- config/locales/errors/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/21212942
> Update validation error message for steps/miam/consent_order

- config/locales/cya/en.yml
- config/locales/en.yml
Story: https://mojdigital.teamwork.com/#/tasks/21212942
> Update MIAM consent order page

- app/lib/audit_helper.rb
- app/views/backoffice/dashboard/_completion.en.html.erb
- config/locales/backoffice/en.yml
- spec/lib/audit_helper_spec.rb
And expose the value in the back office.
This is mainly for analytics and diagnose purposes.
Individual commits for more details.
> Add `consent_order` value to audit table

- app/views/entrypoint/what_is_needed.en.html.erb
Story: https://mojdigital.teamwork.com/#/tasks/21212942
What the page will look like once these changes are approved:
> Amend bullet points on the page.

- app/views/steps/miam/consent_order_sought/show.en.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
Task: https://mojdigital.teamwork.com/#/tasks/21334450
Changes following approval of this PR:
> Update question and playback for consent order applications

- app/controllers/steps/children/special_guardianship_order_controller.rb
- app/forms/steps/children/special_guardianship_order_form.rb
- app/models/minor.rb
- app/models/person.rb
- app/services/c100_app/children_decision_tree.rb
- app/views/steps/children/special_guardianship_order/edit.html.erb
- config/locales/en.yml
- config/locales/errors/en.yml
- config/routes.rb
- db/migrate/20200803111915_add_sg_order_to_people.rb
- db/schema.rb
- features/children_details.feature
- lib/generators/step/templates/edit/edit.html.erb
- lib/generators/step/templates/question/edit.html.erb
- lib/generators/step/templates/show/show.html.erb
- spec/controllers/steps/children/special_guardianship_order_controller_spec.rb
- spec/forms/steps/children/special_guardianship_order_form_spec.rb
- spec/services/c100_app/children_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21392185
CYA and PDF will be done in a follow-up PR as this was already growing too much.
This will also be hidden behind a feature flag, before promoting to production, as we don't really want to start asking this question until we've finished the non-parents journey.
> Add special guardianship order step to children loop

- app/services/c100_app/applicant_decision_tree.rb
- app/services/c100_app/other_party_decision_tree.rb
- app/services/people_decision_tree.rb
- spec/services/c100_app/applicant_decision_tree_spec.rb
- spec/services/c100_app/other_party_decision_tree_spec.rb
- spec/services/c100_app/respondent_decision_tree_spec.rb
- spec/support/decision_tree_shared_examples.rb
Some preparation work to be able to fit more nicely the new non-parents journey.
I'm splitting this work apart from the following PR as otherwise it would be too big. Also, in reality, this work can be seen as separate from non-parents.
> Preparation work for non-parents

- config/locales/en.yml
Task: https://mojdigital.teamwork.com/#/tasks/21392176
If these changes are approved the question will look like this:
> Update guardian and special guardian hints.

- app/forms/steps/permission/family_form.rb
- app/forms/steps/permission/local_authority_form.rb
- app/forms/steps/permission/relative_form.rb
- app/services/c100_app/permission_decision_tree.rb
- config/locales/en.yml
- spec/forms/steps/permission/consent_form_spec.rb
- spec/forms/steps/permission/family_form_spec.rb
- spec/forms/steps/permission/local_authority_form_spec.rb
- spec/forms/steps/permission/relative_form_spec.rb
- spec/services/c100_app/permission_decision_tree_spec.rb
Task: https://mojdigital.teamwork.com/#/tasks/21392212
I have noticed some of the earlier questions have been updated recently - will rectify these in another PR.
This PR adds the final 3 questions (family, local_authority, relative) to the non-parents journey.
If approved the new questions will look like:
> Family local authority relative questions

- app/presenters/valid_payments_array.rb
- app/views/entrypoint/v1.en.html.erb
- spec/presenters/valid_payments_array_spec.rb
This PR to be merged once we are certain of the courts that will take part on the pilot (I've added 2 as an example, but probably West London will be part of the pilot) and once we have a production `GOVUK_PAY_API_KEY`
> Add online payments pilot mechanism

- app/views/entrypoint/v1.en.html.erb
- app/views/steps/miam/child_protection_cases/edit.html.erb
- app/views/steps/miam/child_protection_info/show.en.html.erb
- app/views/steps/miam/consent_order/edit.html.erb
- app/views/steps/miam/consent_order_sought/show.en.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
- config/locales/errors/en.yml
- features/fixtures/files/child_protection_cases.html
- features/fixtures/files/child_protection_cases_with_errors.html
Ticket: https://mojdigital.teamwork.com/#/tasks/21485498
As agreed with content designer.
> Further consent order copy tweaks

- app/assets/stylesheets/local/util.scss
- app/jobs/payments_mop_up_job.rb
- app/views/backoffice/dashboard/_payment.en.html.erb
- app/views/backoffice/dashboard/_payments_table.en.html.erb
- spec/jobs/payments_mop_up_job_spec.rb
A couple minor improvements to the back office payments table, and to the mop up task.
> Improve the payments mop up task

- app/presenters/summary/sections/additional_information.rb
- config/locales/pdf/en.yml
- spec/presenters/summary/sections/additional_information_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21483874
Split the question that previously was "Case with an international element or factors affecting litigation capacity?" into 2 separate questions, following changes that will be introduced as well in the paper form.
> Split international/litigation PDF question

- app/views/about/privacy.en.html.erb
- app/views/steps/screener/no_court_found/show.en.html.erb
- app/views/steps/screener/start/show.en.html.erb
- config/locales/pdf/en.yml
Ticket: https://mojdigital.teamwork.com/#/tasks/21498764
Reduce the places where we assume the applicant is a parent of the children (as we are about to release non-parents).
> Minor copy tweaks for non-parents

- app/controllers/concerns/savepoint_step.rb
- app/helpers/custom_form_helpers.rb
- app/models/court.rb
- app/views/errors/application_screening.html.erb
- app/views/errors/shared/_continue_button.html.erb
- app/views/steps/application/check_your_answers/resume.html.erb
- config/locales/en.yml
- features/00_opening.feature
- features/miam.feature
- features/step_definitions/common.rb
- spec/helpers/custom_form_helpers_spec.rb
- spec/models/court_spec.rb
Tickets: https://mojdigital.teamwork.com/#/tasks/21934210 and https://mojdigital.teamwork.com/#/tasks/21934206
Continuation to previous PRs, in this case with some minor amendments and tweaks, in order to make everything ready for the release to production.
> Screener cleanup and tweaks

- config/locales/en.yml
Do not merge until we have written confirmation for this change.
Task: https://mojdigital.teamwork.com/#/tasks/21964062
> Remove financial abuse wording

- app/services/c100_app/navigation_stack.rb
- spec/controllers/steps/application/court_proceedings_controller_spec.rb
- spec/controllers/steps/application/litigation_capacity_details_controller_spec.rb
- spec/controllers/steps/application/permission_details_controller_spec.rb
- spec/controllers/steps/application/urgent_hearing_details_controller_spec.rb
- spec/controllers/steps/application/without_notice_details_controller_spec.rb
- spec/controllers/steps/attending_court/intermediary_controller_spec.rb
- spec/controllers/steps/attending_court/language_controller_spec.rb
- spec/controllers/steps/attending_court/special_arrangements_controller_spec.rb
- spec/controllers/steps/attending_court/special_assistance_controller_spec.rb
- spec/controllers/steps/safety_questions/address_confidentiality_controller_spec.rb
Follow-up to previous PR #1109.
Add some more steps that can safely do a fast-forward to the CYA when editing something.
> Add a few more steps to CYA fast-forward

- Gemfile
- Gemfile.lock
- app/views/steps/alternatives/court/edit.en.html.erb
- app/views/steps/applicant/under_age/edit.html.erb
- app/views/steps/court_orders/details/edit.html.erb
- app/views/steps/miam/acknowledgement/edit.en.html.erb
- app/views/steps/other_party/address_details/edit.html.erb
- app/views/steps/petition/orders/edit.html.erb
- app/views/steps/respondent/address_details/edit.html.erb
- app/views/steps/shared/_dob_form_element.html.erb
- config/locales/en.yml
- features/fixtures/files/miam_certification_date.html
- features/fixtures/files/miam_certification_date_with_errors.html
- features/fixtures/files/nature_of_application.html
- features/fixtures/files/nature_of_application_with_errors.html
- package-lock.json
- package.json
Story: https://mojdigital.teamwork.com/#/tasks/21794372
> Use v2 branch of `govuk_design_system_formbuilder`

- app/services/c100_app/navigation_stack.rb
- spec/controllers/steps/abuse_concerns/contact_controller_spec.rb
- spec/controllers/steps/applicant/address_details_controller_spec.rb
- spec/controllers/steps/other_party/address_details_controller_spec.rb
- spec/controllers/steps/petition/protection_controller_spec.rb
- spec/controllers/steps/respondent/address_details_controller_spec.rb
Add a couple more steps to the CYA fast-forward based on analytics usage, and add a few missing spec tests too.
> Add 2 more pages to CYA fast-forward

- Dockerfile
- Gemfile
- Gemfile.lock
Ticket: https://mojdigital.teamwork.com/#/tasks/22398318
Only some minor releases except `wicked_pdf` but I've checked and there are no breaking changes or regressions as far as I can see.
> Bump some gem versions

- app/controllers/steps/applicant/address_details_controller.rb
- app/controllers/steps/other_party/address_details_controller.rb
- app/controllers/steps/respondent/address_details_controller.rb
- app/forms/form_attribute_methods.rb
- app/forms/steps/solicitor/address_details_form.rb
- app/models/solicitor.rb
- app/presenters/summary/html_sections/solicitor_details.rb
- app/presenters/summary/sections/c1a_solicitor_details.rb
- app/presenters/summary/sections/solicitor_details.rb
- app/views/steps/solicitor/address_details/edit.html.erb
- config/locales/en.yml
- config/locales/errors/en.yml
- spec/forms/steps/solicitor/address_details_form_spec.rb
- spec/models/solicitor_spec.rb
- spec/presenters/summary/html_sections/solicitor_details_spec.rb
- spec/presenters/summary/sections/c1a_solicitor_details_spec.rb
- spec/presenters/summary/sections/solicitor_details_spec.rb
Note this PR might be a bit long, but I've grouped it in a few separate commits with individual details for easier review and understanding.
> Split solicitor address into structured data

- app/views/steps/shared/_download_pdf_copy.en.html.erb
- config/locales/en.yml
Ticket: https://mojdigital.teamwork.com/#/tasks/22631863
Some minor copy tweaks as per content designer.
> Copy tweaks to download draft PDF

- app/presenters/summary/html_sections/miam_requirement.rb
- app/presenters/summary/sections/miam_requirement.rb
- app/services/c100_app/miam_decision_tree.rb
- config/locales/cya/en.yml
- config/locales/pdf/en.yml
- features/miam.feature
- spec/presenters/summary/html_sections/miam_requirement_spec.rb
- spec/presenters/summary/sections/miam_requirement_spec.rb
- spec/services/c100_app/miam_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/22821199
Follow-up to PRs #1132 and #1133 
* Add the new question to the decision tree so it will show after answering NO to the question `Have you attended a MIAM?`
* Add the answer to this new question to the CYA and to the PDF.
> Add mediator’s exemption to CYA and PDF

- app/views/steps/miam/acknowledgement/edit.en.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
- features/miam.feature
Ticket: https://mojdigital.teamwork.com/#/tasks/22823916
Copy changes proposed by content designer as a follow-up to PR #1131 where we removed the 4-months validation.
> Copy changes to remove references to 4 months MIAM

- app/views/steps/miam/certification_confirmation/show.en.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
- features/fixtures/files/miam_certification_date.html
- features/fixtures/files/miam_certification_date_with_errors.html
- features/miam.feature
https://mojdigital.teamwork.com/#/tasks/22821273
> Copy changes for MIAM pages

- app/views/steps/miam/certification_confirmation/show.en.html.erb
There was a last minute change to reflect it's needed for the first 
court hearing.
Story: https://mojdigital.teamwork.com/#/tasks/22821273
> Update copy for MIAM certification confirmation

- app/services/c100_app/address_lookup_service.rb
- spec/fixtures/files/address_lookups/guernsey.json
- spec/fixtures/files/address_lookups/isle_of_man.json
- spec/fixtures/files/address_lookups/jersey.json
- spec/fixtures/files/address_lookups/no_results.json
- spec/fixtures/files/address_lookups/success.json
Ticket: https://trello.com/c/KLgxJkLM
With new API Key
> Update Ordnance Survey API Endpoint

- app/views/steps/alternatives/mediation/edit.en.html.erb
Ticket: https://trello.com/c/0p9OguIb
Support a priority campaign for Policy by ‘marketing’ the scheme on CAS and CAIT.
The link will be shown only in the "alternatives to court" mediation page.
After the campaign has finished we need to remove the link/copy.
Slack thread with more context and screenshots:
https://mojdt.slack.com/archives/C017JHRS0V8/p1616583249002300
> Promote mediation vouchers campaign

- app/views/layouts/_cookie_banner.html.erb
This PR adds some text that was missing from the banner done in RST-3292
> RST-3292 Added text that was omitted from the banner

- config/court_slugs.yml
- spec/models/concerns/court_contact_details_spec.rb
**JIRA**
[RST-3297](https://tools.hmcts.net/jira/browse/RST-3297)
Adds the following courts:
- carlisle-combined-court
- barrow-in-furness-county-court-and-family-court
- preston-crown-court-and-family-court-sessions-house
> [RST-3297] Add 3 new courts to centralisation pilot

- config/court_slugs.yml
- spec/models/concerns/court_contact_details_spec.rb
**JIRA**
[RST-3310](https://tools.hmcts.net/jira/browse/RST-3310)
Adding Central Family Court to centralisation
> RST-3310 Centralisation rollout

- config/court_slugs.yml
- spec/models/concerns/court_contact_details_spec.rb
**JIRA**
[RST-3313](https://tools.hmcts.net/jira/browse/RST-3313)
6th round of court rollout planned to go live *04/05/21*
> RST-3313 Centralisation update 04 05 21

- config/court_slugs.yml
- spec/models/concerns/court_contact_details_spec.rb
teesside-combined-court-centre
> RST-3338 Add missing court to centralisation

- config/court_slugs.yml
- spec/models/concerns/court_contact_details_spec.rb
**JIRA**
[RST-3328](https://tools.hmcts.net/jira/browse/RST-3328)
6th round of court rollout planned to go live *11/05/21*
> RST-3328 centralisation update 11 05 21

- app/models/court.rb
- spec/models/court_spec.rb
Reverts ministryofjustice/c100-application#1190
> Revert "Use county_location_code in api data"

- config/court_slugs.yml
- spec/models/concerns/court_contact_details_spec.rb
**JIRA**
[RST-3324](https://tools.hmcts.net/jira/browse/RST-3324)
Adding new courts
> RST-3324 centralisation rollout 18 May 2021

- app/forms/steps/application/declaration_form.rb
- app/views/steps/application/check_your_answers/edit.html.erb
- config/locales/en.yml
- config/locales/errors/en.yml
- db/migrate/20210520120856_add_declaration_confirmation_to_c100_application.rb
- db/schema.rb
- spec/forms/steps/application/declaration_form_spec.rb
**JIRA**
[RST-3355](https://tools.hmcts.net/jira/browse/RST-3355)
Replace the declaration statement with the Statement of Truth
> RST-3355 change declaration statement to Statement of Truth

- app/forms/steps/applicant/contact_details_form.rb
- features/applicant_details.feature
- spec/forms/steps/applicant/contact_details_form_spec.rb
**JIRA**
[RST-3335](https://tools.hmcts.net/jira/browse/RST-3335)
Add applicant email format validation
> RST-3335 applicant email format validation

- app/forms/backoffice/lookup_form.rb
- spec/forms/backoffice/lookup_form_spec.rb
https://tools.hmcts.net/jira/browse/RST-3377
> RST-337 - Reference code lookup need to be uppercase

- package-lock.json
- package.json
https://tools.hmcts.net/jira/browse/RST-3392
> RST-3392-Updating version of gov uk frontend

- app/forms/steps/applicant/contact_details_form.rb
- app/forms/steps/solicitor/contact_details_form.rb
- app/presenters/summary/html_sections/people_details.rb
- app/presenters/summary/html_sections/solicitor_details.rb
- app/views/steps/applicant/contact_details/edit.html.erb
- app/views/steps/solicitor/contact_details/edit.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
- db/migrate/20210527143629_add_email_provided_to_people.rb
- db/migrate/20210601111447_add_email_provided_to_solicitors.rb
- db/schema.rb
- features/applicant_details.feature
- spec/forms/steps/applicant/contact_details_form_spec.rb
- spec/forms/steps/solicitor/contact_details_form_spec.rb
- spec/presenters/summary/html_sections/applicants_details_spec.rb
- spec/presenters/summary/html_sections/respondents_details_spec.rb
- spec/presenters/summary/html_sections/solicitor_details_spec.rb
**JIRA**
[RST-3336](https://tools.hmcts.net/jira/browse/RST-3336)
Applicant and Solicitor must states whether an email is provided
> RST-3336 Applicant select to provide email

- app/views/steps/applicant/contact_details/edit.html.erb
- app/views/steps/solicitor/contact_details/edit.html.erb
- config/locales/en.yml
- features/applicant_details.feature
Change copy in contact details form for applicant and solicitor
> Copy text changes

- app/forms/steps/solicitor/contact_details_form.rb
- app/presenters/summary/html_sections/solicitor_details.rb
- app/views/steps/solicitor/contact_details/edit.html.erb
- spec/forms/steps/solicitor/contact_details_form_spec.rb
- spec/presenters/summary/html_sections/solicitor_details_spec.rb
> Revert Solicitor email selection changes

- config/locales/en.yml
**JIRA**
[RST-3399](https://tools.hmcts.net/jira/browse/RST-3399)
Update help text for Consent order option within
'What type of application do you want to make' page
> RST 3399 Update copy on opening consent order

- config/locales/cya/en.yml
- config/locales/en.yml
- config/locales/pdf/en.yml
> Copy change `Grandparent`

- app/views/steps/opening/start/show.en.html.erb
- app/views/steps/respondent/address_details/edit.html.erb
- config/locales/en.yml
**JIRA**
* [RST-3431](https://tools.hmcts.net/jira/browse/RST-3431)
* [RST-3432](https://tools.hmcts.net/jira/browse/RST-3432)
* [RST-3434](https://tools.hmcts.net/jira/browse/RST-3434)
> Various copy changes

- .circleci/config.yml
- config/environments/test.rb
- pa11y/screenshots/.gitignore
- pa11y/tests/.pa11yci.json
- package.json
- spec/spec_helper.rb
- added a screen capture at end of url test
seems to help ¯\_(ツ)_/¯
> Add Middleware in test env to allow pa11y testing

- .circleci/config.yml
- config/locales/en.yml
**JIRA**
[RST-3465](https://tools.hmcts.net/jira/browse/RST-3465)
Fix typo in statement of truth
> RST-3465 Fix typo

- app/views/steps/opening/start/show.en.html.erb
**JIRA**
[RST-3471](https://tools.hmcts.net/jira/browse/RST-3471)
Additional consent order guidance to page 'What you’ll need to complete your application'
No change to formatting of current content on page
> RST-3471 Complete your application page consent order guidance

- app/presenters/valid_payments_array.rb
- spec/presenters/valid_payments_array_spec.rb
**JIRA**
[RST-3529](https://tools.hmcts.net/jira/browse/RST-3529)
remove the option of phone payments for all courts where applicants are submitted online.
> RST-3529 Stop phone payment

- app/mailers/reports_mailer.rb
- app/services/reports/payment_types_report.rb
- config/govuk_notify_templates.yml
- lib/tasks/daily_tasks.rake
- spec/mailers/reports_mailer_spec.rb
**JIRA**
[RST-3430](https://tools.hmcts.net/jira/browse/RST-3430)
**Depends On**
https://github.com/ministryofjustice/c100-application-deploy/pull/71
Generate a daily report (csv file) with the number of applications for each of the payment types
> RST-3430 Add daily payment type report

- app/services/reports/payment_types_report.rb
**JIRA**
[RST-3430](https://tools.hmcts.net/jira/browse/RST-3430)
Fix CSV generation
> RST-3430 Payment type report

- Gemfile.lock
- app/models/court.rb
- spec/models/court_spec.rb
https://tools.hmcts.net/jira/browse/RST-3539
> RST-3539 - Address end point updated for FACT changes

- config/application.rb
- spec/helpers/fees_helper_spec.rb
- spec/mailers/notify_submission_mailer_spec.rb
- spec/services/c100_app/online_payments_spec.rb
https://tools.hmcts.net/jira/browse/RST-3653
https://tools.hmcts.net/jira/browse/RST-3654
https://tools.hmcts.net/jira/browse/RST-3484
https://tools.hmcts.net/jira/browse/RST-3485
> RST-3654 - Updating fee

- app/forms/steps/applicant/address_details_form.rb
- app/forms/steps/applicant/contact_details_form.rb
- app/helpers/application_helper.rb
- app/presenters/summary/html_sections/people_details.rb
- app/presenters/summary/sections/c8_applicants_details.rb
- app/presenters/summary/sections/people_details.rb
- app/views/steps/applicant/address_details/edit.html.erb
- app/views/steps/applicant/contact_details/edit.html.erb
- config/locales/cya/en.yml
- config/locales/en.yml
- config/locales/errors/en.yml
- config/locales/pdf/en.yml
- db/migrate/20211111141349_add_residence_keep_private_to_people.rb
- db/migrate/20211115125429_add_contanct_details_keep_private.rb
- db/schema.rb
- spec/forms/steps/applicant/address_details_form_spec.rb
- spec/forms/steps/applicant/contact_details_form_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/presenters/summary/html_sections/applicants_details_spec.rb
- spec/presenters/summary/html_sections/other_parties_details_spec.rb
- spec/presenters/summary/html_sections/respondents_details_spec.rb
- spec/presenters/summary/sections/applicants_details_spec.rb
- spec/presenters/summary/sections/c8_applicants_details_spec.rb
- spec/presenters/summary/sections/c8_other_parties_details_spec.rb
- spec/presenters/summary/sections/other_parties_details_spec.rb
- spec/presenters/summary/sections/respondents_details_spec.rb
V2 because I had to revert the original branch bcs it was not approved to go live.
> RST-3703 v2

- app/forms/steps/applicant/contact_details_form.rb
- app/presenters/c8_confidentiality_presenter.rb
- app/views/steps/applicant/contact_details/edit.html.erb
- spec/forms/steps/applicant/contact_details_form_spec.rb
- spec/presenters/c8_confidentiality_presenter_spec.rb
- spec/presenters/summary/sections/c1a_applicant_details_spec.rb
https://tools.hmcts.net/jira/browse/RST-3703
> RST-3703 Changing the way how private attribute is checked

- app/presenters/c8_confidentiality_presenter.rb
- app/presenters/summary/sections/c8_applicants_details.rb
- spec/presenters/c8_confidentiality_presenter_spec.rb
- spec/presenters/summary/sections/c8_applicants_details_spec.rb
https://tools.hmcts.net/jira/browse/RST-4048
> RST-4048 Bug fix for privacy with old data and new logic

- config/locales/en.yml
Added content to the hint of the yes option for the consent order in '' What kind of application do you want to make '' page.
> RST-3854 Added content for consent order options hint.

- .circleci/config.yml
- Add changes to the pipeline configuration file to deploy in both the clusters.
- Removed  DEV block in the workflow as it is no longer needed.
> Add changes to the pipeline configuration to deploy in both the clusters

- .circleci/config.yml
Deploy to Staging live and Production live cluster.
> Add changes to the pipeline to deploy in live cluster

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/new_framework_defaults_6_0.rb
- features/create_account.feature
- features/step_definitions/account_steps.rb
Fixing missing url host and updating govuk notify
> RST-3820 rails tests

- Gemfile.lock
After dependepot updated puma gemfile lock stayed the same.
> Updating gemfile.lock

- app/models/payment_intent.rb
- spec/models/payment_intent_spec.rb
https://tools.hmcts.net/jira/browse/RST-4381
> RST-4318 Passing https protocol for govuk pay when relevant

- app/models/court.rb
- app/services/c100_app/court_postcode_checker.rb
- app/services/c100_app/courtfinder_api.rb
- features/00_opening.feature
- features/step_definitions/common.rb
- spec/models/court_spec.rb
- spec/presenters/valid_payments_array_spec.rb
- spec/services/c100_app/court_postcode_checker_spec.rb
- spec/services/c100_app/courtfinder_api_spec.rb
https://tools.hmcts.net/jira/browse/RST-4179
> RST-4179 court API update

- app/models/court.rb
- app/services/c100_app/court_postcode_checker.rb
- app/services/c100_app/courtfinder_api.rb
- features/00_opening.feature
- features/step_definitions/common.rb
- spec/models/court_spec.rb
- spec/presenters/valid_payments_array_spec.rb
- spec/services/c100_app/court_postcode_checker_spec.rb
- spec/services/c100_app/courtfinder_api_spec.rb
This reverts commit c656600985d3a013bb4d0ab2cdb80872e7fc69f0, reversing
changes made to 3a8f223c4830e57205d8b744f4bffcca63dc0fca.
> Revert "merge ministryofjustice/feature/rst-4179

- app/forms/concerns/miam_exemptions_form.rb
Passed in correct values to check if only none is selected
> RST-4646-new

- config/environments/production.rb
https://tools.hmcts.net/jira/browse/RST-4797
> RST-4797 - Force ssl in production

- features/00_opening.feature
- features/create_account.feature
- features/step_definitions/account_steps.rb
- features/step_definitions/common.rb
- features/support/page_objects/any_page.rb
Additions to testing at the start of the application
> RST-4887 - Increasing test complexity pre-account choices

- Gemfile.lock
Edited Gemfile.lock to fix any breaks from previous automation suite pull request
> Edited Gemfile.lock 

- config/cucumber.yml
- features/00_opening.feature
- features/step_definitions/common.rb
Test suite currently has series of failures, pull request opened to fix these errors
> Test suite updates

- app/models/concerns/court_redirections.rb
- spec/models/c100_application_spec.rb
> RST-6124: Redirect applications for specific postcodes only (#2)

- app/presenters/summary/sections/c8_other_parties_details.rb
- spec/presenters/summary/sections/c8_other_parties_details_spec.rb
Reverts ministryofjustice/c100-application#1619
> Revert "rst-6031 check for nil are_contact_details_private"

- app/controllers/steps/other_party/children_cohabit_other_controller.rb
- app/controllers/steps/other_party/privacy_preferences_controller.rb
- app/forms/steps/other_party/children_cohabit_other_form.rb
- app/forms/steps/other_party/privacy_preferences_form.rb
- app/models/concerns/application_inquiry_methods.rb
- app/models/concerns/person_with_privacy.rb
- app/presenters/relationships_presenter.rb
- app/presenters/summary/html_sections/people_details.rb
- app/presenters/summary/pdf_presenter.rb
- app/presenters/summary/sections/c8_other_parties_details.rb
- app/presenters/summary/sections/other_parties_details.rb
- app/presenters/summary/sections/people_details.rb
- app/services/c100_app/other_party_decision_tree.rb
- app/services/people_decision_tree.rb
- config/routes.rb
- features/respondent_details.feature
- spec/forms/steps/other_party/children_cohbit_other_form_spec.rb
- spec/forms/steps/other_party/privacy_preferences_form_spec.rb
- spec/presenters/relationships_presenter_spec.rb
- spec/presenters/summary/html_sections/applicants_details_spec.rb
- spec/presenters/summary/html_sections/other_parties_details_spec.rb
- spec/presenters/summary/html_sections/respondents_details_spec.rb
- spec/presenters/summary/sections/applicants_details_spec.rb
- spec/presenters/summary/sections/c8_applicants_details_spec.rb
- spec/presenters/summary/sections/c8_other_parties_details_spec.rb
- spec/presenters/summary/sections/other_parties_details_spec.rb
- spec/presenters/summary/sections/respondents_details_spec.rb
- spec/services/c100_app/other_party_decision_tree_spec.rb
left out:
schema
html
en.yml
Confidential Option check
> roll back confidential option

- features/cookie_management.feature
- features/create_account.feature
- features/miam_mediation_change.feature
Previously broken and deactivated tests have been reactivated and repaired
> Repairing tests

- .gitignore
> Ignore .end.development

- app/presenters/summary/html_sections/people_details.rb
https://tools.hmcts.net/jira/browse/RST-7085
> RST-7085 - Added try when capitalizing content

- .circleci/config.yml
- Dockerfile
- app/validators/application_fulfilment_validator.rb
- spec/validators/application_fulfilment_validator_spec.rb
https://tools.hmcts.net/jira/browse/RST-7081
> RST-7081 - Added new MIAM exemption validation

- .circleci/config.yml
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/RST-7101
> RST-7101 - Updated GovUK Frontend to v5.8.0

- db/migrate/20250130103534_copy_mobile_provided.rb
- db/schema.rb
Mobile provided columns copied into the new phone number columns introduced in https://tools.hmcts.net/jira/browse/RST-7077
> RST-7077c - Copy mobile provided values into phone number

- .circleci/config.yml
- app/presenters/summary/sections/c8_applicants_details.rb
- app/presenters/summary/sections/c8_other_parties_details.rb
- spec/presenters/summary/sections/c8_applicants_details_spec.rb
- spec/presenters/summary/sections/c8_other_parties_details_spec.rb
https://tools.hmcts.net/jira/browse/RST-7103
> RST-7103 - Move C8 Refuge answer to top of Details question

- app/presenters/summary/pdf_presenter.rb
- spec/presenters/summary/pdf_presenter_spec.rb
Fix for Sentry issue https://ministryofjustice.sentry.io/issues/6330710430/?project=5373141&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0
> Fixing missing method call

- Gemfile
- Gemfile.lock
- config/initializers/sentry.rb
Adding Sentry profiling to see why the autoscaling is so busy
> Adding Sentry profiling

- app/assets/javascripts/modules/session-timeout.js
Reverts ministryofjustice/c100-application#1754
> Revert "RST-7246 remove ping in session timeout check"

- .circleci/config.yml
- app/helpers/auth0_helper.rb
- app/views/backoffice/auth0/index.en.html.erb
https://tools.hmcts.net/jira/browse/RST-7266
> RST-7266 Backoffice Access

- .circleci/config.yml
- app/assets/javascripts/application.js
- app/assets/javascripts/modules/pdf-status.js
- app/assets/stylesheets/local/misc.scss
- app/views/layouts/govuk_template.html.erb
- app/views/steps/application/check_your_answers/edit.html.erb
- app/views/steps/shared/_download_pdf_copy.en.html.erb
- config/locales/en.yml
https://tools.hmcts.net/jira/browse/RST-7333
> RST-7333 - Disable PDF button when not ready

- README.md
Reverts ministryofjustice/c100-application#1769
> Revert "New git history and readme update"

- app/services/c100_app/court_postcode_checker.rb
- config/environments/development.rb
- features/00_opening.feature
- features/step_definitions/common.rb
> RST-6888 - Fixing court not find logic

- Gemfile
- Gemfile.lock
- config/initializers/sentry.rb
https://tools.hmcts.net/jira/browse/RST-7206
> RST-7206 Updating Sentry config for detailed profiling

- app/presenters/summary/sections/c1a_base_abuse_summary.rb
- spec/presenters/summary/sections/c1a_applicant_abuse_summary_spec.rb
- spec/presenters/summary/sections/c1a_children_abuse_summary_spec.rb
https://tools.hmcts.net/jira/browse/RST-7474
> RST-7474 Refactoring base abuse presenter

- .circleci/config.yml
https://tools.hmcts.net/jira/browse/RST-7609
> RST-7609 -Updating CI db version
