ministryofjustice/c100-application

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/routes.rb
There were a couple of bits of code in the app. that were not
being used, and which were keeping the test coverage from reaching
100%. This commit removes those, for now, so that we can get the
CI/CD pipeline to Heroku working.
=> Remove unused/unnecessary code, to get coverage

lib/generators/step/templates/edit.html.erb
Without this, every generated page raises a missing page title
exception when it is rendered.
=> Add a page title in generated step template

.rubocop.yml, app/attributes/normalised_email_type.rb, app/controllers/home_controller.rb, app/controllers/step_controller.rb, app/controllers/steps/nature_of_application/case_type_controller.rb, app/controllers/steps/nature_of_application/case_type_kickout_controller.rb, app/controllers/steps/nature_of_application_step_controller.rb, app/controllers/users/logins_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/forms/steps/nature_of_application/case_type_form.rb, app/mailers/notify_mailer.rb, app/models/application_record.rb, app/services/c100_app/case_details_pdf.rb, app/services/c100_app/decision_tree.rb, app/value_objects/value_object.rb, lib/tasks/rubocop.rake
Using a slightly tweaked version (tweaks added to the bottom of the `.rubocop.yml` file) of the GDS styleguide https://github.com/alphagov/govuk-lint/tree/master/configs/rubocop
The whole project has been linted and where it made sense, fixed style issues, otherwise (only one instance) ignore Rubocop by adding a code comment.
Also, rubocop now will run first thing before rspec when using `rake`.
=> Setup Rubocop and lint project

.rubocop.yml, app/controllers/step_controller.rb, app/controllers/steps/applicant/personal_details_controller.rb, app/forms/base_form.rb, app/forms/steps/applicant/personal_details_form.rb, app/models/c100_application.rb, app/services/base_decision_tree.rb, app/services/c100_app/applicant_decision_tree.rb, app/views/steps/applicant/personal_details/_applicant_row.html.erb, app/views/steps/applicant/personal_details/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/applicant/personal_details_controller_spec.rb, spec/forms/steps/applicant/personal_details_form_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/support/matchers/decision_tree_matcher.rb, spec/support/step_controller_shared_examples.rb
Following the previous PR, this will enable the ability to add multiple
Applicants, and also edit and delete existing ones.
Some of the code will be candidate to extract to superclasses or modules
once we are happy with the solution and also once we have another similar
step (like Respondents) where we will be able to reuse some stuff.
There are however some rough corners in this solution, which hopefully we
will be polishing as part of following PRs.
A very ugly little interface has been incorporated to the top of the step
view to be able to manipulate the Applicant entries visually. Of course this
will change in the future.
=> Enable a basic CRUD for Applicants

app/controllers/step_controller.rb
This also gets rid of a deprecation warning to use `attribute_set`
instead if just `attributes`.
=> Simplify the permitted_params method

.rubocop.yml, app/controllers/steps/applicant/personal_details_controller.rb, app/controllers/steps/respondent/personal_details_controller.rb, app/controllers/steps/respondent_step_controller.rb, app/forms/steps/respondent/personal_details_form.rb, app/models/c100_application.rb, app/models/respondent.rb, app/services/c100_app/respondent_decision_tree.rb, app/value_objects/has_previous_name.rb, app/views/steps/respondent/personal_details/_respondent_row.html.erb, app/views/steps/respondent/personal_details/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20171106112653_create_respondents_table.rb, db/schema.rb, spec/controllers/steps/respondent/personal_details_controller_spec.rb, spec/forms/steps/respondent/personal_details_form_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb, spec/support/matchers/validation_matchers.rb
This mimics the Applicant CRUD and allows to add 1 or more Respondant.
Right now there is no limitation on how many you can add but apparently
there will be a limit of 2 (to be clarified).
Also, there is (on purpose) duplication as we have now 2 very similar
form objects and views, so next step will be to DRY all this, including
i18n and specs (potential to extract shared examples).
=> Add Respondent task and steps with CRUD

app/controllers/concerns/crud_step.rb, app/controllers/steps/applicant/personal_details_controller.rb, app/controllers/steps/respondent/personal_details_controller.rb, app/models/application_record.rb, app/models/c100_application.rb, app/views/steps/applicant/personal_details/edit.html.erb, app/views/steps/respondent/personal_details/edit.html.erb
As we now have 2 entities (applicants and respondents) that requires CRUD
actions in the controller, we can create a concern to be included in these
and other future controllers to enforce the same interface.
For now, I'm leaving untouched the list of attributes although many are
common. Once we have more entities (children? etc.) we will have a more
clear opinion of how many of these attributes can be shared and extracted
to a superclass or a module.
As part of another PR we can also DRY the form objects unless it makes
them less readable/maintanable.
=> DRY crud controllers

.rubocop.yml, app/controllers/steps/applicant/personal_details_controller.rb, app/controllers/steps/respondent/personal_details_controller.rb, app/forms/base_form.rb, app/forms/steps/applicant/personal_details_form.rb, app/forms/steps/respondent/personal_details_form.rb
Simplified and removed duplication of attribute mass assignments in
personal details controllers and form objects.
This same approach can be extended to any other controller or form
object, but the ones we have at the moment are pretty simple with only
one or two attributes, so for now it is not worth changing those.
=> Cleanup humongous mass assignments

app/controllers/steps/children/additional_details_controller.rb, app/forms/base_form.rb, app/forms/steps/children/additional_details_form.rb, app/forms/steps/respondent/personal_details_form.rb, app/models/c100_application.rb, app/models/respondent.rb, app/services/c100_app/children_decision_tree.rb, app/value_objects/children_residence.rb, app/value_objects/generic_yes_no_unknown.rb, app/views/steps/children/additional_details/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20171108113601_add_children_additional_details_fields.rb, db/schema.rb, spec/controllers/steps/children/additional_details_controller_spec.rb, spec/forms/steps/children/additional_details_form_spec.rb, spec/forms/steps/respondent/personal_details_form_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb, spec/support/form_validation_shared_examples.rb, spec/support/matchers/validation_helpers.rb
This form view has quite a lot of show/hide elements controlled by radio options. As we don't have a functional show/hide mechanism at the moment, all fields will be visible at once in the view, but the validations behind are implemented based on the prototype rules.
Talking about validations, for these kind of form objects are quite verbose and repetitive. Might be a potential area to try to refactor or come with a more cleaner way of doing it in the future.
=> Add new children additional details step

app/forms/steps/abuse_concerns/base_abuse_form.rb, app/forms/steps/abuse_concerns/details_form.rb, app/forms/steps/abuse_concerns/question_form.rb, app/forms/steps/applicant/personal_details_form.rb, app/forms/steps/applicant/user_type_form.rb, app/forms/steps/children/additional_details_form.rb, app/forms/steps/children/personal_details_form.rb, app/forms/steps/help_with_fees/help_paying_form.rb, app/forms/steps/respondent/personal_details_form.rb, app/value_objects/value_object.rb, lib/generators/step/templates/edit/form.rb
We are using a lot, in different places `.values.map(&:to_s)` so this
exposes a helper method in the ValueObject superclass to encapsulate it.
=> Expose a helper method for a common task

Gemfile.lock, app/forms/steps/abuse_concerns/details_form.rb, app/views/steps/abuse_concerns/details/edit.html.erb, config/locales/en.yml, spec/forms/steps/abuse_concerns/details_form_spec.rb
Making use of latest changes pushed to the `govuk_elements_form_builder`
to enable code blocks inside the panel (so not limited to one single
element anymore) and also to allow to have the panel markup not
immediately follows the radio, but position it in another place with
easy, and reference it in the radio with the `panel_id` attribute.
=> Support for code blocks inside revealing panels

.rubocop.yml, app/forms/steps/abuse_concerns/question_form.rb, spec/forms/steps/abuse_concerns/question_form_spec.rb
Although technically this doesn't affect following questions, we can
safely reset the abuse detail fields when the answer is `no` in order
to not leave leftovers or if the user go back and changes the answer
multiple times.
If the details are still not filled this has no negative impact as they
are already nil.
=> Reset abuse details when answering `no`

app/attributes/yes_no.rb, app/attributes/yes_no_unknown.rb, app/forms/steps/abuse_concerns/base_abuse_form.rb, app/forms/steps/abuse_concerns/details_form.rb, app/forms/steps/abuse_concerns/question_form.rb, app/forms/steps/applicant/personal_details_form.rb, app/forms/steps/children/additional_details_form.rb, app/forms/steps/court_orders/has_orders_form.rb, app/forms/steps/respondent/personal_details_form.rb, app/value_objects/generic_yes_no_unknown.rb, app/views/steps/abuse_concerns/question/edit.html.erb, app/views/steps/children/additional_details/edit.html.erb, app/views/steps/court_orders/has_orders/edit.html.erb, spec/attributes/yes_no_spec.rb, spec/attributes/yes_no_unknown_spec.rb, spec/forms/steps/abuse_concerns/question_form_spec.rb, spec/forms/steps/applicant/personal_details_form_spec.rb, spec/forms/steps/children/additional_details_form_spec.rb, spec/forms/steps/court_orders/has_orders_form_spec.rb, spec/forms/steps/respondent/personal_details_form_spec.rb, spec/value_objects/generic_yes_no_unknown_spec.rb
Updating all the forms that currently use Yes/No/Unknown fields to make use of this better approach introduced in the PR #40 
Still we can go a bit further, and probably I will, as part of a future PR, to unify the 'Virtus' attributes and the ValueObject classes so we don't need 2 different classes.
=> DRY yes/no/unknown attributes and value-objects

app/controllers/steps/abuse_concerns/emergency_proceedings_controller.rb, app/forms/concerns/single_question_form.rb, app/forms/steps/abuse_concerns/emergency_proceedings_form.rb, app/forms/steps/abuse_concerns/previous_proceedings_form.rb, app/models/c100_application.rb, app/services/c100_app/abuse_concerns_decision_tree.rb, app/views/steps/abuse_concerns/emergency_proceedings/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20171120112650_add_emergency_proceedings_field.rb, db/schema.rb, spec/controllers/steps/abuse_concerns/emergency_proceedings_controller_spec.rb, spec/forms/steps/abuse_concerns/emergency_proceedings_form_spec.rb, spec/forms/steps/abuse_concerns/previous_proceedings_form_spec.rb, spec/services/c100_app/abuse_concerns_decision_tree_spec.rb, spec/support/form_validation_shared_examples.rb
Other than adding another step, with a single question Yes/No, this
PR will extract duplicated and shared code to a concern module called
`SingleQuestionForm` to be used when we have form objects with only
one Yes/No question (as these are quite common) and also added shared
examples to simplify the testing of these form objects.
In a follow-up PR I will refactor the rest of form objects we have with
one question to use this concern, and their tests, as I didn't want to
grow too much this PR.
=> Add `emergency proceedings` step and refactor

app/forms/steps/court_orders/has_orders_form.rb, spec/forms/steps/court_orders/has_orders_form_spec.rb
Ok, it turned out this is the other form we can DRY making use of the
concern, but eventually we will have MANY more forms with just one
Yes/No question, and then this will be seen more useful.
=> DRY HasOrders form using `SingleQuestionForm`

lib/generators/step/step_generator.rb, lib/generators/step/templates/question/controller.rb, lib/generators/step/templates/question/controller_spec.rb, lib/generators/step/templates/question/edit.html.erb, lib/generators/step/templates/question/form.rb, lib/generators/step/templates/question/form_spec.rb
This is similar to the `edit` one but the form object uses the
`SingleQuestionForm` and the test, and view are also adapted to this.
As the controller and its spec are identical, using symlinks to those
files in the `edit` directory.
=> Add a `question step` generator

app/controllers/steps/abduction/children_have_passport_controller.rb, app/controllers/steps/abduction_step_controller.rb, app/forms/base_form.rb, app/forms/concerns/has_one_association_form.rb, app/forms/concerns/single_question_form.rb, app/forms/steps/abduction/children_have_passport_form.rb, app/models/abduction_detail.rb, app/models/c100_application.rb, app/services/c100_app/abduction_decision_tree.rb, app/services/c100_app/safety_questions_decision_tree.rb, app/views/steps/abduction/children_have_passport/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20171124141636_create_abduction_details_table.rb, db/schema.rb, spec/controllers/steps/abduction/children_have_passport_controller_spec.rb, spec/forms/steps/abduction/children_have_passport_form_spec.rb, spec/services/c100_app/abduction_decision_tree_spec.rb, spec/services/c100_app/safety_questions_decision_tree_spec.rb
Also added as part of this, as we are going to need it for the whole
abduction journey (and others), a `HasOneAssociationForm` concern to
simplify and DRY the fact many forms read/update attributes from a
different model to the 'main' one.
For example in the Abduction journey, the details are stored in the
`abduction_details` table, which `belongs_to` a c100_application.
There are some old form objects that we can refactor to use this
concern, once we are sure it is fit for purpose.
Also when we do this, we will extract some of the common tests to
shared examples.
=> Add `abduction` task and first steps

app/controllers/steps/abduction/international_controller.rb, app/forms/steps/abduction/international_form.rb, app/services/base_decision_tree.rb, app/services/c100_app/abduction_decision_tree.rb, app/views/steps/abduction/international/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/abduction/international_controller_spec.rb, spec/forms/steps/abduction/children_have_passport_form_spec.rb, spec/forms/steps/abduction/international_form_spec.rb, spec/services/c100_app/abduction_decision_tree_spec.rb, spec/support/form_validation_shared_examples.rb, spec/support/matchers/validation_matchers.rb
Also, beginning to extract some common code to shared examples. More
to come as we create more forms using `HasOneAssociationForm` concern.
=> Add `international` abduction step

app/controllers/steps/alternatives/start_controller.rb, app/services/c100_app/alternatives_decision_tree.rb, app/services/c100_app/safety_questions_decision_tree.rb, app/views/steps/alternatives/start/show.en.html.erb, config/routes.rb, spec/controllers/steps/alternatives/start_controller_spec.rb, spec/services/c100_app/alternatives_decision_tree_spec.rb, spec/services/c100_app/safety_questions_decision_tree_spec.rb
Also, disabling for now the `court` step until prototype decides
what to do with it.
=> Add a `start` page to Alternatives journey

app/assets/stylesheets/local/buttons.scss, app/controllers/step_controller.rb, app/controllers/steps/children/names_controller.rb, app/forms/steps/children/names_form.rb, app/services/c100_app/children_decision_tree.rb, app/views/steps/children/names/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20171129153909_add_name_to_children_table.rb, db/schema.rb, spec/controllers/steps/children/names_controller_spec.rb, spec/forms/steps/children/names_form_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb
This is a step using most of the code already created for the concern
`CrudStep` but with some modifications in the form object to be able to
create several children records at once, or update existing ones.
Next children steps now need to be adapted to use the children records
created by this step, to match the prototype, as these are now outdated.
This will be done in a follow-up PR.
=> Add step `children names`

app/controllers/step_controller.rb, app/controllers/steps/applicant/personal_details_controller.rb, app/controllers/steps/children/personal_details_controller.rb, app/controllers/steps/respondent/personal_details_controller.rb, app/forms/base_form.rb, app/forms/concerns/has_one_association_form.rb, app/forms/concerns/single_question_form.rb, app/forms/steps/abduction/international_form.rb, app/forms/steps/abduction/previous_attempt_details_form.rb, app/forms/steps/abduction/risk_details_form.rb, app/forms/steps/children/personal_details_form.rb, app/models/application_record.rb, app/models/c100_application.rb, app/services/base_decision_tree.rb, app/services/c100_app/children_decision_tree.rb, app/views/steps/children/personal_details/_child_row.html.erb, app/views/steps/children/personal_details/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/children/personal_details_controller_spec.rb, spec/forms/steps/applicant/personal_details_form_spec.rb, spec/forms/steps/children/personal_details_form_spec.rb, spec/forms/steps/respondent/personal_details_form_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb
For more complex views, like cycling through all the created children
and editing their details, also showing the child name being edited
in the view, we need a bit of refactor, to have always handy the current
record being edited.
We will need to apply the same changes to to applicants/respondents too.
=> Redo children details

app/controllers/steps/other_children/names_controller.rb, app/controllers/steps/other_children/personal_details_controller.rb, app/controllers/steps/other_children_step_controller.rb, app/forms/steps/other_children/names_form.rb, app/forms/steps/other_children/personal_details_form.rb, app/models/child.rb, app/services/c100_app/children_decision_tree.rb, app/services/c100_app/other_children_decision_tree.rb, app/value_objects/children_type.rb, app/views/steps/other_children/names/edit.html.erb, app/views/steps/other_children/personal_details/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/other_children/names_controller_spec.rb, spec/controllers/steps/other_children/personal_details_controller_spec.rb, spec/forms/steps/other_children/names_form_spec.rb, spec/forms/steps/other_children/personal_details_form_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb, spec/services/c100_app/other_children_decision_tree_spec.rb
This is identical code to the `main children` names step and form object.
Will be refactored and extracted to a module/concern once we also create
some other, like the applicant names, to see how much code we can share
and how to parametrize the attributes/record set.
Still we need to update the `main children` journey to scope the DB
queries. Another PR coming soon for this.
=> Add `other children` journey

app/controllers/steps/children/names_controller.rb, app/controllers/steps/children/personal_details_controller.rb, app/forms/steps/children/names_form.rb, app/models/child.rb, app/services/c100_app/children_decision_tree.rb, app/value_objects/children_type.rb, spec/forms/steps/children/names_form_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb
As we have now 2 kinds of children (primary and secondary) and we are
already scoping the secondary children, we need to also update the
`primary` children steps we had previously created.
Note: primary and secondary are just internal identifiers, not really
showing to the user at any time.
=> Scope the children steps

app/controllers/steps/children/names_controller.rb, app/controllers/steps/children/personal_details_controller.rb, app/controllers/steps/other_children/names_controller.rb, app/controllers/steps/other_children/personal_details_controller.rb, app/forms/steps/children/names_form.rb, app/forms/steps/other_children/names_form.rb, app/forms/steps/other_children/personal_details_form.rb, app/models/c100_application.rb, app/models/other_child.rb, app/models/person.rb, app/services/c100_app/children_decision_tree.rb, app/services/c100_app/other_children_decision_tree.rb, app/value_objects/person_type.rb, db/migrate/20171206093223_create_people_table.rb, db/migrate/20171207092509_drop_children_table.rb, db/schema.rb, spec/forms/steps/children/names_form_spec.rb, spec/forms/steps/other_children/names_form_spec.rb, spec/forms/steps/other_children/personal_details_form_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb, spec/services/c100_app/other_children_decision_tree_spec.rb
This creates a table with all the common details that we need to ask
about all the different parties (applicants, respondents, children...)
Dropped the children table in favour of this new table.
The next steps are to replace the `applicants` and `respondents` tables
with this one, and in the process, implement the `Names` step to ask for
the names of said people, the same we are doing with the children, and
hopefully extract all the shared and duplicated code to some superclass
or module to reuse.
=> Unify in one table the common details of people

app/controllers/steps/applicant/relationship_controller.rb, app/forms/steps/applicant/relationship_form.rb, app/models/c100_application.rb, app/models/child.rb, app/models/person.rb, app/models/relationship.rb, app/services/base_decision_tree.rb, app/services/c100_app/applicant_decision_tree.rb, app/value_objects/relation.rb, app/views/steps/applicant/relationship/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20171218141037_create_relationships_table.rb, db/schema.rb, spec/controllers/steps/applicant/relationship_controller_spec.rb, spec/forms/steps/applicant/relationship_form_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/support/relationship_step_controller_shared_examples.rb, spec/value_objects/relation_spec.rb
This step will create the relationship between each applicant and
each child. The same will apply to respondents and other parties, and
we should be able to extract most of the code to a module/superclass.
=> Add `relationship` step to Applicants

app/controllers/steps/other_parties/relationship_controller.rb, app/services/c100_app/other_parties_decision_tree.rb, app/views/steps/other_parties/relationship/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/other_parties/relationship_controller_spec.rb, spec/services/c100_app/other_parties_decision_tree_spec.rb
Just using the previously created code.
Again, some repetition in the decision tree, which probably will be
extracted sooner rather than later as all these decision trees
(applicants, respondents, other parties) share almost identical steps
(names, personal details, relationships and contact details).
=> Add `relationship` step to OtherParty

config/application.rb, db/migrate/20180108123316_enable_pgcrypto_extension.rb, db/schema.rb
Since version 9.4, the PostgreSQL community recommends moving away
from uuid-ossp's UUID generation functions and using pcrypto's
gen_random_uuid() instead.
Rails 5.1 uses `gen_random_uuid()` by default instead of previous
one `uuid_generate_v4()` so we need to enable the extension. For old
migrations, the old function continues to apply so this is only needed
for new migrations from now on.
**Note**: lots of indentation changes and removing default btree for 
indexes in `schema.rb` file, autogenerated by Rails 5.1.x `db:migrate`
=> Enable `pgcrypto` PostgreSQL extension

README.md, lib/tasks/mutant.rake
As the project grows, mutant is taking a huge amount of time to finish,
and lately Travis can't handle it, killing the build after 45 mins or so.
With these changes, by default mutant will run in a smaller sample of
classes but still can be run on the whole project manually.
Updated README to explain the options.
=> Speed up mutant, reducing scope by default

.travis.yml, app/controllers/steps/children/residence_controller.rb, app/forms/steps/children/residence_form.rb, app/models/child.rb, app/models/child_residence.rb, app/services/c100_app/children_decision_tree.rb, app/services/c100_app/other_parties_decision_tree.rb, app/services/c100_app/respondent_decision_tree.rb, app/views/steps/children/residence/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180108145551_create_child_residences_table.rb, db/schema.rb, spec/controllers/steps/children/residence_controller_spec.rb, spec/forms/steps/children/residence_form_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb, spec/services/c100_app/other_parties_decision_tree_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb
This step will show a list of names (checkboxes) of all people previously created (applicants, respondents and "other parties" but not children and other children, obviously) and let the user choose who each of the children lives with.
There is also an `other` checkbox to reveal a hidden panel with a text field input.
=> Add children residence step

Gemfile.lock, app/forms/steps/children/personal_details_form.rb, app/forms/steps/other_children/personal_details_form.rb, app/forms/steps/other_parties/personal_details_form.rb, app/forms/steps/respondent/personal_details_form.rb, app/views/steps/children/personal_details/edit.html.erb, app/views/steps/other_children/personal_details/edit.html.erb, app/views/steps/other_parties/personal_details/edit.html.erb, app/views/steps/respondent/personal_details/edit.html.erb, config/locales/en.yml, spec/forms/steps/children/personal_details_form_spec.rb, spec/forms/steps/other_children/personal_details_form_spec.rb, spec/forms/steps/other_parties/personal_details_form_spec.rb, spec/forms/steps/respondent/personal_details_form_spec.rb
The `govuk_elements_form_builder` gem has been updated to support
revealing panels triggered by checkboxes in a similar way to what we
already had for radio options.
Now we can implement this missing feature, mimicking the prototype.
Link to the PR (existing PR, new commit for check boxes):
https://github.com/ministryofjustice/govuk_elements_form_builder/pull/95
=> Add approximate age revealing panels

app/controllers/steps/applicant/under_age_controller.rb, app/controllers/steps/respondent/under_age_controller.rb, app/forms/steps/shared/under_age_form.rb, app/services/c100_app/applicant_decision_tree.rb, app/services/c100_app/respondent_decision_tree.rb, app/views/steps/applicant/under_age/edit.html.erb, app/views/steps/respondent/under_age/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/applicant/under_age_controller_spec.rb, spec/controllers/steps/respondent/under_age_controller_spec.rb, spec/forms/steps/shared/under_age_form_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb
This applies to applicants and respondents.
For respondents, for now only validating the DoB, not the free text 'approximate' age/year field. This can be a refinement when we have more time and are sure of the rules.
A bit of duplication which I considered refactor but then I thought only for 2 instances it doesn't make too much sense and this way makes the code more explicit and easy to read. If we end up having this age validation in more parties, then it might make more sense.
=> Implement the `under age` validation/step

README.md, lib/tasks/mutant.rake
I realised we don't need to run mutant on all models, as most of them
are 'empty shells' for ActiveRecord relationships, and we don't even
have corresponding spec tests for those, so there is no point including
these in the mutation test, and thus we can save some time.
=> Make mutant faster

app/forms/steps/abduction/international_form.rb, app/views/steps/abduction/international/edit.html.erb, app/views/steps/help_with_fees/help_paying/edit.html.erb, config/locales/en.yml, spec/forms/steps/abduction/international_form_spec.rb
As we can now use revealing panels triggered by checkboxes, this is
one of the views where we can start using it.
Also updated form object to reset the free text input when the `other`
checkbox is unselected, to not leave leftovers in DB.
=> Update international abduction markup with panel

app/controllers/steps/international/jurisdiction_controller.rb, app/controllers/steps/international/request_controller.rb, app/controllers/steps/international/resident_controller.rb, app/controllers/steps/international_step_controller.rb, app/forms/steps/international/jurisdiction_form.rb, app/forms/steps/international/request_form.rb, app/forms/steps/international/resident_form.rb, app/services/c100_app/application_decision_tree.rb, app/services/c100_app/international_decision_tree.rb, app/views/steps/international/jurisdiction/edit.html.erb, app/views/steps/international/request/edit.html.erb, app/views/steps/international/resident/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180112105909_add_international_fields.rb, db/schema.rb, spec/controllers/steps/international/jurisdiction_controller_spec.rb, spec/controllers/steps/international/request_controller_spec.rb, spec/controllers/steps/international/resident_controller_spec.rb, spec/forms/steps/international/jurisdiction_form_spec.rb, spec/forms/steps/international/request_form_spec.rb, spec/forms/steps/international/resident_form_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/services/c100_app/international_decision_tree_spec.rb, spec/support/form_validation_shared_examples.rb
3 new yes-no steps, but with a linked, revealing panel for a text area.
As this is going to be common pattern for a few remaining steps, I've updated the shared spec examples to cope with this extra linked attribute.
=> Add `international` steps

app/forms/steps/applicant/contact_details_form.rb, app/forms/steps/other_parties/contact_details_form.rb, app/forms/steps/respondent/contact_details_form.rb, app/views/steps/applicant/contact_details/edit.html.erb, app/views/steps/other_parties/contact_details/edit.html.erb, app/views/steps/respondent/contact_details/edit.html.erb, config/locales/en.yml, db/migrate/20180117154337_rename_postcode_unknown_field.rb, db/migrate/20180117160059_remove_postcode_field.rb, db/schema.rb, spec/forms/steps/applicant/contact_details_form_spec.rb, spec/forms/steps/other_parties/contact_details_form_spec.rb, spec/forms/steps/respondent/contact_details_form_spec.rb
The postcode is to be included in the `address` text area, and the previously named `postcode_unknown` is now `address_unknown`.
Removed `postcode` from everywhere.
A bit of fields reordering in the contact forms.
=> Remove postcodes from all parties

app/controllers/steps/abuse_concerns/applicant_info_controller.rb, app/controllers/steps/abuse_concerns/children_info_controller.rb, app/services/c100_app/abuse_concerns_decision_tree.rb, app/views/steps/abuse_concerns/applicant_info/show.en.html.erb, app/views/steps/abuse_concerns/children_info/show.en.html.erb, app/views/steps/abuse_concerns/start/show.en.html.erb, config/routes.rb, spec/controllers/steps/abuse_concerns/applicant_info_controller_spec.rb, spec/controllers/steps/abuse_concerns/children_info_controller_spec.rb, spec/services/c100_app/abuse_concerns_decision_tree_spec.rb
Add a couple of info pages, one before the start of children abuse concerns, and the other at the end of this journey and the beginning of applicant abuse concerns.
This matches the latest version of prototype.
=> Add concerns info pages

app/controllers/steps/miam_exemptions/safety_controller.rb, app/controllers/steps/miam_exemptions/urgency_controller.rb, app/controllers/steps/miam_exemptions_step_controller.rb, app/forms/steps/miam_exemptions/safety_form.rb, app/forms/steps/miam_exemptions/urgency_form.rb, app/models/c100_application.rb, app/models/exemption.rb, app/services/c100_app/abuse_concerns_decision_tree.rb, app/services/c100_app/miam_exemptions_decision_tree.rb, app/views/steps/miam_exemptions/safety/edit.html.erb, app/views/steps/miam_exemptions/urgency/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180119102958_create_exemptions_table.rb, db/schema.rb, spec/controllers/steps/miam_exemptions/safety_controller_spec.rb, spec/controllers/steps/miam_exemptions/urgency_controller_spec.rb, spec/forms/steps/miam_exemptions/safety_form_spec.rb, spec/forms/steps/miam_exemptions/urgency_form_spec.rb, spec/services/c100_app/abuse_concerns_decision_tree_spec.rb, spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
This will set the foundations of the MIAM exemptions (so still lots of things to do).
Initially this PR introduces the **Safety** exemptions and the **Urgency** exemptions, but only with a limited group of exemptions as an initial version.
As this PR otherwise would grow too much, better to get something functional out. Next to do would be introduce the rest of exemptions groups (for which we have the DB table fields) and refactor them in a sensible way to be able to handle validations, resets, etc. into a ValueObject.
=> Add initial MIAM exemption steps

app/assets/stylesheets/application.scss
Added style properties to the following stylesheet so that the rails application page https://c100-demo.herokuapp.com/entrypoint/what_is_needed matches the styling of the prototype.
app/assets/stylesheets/application.scss
fixes #112
=> Chg style of what-is-needed page

.travis.yml
Danger is slowing down Steph PR's and my time is limited to help
resolve these conflicts, so Danger has to go temporarily.
=> Disabling `Danger` checks temporarily

Gemfile, Gemfile.lock
I can't believe the day has come where we can again use the latest
published version of this gem :-)
This version includes the PRs needed for radio/checkbox reveal panels,
=> Using latest version of `govuk_elements_form_builder`

app/assets/stylesheets/local/pdf_summary.scss, app/presenters/summary/base_answer.rb, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/risk_concerns.rb, app/views/steps/completion/shared/_risk_concerns.html.erb, app/views/steps/completion/shared/_risk_concerns.pdf.erb, config/locales/summary/en.yml, spec/presenters/summary/base_answer_spec.rb, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/risk_concerns_spec.rb
This involved a weirdly crafted table inside another table which is horrible but the PDF renders just well.
=> Add `Concerns about risk` section to PDF

app/presenters/petition_presenter.rb, spec/presenters/petition_presenter_spec.rb
So we can render and iterate the PDF quickly, without having to go
through all of the questions. In this case, the render was blowing
up if we didn't answer the `Petition` orders step.
=> Protect from a nil asking order

app/presenters/summary/date_answer.rb, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/children_details.rb, app/presenters/summary/sections/mediator_certification.rb, app/views/steps/completion/shared/_date_row.html.erb, app/views/steps/completion/shared/_date_row.pdf.erb, config/locales/en.yml, config/locales/summary/en.yml, spec/presenters/summary/date_answer_spec.rb, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/children_details_spec.rb, spec/presenters/summary/sections/mediator_certification_spec.rb
There are 2 missing bits of information we need to ask in the MIAM steps but there is no design in the prototype yet, so holding on it for now.
The rest is pretty straight forward.
Added a new Date answer to handle the format locale properly.
=> Add mediator details section to PDF

app/assets/stylesheets/local/pdf_summary.scss, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/applicants_details.rb, app/presenters/summary/sections/children_details.rb, app/presenters/summary/separator.rb, app/views/steps/completion/shared/_separator.html.erb, app/views/steps/completion/shared/_separator.pdf.erb, config/locales/summary/en.yml, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/applicants_details_spec.rb, spec/presenters/summary/sections/children_details_spec.rb, spec/presenters/summary/separator_spec.rb
There are some things missing that will be added as part of another PR to not grow this one too much.
The good news is, for respondents and 'other parties' is going to look very similar or identical and we may be able to share a lot of code.
=> Add `applicants` section to PDF

app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/applicants_details.rb, app/presenters/summary/sections/people_details.rb, app/presenters/summary/sections/respondents_details.rb, config/locales/summary/en.yml, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/applicants_details_spec.rb, spec/presenters/summary/sections/respondents_details_spec.rb
This was done reusing/refactoring the code we had for applicants. I expect to be able to use it for 'other parties' too, which is very similar.
=> Add `respondents` section to PDF

.rubocop.yml, app/presenters/relationships_presenter.rb, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/children_relationships.rb, app/presenters/summary/sections/other_parties_details.rb, app/presenters/summary/sections/people_details.rb, config/locales/summary/en.yml, spec/presenters/relationships_presenter_spec.rb, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/applicants_details_spec.rb, spec/presenters/summary/sections/children_relationships_spec.rb, spec/presenters/summary/sections/other_parties_details_spec.rb, spec/presenters/summary/sections/respondents_details_spec.rb
Including a bit of refactor of the relationships to a presenter to be reused in several of the sections.
=>  Add `other parties` details to PDF

app/assets/stylesheets/local/pdf_summary.scss, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/base_children_details.rb, app/presenters/summary/sections/children_details.rb, app/presenters/summary/sections/other_children_details.rb, app/views/steps/completion/shared/_date_row.pdf.erb, app/views/steps/completion/shared/_free_text_row.pdf.erb, app/views/steps/completion/shared/_multi_answer_row.pdf.erb, app/views/steps/completion/shared/_row.pdf.erb, config/locales/summary/en.yml, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/other_children_details_spec.rb
Small refactor to reuse as much as possible between `children` and `other children` sections, as they are quite similar.
Also, this is prepared to show the relationships, but we are not asking for them in the case of 'other children' (we do only for 'children' - main ones). So next PR will modify the steps to ask for this.
=> Add `other children` section to PDF

app/controllers/concerns/relationship_step.rb, app/forms/steps/shared/relationship_form.rb, app/models/c100_application.rb, app/models/child.rb, app/models/minor.rb, app/models/other_child.rb, app/models/person.rb, app/models/relationship.rb, app/presenters/relationships_presenter.rb, app/services/c100_app/applicant_decision_tree.rb, app/services/c100_app/other_parties_decision_tree.rb, app/services/c100_app/respondent_decision_tree.rb, app/services/people_decision_tree.rb, app/views/steps/shared/_relationship_step.html.erb, config/locales/summary/en.yml, db/migrate/20180205101502_rename_relationships_foreign_key.rb, db/schema.rb, lib/tasks/mutant.rake, spec/presenters/relationships_presenter_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/other_parties_decision_tree_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb, spec/support/relationship_step_controller_shared_examples.rb
This was missing from the rails app (and I think also the prototype) but was confirmed with Andy it is needed.
Due to this oversight we didn't model properly the Child and OtherChild in first place and now a substantial refactor had to be made, introducing an intermediate model called `Minor` (inheriting from `Person`) and then our current models `Child` and `OtherChild` can inherit from `Minor`.
This allows us to create relationships between a 'person' (being these applicant, respondent or other party) and a 'minor' (being these child or other child). And to retrieve all kind of children using `#minors`.
=> Implement `Other children` relationships

app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/solicitor_details.rb, config/locales/summary/en.yml, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/solicitor_details_spec.rb
This is always a hardcoded `NO` answer, for pilot, as we are screening
out people with a solicitor.
=> Add `solicitor details` section to PDF

.rubocop.yml, app/presenters/c8_confidentiality_presenter.rb, app/presenters/summary/sections/people_details.rb, config/locales/summary/en.yml, spec/presenters/c8_confidentiality_presenter_spec.rb, spec/presenters/summary/sections/applicants_details_spec.rb, spec/presenters/summary/sections/other_parties_details_spec.rb, spec/presenters/summary/sections/respondents_details_spec.rb
If the applicant enables the confidentiality of personal details,
then the C100 PDF form will hide a limited set of details and will
generate an extra C8 form with the omitted details.
This PR only implements the 'hiding' of details in a flexible way,
but not yet the output of the C8 form.
=> Implement C8 details confidentiality

app/assets/stylesheets/local/pdf_summary.scss, app/models/c100_application.rb, app/presenters/c8_confidentiality_presenter.rb, app/presenters/summary/answer_box.rb, app/presenters/summary/c8_form.rb, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/c8_court_details.rb, app/views/steps/completion/shared/_answer_box.pdf.erb, config/locales/summary/en.yml, spec/models/c100_application_spec.rb, spec/presenters/c8_confidentiality_presenter_spec.rb, spec/presenters/summary/answer_box_spec.rb, spec/presenters/summary/c8_form_spec.rb, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/c8_court_details_spec.rb
This PR generates a C8 form if required based on address confidentiality question, and append it to the PDF bundle together with the 3 copies of the C100.
Only a small section of the first page has been implemented for now. Following PRs will implement more sections.
=> Implement C8 - Part I

app/assets/stylesheets/local/pdf_summary.scss, app/presenters/summary/c8_form.rb, app/presenters/summary/partial.rb, app/presenters/summary/sections/c8_court_details.rb, app/views/steps/completion/shared/_blank_space.pdf.erb, app/views/steps/completion/shared/_c8_instructions.en.pdf.erb, config/locales/summary/en.yml, spec/presenters/summary/c8_form_spec.rb, spec/presenters/summary/partial_spec.rb, spec/presenters/summary/sections/c8_court_details_spec.rb
Using  localised partial (`_c8_instructions.en.pdf.erb`)
Also changed the previous 'blank_space' to be a partial too, for consistency.
=> Add C8 form instructions

app/presenters/c8_confidentiality_presenter.rb, app/presenters/relationships_presenter.rb, app/presenters/summary/c100_form.rb, app/presenters/summary/sections/children_relationships.rb, app/presenters/summary/sections/children_residence.rb, spec/presenters/c8_confidentiality_presenter_spec.rb, spec/presenters/relationships_presenter_spec.rb, spec/presenters/summary/c100_form_spec.rb, spec/presenters/summary/sections/children_relationships_spec.rb, spec/presenters/summary/sections/children_residence_spec.rb
If confidentiality has been triggered, then we need to completely
hide `other parties` relationships, if there are any other parties.
Also eventually we will need to do a similar thing for the residence
details, but leaving it for now until I have confirmation.
A bit of refactor to split into two separate section presenters the
relationships and the residence.
=> C8 handling for `other parties` relationships

app/presenters/summary/c100_form.rb, app/presenters/summary/sections/other_court_cases.rb, config/locales/summary/en.yml, spec/presenters/summary/c100_form_spec.rb, spec/presenters/summary/sections/other_court_cases_spec.rb
As we have now the corresponding step, we can finish this section in
the C100 PDF.
=> Add `Other court cases` section to C100 PDF

app/forms/steps/children/residence_form.rb, app/presenters/summary/sections/children_residence.rb, app/views/steps/children/residence/edit.html.erb, config/locales/en.yml, config/locales/summary/en.yml, db/migrate/20180219161354_remove_other_residence_field.rb, db/schema.rb, spec/forms/steps/children/residence_form_spec.rb, spec/presenters/summary/sections/children_residence_spec.rb
This removes the `other` checkbox and its associated text field input, as
it is not neccessary for pilot.
C100 pdf form updated to not show the names but just the 'type' of
the person, i.e. Applicant, Respondent or Other.
Fixes #202
=> Remove `other` from the Residence step

config/locales/en.yml
This is a shared screen between applicants and children so making
some copy generic to cope with both (no need to overcomplicate things).
=> Make copy generic to cope with applicants and children

app/forms/steps/applicant/contact_details_form.rb, app/forms/steps/respondent/contact_details_form.rb, app/views/steps/respondent/contact_details/edit.html.erb, config/locales/en.yml, spec/forms/steps/applicant/contact_details_form_spec.rb, spec/forms/steps/respondent/contact_details_form_spec.rb
Remove the `I don't know` checkboxes for mobile and email, and also
validate the email only if present, for both applicant and respondent.
Some minor copy changes.
Fixes #200 #201
=> Simplify contact details form

app/assets/stylesheets/local/pdf_summary.scss, app/models/c100_application.rb, app/presenters/summary/c1a_form.rb, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/c100_court_details.rb, app/presenters/summary/sections/c1a_court_details.rb, app/presenters/summary/sections/risk_concerns.rb, app/services/c100_app/miam_exemptions_decision_tree.rb, config/locales/summary/en.yml, spec/models/c100_application_spec.rb, spec/presenters/summary/c100_form_spec.rb, spec/presenters/summary/c1a_form_spec.rb, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/c100_court_details_spec.rb, spec/presenters/summary/sections/c1a_court_details_spec.rb, spec/presenters/summary/sections/risk_concerns_spec.rb
Individual commits with more contextual details to make it easier to see what is going on.
This will just render (if safety concerns triggered) a small portion of the C1A, the admin section.
It is a start.
=> Implement the basics of the C1A form

app/presenters/summary/c1a_form.rb, app/presenters/summary/sections/c1a_applicant_details.rb, config/locales/summary/en.yml, spec/presenters/summary/c1a_form_spec.rb, spec/presenters/summary/sections/c1a_applicant_details_spec.rb
A few details related to the (first) applicant.
=> Implement `applicant details` C1A section

app/presenters/summary/c1a_form.rb, app/presenters/summary/sections/c1a_children_details.rb, app/presenters/summary/sections/c1a_solicitor_details.rb, config/locales/summary/en.yml, spec/presenters/summary/c1a_form_spec.rb, spec/presenters/summary/sections/c1a_children_details_spec.rb, spec/presenters/summary/sections/c1a_solicitor_details_spec.rb
And also the solicitor section, which is always set to NO.
=> Implement `children details` C1A section

app/presenters/summary/c1a_form.rb, app/presenters/summary/sections/c1a_children_other_abuse_details.rb, config/locales/summary/en.yml, spec/presenters/summary/c1a_form_spec.rb, spec/presenters/summary/sections/c1a_children_other_abuse_details_spec.rb
This is the same as the previously implemented abuse concerns, but
only for kind `other` and only for children.
=> Add `children other abuse` section

app/controllers/steps/children/orders_controller.rb, app/controllers/steps/petition/orders_controller.rb, app/controllers/steps/petition/playback_controller.rb, app/forms/form_attribute_methods.rb, app/forms/steps/petition/orders_form.rb, app/models/asking_order.rb, app/models/c100_application.rb, app/presenters/petition_presenter.rb, app/presenters/summary/sections/nature_of_application.rb, app/value_objects/petition_order.rb, app/views/steps/petition/orders/edit.html.erb, app/views/steps/petition/playback/show.html.erb, config/locales/en.yml, config/locales/summary/en.yml, db/migrate/20180227130146_add_orders_fields.rb, db/migrate/20180228111024_drop_asking_orders_table.rb, db/schema.rb, spec/controllers/steps/petition/playback_controller_spec.rb, spec/forms/steps/children/orders_form_spec.rb, spec/forms/steps/petition/orders_form_spec.rb, spec/presenters/petition_presenter_spec.rb, spec/presenters/summary/sections/nature_of_application_spec.rb, spec/value_objects/petition_order_spec.rb
This follows the same mechanism as the MIAM exemptions, so we don’t
need to create dozens of DB fields, just we use a value-object to hold
the different values and can be grouped and extended/modified more
easily.
Lots of copy changes.
=> Refactor petition orders to use value-object

app/presenters/summary/sections/mediator_certification.rb, config/locales/summary/en.yml, spec/presenters/summary/sections/mediator_certification_spec.rb
Just a static sentence, if there is certification details. If no
certification we return `non applicable`.
=> Add HMCTS instructions sentence

app/controllers/users/drafts_controller.rb, app/controllers/users/logins_controller.rb, app/controllers/users/registrations_controller.rb, app/forms/steps/screener/email_consent_form.rb, app/mailers/notify_mailer.rb, app/models/user.rb, app/services/c100_app/save_application_for_later.rb, app/views/layouts/_current_user_menu.html.erb, app/views/users/drafts/index.html.erb, app/views/users/logins/logged_out.html.erb, app/views/users/logins/save_confirmation.html.erb, app/views/users/registrations/save_confirmation.html.erb, app/views/users/registrations/update_confirmation.html.erb, app/views/users/shared/_application_saved.html.erb, config/application.rb, config/govuk_notify_templates.yml, config/locales/en.yml, config/routes.rb, lib/tasks/mutant.rake, spec/controllers/users/drafts_controller_spec.rb, spec/controllers/users/logins_controller_spec.rb, spec/controllers/users/passwords_controller_spec.rb, spec/controllers/users/registrations_controller_spec.rb, spec/helpers/authentication_helpers_spec.rb, spec/mailers/notify_mailer_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/services/c100_app/save_application_for_later_spec.rb, spec/support/notify_mailer_shared_examples.rb
Most of the code came from https://github.com/ministryofjustice/tax-tribunals-datacapture and we can use it "as it is" without any change, which is great.
Some other code will need to change to cater to the requirements of this service, but for now this PR will sets the basics.
=> Implement Save & Return basics

app/helpers/application_helper.rb, app/mailers/notify_mailer.rb, app/views/application/_step_header.html.erb, app/views/home/cookies.en.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, spec/helpers/application_helper_spec.rb
Sort out the mess with the service name and titles, and unify it in a
sensible way to ever touch in one place if we need to change it again.
=> Update service name and titles

app/assets/stylesheets/local/tables.scss, app/controllers/application_controller.rb, app/controllers/concerns/savepoint_step.rb, app/controllers/errors_controller.rb, app/controllers/steps/miam/consent_order_controller.rb, app/controllers/users/drafts_controller.rb, app/errors/errors.rb, app/mailers/notify_mailer.rb, app/models/c100_application.rb, app/models/user.rb, app/presenters/draft_presenter.rb, app/views/errors/application_not_found.html.erb, app/views/users/drafts/_draft_row.html.erb, app/views/users/drafts/index.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180305101934_add_application_status_field.rb, db/schema.rb, spec/controllers/application_controller_spec.rb, spec/controllers/steps/miam/consent_order_controller_spec.rb, spec/controllers/users/drafts_controller_spec.rb, spec/mailers/notify_mailer_spec.rb, spec/models/c100_application_spec.rb, spec/presenters/draft_presenter_spec.rb, spec/support/step_controller_shared_examples.rb
Renders the current user drafts and allows to delete or resume any of them.
Still we don’t know if we will limit this to only 1 draft, but for now, it mimics very much TaxTribs.
More context in separate commits.
=> Implement the drafts portfolio functionality

app/mailers/notify_mailer.rb, app/services/c100_app/draft_reminders.rb, app/services/c100_app/reminder_rule_set.rb, config/govuk_notify_templates.yml, lib/tasks/daily_tasks.rake, spec/mailers/notify_mailer_spec.rb, spec/services/c100_app/draft_reminders_spec.rb, spec/services/c100_app/reminder_rule_set_spec.rb
This will be triggered by a daily task.
We setup 2 draft expire reminders, one to be sent when 5 days left and another one to be sent when 1 day left.
The mechanism is flexible enough to setup as many reminders as we want to trigger at specific moments in time.
=> Implement draft reminder emails

app/assets/stylesheets/application.scss, app/assets/stylesheets/local/developer_tools.scss, app/controllers/concerns/savepoint_step.rb, app/controllers/entrypoint_controller.rb, app/controllers/sessions_controller.rb, app/controllers/steps/miam/child_protection_cases_controller.rb, app/controllers/steps/miam/consent_order_controller.rb, app/controllers/steps/screener/done_controller.rb, app/controllers/steps/screener/start_controller.rb, app/services/base_decision_tree.rb, app/services/c100_app/screener_decision_tree.rb, app/views/application/_developer_tools.html.erb, app/views/entrypoint/how_long.en.html.erb, app/views/entrypoint/what_is_needed.en.html.erb, app/views/layouts/application.html.erb, app/views/steps/screener/done/show.html.erb, app/views/steps/screener/start/show.en.html.erb, config/routes.rb, spec/controllers/entrypoint_controller_spec.rb, spec/controllers/steps/miam/child_protection_cases_controller_spec.rb, spec/controllers/steps/miam/consent_order_controller_spec.rb, spec/controllers/steps/screener/done_controller_spec.rb, spec/controllers/steps/screener/start_controller_spec.rb, spec/services/c100_app/screener_decision_tree_spec.rb, spec/support/step_controller_shared_examples.rb
Reorganise the screener steps, introduce a start and done steps, and make sure back links, etc. are consistent.
Also, to simplify some repetitive tasks, added a developer tools section in the footer to bypass the screener or reset the session.
=> Screener reordering

app/presenters/relationships_presenter.rb, app/presenters/summary/sections/c8_other_parties_details.rb, app/presenters/summary/sections/people_details.rb, spec/presenters/relationships_presenter_spec.rb, spec/presenters/summary/sections/applicants_details_spec.rb, spec/presenters/summary/sections/c8_applicants_details_spec.rb, spec/presenters/summary/sections/c8_other_parties_details_spec.rb, spec/presenters/summary/sections/other_parties_details_spec.rb, spec/presenters/summary/sections/respondents_details_spec.rb
We were hiding the relationships details for Other Parties in the C8 form. This solves the issue.
=> Fix for C8 Other Party relationships

app/controllers/steps/petition/playback_controller.rb, app/controllers/steps/petition/protection_controller.rb, app/forms/steps/petition/protection_form.rb, app/services/c100_app/petition_decision_tree.rb, app/views/steps/petition/playback/show.html.erb, app/views/steps/petition/protection/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180309155937_add_children_protection_fields.rb, db/schema.rb, spec/controllers/steps/petition/playback_controller_spec.rb, spec/controllers/steps/petition/protection_controller_spec.rb, spec/forms/steps/petition/protection_form_spec.rb, spec/services/c100_app/petition_decision_tree_spec.rb
This was a missing step.
Simple Yes/No question, with revealing text area when choosing Yes.
=> Add C1A step `Protection Orders`

app/services/c100_app/alternatives_decision_tree.rb, spec/services/c100_app/alternatives_decision_tree_spec.rb
The condition was swapped. We go to the alternatives, if there are NOT safety concerns.
Also, using the C100Application helper method, instead of repeating again the same implementation.
=> Fix alternatives to court route

app/presenters/summary/sections/risk_concerns.rb, app/views/steps/completion/shared/_risk_concerns.pdf.erb, spec/presenters/summary/sections/risk_concerns_spec.rb
Apart from the "top level" question, and as it can be NO, we need to check if there are C1A abuse concerns for applicants and children too.
=> Include C1A answers in risk concerns

app/controllers/steps/application/declaration_controller.rb, app/forms/steps/application/declaration_form.rb, app/services/c100_app/application_decision_tree.rb, app/views/steps/application/declaration/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180313105729_add_declaration_made_field.rb, db/schema.rb, spec/controllers/steps/application/declaration_controller_spec.rb, spec/forms/steps/application/declaration_form_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb
Declaration step to go before the `What's next`.
The checkbox is functional but the error message doesn't link properly. This is due to the way form_builder works. I will try to figure out why.
We have this same problem in at least a couple of other steps.
=> Add `declaration` step

app/assets/stylesheets/application.scss, app/assets/stylesheets/local/inputs.scss, app/assets/stylesheets/local/typography.scss, app/helpers/custom_form_helpers.rb, app/views/steps/alternatives/court/edit.en.html.erb, app/views/steps/application/declaration/edit.html.erb, app/views/steps/miam/acknowledgement/edit.en.html.erb, app/views/steps/miam_exemptions/adr/edit.html.erb, app/views/steps/miam_exemptions/domestic/edit.html.erb, app/views/steps/miam_exemptions/misc/edit.html.erb, app/views/steps/miam_exemptions/protection/edit.html.erb, app/views/steps/miam_exemptions/urgency/edit.html.erb, app/views/steps/other_parties/contact_details/edit.html.erb, app/views/steps/respondent/contact_details/edit.html.erb, config/locales/en.yml, spec/helpers/custom_form_helpers_spec.rb
The `govuk_elements_form_builder` gem doesn't provide with an easy way to render single, individual checkboxes, instead of groups of checkboxes.
We had several places in the app where individual checkboxes were neccessary and this solve the issue with the error messages not being rendered properly and not linking from the error summary.
It follows GOV.UK elements pattern.
=> Implement single checkbox form helper

config/locales/en.yml
We don't use "Please" for error messages.
=> Remove `please` in error messages

README.md, app/controllers/application_controller.rb, set_heroku_env_vars.sh
This env var is only set if a specific plugin is enabled on Heroku. If we ever move out of Heroku this will not make sense. Better to have a specific.
=> Do not rely on `HEROKU_APP_NAME` env var

app/assets/stylesheets/local/typography.scss, app/controllers/application_controller.rb, app/controllers/concerns/completion_step.rb, app/controllers/concerns/error_handling.rb, app/controllers/concerns/savepoint_step.rb, app/controllers/errors_controller.rb, app/controllers/sessions_controller.rb, app/controllers/step_controller.rb, app/controllers/steps/completion/what_next_controller.rb, app/controllers/steps/screener_step_controller.rb, app/errors/errors.rb, app/views/errors/application_completed.html.erb, app/views/errors/application_not_found.html.erb, app/views/errors/application_screening.html.erb, app/views/errors/unhandled.html.erb, app/views/steps/completion/what_next/show.html.erb, app/views/steps/screener/start/show.en.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/application_controller_spec.rb, spec/controllers/steps/completion/what_next_controller_spec.rb, spec/support/relationship_step_controller_shared_examples.rb, spec/support/step_controller_shared_examples.rb
Introduce a `CompletionStep` concern to mark the final step when an application is considered completed, so, for example, it doesn't appear anymore in drafts, and we don't send email reminders anymore about it.
Also, check the application is not still screening in case the user had a bookmark, or enter a URL manually.
The copy for the errors is TBD.
=> Handle c100 status

Gemfile.lock
This should finally remove the github security vulnerability alert.
=> Bump loofah due to CVE-2018-8048

app/controllers/steps/screener/error_but_continue_controller.rb, app/views/steps/screener/error_but_continue/show.html.erb, config/locales/en.yml, spec/controllers/steps/screener/error_but_continue_controller_spec.rb
Differentiate between an unrecognised postcode, and the courtfinder API being down, showing slightly different wording for each case
OR
=> Improve the exit page for an error checking postcode. 

app.json
This config file tells Heroku which environment variables to copy from staging when cloning the app. It will lets Heroku automatically generate disposable 'review' apps from submitted PRs
=> add app.json to enable Heroku review apps

app/value_objects/petition_order.rb, config/locales/en.yml, spec/presenters/petition_presenter_spec.rb, spec/value_objects/petition_order_spec.rb
as per https://trello.com/c/gXzOD0fG/217-nature-of-application-remove-2-options
=> remove _contact and _access options from petition order + form

config/environments/production.rb
as per [section 4.5 in the pentest report](https://docs.google.com/document/d/1xG5GNKTnBHToawfH00kVOEf_LY2jEZKNlVeORgaMr4A/edit?ts=5ab8e04d#heading=h.hbjovvwcsyy8) & the corresponding [Trello card](https://trello.com/c/Nc55Lv5X/222-enforce-ssl-only-and-add-hypertext-sts-header)
=> Force SSL-only in production

app/views/steps/applicant/under_age/edit.html.erb, app/views/steps/respondent/under_age/edit.html.erb, config/locales/en.yml
as per [the Trello card](https://trello.com/c/rZPQYXVG/226-applicant-respondent-under-age)
=> add what-next content to under_age exits

app/controllers/concerns/error_handling.rb, config/environments/development.rb, config/initializers/session_store.rb
Looked like the session timeout environment variable wasn't being obeyed in the app session timeout (see [Trello card](https://trello.com/c/IZbQV29E/229-check-session-timeout-on-production-rebecca-brawn-getting-several-session-timeouts-at-much-less-than-1hr-intervals)).
This seems to fix the issue (although it's difficult to provide a test case to prove it)
=> fix session timeout env var being ignored by app

app/controllers/steps/screener/error_but_continue_controller.rb, app/presenters/summary/sections/children_details.rb, app/value_objects/petition_order.rb, config/locales/summary/en.yml, spec/controllers/steps/screener/error_but_continue_controller_spec.rb, spec/presenters/summary/sections/children_details_spec.rb, spec/value_objects/petition_order_spec.rb
rather than the more verbose description of the sub-type, as per [Trello card](https://trello.com/c/uG9mTt8T/230-pdf-issue-change-information-displayed-in-orders-applied-for-to-the-actual-order-type)
=> show petition order type in PDF children details -> orders applied for section

app/controllers/errors_controller.rb, app/views/errors/not_found.html.erb, config/locales/en.yml, config/routes.rb, db/schema.rb
This will show a "nice" 404 page when hitting an unrecognized URL.
On localhost however it will continue to show the error trace to help debugging.
=> Add missing 404 page

app/forms/steps/petition/orders_form.rb, spec/forms/steps/petition/orders_form_spec.rb
as per [the Trello card](https://trello.com/c/EfenlGuO/101-pdf-issues-reset-text-area-db-column-when-other-issue-checkbox-in-petition-orders-is-unselected)
=> reset other issue details text area when checkbox is not selected

app/controllers/application_controller.rb, app/controllers/concerns/error_handling.rb, app/controllers/concerns/security_handling.rb, app/controllers/sessions_controller.rb, app/views/errors/invalid_session.html.erb, app/views/home/cookies.en.html.erb, config/initializers/session_store.rb, config/locales/en.yml, spec/controllers/application_controller_spec.rb
* Revert to session-only cookie, so once the browser is closed, the session is revoked.
* In addition to the already existing JS expire mechanism, add a request-based check to ensure the cookie is no older than X, and if so, reset the session. This should add an extra layer of protection in case JS fails or there is no JS available.
=> Improvements to the session expire mechanism

app.json
This only affects the review apps. We don't have or need a worker.
=> Remove worker from Heroku formation

app/assets/stylesheets/local/app.scss, app/views/errors/unhandled.html.erb, app/views/layouts/_sentry_feedback.html.erb
This nice feature from Sentry will show a modal window for users to provide optional feedback about what caused the error, including providing their email for a potential follow-up.
The modal can be closed without providing feedback, as it is optional, and also it will not show without JS (obviously) but will not stop our normal error page from showing.
=> Add sentry user-feedback to the unhandled error page

app/forms/concerns/miam_exemptions_form.rb, app/helpers/custom_form_helpers.rb, config/locales/en.yml, spec/forms/steps/miam_exemptions/adr_form_spec.rb, spec/forms/steps/miam_exemptions/domestic_form_spec.rb, spec/forms/steps/miam_exemptions/misc_form_spec.rb, spec/forms/steps/miam_exemptions/protection_form_spec.rb, spec/forms/steps/miam_exemptions/urgency_form_spec.rb, spec/helpers/custom_form_helpers_spec.rb
This will introduce a basic validation to ensure at least one valid exemption was selected by the user, otherwise they have to select 'none of these' checkbox.
Also it ensures the user can't get away with just selecting top-level group checkboxes without selecting anything inside the group.
=> Introduce validations in MIAM exemptions

app/assets/javascripts/modules/ga-events.js, app/views/steps/completion/what_next/show.en.html.erb
Also, removing target blank in the PDF download to minimise the risk of popup blockers intercepting the download.
=> Disable JS logging

app/forms/steps/application/previous_proceedings_form.rb, app/forms/steps/court_orders/has_orders_form.rb, app/forms/steps/miam/exemption_claim_form.rb, app/forms/steps/safety_questions/risk_of_abduction_form.rb, spec/forms/steps/application/previous_proceedings_form_spec.rb, spec/forms/steps/court_orders/has_orders_form_spec.rb, spec/forms/steps/miam/exemption_claim_form_spec.rb, spec/forms/steps/safety_questions/risk_of_abduction_form_spec.rb
Thanks to ActiveRecord this is pretty straight forward.
We just provide the name of the `has_one` attribute, and Rails will delete the whole row in the associated table, if it exists.
=> Reset of `HasOneAssociationForm` fields

app/assets/stylesheets/local/check_answers.scss, app/forms/steps/miam/attended_form.rb, app/forms/steps/miam/certification_form.rb, app/presenters/summary/answers_group.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/child_protection_cases.rb, app/presenters/summary/html_sections/miam_requirement.rb, app/views/steps/completion/shared/_answers_group.html.erb, app/views/steps/completion/shared/_date_row.html.erb, app/views/steps/completion/shared/_free_text_row.html.erb, app/views/steps/completion/shared/_free_text_row.pdf.erb, app/views/steps/completion/shared/_row.html.erb, app/views/steps/completion/shared/_section.html.erb, config/locales/en.yml, config/locales/summary/en.yml, spec/forms/steps/miam/attended_form_spec.rb, spec/forms/steps/miam/certification_form_spec.rb, spec/presenters/summary/answers_group_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/child_protection_cases_spec.rb, spec/presenters/summary/html_sections/miam_requirement_spec.rb
This is a first version of the check your answers page.
Only the first few questions (MIAM attendance) are shown, and in any case this is not yet integrated into the user journey so will only be visible if the URL is known.
We can iterate on this and if we are happy, start adding more and more question/answers.
=> Basic `check your answers`

app/controllers/users/drafts_controller.rb, app/models/c100_application.rb, app/models/user.rb, app/views/users/drafts/index.html.erb, config/locales/en.yml, spec/controllers/users/drafts_controller_spec.rb
If we know the application is completed, when the user clicks the link from the confirmation email, instead of giving them an 'application not found' error, we can take them directly to the `what next` page, where they can read the instructions again, and download the PDF if they wish to do so.
This should improve a the experience for at least one user we've detected having issues resuming their application (as it was completed and no longer shown in the drafts page).
=> Allow resuming a completed application

app/services/c100_app/court_postcode_checker.rb, spec/services/c100_app/court_postcode_checker_spec.rb
The court postcode checker was looking for _any_ match in the list of courts returned by the courtfinder API. This caused a situation where someone with an Oxford postcode was sent to Milton Keynes court, when they should have been told they were ineligible.
This PR changes the check to only consider the _first_ (ie. closest) court in the list of results. 
As a side-effect of this change, Slough postcodes would now be ineligible - so I have added Slough court to the list of courts in the trial. Their postal & email addresses are listed in Courtfinder as those of Reading Court Administration Centre, so that is where the user will be told to send their PDFs, as desired.
(All the above has been discussed & agreed with Alejandra)
=> make eligibility check & destination address only consider closest court

app/assets/stylesheets/local/lists.scss, app/assets/stylesheets/local/utilities.scss, app/views/steps/completion/what_next/show.en.html.erb
A few copy amendments and adding some callouts to the `what next` page, as detailed here:
https://trello.com/c/CBVF9OKR
=> Copy amendments to `what next` page

app/services/c100_app/court_postcode_checker.rb, spec/services/c100_app/court_postcode_checker_spec.rb
After much discussion, the team (including Alejandra) have decided that PR #365 should stand - even though that means a couple of Reading postcodes will not be considered eligible as their closest court in courtfinder is Oxford.
If this highlights something not right in the setup of the Courtfinder data, then we should fix that _in Courtfinder_, rather than trying to special-case it in a downstream service. That way lies more legacy lock-in headaches for the future.
This reverts commit f2c466955016ff8d5f8f7dd2a79d2597b4fbbc00.
=> re-apply "make eligibility check & dest'n address only consider closest court" (#365)

app/presenters/miam_exemptions_presenter.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/miam_exemptions.rb, app/views/steps/completion/shared/_multi_answer_row.html.erb, config/locales/summary/en.yml, spec/presenters/miam_exemptions_presenter_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/miam_exemptions_spec.rb
Show, in groups, the MIAM exemptions selected by the user, if any, and link to each of the exemption pages directly.
The copy is still WIP and we should review it to simplify and shorten as much as possible so is easy to check by the user without having lots of copy to read.
Also the layout might change but this follows the current CYA layout and is 100% responsive (for mobile devices), so leaving it for now.
=> Add MIAM exemptions to Check your answers

app/controllers/users/drafts_controller.rb, app/views/entrypoint/how_long.en.html.erb, app/views/errors/application_completed.html.erb, app/views/users/drafts/_draft_row.html.erb, app/views/users/drafts/index.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/users/drafts_controller_spec.rb
As discussed, and based in google analytics findings, some changes to the drafts page:
- Completed applications are also visible and accessible using the link 'How to submit'
- Link 'how to submit' leads to a variation of '/what_next' page URL, called '/how_to_submit' - content is exactly the same, it's purely for analytics
For consistency, updated some copy in this and other pages.
=> Show complete applications in drafts page

app/views/steps/shared/_finish_button.html.erb, app/views/users/logins/logged_out.html.erb, app/views/users/passwords/reset_sent.html.erb, app/views/users/registrations/save_confirmation.html.erb, app/views/users/registrations/update_confirmation.html.erb, config/locales/en.yml
Previously links, now these are buttons as they are the main call-to-action, and in one instance, a button as main action and a link as secondary action.
https://trello.com/c/lx6ptfL6
=> Change to buttons some CTA

app/assets/stylesheets/local/check_answers.scss, app/presenters/summary/answers_group.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/base_children_details.rb, app/presenters/summary/html_sections/children_details.rb, app/views/steps/completion/shared/_answers_group.html.erb, app/views/steps/completion/shared/_date_row.html.erb, app/views/steps/completion/shared/_free_text_row.html.erb, app/views/steps/completion/shared/_multi_answer_row.html.erb, app/views/steps/completion/shared/_row.html.erb, app/views/steps/completion/shared/_section.html.erb, app/views/steps/completion/shared/_separator.html.erb, config/locales/summary/en.yml, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/children_details_spec.rb
Also fix broken HTML structure in the summary, replacing wrapper DL's with wrapper divs, and pushing the DL elements to the individual answers.
_NOTE_ this does not include the "do you have any other children?" sections, that will be a separate PR
=> Add check answers children details

app/controllers/sessions_controller.rb
(Only relevant to dev/staging environments)
The bypass was creating duplicate screener_answers entries if a valid c100_application was already in the session.
This will solve it.
=> Avoid screener dup entries when using the bypass

app/views/entrypoint/v1.en.html.erb, app/views/entrypoint/what_is_needed.en.html.erb, app/views/steps/completion/what_next/show.en.html.erb
- Copy amendments in the `What is needed` bullet list.
- Changed to lede the first paragraph in the entry page.
- If user is logged in, we can hide the download callout in the `what_next` page.
=> More copy changes

app/presenters/summary/answers_group.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/base_abuse_details.rb, app/presenters/summary/html_sections/children_abuse_details.rb, config/locales/summary/en.yml, spec/presenters/summary/answers_group_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/children_abuse_details_spec.rb
The applicant section will follow the same structure, only the header will change.
I will do it as part of another PR.
=>  Add `children abuse` section to CYA

app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/applicant_abuse_details.rb, config/locales/summary/en.yml, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/applicant_abuse_details_spec.rb, spec/presenters/summary/html_sections/children_abuse_details_spec.rb
Same as children, but for applicant.
=> Add `applicant abuse` section to CYA

app/presenters/summary/html_sections/nature_of_application.rb, config/locales/summary/en.yml, spec/presenters/summary/html_sections/nature_of_application_spec.rb
We need to include in this section the protection orders question and details, if C1A triggered.
=> Update `nature of application` section in CYA

app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/applicants_details.rb, app/presenters/summary/html_sections/people_details.rb, app/views/steps/completion/shared/_separator.html.erb, config/locales/summary/en.yml, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/applicants_details_spec.rb
Still we need to figure out where to place the relationships and how to present these.
The respondents and other parties will follow the same structure and will inherit from the superclass.
=> Add `applicants` section to CYA

app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/children_details.rb, app/presenters/summary/html_sections/children_further_information.rb, config/locales/summary/en.yml, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/children_details_spec.rb, spec/presenters/summary/html_sections/children_further_information_spec.rb
Make it a separate section to stand out. This was previously inside the Children section.
=> Add children `further information` section to CYA

app/presenters/summary/base_answer.rb, app/presenters/summary/html_sections/applicants_details.rb, app/presenters/summary/html_sections/other_parties_details.rb, app/presenters/summary/html_sections/people_details.rb, app/presenters/summary/html_sections/respondents_details.rb, app/views/steps/completion/shared/_free_text_row.html.erb, app/views/steps/completion/shared/_free_text_row.pdf.erb, app/views/steps/completion/shared/_row.html.erb, app/views/steps/completion/shared/_row.pdf.erb, config/locales/cya/en.yml, spec/presenters/summary/base_answer_spec.rb, spec/presenters/summary/html_sections/applicants_details_spec.rb, spec/presenters/summary/html_sections/other_parties_details_spec.rb, spec/presenters/summary/html_sections/respondents_details_spec.rb
Unfortunately it is just too much work to try to fit this into an AnswerGroup, as technically, it is not a single group. Each of the relations, require their own links, and that's just not possible with an AnswerGroup (the change links would not even appear in the right column, to start with).
So this is the second best approach.
=>  Add children relationships section to people

app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/attending_court.rb, config/locales/cya/en.yml, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/attending_court_spec.rb
This groups together most of the last questions of the service.
The only remaining one, that will go in a different section, is "Help with fees".
=> Add `attending court` section to CYA

app/controllers/application_controller.rb, app/controllers/concerns/error_handling.rb, app/controllers/concerns/security_handling.rb, spec/controllers/application_controller_spec.rb, spec/controllers/steps/screener/start_controller_spec.rb
* We are going to send to Sentry `ActionController::InvalidAuthenticityToken` exceptions, to have visibility in case this is an issue we are hiding.
* When the server-side code that checks the validity of a session "considers" the session has expired, we are going to silently send to Sentry an exception with some debug data (the user will notice nothing, just the same error page as before).
* Make sure we also reset the `last_seen` when resetting the c100 application session data.
=> Improve debug of expiring sessions

app/views/entrypoint/how_long.en.html.erb, app/views/steps/miam/certification_date/edit.html.erb, config/locales/en.yml
* Remove the paragraph about not being able to check your answers at the end of the service, as we now have CYA in place (for now, only staging).
* Add certification date hint text.
=> Improvements based on UR feedback

.travis.yml, Gemfile, Gemfile.lock, README.md, features/support/env.rb, lib/tasks/all_tests.rake, lib/tasks/brakeman.rake, lib/tasks/cucumber.rake, lib/tasks/mutant.rake, lib/tasks/rubocop.rake, lib/tasks/travis.rake, spec/rails_helper.rb, spec/spec_helper.rb
Cucumber was not able to run on travis-ci, so we had to run it locally only.
This PR:
* fixes the issue
* still allows cucumber to be run locally and pointed at arbitrary servers via the CUCUMBER_URL env var
* refactors the rake tasks to only hook into the default task prerequisites in one place rather than everywhere in unclear order
* updates the README to reflect the change from using EXTERNAL_URL to CUCUMBER_URL
=> Make cucumber tests work on travis

app/controllers/sessions_controller.rb
If we are destroying the session, there is little point on running the validity code, which can give us race conditions and raise false alarms in Sentry.
Bypassing this, for `destroy` session action.
=> Do not check session validity on delete

app/presenters/summary/base_pdf_form.rb, app/presenters/summary/blank_page.rb, app/presenters/summary/partial.rb, app/presenters/summary/pdf_presenter.rb, app/presenters/summary/sections/risk_concerns.rb, app/services/c100_app/pdf_generator.rb, app/views/steps/completion/shared/_blank_page.pdf.erb, app/views/steps/completion/shared/_risk_concerns.pdf.erb, config/locales/pdf/en.yml, spec/presenters/summary/blank_page_spec.rb, spec/presenters/summary/partial_spec.rb, spec/presenters/summary/pdf_presenter_spec.rb, spec/presenters/summary/sections/risk_concerns_spec.rb, spec/services/c100_app/pdf_generator_spec.rb
* Add C8 instructions to risk concerns PDF section.
* Insert a blank page before C8 form (if triggered).
(individual commits for easier PR review)
=> Insert a blank page before C8 form

app/presenters/summary/blank_page.rb, config/locales/pdf/en.yml, spec/presenters/c8_confidentiality_presenter_spec.rb, spec/presenters/relationships_presenter_spec.rb
There is some text included in the PDF that is not user input text, but instead added by us to give instructions to the courts or to indicate a section is not applicable for this user.
Make this copy more evident, more 'computer generated' kind of.
=> Copy changes to PDF non-user text

app/controllers/concerns/security_handling.rb
For the purposes of this debug logging, we only care about the sessions with a current application ID.
Otherwise we get too much noise.
=> Only log exception for valid sessions

app/controllers/steps/application/payment_controller.rb, app/forms/steps/application/payment_form.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/payment.rb, app/services/c100_app/application_decision_tree.rb, app/value_objects/payment_type.rb, app/views/steps/application/payment/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/routes.rb, db/migrate/20180521113047_add_payment_fields.rb, db/schema.rb, spec/controllers/steps/application/payment_controller_spec.rb, spec/forms/steps/application/payment_form_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/payment_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/value_objects/payment_type_spec.rb
This, eventually, will replace the current `help paying` step, but for now it only shows in dev/staging environments, in order to do user testing.
Also updated the CYA to support this new step and set of questions (only on staging).
=> Add new `payment` step, behind feature flag

Aptfile, app.json, config/initializers/wicked_pdf.rb
Sometime in the last few days Heroku has migrated our envs from Cedar16 to Heroku18, which doesn't have the libxrender1 at runtime (only buildtime) and that was breaking our PDF generation.
This makes sure libxrender1 is installed as part of the deployment process.
=> Wickedpdf config with buildpack

app/assets/stylesheets/local/pdf_summary.scss
After the change in Heroku stacks, the PDF fonts are not consistent between local/dev and production envs.
This makes sure we use Arial as a first attempt, which should be available in Heroku stacks.
It is actually the font we've been using up until now (`nta` seemed not to be available regardless).
=> Remove `nta` from PDF font-family

app/assets/stylesheets/local/app.scss, app/controllers/steps/application/submission_controller.rb, app/forms/steps/application/submission_form.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/submission.rb, app/services/c100_app/application_decision_tree.rb, app/value_objects/submission_type.rb, app/views/steps/application/submission/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/routes.rb, db/migrate/20180525105634_add_submission_fields.rb, db/schema.rb, spec/controllers/steps/application/submission_controller_spec.rb, spec/forms/steps/application/submission_form_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/submission_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/value_objects/submission_type_spec.rb
This will capture the user decision to send the application online (and if so, optionally the email for a receipt) or print and post.
Also updated the CYA to show these details.
Only visible on local/staging environments. Still kind of a prototype, WIP, things may change.
=> Add `submission` step (feature-flagged)

app/controllers/concerns/completion_step.rb, app/controllers/steps/application/check_your_answers_controller.rb, app/controllers/steps/completion/confirmation_controller.rb, app/models/c100_application.rb, app/presenters/summary/html_presenter.rb, app/services/c100_app/application_decision_tree.rb, app/views/steps/application/check_your_answers/edit.html.erb, app/views/steps/completion/confirmation/show.en.html.erb, app/views/steps/completion/what_next/show.en.html.erb, app/views/steps/shared/_court_help.en.html.erb, app/views/steps/shared/_download_instructions.en.html.erb, app/views/steps/shared/_payment_instructions.en.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/application/check_your_answers_controller_spec.rb, spec/controllers/steps/completion/confirmation_controller_spec.rb, spec/controllers/steps/completion/what_next_controller_spec.rb, spec/models/c100_application_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/support/step_controller_shared_examples.rb
Depending on whether it is an online submission or a print and post, we customise a bit the CYA copy and continue button label.
And DRY a bit the current what next and new confirmation pages to use common partials.
=> Application submitted confirmation page

app/models/c100_application.rb, app/models/concerns/application_reference.rb, app/services/c100_app/pdf_generator.rb, app/views/steps/completion/confirmation/show.en.html.erb, spec/models/concerns/application_reference_spec.rb, spec/services/c100_app/pdf_generator_spec.rb
This reference code is just a simple short version of the created_at, and the UUID of the application.
The purpose is mainly give the user peace of mind having a reference code to confirm their application has been sent and to be able to cross-reference in the future PDF with their codes in case the user wants to know about their application.
Will also be sent in the receipt email if the user chose to.
=> Add a reference code to PDF and confirmation page

config/initializers/court_email_interceptor.rb, lib/court_email_interceptor.rb, spec/lib/court_email_interceptor_spec.rb
In order to avoid inadvertently sending to court test, not real, applications, once we integrate the online submission.
This interceptor works on a whitelist basis, letting through emails that are 'safe' to send, and intercepting others, based on their `delivery_handler`.
=> Add an email interceptor intended for dev/test envs

lib/court_email_interceptor.rb, spec/lib/court_email_interceptor_spec.rb
Cancelling the delivery with `message.perform_deliveries = false` was not having an effect, so to not spam courts, we will send instead this emails to our google group.
If the reply-to is present, we continue using this.
=> Fix interceptor when there is no reply-to address

app/models/cumulative_data.rb, db/migrate/20180605110750_cumulative_data_table.rb, db/schema.rb, lib/tasks/daily_tasks.rake
As our retention policy is quite restrictive (28 days for applications), and in order to quickly answer question like `how many applications were submitted last week`, etc. we need a way to persist totals for the most common metrics.
In GA we have almost all of this information too, so not really spending too much time here duplicating something GA do quite well.
Run daily through `daily_tasks.rake`
=> Very basic application stats

app/lib/short_url_expander.rb, app/models/short_url.rb, config/routes.rb, db/migrate/20180606145430_short_urls_table.rb, db/schema.rb, lib/tasks/mutant.rake, lib/tasks/short_urls.rake, spec/lib/short_url_expander_spec.rb, spec/models/short_url_spec.rb
This works together with our new 'shorter' domain CNAME `c100.dsd.io`
Short urls can be added and/or listed via a rake task as a first step. In the future, and if needed, we can expose a simple CRUD admin page, but at the moment this is the MVP to be able to produce short URLs with tracking.
=> Add a simple URL shortener feature

app/controllers/concerns/completion_step.rb, app/models/completed_applications_audit.rb, db/migrate/20180608081404_create_completed_applications_audit_table.rb, db/schema.rb, lib/tasks/misc.rake, lib/tasks/mutant.rake, spec/models/completed_applications_audit_spec.rb, spec/support/step_controller_shared_examples.rb
We will record an audit log with a few details about applications completed, intended for analytics past the 28 days retention time.
Simple rake task to prepopulate the table with whatever data we still hold.
=> Completed applications audit

app/controllers/steps/application/urgent_hearing_controller.rb, app/controllers/steps/application/urgent_hearing_details_controller.rb, app/forms/steps/application/urgent_hearing_details_form.rb, app/forms/steps/application/urgent_hearing_form.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/urgent_hearing_details.rb, app/presenters/summary/sections/additional_information.rb, app/presenters/summary/sections/urgent_hearing.rb, app/services/c100_app/application_decision_tree.rb, app/views/steps/application/urgent_hearing/edit.html.erb, app/views/steps/application/urgent_hearing_details/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/pdf/en.yml, config/routes.rb, db/migrate/20180608112820_add_urgent_hearing_fields.rb, db/schema.rb, spec/controllers/steps/application/urgent_hearing_controller_spec.rb, spec/controllers/steps/application/urgent_hearing_details_controller_spec.rb, spec/forms/steps/application/urgent_hearing_details_form_spec.rb, spec/forms/steps/application/urgent_hearing_form_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/urgent_hearing_details_spec.rb, spec/presenters/summary/sections/additional_information_spec.rb, spec/presenters/summary/sections/urgent_hearing_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb
The screener question is still there, as we don't know yet if we are going to release this to production or not. 
* If we release this, I will create a follow-up PR to remove the screener question.
* If we are not releasing just yet, then I will need to create a follow-up PR to bypass these new steps in production, so these don't show, and everything continues to behave as it is now (with the screening question present).
PDF:
=> Implement `urgent hearing` steps

app/controllers/steps/applicant/has_solicitor_controller.rb, app/controllers/steps/solicitor/contact_details_controller.rb, app/controllers/steps/solicitor/personal_details_controller.rb, app/controllers/steps/solicitor_step_controller.rb, app/forms/steps/applicant/has_solicitor_form.rb, app/forms/steps/solicitor/contact_details_form.rb, app/forms/steps/solicitor/personal_details_form.rb, app/models/c100_application.rb, app/models/solicitor.rb, app/services/c100_app/applicant_decision_tree.rb, app/services/c100_app/solicitor_decision_tree.rb, app/views/steps/applicant/has_solicitor/edit.html.erb, app/views/steps/solicitor/contact_details/edit.html.erb, app/views/steps/solicitor/personal_details/edit.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180611114319_add_solicitor_fields.rb, db/migrate/20180611122325_create_solicitors_table.rb, db/schema.rb, spec/controllers/steps/applicant/has_solicitor_controller_spec.rb, spec/controllers/steps/solicitor/contact_details_controller_spec.rb, spec/controllers/steps/solicitor/personal_details_controller_spec.rb, spec/forms/steps/applicant/has_solicitor_form_spec.rb, spec/forms/steps/solicitor/contact_details_form_spec.rb, spec/forms/steps/solicitor/personal_details_form_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/solicitor_decision_tree_spec.rb
Note: the screener question is still present, will be removed as part of a future PR. Also, CYA and PDF not yet updated to show the solicitor details. 
If yes:
* solicitor personal details
* solicitor contact details
=> Add solicitor steps

app/models/user.rb, spec/models/user_spec.rb
Devise was already validating the presence of the email, but not the syntax.
This will ensure an error is also returned to the user if the email is malformed.
=> Improve user email validation

app/presenters/summary/c100_form.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/sections/court_fee.rb, app/services/c100_app/application_decision_tree.rb, app/value_objects/payment_type.rb, app/views/steps/application/payment/edit.html.erb, app/views/steps/application/submission/edit.html.erb, app/views/steps/completion/confirmation/show.en.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/pdf/en.yml, spec/forms/steps/application/payment_form_spec.rb, spec/presenters/summary/c100_form_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/payment_spec.rb, spec/presenters/summary/sections/court_fee_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/value_objects/payment_type_spec.rb
This replaces the current Help with fees step. The old Help with fees code has not been removed yet, until we are sure we don't need it anymore.
And in the PDF:
=> Reintroduce and update `Payment` step

app/views/steps/application/details/edit.html.erb, config/locales/en.yml
People seem to take longer in this step than others, so adding a warning about the session expiring.
=>  Add timeout warning in application details

app/presenters/summary/sections/c1a_solicitor_details.rb, app/presenters/summary/sections/solicitor_details.rb, config/locales/pdf/en.yml, spec/presenters/summary/sections/c1a_solicitor_details_spec.rb, spec/presenters/summary/sections/solicitor_details_spec.rb
We already had this sections but hardcoded to `no`. Now it will show the details if present.
=> Add solicitor details to C100 and C1A pdf

app/mailer_previews/submission_mailer_preview.rb, app/mailers/court_mailer.rb, app/mailers/receipt_mailer.rb, app/mailers/submission_mailer.rb, app/views/mailers/court_mailer/submission_to_court.en.html.erb, app/views/mailers/court_mailer/submission_to_court.en.text.erb, app/views/mailers/shared/_technical_help.en.html.erb, app/views/mailers/shared/_technical_help.en.text.erb, spec/mailers/court_mailer_spec.rb, spec/mailers/receipt_mailer_spec.rb, spec/support/submission_mailer_shared_examples.rb
Instead of the generic `someone` we want the applicant full name to appear in the email sent to court (if there are more than 1 applicant only the first one is considered).
Reorganised a bit the code and specs as a side effect of this.
=> Add applicant name to email sent to court

app/assets/stylesheets/local/pdf_summary.scss, app/services/c100_app/pdf_generator.rb, app/views/steps/completion/shared/_admin_court_and_case_number.pdf.erb, app/views/steps/completion/shared/_admin_date_issued.en.pdf.erb, app/views/steps/completion/shared/_admin_orders_applied_for.pdf.erb, app/views/steps/completion/shared/_answer_box.pdf.erb, config/locales/pdf/en.yml, spec/services/c100_app/pdf_generator_spec.rb
In each of these forms, there is an area to be filled by the court.
We can make these inputs fillable in the generated PDF with some minor changes to our markup.
=> Make C100, C1A and C8 fillable inputs

app/assets/javascripts/modules/session-timeout.js, app/controllers/concerns/security_handling.rb, spec/controllers/application_controller_spec.rb
TL;DR: if opening multiple tabs, the session can be inadvertently expired in one of the non-active tabs, while the user is still filling the form in another tab, because of the javascript timers.
This small change makes the `forceAbort()` function non-destructive to avoid this scenario.
=> Protect against JS inadvertently expiring the session

app/controllers/steps/screener/legal_representation_controller.rb, app/controllers/steps/screener/legal_representation_exit_controller.rb, app/forms/steps/screener/legal_representation_form.rb, app/presenters/summary/html_sections/solicitor_details.rb, app/services/c100_app/applicant_decision_tree.rb, app/services/c100_app/screener_decision_tree.rb, app/views/entrypoint/v1.en.html.erb, app/views/entrypoint/what_is_needed.en.html.erb, app/views/steps/screener/legal_representation/edit.html.erb, app/views/steps/screener/legal_representation_exit/show.html.erb, app/views/steps/screener/start/show.en.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20180612135807_remove_legal_representation_field_from_screener_answers.rb, db/migrate/20180622102800_add_screener_answers_legal_rep_again.rb, db/schema.rb, features/screener.feature, spec/controllers/steps/screener/legal_representation_controller_spec.rb, spec/controllers/steps/screener/legal_representation_exit_controller_spec.rb, spec/forms/steps/screener/legal_representation_form_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/screener_decision_tree_spec.rb
As we are not releasing just yet the solicitor details steps, we must introduce again the screening question, and do not show the solicitor steps.
Also some other copy changes for consistency.
=> Revert the removal of legal rep screening question

app/views/layouts/mailer.html.erb, app/views/mailers/receipt_mailer/copy_to_user.en.html.erb, app/views/mailers/receipt_mailer/copy_to_user.en.text.erb, app/views/mailers/shared/_court_help.en.html.erb, app/views/mailers/shared/_court_help.en.text.erb, app/views/steps/completion/confirmation/show.en.html.erb, spec/mailers/receipt_mailer_spec.rb
For electronic submissions, do not just say 'your application has been sent to the court' but instead show the actual name of the court.
And a bit of styling amendments.
=> Show the name of the court in confirmation and email

Gemfile, Gemfile.lock, app/models/email_submission.rb, app/services/c100_app/pdf_email_submission.rb, spec/services/c100_app/pdf_email_submission_spec.rb
This basically is so we don't inadvertently send duplicated emails that were already sent.
But also, so we can manually `nil` the corresponding `message_id` attribute (for court or for user copy) and let us send a manual duplicate email, which in some cases, like bounces, we need to do.
=> Make online submission email code idempotent

Gemfile, Gemfile.lock
A known vulnerability was found in version `3.7.1` so declaring `3.7.2` in Gemfile until Rails bump their dependencies.
=> Bump version of sprockets due to vulnerability

app/mailer_previews/submission_mailer_preview.rb, app/mailers/court_mailer.rb, app/services/c100_app/pdf_email_submission.rb, app/views/mailers/court_mailer/submission_to_court.en.html.erb, app/views/mailers/court_mailer/submission_to_court.en.text.erb, app/views/mailers/shared/_technical_help.en.html.erb, app/views/mailers/shared/_technical_help.en.text.erb, lib/court_email_interceptor.rb, spec/lib/court_email_interceptor_spec.rb, spec/mailers/court_mailer_spec.rb, spec/mailers/receipt_mailer_spec.rb, spec/services/c100_app/pdf_email_submission_spec.rb, spec/support/submission_mailer_shared_examples.rb
* Removed the `reply_to` header in the court email, as that was potentially flagging the email as spam.
* Added a generic message to let court know they shouldn't reply directly to the email.
* Removed the service URL from court email body, as that might also be causing spam issues.
=> Reduce chances of court email being marked as spam

app/views/steps/abuse_concerns/details/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml
C8 confidentiality question, and add an explanation block to abuse detail pages.
* In the address confidentiality question:
* In each of the abuse detail pages:
=> Update some copy based on feedback

app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/app/pros_cons.scss, app/assets/stylesheets/local/app/sidebar.scss, app/assets/stylesheets/local/utilities.scss, app/forms/steps/abuse_concerns/details_form.rb, app/presenters/summary/sections/c1a_base_abuse_details.rb, app/views/steps/abuse_concerns/applicant_info/show.en.html.erb, app/views/steps/abuse_concerns/children_info/show.en.html.erb, app/views/steps/abuse_concerns/details/edit.html.erb, app/views/steps/abuse_concerns/start/show.html.erb, app/views/steps/children/has_other_children/edit.html.erb, app/views/steps/safety_questions/start/show.en.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/pdf/en.yml, spec/forms/steps/abuse_concerns/details_form_spec.rb
Implemeting some copy changes and other user interface elements to streamline and make more clear why we are gathering some of the data.
Make all fields in the abuse details optional.
Still WIP and requires policy sign-off.
=> Copy changes to C1A journeys

config/locales/pdf/en.yml
This copy (and the ones in the previous PR) has now been signed off.
=> Copy change for C1A details absense

app/views/steps/screener/start/show.en.html.erb
New copy:
`This trial is also taking place in Cardiff. A Welsh language version will be available after the trial is completed.`
=> Minor Cardiff copy change

app/models/short_url.rb, config/application.rb, db/migrate/20180712101836_add_visits_to_short_urls_table.rb, db/schema.rb, lib/tasks/short_urls.rake, spec/controllers/sessions_controller_spec.rb, spec/models/short_url_spec.rb
This will allow us to track visits to external URLs where we don't have easy access to analytics (in particular, will be used as part of the bot experiment).
=> Add a visits counter to short urls

app/models/court.rb, spec/models/court_spec.rb
If there is an email address with `Family Applications` in the description, we pick that one first, and if not, we try to find as before anything with `Family` in the description.
=> Tweak the court email finder

.travis.yml, lib/tasks/all_tests.rake, lib/tasks/mutant.rake, lib/tasks/travis.rake
The flag `--since=master` can be used to restrict Mutant to only those files which have changed in the current branch as compared to master.
This can massively speed up mutation testing runs (e.g. from 6m down to 100s on a previous PR - https://github.com/ministryofjustice/c100-application/pull/491 )
=> Speed up Mutant task by passing --since-master when on CI

app/presenters/summary/sections/c1a_applicant_details.rb, spec/presenters/summary/sections/c1a_applicant_details_spec.rb
These are considered contact details and should be hidden too in the C1A as we are doing in the C100.
=> Hide phone/email in C1A if C8 was triggered

app/mailer_previews/submission_mailer_preview.rb, app/views/mailers/court_mailer/submission_to_court.en.html.erb, app/views/mailers/court_mailer/submission_to_court.en.text.erb, app/views/mailers/shared/_application_warnings.en.html.erb, app/views/mailers/shared/_application_warnings.en.text.erb, app/views/mailers/shared/_technical_help.en.html.erb, app/views/mailers/shared/_technical_help.en.text.erb, spec/mailers/court_mailer_spec.rb
Just as a heads up, based on some feedback, and because the C8 is included in the application PDF, not as a separated file.
=> Add warning about C8 in email to court

app/views/steps/screener/start/show.en.html.erb
In the screener start page. As that is really all the catchment area.
=> Replace Leeds with West Yorkshire

app/controllers/concerns/error_handling.rb, app/controllers/users/registrations_controller.rb
If, after saving an application, the user starts a new session, there is no associated user anymore and if they go back in the browser history, they might get an exception.
Also, restore `InvalidAuthenticityToken` exceptions as invalid session errors.
=> Protect from nil user

app/views/steps/safety_questions/children_abuse/edit.html.erb, app/views/steps/safety_questions/domestic_abuse/edit.html.erb
Add the `Why do we need this information and what will we do with it?` section in these screens.
=> Add the info link in more places

app/forms/steps/application/payment_form.rb, app/validators/help_with_fees_reference_validator.rb, config/locales/en.yml, spec/forms/steps/application/payment_form_spec.rb
To avoid obvious malformed or fake HWF reference numbers, introduce a simple validation in the Payment form.
=> Validate Help with fees format

app/views/about/cookies.en.html.erb, app/views/about/privacy.en.html.erb, app/views/about/terms_and_conditions.en.html.erb, app/views/entrypoint/v1.en.html.erb, app/views/home/miam_exemptions.en.html.erb, app/views/steps/abuse_concerns/applicant_info/show.en.html.erb, app/views/steps/abuse_concerns/children_info/show.en.html.erb, app/views/steps/abuse_concerns/details/edit.html.erb, app/views/steps/alternatives/collaborative_law/edit.en.html.erb, app/views/steps/alternatives/court/edit.en.html.erb, app/views/steps/alternatives/lawyer_negotiation/edit.en.html.erb, app/views/steps/alternatives/mediation/edit.en.html.erb, app/views/steps/alternatives/negotiation_tools/edit.en.html.erb, app/views/steps/completion/confirmation/show.en.html.erb, app/views/steps/completion/shared/_c1a_getting_support.en.pdf.erb, app/views/steps/completion/what_next/show.en.html.erb, app/views/steps/miam/acknowledgement/edit.en.html.erb, app/views/steps/miam/certification_expired_info/show.html.erb, app/views/steps/miam_exemptions/exit_page/show.en.html.erb, app/views/steps/safety_questions/start/show.en.html.erb, app/views/steps/shared/_court_help.en.html.erb, app/views/steps/shared/_payment_instructions.en.html.erb, config/locales/en.yml
Mobile devices seem to handle properly the opening of these external links in a new tab, but desktop browsers (at least Safari and Chrome) are having trouble.
This has something to do with the JS code we are using to intercept these links and track hits to GA.
Adding back the target (it was there some time ago) to be a explicit link attribute in order to err on the side of caution so desktop browsers open new tabs.
=> Restore target attribute in external links

app/services/people_decision_tree.rb, spec/services/c100_app/other_parties_decision_tree_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb
There was a bug that only now has made appearance due to a Sentry error trace, where we were using the 'minors' collection instead of the 'children' collection in the Residence step.
https://sentry.service.dsd.io/mojds/c100-application-prod/issues/33305/
It was working fine because when using `minor_ids.first` it was always returning a `Child` type first, instead of an `OtherChild`, but, as an edge case, if the applicant deleted some or all of the Child and added later some OtherChild, will alter the returned elements.
This has now been corrected by using always the proper collection (child_ids) for residence, so regardless the order, it can't return an `OtherChild`.
=> Fix bug involving OtherChild residence

app/services/c100_app/court_postcode_checker.rb, app/views/steps/screener/start/show.en.html.erb, spec/services/c100_app/court_postcode_checker_spec.rb
A new court is joining the pilot. Added the slug and updated copy in the screener start page.
=> Add East London family court to the pilot

app/models/abuse_concern.rb, app/presenters/summary/html_sections/base_abuse_details.rb, app/presenters/summary/sections/c1a_base_abuse_details.rb, db/migrate/20181015101148_add_timestamps_to_abuse_concerns.rb, db/schema.rb, spec/presenters/summary/html_sections/applicant_abuse_details_spec.rb, spec/presenters/summary/html_sections/children_abuse_details_spec.rb, spec/presenters/summary/sections/c1a_applicant_abuse_details_spec.rb, spec/presenters/summary/sections/c1a_children_abuse_details_spec.rb, spec/presenters/summary/sections/c1a_children_other_abuse_details_spec.rb
We can't rely on the default sorting by ID as we are using UUIDs.
This had no major impact other than the CYA page showing the abuse concerns in a slighly different order to the one we use when asking for these.
With the addition of timestamps now we can start using it to ensure we show the abuses in the same order they are created.
=> Ensuring consistent abuse concerns order

app/views/layouts/application.html.erb, config/routes.rb, lib/tasks/short_urls.rake
This will ensure we redirect to the new service domain and stop using the dsd.io, which will continue working for some time anyway.
=> Using the new `service` domain

app/assets/javascripts/modules/ga-events.js, app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/utilities.scss, app/views/steps/miam_exemptions/exit_page/show.en.html.erb, config/locales/en.yml
Same as we did in CAIT, we are going to let the user enter a postcode
and do a (GET) request to FMC website to preload results.
Some other copy changes, and extra JS code to cope with new tracking.
=> Add FMC postcode lookup to MIAM kickout page

app/models/court.rb, app/services/c100_app/court_postcode_checker.rb, app/views/steps/screener/start/show.en.html.erb, spec/models/court_spec.rb, spec/services/c100_app/court_postcode_checker_spec.rb
Also some improvements to the way we seek the most suitable court email address, due to the fact some courts are starting to use explanations instead of descriptions.
Updated Newport slug.
=> Add Medway family court to the pilot

app/controllers/concerns/completion_step.rb, spec/support/step_controller_shared_examples.rb
Make this a bit more strict and only mark as completed (and thus audit it) applications `in_progress`, and not like now, those also including the `screening` stage.
=> Only mark as completed if `in_progress`

app/controllers/sessions_controller.rb, app/controllers/steps/screener/start_controller.rb, app/controllers/steps/screener/warning_controller.rb, app/controllers/steps/screener_step_controller.rb, app/views/steps/screener/warning/show.html.erb, app/views/users/drafts/index.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/steps/screener/start_controller_spec.rb, spec/controllers/steps/screener/warning_controller_spec.rb
Before resetting the session and thus risking losing all the progress,
we can warn the user and let them choose to continue with the current
application or to start a new one.
=> Warn user if an application is in progress

app/controllers/concerns/completion_step.rb, spec/support/step_controller_shared_examples.rb
This reverts commit 56b0b3fd274f91c3b5efcbf1a709b889732a9f57.
This was not a good idea, because there are other valid states that can be marked as completed, like the reminders `first_reminder_sent` or `last_reminder_sent`.
Reverting the changes and leaving as it was before.
=> Revert "Only mark as completed if `in_progress`"

app/controllers/concerns/completion_step.rb, app/mailer_previews/submission_mailer_preview.rb, app/views/mailers/receipt_mailer/copy_to_user.en.html.erb, app/views/mailers/receipt_mailer/copy_to_user.en.text.erb, app/views/steps/completion/confirmation/show.en.html.erb, app/views/steps/completion/what_next/show.en.html.erb, app/views/steps/shared/_payment_instructions.en.html.erb, app/views/steps/shared/_payment_instructions.en.text.erb, app/views/steps/shared/_post_instructions.en.html.erb, spec/support/step_controller_shared_examples.rb
Instead of a big catch-all payment instructions block, we are now giving specific payment instructions depending on the payment method (and in some cases the submission method) the applicant chose.
This affects the confirmation pages (online and print&post) and the confirmation email (only for online submission).
=> Improve payment instructions copy

app/views/about/contact.en.html.erb, app/views/layouts/_footer_links.html.erb, app/views/layouts/_phase_banner.html.erb, config/locales/en.yml
Expose a contact page showing the email they can use to get in touch with us.
=> Add link to contact page

config/initializers/devise.rb, config/locales/en.yml, spec/controllers/users/registrations_controller_spec.rb
Following ICO guidance on passwords for online services under GDPR.
=> Increase min pass length

app/forms/steps/applicant/personal_details_form.rb, app/forms/steps/children/personal_details_form.rb, app/forms/steps/miam/certification_date_form.rb, app/forms/steps/other_children/personal_details_form.rb, app/forms/steps/other_parties/personal_details_form.rb, app/forms/steps/respondent/personal_details_form.rb, app/validators/sensible_date_validator.rb, config/locales/en.yml, spec/forms/steps/applicant/personal_details_form_spec.rb, spec/forms/steps/children/personal_details_form_spec.rb, spec/forms/steps/miam/certification_date_form_spec.rb, spec/forms/steps/other_children/personal_details_form_spec.rb, spec/forms/steps/other_parties/personal_details_form_spec.rb, spec/forms/steps/respondent/personal_details_form_spec.rb, spec/support/personal_details_shared_examples.rb
This will validate it is a sensible date, i.e. not in the future, and not older than some given year.
Main purpose is to avoid single or double digit years, as, with the gem we are using, these are left-padded with 0 when printing in the PDF making the date wrong, for example, single digit `8` becomes `0008`.
And also stop clear typos like year `0218` for `2018`.
This is implemented in all parties DOB, and in the MIAM certification date.
=> Implement custom date validator

lib/tasks/mutant.rake
Having this code outside the task means it was running every time any task (not only this one) was invoked. There is no need for this.
=> Move code inside task definition

Gemfile, Gemfile.lock, lib/tasks/cucumber.rake, spec/controllers/users/registrations_controller_spec.rb, spec/models/short_url_spec.rb, spec/rails_helper.rb, spec/support/step_controller_shared_examples.rb
When running mutant con CircleCI sometimes there are DB deadlocks.
This is due to the use of `database_cleaner` gem and not good spec practises to ensure we don't abuse the database.
This should be now solved. We get rid of database_cleaner and fix the offending tests.
=> Remove database_cleaner and fix specs

Gemfile.lock
Fixes CVE-2018-16470 and CVE-2018-16471.
=> Bump `rack` gem

README.md, config/routes.rb
We need to start using the new K8s staging env in our day to day, so this redirect will help.
=> Redirect Heroku staging to K8s cluster

.circleci/config.yml
This will be a bit more useful than just having <none> in the `CHANGE-CAUSE` column.
Another way to do it (but we can't control what the annotation says this way) would be to pass the `--record` flag to the `set image` command.
=> Annotate last deploy in rollout history

app/models/email_submission.rb, app/services/c100_app/online_submission_queue.rb, app/services/c100_app/pdf_email_submission.rb, db/migrate/20181211105507_add_timestamps_to_email_submissions.rb, db/schema.rb, spec/services/c100_app/online_submission_queue_spec.rb, spec/services/c100_app/pdf_email_submission_spec.rb
* Make sure there are no race conditions as 2 jobs try to update the same record in database, sometimes at the same time.
* Also, ensure we can't process by mistake again the jobs, if they were already processed.
* Add a couple timestamps to the DB table to make it easier to debug submissions, in case is needed.
=> Improvements to email submission jobs

app/services/c100_app/notify_callback.rb, spec/services/c100_app/notify_callback_spec.rb
Ensure we lowercase the email address before hashing it (we were already doing the same on the finder).
This will avoid potential mismatches.
=> Avoid email mismatch due to lower/upper case

config/puma.rb
Puma killer is quite pessimistic with the amount of available free memory, so it would kill the workers when there is still enough memory.
We can use the env variable to set the available ram slighly higher (about 120mb higher) than the actual ram, so puma killer do a more accurate job.
=> Tune a bit puma killer

app/mailers/smtp_submission_mailer.rb, app/services/c100_app/online_submission.rb, app/services/c100_app/pdf_email_submission.rb, spec/mailers/court_mailer_spec.rb, spec/mailers/receipt_mailer_spec.rb, spec/services/c100_app/online_submission_spec.rb, spec/services/c100_app/pdf_email_submission_spec.rb
We don't really need a temporary file in disk, and this way we avoid some extra processing/memory overhead.
=> Use StringIO instead of Tempfile

app/models/email_submissions_audit.rb
This method is for debug/diagnosis purposes. Make it so we can query the table only by reference, or by reference + email.
Add some code comments for clarification.
=> Allow lookup without an email

features/screener.feature
The test checks that the right page appears after selecting the 'not a parent' option.
=> Add cucumber test for the not a parent path

app/controllers/crud_step_controller.rb, app/controllers/steps/applicant_step_controller.rb, app/controllers/steps/children_step_controller.rb, app/controllers/steps/other_children_step_controller.rb, app/controllers/steps/other_parties_step_controller.rb, app/controllers/steps/respondent_step_controller.rb, app/forms/steps/applicant/names_split_form.rb, app/forms/steps/other_children/names_split_form.rb, app/forms/steps/other_parties/names_split_form.rb, app/forms/steps/respondent/names_split_form.rb, app/views/steps/applicant/names/edit.html.erb, app/views/steps/children/names/edit.html.erb, app/views/steps/other_children/names/edit.html.erb, app/views/steps/other_parties/names/edit.html.erb, app/views/steps/respondent/names/edit.html.erb, app/views/steps/shared/_existing_names.html.erb, app/views/steps/shared/_new_name.html.erb, config/locales/en.yml, spec/controllers/steps/applicant/names_controller_spec.rb, spec/controllers/steps/children/names_controller_spec.rb, spec/controllers/steps/other_children/names_controller_spec.rb, spec/controllers/steps/other_parties/names_controller_spec.rb, spec/controllers/steps/respondent/names_controller_spec.rb, spec/forms/steps/applicant/names_split_form_spec.rb, spec/forms/steps/other_children/names_split_form_spec.rb, spec/forms/steps/other_parties/names_split_form_spec.rb, spec/forms/steps/respondent/names_split_form_spec.rb, spec/support/step_controller_shared_examples.rb
This will extend the work already done for children in previous PR #584 to all parties:
* applicant
* respondent
* other children
* other parties
Although it looks like A LOT of files, it actually is a very simple change, only multiplied by 4. Individual commits for easier read.
One could argue that's a lot of "duplicated" code, but in this case, given the life expectancy of most of this code will be less than 1 month (until all records in the database are using the new format) and then we are going to clean it up, it is not worth it coming up with another (more complicated) abstraction level.
=> Extend split names to all parties

app/assets/stylesheets/local/forms.scss, app/views/steps/applicant/names/edit.html.erb, app/views/steps/children/names/edit.html.erb, app/views/steps/other_children/names/edit.html.erb, app/views/steps/other_parties/names/edit.html.erb, app/views/steps/respondent/names/edit.html.erb, app/views/steps/shared/_existing_names.html.erb, app/views/steps/shared/_new_name.html.erb
We now ask for both first name and last name in separate text fields
rather than one.
This could potentially lead to confusion when there are multiple names
as there isn't as good distinction between groups of names.
This change switches the font weight to create a visual separation
between the form groups.
=> Update multiple names UI

app/models/court.rb, app/services/c100_app/court_postcode_checker.rb, app/views/steps/screener/start/show.en.html.erb, spec/models/court_spec.rb, spec/services/c100_app/court_postcode_checker_spec.rb
Also, extended the `best_enquiries_email` method to take into consideration also the actual email addresses, as a fallback in case no description or explanation matches.
=> Add Barnstaple court to the trial

app/assets/stylesheets/local/forms.scss, config/locales/exemptions/en.yml
The gem updates made the checkboxes slightly out of alignment on the custom MIAM page. This commit fixes the CSS so that the text now lines up with the checkbox. It also removes <br> elements from the text, which were no longer needed and also causing layout issues because the <span> elements had been given display: block in the gem update.
=> Realign checkboxes in MIAM section

app/helpers/application_helper.rb, config/locales/en.yml, spec/helpers/application_helper_spec.rb
As part of the accessibility audit and being a recommendation by the Design System, if we detect the current page form has errors, we prefix the title with a hint so screen readers know.
https://design-system.service.gov.uk/components/error-summary/
Also, a minor copy change in the error summary title based on the design guidelines.
=> Prefix page title when form has errors

app/assets/stylesheets/local/buttons.scss
Some elements with the class of button-secondary are link tags, and when they are unvisited, their focus state made their text white and therefore unreadable against a whie background. This commit overrides that CSS by explicitely setting a button-secondary focus state text color.
=> Fix focus state on button-secondary links

app/views/steps/safety_questions/start/show.en.html.erb
The current markup for the safety concerns page styles a paragraph
element to visually appear like a heading rather than using a heading
element.
This change swaps the `<p>` and nested `<strong>` tag for a `<h2>`
which makes more sense semantically.
**Note:** It now appears slightly differently visually but this fits the existing
heading styles better.
=> Update markup for safety concerns to be heading

Gemfile.lock, app/assets/stylesheets/local/buttons.scss, app/assets/stylesheets/local/forms.scss, app/controllers/concerns/names_crud_step.rb, app/views/steps/applicant/names/edit.html.erb, app/views/steps/children/names/edit.html.erb, app/views/steps/other_children/names/edit.html.erb, app/views/steps/other_parties/names/edit.html.erb, app/views/steps/respondent/names/edit.html.erb, app/views/steps/shared/_existing_names.html.erb, config/locales/en.yml, spec/support/step_controller_shared_examples.rb
We had a functionality depending on JS being enabled. This is not ideal and we've refactor the code to get rid of the JS dependency and as a side effect enable the possibility of remove individual names, no matter their position in the list.
As a consequence of this change, there is now some styling TLC and possibly the need to disable the ENTER key with JS, which is a minor inconvenience.
=> Make `remove name` work without JS

app/assets/stylesheets/local/forms.scss, app/views/steps/abduction/risk_details/edit.html.erb
The label for the text area at steps/abduction/risk_details was completely hidden rather than just visually hidden. This makes it available to screen readers again.
=> Unhide label on abduction textarea form field

app/assets/javascripts/modules/disable-enter-key.js, app/views/steps/applicant/names/edit.html.erb, app/views/steps/children/names/edit.html.erb, app/views/steps/other_children/names/edit.html.erb, app/views/steps/other_parties/names/edit.html.erb, app/views/steps/respondent/names/edit.html.erb, app/views/steps/shared/_existing_names.html.erb, config/locales/en.yml
A side effect of having individual 'remove' buttons is, on `enter` keypress in any of the text inputs, this submit action is actioned, removing the active name.
In order to stop this behaviour, we are going to disable form submits on enter keypress, only on text inputs, and only for the names form, not other forms.
=> Disable `enter` keypress in names form

app/controllers/errors_controller.rb
Some error pages rely on having a valid session to show different copy depending on the C100 application status.
But in rare occasions users leave these error pages open. When they come back and the browser (mostly mobile devices) auto reloads the URL, the session is gone, and a Sentry exception is thrown:
https://sentry.service.dsd.io/mojds/c100-application-prod/issues/33394/
We can avoid these exceptions if we check for a valid session in the particular error routes where we should have one.
=> Check for valid session on some error paths

config/locales/en.yml
The label (which is visually hidden and present for users of assistive technology) was a little vague. This PR makes it clear what the form field is about.
=> Update text on risk details form field to make it clearer

app/assets/stylesheets/local/typography.scss
When you click on the back link, it enters into a focused state. This commit fixes an issue where there is a white border at the top of the text, which is inconsistent with the orange background on the element.
Before: 
After:
=> Remove blank line from top of back link when focused

app/views/about/contact.en.html.erb
Add a bit more copy to clarify what the email address is for, and a link to court tribunal finder.
=> Update contact page copy

lib/tasks/mutant.rake
When raising a pull request, mutant will run in any modified class against master.
When merging to master, we will bypass running mutant again.
=> Do not run mutant on CI master

app/models/email_submissions_audit.rb, config/application.rb, lib/tasks/daily_tasks.rake, spec/models/email_submissions_audit_spec.rb
Applicant confirmation email, and court email, are sent via Notify, but Notify has a very limited retention period.
We maintain an audit (with no personal details) of the delivery result of these emails for diagnostic and debug purposes.
The purge retention period can be configured but initially will be 90 days. This purge will run together with the rest of daily tasks over night.
Also, as a minor fix, removed the downcase of the email argument in the `find_records` method because we really want to ensure case sensitivity in the search.
=> Add periodic purge of email submissions audit

config/environments/production.rb
We are no longer sending emails via SMTP. Instead we use GOV.UK Notify.
Remove these leftovers (will also be removed from the k8s deploy config map).
=> Remove unused SMTP config

.circleci/config.yml
We've created the k8s production namespace and now we can start promoting builds to k8s production.
The worflow have been updated to support this.
Also, removed a conditional in the `build_staging` job, checking if we were in master branch, because we always are in master if this job runs (there is filter set to 'only master' in the workflow).
=> Update CircleCI workflow to promote to production

app/controllers/bare_application_controller.rb, config/brakeman.ignore
The callbacks #notify endpoint receives a POST, and we are authenticating it with a bearer token already, so we don't need the `protect_from_forgery`
The status controller only uses GET endpoints.
=> Restore brakeman exemption

config/locales/en.yml
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/14567479)
This will update the page titles to the new content supplied by the Content Designer. Previously, the page titles weren't always clear about the purpose of the page, and the page title is the first thing read out to screen reader users when a new page loads. So this clarifies the pages to them.
The content has been taken from this Google spreadsheet from Amanda (Content Designer):
https://docs.google.com/spreadsheets/d/1RbZ3Lke3zfY0wkxNBdbw73647F7PEmMChB54XU65ffo/edit#gid=0
=> Update page titles

spec/controllers/callbacks_controller_spec.rb
It was too easy to break the `#notify` callback endpoint (which receives a POST) just by messing around with the `protect_from_forgery` config.
Ensure we cover this scenario in case it happens again in the future.
This endpoint must not have forgery protection enabled because we are using instead a Bearer token for a custom authentication.
=> Add a forgery protection test in callbacks controller

app/value_objects/petition_order.rb, app/views/steps/abuse_concerns/details/edit.html.erb, app/views/steps/children/orders/edit.html.erb, app/views/steps/children/residence/edit.html.erb, app/views/steps/petition/orders/edit.html.erb, config/locales/en.yml, spec/value_objects/petition_order_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/14567208)
Some of the checkboxes don't need legends, so this removes some of the unneccessary yml strings for them. It also adds in legends for checkbox fieldsets that need them.
=> Tidy up checkbox legends

app/views/entrypoint/v1.en.html.erb, config/locales/en.yml, config/locales/errors/en.yml
[Link to story](https://mojdigital.teamwork.com/#/tasks/14030547)
We need to reword most of the error messages in the application forms, in order to comply with accessibility and design guidelines.
As this is going to take a while and a lot of changes in the locales are expected, let's create smaller PRs as we go, so there is less risk of introducing regressions.
This first PR will create a new `locales/errors/en.yml` file where we move all the form errors previously in the general `en.yml`, and start adding/rewording some of the errors.
=> Refactor and reword error messages - Part 1

config/environments/production.rb, docker-compose.yml
Same as we did in Disclosure Checker, to ensure we can build and start a local container easily.
=> Fix docker-compose

app/assets/stylesheets/local/forms.scss, app/views/steps/miam/certification_date/edit.html.erb, config/locales/en.yml
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/14567229)
Two questions had issues with their legends: MIAM Certification Date and Substance Abuse Details. Both were excluded from the previous `<legend>` PRs ([621](https://github.com/ministryofjustice/c100-application/pull/621) and [616](https://github.com/ministryofjustice/c100-application/pull/616)) because they were both a bit more complex. Both had a form hint that would have been hidden by the solution used in that previous PR.
`/steps/miam/certification_date`has now had the question added into the legend. This has been visually hidden by extending the visually hidden class in the CSS using a (grand)child selector, rather than via the HTML.
`steps/safety_questions/substance_abuse_details` has a different solution. …
=> Textarea date labels

app/views/layouts/_analytics.html.erb
There is some unnecessary code in the Google Analytics script, that was brought over from Tax Tribunal. This isn't needed so this removes it. This is a quick fix for something @zheileman and I noticed whilst working on Google Analytics for Disclosure Checker, so there isn't a ticket for it.
=> Remove unnecessary code from Google Analytics file

app/presenters/summary/pdf_presenter.rb, app/services/c100_app/pdf_generator.rb, spec/presenters/summary/pdf_presenter_spec.rb, spec/services/c100_app/pdf_generator_spec.rb
We have a requirement to split out the C8 form from the other forms.
This PR prepares for it, making the PDF generation more flexible to allow for different combinations of bundle and individual also forms, for example:
* `#generate` -- will generate the whole bundle (current behaviour)
* `#generate(:c100, :c1a)` -- will generate a bundle with the C100 and C1A (if triggered).
* `#generate(:c8)` -- will generate only the C8 (if triggered)
No breaking changes in this PR. Current behaviour is maintained.
A follow-up PR will continue the necessary work to split the forms in the email to court.
=> Parametrise the PDF generation

app/controllers/steps/applicant/address_details_controller.rb, app/forms/steps/applicant/address_details_form.rb, app/forms/steps/applicant/contact_details_form.rb, app/presenters/summary/html_sections/applicants_details.rb, app/services/c100_app/applicant_decision_tree.rb, app/services/people_decision_tree.rb, app/views/steps/applicant/address_details/edit.html.erb, app/views/steps/applicant/contact_details/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, spec/forms/steps/applicant/address_details_form_spec.rb, spec/presenters/summary/html_sections/applicants_details_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/15321247)
This first PR will separate only contact details and address into separate forms only for applicant.  There will be other PRs for respondents, other parties and check your answers to separate contact details and address details form.
For now, only C100 Application records with version greater than 3 will have the splitting of the contact details and address forms enabled. This will allow us to release this in a controlled way as we need to ensure backward compatibility with existing saved applications in the database.
For testing purposes, in local, an ENV variable named SPLIT_ADDRESS can be set (to any value) to enable the splitting of the applicant contact and address forms regardless of the version.
The address …
=> Split contact details and address into separate forms for only the applicant

app/controllers/steps/respondent/address_details_controller.rb, app/forms/steps/respondent/address_details_form.rb, app/forms/steps/respondent/contact_details_form.rb, app/presenters/summary/html_sections/respondents_details.rb, app/services/c100_app/respondent_decision_tree.rb, app/views/steps/respondent/address_details/edit.html.erb, app/views/steps/respondent/contact_details/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, spec/forms/steps/respondent/address_details_form_spec.rb, spec/forms/steps/respondent/contact_details_form_spec.rb, spec/presenters/summary/html_sections/respondents_details_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/15321247)
Split contact details form into two separate form one for address details another for contact details for the respondent, the same as i have done for the applicant in PR[#60](https://github.com/ministryofjustice/c100-application/pull/640)
=> split contact details and address into separate forms for the respondent

app/mailers/notify_submission_mailer.rb, app/services/base_online_submission.rb, app/services/c100_app/applicant_online_submission.rb, app/services/c100_app/court_online_submission.rb, spec/mailers/notify_submission_mailer_spec.rb, spec/services/c100_app/applicant_online_submission_spec.rb, spec/services/c100_app/court_online_submission_spec.rb
Follow-up to #638 and #639.
No breaking changes or new behaviour. Everything still the same, just refactoring and preparing the path for the next PR.
- Allows to send emails that contain more than one document.
- DRY some duplicated code to a superclass `BaseOnlineSubmission`.
As we can't deploy just yet the split of the C8 (target is May 13th), in the next PR we will need to introduce a feature-flag so the split only happens on staging, but not on production environments.
=> Prepare for C8 form split in court email

app/presenters/summary/html_sections/applicants_details.rb, app/presenters/summary/html_sections/other_parties_details.rb, app/presenters/summary/html_sections/people_details.rb, app/presenters/summary/html_sections/respondents_details.rb, config/locales/cya/en.yml, config/locales/en.yml, spec/presenters/summary/html_sections/applicants_details_spec.rb, spec/presenters/summary/html_sections/other_parties_details_spec.rb, spec/presenters/summary/html_sections/respondents_details_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/15321247)
I have split contact details block in check your answers into two separate blocks (address details and  
contact details)
Also made a few small text changes from this [ticket](https://mojdigital.teamwork.com/index.cfm#/tasks/15321257)
=> Split contact details block in check your answers into two blocks

app/mailers/notify_submission_mailer.rb, app/services/base_online_submission.rb, app/services/c100_app/court_online_submission.rb, app/services/c100_app/pdf_generator.rb, config/govuk_notify_templates.yml, spec/mailers/notify_submission_mailer_spec.rb, spec/services/c100_app/court_online_submission_spec.rb, spec/services/c100_app/pdf_generator_spec.rb
[Link to story](https://mojdigital.teamwork.com/#/tasks/15321243)
Follow up to PRs #638, #639 and #644.
Individual commits with more context and to be easier to review.
This is the final PR that completes the work necessary to split the C8 form (if generated) out of the main PDF bundle (C100 + C1A) in the email to court.
As we don't want this to be enabled just yet on production, there is a feature flag based on ENV variables so it can be easily tested on local, and enabled by default on staging, but not on production until we have the green light (May 13th).
Once we enable this on production, we will raise another PR to do the cleanup of the feature flag and other code no longer needed.
=> Split C8 form to court (with feature flag)

config/routes.rb
For some time we will also need to maintain the `dsd.io` one but we can probably handle the redirect at s3/route53 level.
=> Prepare short url for live-1 cluster

app/controllers/steps/other_parties/address_details_controller.rb, app/forms/steps/other_parties/address_details_form.rb, app/models/applicant.rb, app/models/other_party.rb, app/models/person.rb, app/models/respondent.rb, app/views/steps/other_parties/address_details/edit.html.erb, app/views/steps/respondent/address_details/edit.html.erb, spec/forms/steps/other_parties/address_details_form_spec.rb, spec/forms/steps/respondent/address_details_form_spec.rb, spec/models/other_party_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/15152297)
Update other parties address form to separate address column into several text boxes and save in address_data form, when feature flag SPLIT_ADDRESS is enabled.  This is a follow on from [#646](https://github.com/ministryofjustice/c100-application/pull/646) [#647] and (https://github.com/ministryofjustice/c100-application/pull/647) PRs only for other parties.
=> Add split text boxes for other parties address details form

app/mailers/notify_submission_mailer.rb, app/services/base_online_submission.rb, app/services/c100_app/court_online_submission.rb, config/govuk_notify_templates.yml, config/locales/pdf/en.yml, spec/mailers/notify_submission_mailer_spec.rb, spec/presenters/c8_confidentiality_presenter_spec.rb, spec/presenters/relationships_presenter_spec.rb, spec/presenters/summary/sections/c1a_applicant_details_spec.rb, spec/services/c100_app/court_online_submission_spec.rb
[Link to story](https://mojdigital.teamwork.com/#/tasks/15321243)
Remove/undo the temporary feature flag code in order to enable the C8 split in all environments.
Also, a few copy changes, due to the fact the C8 form will not be included in the bundle anymore, and we have to make the copy in the PDF consistent with this.
=> Enable C8 split (remove feature flag)

app/forms/address_base_form.rb, spec/forms/steps/applicant/address_details_form_spec.rb
Add default to `address_unknown` because the following validation `validate_split_address?` is failing  when  `address_unknown` hasn't got a default value and is returning nil
=> Add default false for address_unknown

app/views/steps/applicant/personal_details/edit.html.erb, config/locales/en.yml
Assorted fixes, but mainly:
Moving out of the `PERSONAL_CONTACT_FIELDS` dictionary the keys related to address, as these now must be in the `PERSONAL_ADDRESS_FIELDS`.
Also, `steps_other_parties_address_details_form` was using the contact dictionary instead of the address dictionary.
Added the (hidden) label for `address_line_2`.
=> Locale fixes

app/controllers/crud_step_controller.rb, app/controllers/steps/address/lookup_controller.rb, app/controllers/steps/address_step_controller.rb, app/forms/steps/address/lookup_form.rb, app/services/c100_app/address_decision_tree.rb, app/services/people_decision_tree.rb, app/validators/full_uk_postcode_validator.rb, app/views/steps/address/lookup/_applicant.html.erb, app/views/steps/address/lookup/_other_party.html.erb, app/views/steps/address/lookup/_respondent.html.erb, app/views/steps/address/lookup/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, lib/tasks/mutant.rake, spec/controllers/steps/address/lookup_controller_spec.rb, spec/forms/steps/address/lookup_form_spec.rb, spec/services/c100_app/address_decision_tree_spec.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/other_parties_decision_tree_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb
**Note: as this is a big PR, I've split the different changes into smaller chunks with their own commit messages explaining each one. Please refer to each commit in this PR for more context.**
Also please mind you all copy is provisional.
In order to test this locally, please ensure you've bumped the version of the c100_application table to 3 (dependent on previous split address work) and expose an variable `ADDRESS_LOOKUP_ENABLED`.
Basically this:
```ruby
def address_lookup_enabled?
c100_application.version > 2 && ENV.key?('ADDRESS_LOOKUP_ENABLED')
end
```
=> Add main scaffolding for the address lookup steps

Gemfile, Gemfile.lock, app/forms/address_base_form.rb, app/forms/steps/applicant/address_details_form.rb, config/locales/en.yml, config/locales/errors/en.yml, spec/forms/steps/applicant/address_details_form_spec.rb, spec/forms/steps/other_parties/address_details_form_spec.rb, spec/forms/steps/respondent/address_details_form_spec.rb, spec/models/person_spec.rb, spec/support/address_form_shared_examples.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/15321247)
Update the following
- To change ‘postal/zip code’ to ‘postcode’
-  To make the following fields mandatory for the applicant address: first line, town/city, country
-  To make the following fields mandatory for the respondent and other parties’ addresses: first line, town/city. If the applicant is unable to fill in these fields they will be directed to check the box ‘I don’t know their address’
- update split address validation messages
applicant address form
respondent address form 
Other parties form
- remove climate_control gem 
=> Update split address validations

app/assets/stylesheets/local/utilities.scss, app/attributes/split_address.rb, app/controllers/steps/address/results_controller.rb, app/controllers/steps/address_step_controller.rb, app/forms/steps/address/results_form.rb, app/helpers/person_url_helper.rb, app/services/c100_app/address_decision_tree.rb, app/services/c100_app/address_lookup_service.rb, app/services/c100_app/map_address_lookup_results.rb, app/views/steps/address/results/_no_results.en.html.erb, app/views/steps/address/results/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, spec/attributes/split_address_spec.rb, spec/controllers/steps/address/results_controller_spec.rb, spec/forms/steps/address/results_form_spec.rb, spec/services/c100_app/address_decision_tree_spec.rb, spec/services/c100_app/address_lookup_service_spec.rb, spec/services/c100_app/map_address_lookup_results_spec.rb
Again, a few separated commits to organise the work.
This PR is a follow-up to previous PR #658 and introduces the results page, with a dropdown to select an address from the returned ones when calling the `AddressLookupService`.
There is also a placeholder (copy is provisional) error page for when there are no results or something failed in the request.
=> Add lookup address results step

app/forms/steps/address/lookup_form.rb, app/services/c100_app/map_address_lookup_results.rb, spec/forms/steps/address/lookup_form_spec.rb, spec/services/c100_app/address_decision_tree_spec.rb, spec/services/c100_app/map_address_lookup_results_spec.rb
This is a kind of edge case but... if the user search for a postcode and select an address from the list, but then they go back (for whatever reason) and search another postcode, and, without selecting a new address (could happen the lookup didn't return results) go to the address edit page, then the old address is still pre-populated, which is confusing for the user.
We avoid this by checking if the postcode has changed or not, to reset dependent attributes.
Also, we pre-populate the country as we know 99% of users will be in United Kingdom if using the postcode lookup, although for the cases where not (Isle of Man or Channel Islands) they can always change it.
This was a suggestion by Simon to improve the UX for users that couldn't find their address in the list.
Before you ask people …
=> Reset address lookup dependent attributes

app/forms/steps/applicant/contact_details_form.rb, app/forms/steps/respondent/address_details_form.rb, config/locales/errors/en.yml, spec/forms/steps/applicant/contact_details_form_spec.rb, spec/forms/steps/respondent/address_details_form_spec.rb
As per this ticket:
https://mojdigital.teamwork.com/#/tasks/15321247
We've made mandatory the mobile number for the applicant, and remove the validation on the address history for respondent.
Some copy changes to the error messages.
=> Some validations/error messages tweaks

app/services/people_decision_tree.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/other_parties_decision_tree_spec.rb, spec/services/c100_app/respondent_decision_tree_spec.rb, spec/support/decision_tree_shared_examples.rb
And bypass the lookup if the person has already entered address details, or their address is `unknown`.
This is a continuation to PR #664.
=> Enable address lookup on dev/staging

app/models/person.rb, spec/models/person_spec.rb
The order in the `address_data` Hash (store) is not guaranteed, and in fact, some keys (postcode or country) are created before others (address lines).
This has the side effect of sometimes returning a funny `full_address` that does not maintain the order people are used to.
Make the `#full_address` method resilient to these scenarios and always return the attribute values in the same order they were declared, regardless of the order of the keys in the Hash.
=> Ensure a predictable full address order

app/services/c100_app/map_address_lookup_results.rb, spec/fixtures/files/address_lookups/guernsey.json, spec/fixtures/files/address_lookups/isle_of_man.json, spec/fixtures/files/address_lookups/jersey.json, spec/services/c100_app/map_address_lookup_results_spec.rb
Currently we default country names to UNITED KINGDOM.  This is incorrect for ISLE OF MAN,JERSEY  and GUERNSEY.  For postcodes from the above countries, the service returns the country name in  POST_TOWN and the town/city name in DEPENDENT_LOCALITY field.
=> Fix issues with country name / post town for postcode lookup service

app/views/layouts/application.html.erb, config/application.rb, config/routes.rb, lib/tasks/short_urls.rake
We are now using a new short URL under the `service.justice.gov.uk` domain.
The govuk Notify templates will be also updated to use the new short URL.
For the time being the (already) deployed application in Heroku will handle the old `dsd.io` URLs but eventually we will also decommission the app and use a simple s3 redirect or something like that so we don't have to maintain another app in Heroku.
[Link to story](https://mojdigital.teamwork.com/#/tasks/15821117)
=> Remove references to old dsd URL

app/models/person.rb, app/services/c100_app/address_lookup_service.rb, app/services/c100_app/map_address_lookup_results.rb, config/initializers/extensions.rb, lib/extensions/array_extension.rb, spec/lib/extensions/array_extension_spec.rb, spec/services/c100_app/address_lookup_service_spec.rb
We still have some little issues with the postcode lookup. This PR will fix a couple, and a follow-up PR will try to fix another one, related to Wales postcodes like LL61 5AB not returning the country properly.
In this PR (refer to the individual commits for more context):
* Fix duplicated addresses in Welsh.
* Fix extra trailing comma in addresses without `address_line_2`.
Before:
After:
=> Postcode lookup fixes

app/views/steps/address/lookup/_applicant.html.erb, app/views/steps/address/lookup/_other_party.html.erb, app/views/steps/address/lookup/_respondent.html.erb, app/views/steps/address/results/_no_results.en.html.erb
In order to have a better understanding of how users are using the address lookup, as we do in other places in the application, and diagnose issues when addresses are not found, we are going to track the use of `manual entry` links and `no results` links.
=> Add address lookup analytics

app/services/people_decision_tree.rb
We have the green light. Up until now this feature has been only visible on staging and local dev environments.
Still, we must ensure this is only enabled for `version >= 3` of the applications, so the condition will remain until all applications are in the new version, which can still take a couple weeks.
=> Enable the address lookup in production

app/presenters/summary/sections/c1a_abduction_details.rb, app/presenters/summary/sections/other_court_cases.rb, spec/presenters/summary/sections/c1a_abduction_details_spec.rb, spec/presenters/summary/sections/other_court_cases_spec.rb
Under certain circunstances, an applicant might leave out some mandatory follow-up questions after changing their answer to the `abduction risk` or the `previous proceedings` questions.
The result of this would be an exception when trying to generate the PDF, due to missing data.
Although this has occurred only twice in the past so far, we better protect from this from happening again.
[Link to story](https://mojdigital.teamwork.com/#/tasks/15890246)
=> Protect from nil values

app/jobs/applicant_delivery_job.rb, app/jobs/court_delivery_job.rb, spec/jobs/applicant_delivery_job_spec.rb, spec/jobs/court_delivery_job_spec.rb
We continue to have memory peaks after each submission. This is mostly a consequence of the PDF generation, and the tools used to combine multiple files into one.
Let's experiment for a few days by having an explicit garbage collection after the jobs complete, and see if this  improves in any way the situation.
As these are async jobs, there is no penalty to the user (that otherwise would be if this was part of the request lifecycle).
=> Force garbage collection on delivery jobs

app/controllers/concerns/savepoint_step.rb, app/controllers/sessions_controller.rb, app/models/screener_answers.rb, lib/tasks/mutant.rake, spec/controllers/steps/miam/child_protection_cases_controller_spec.rb, spec/models/screener_answers_spec.rb, spec/support/matchers/validation_helpers.rb, spec/support/matchers/validation_matchers.rb, spec/support/step_controller_shared_examples.rb
There was an edge case where once you obtain a session (just visiting the postcode step, for example) and then jumping manually to the `child_protection_cases` step, would actually let you pass with a corrupt or missing 'screening', thus failing at submission time.
The validation has been improved.
Individual commits for more details and context.
[Link to story](https://mojdigital.teamwork.com/#/tasks/15910041)
=> Add a screener sanity check validation

app/mailers/reports_mailer.rb, app/services/reports/failed_emails_report.rb, config/govuk_notify_templates.yml, lib/court_email_interceptor.rb, lib/tasks/daily_tasks.rake, spec/lib/court_email_interceptor_spec.rb, spec/mailers/reports_mailer_spec.rb
As part of the work to improve the monitoring around the submission jobs, a new daily report has been created to detect any submission where the emails (to court, or applicant copy if they chose so) were not sent.
This report will run daily together with the rest of maintenance task we have, and will check all online submissions from the day before (00:00:00 to 23:59:59).
If any issue is found, will send an alert email to the team, with a simple report, to analise further. See example of the report below.
[Link to story](https://mojdigital.teamwork.com/#/tasks/16039120)
=> Daily failed emails report (if any)

app/models/concerns/application_reference.rb, spec/models/concerns/application_reference_spec.rb
There was an edge case where applications created in the last day of the month were not found when using the utility method `#find_by_reference_code`.
To ensure these applications are also included, we will force the end of the day, so the where clause is (take May as an example):
`WHERE (created_at BETWEEN '2019-05-01 00:00:00' AND '2019-05-31 23:59:59.999999')`
This is an internal method for debug purposes and is not used anywhere, so no harm done, but to avoid confusion in the future better to change it.
=> Increase date range in DB lookup

Dockerfile, config/database.yml, config/environments/production.rb, docker-compose.yml
For production environments we are going to force the `verify-full` SSL mode in all connections to the database.
It will be overriden (`DATABASE_SSLMODE=disable`) when using docker-compose so we are still able to run and test the application locally.
This follows best practices and guidance from Cloud Platforms here:
https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#ssl-connections-with-rds
To avoid potential confusion with the introduction of this new ENV var, I'm renaming `DISABLE_SSL` to `DISABLE_HTTPS` so it is more clear this other env variable is for https connections and nothing to do with the database.
[Link to story](https://mojdigital.teamwork.com/#/tasks/16091694)
=> Enable postgres `verify-full` SSL mode

app/jobs/applicant_delivery_job.rb, app/jobs/court_delivery_job.rb, spec/jobs/applicant_delivery_job_spec.rb, spec/jobs/court_delivery_job_spec.rb
Reverts ministryofjustice/c100-application#676
This turned out to not have any meaningful effect, so we are going to get rid of it.
Also, hopefully we should not need to worry about memory anymore, after the recent bump in resources in the kubernetes container.
=> Revert "Force garbage collection on delivery jobs"

Dockerfile, config/database.yml
Instead of having paths in two places, let's give the control of the path to Dockerfile which is actually the one downloading the RDS bundle.
So we expose the bundle in the ENV and can be used in `/config/database.yml` without having to deal with paths and if this ever changes, there is only one place to touch.
=> Set `RDS_COMBINED_CA_BUNDLE` in the ENV

app/services/c100_app/address_lookup_service.rb, spec/services/c100_app/address_lookup_service_spec.rb
If the response from the Ordnance Survey API is not successful, we are raising a custom exception, but this didn't include the error message, which can be useful to diagnose problems.
Now we will propagate this error to Sentry.
=> Propagate ordnance survey errors

app/views/steps/address/results/edit.html.erb
We were not tracking this link, which may be interesting for analytics.
This is when the address lookup returns results, but for whatever reason the address the user is looking for, is not included in the results.
=> Track address not listed link

app/mailers/notify_mailer.rb, app/services/reports/failed_emails_report.rb, spec/mailers/notify_mailer_spec.rb
We already had a mechanism to detect unsent emails, caused by a failure in our service before the email even reached Notify (for example, errors when generating the PDF, or memory issues).
With this PR we extend the functionality to also detect emails that were correctly generated and sent to Notify, but for whatever reason Notify didn't process and delivered them (we use callbacks from Notify to update a table so we know the status of these emails).
Also, related to this, hide the `link_to_c8_pdf` value from any error sent to Sentry, as we already do with the `link_to_pdf`.
[Link to story](https://mojdigital.teamwork.com/#/tasks/16570206)
=> Improve the detection of undelivered emails

app/assets/stylesheets/local/app.scss, app/controllers/steps/application/receipt_email_check_controller.rb, app/services/c100_app/application_decision_tree.rb, app/views/steps/applicant/contact_details/edit.html.erb, app/views/steps/application/receipt_email_check/show.html.erb, app/views/steps/application/submission/edit.html.erb, app/views/steps/respondent/contact_details/edit.html.erb, app/views/steps/screener/email_consent/edit.html.erb, app/views/steps/solicitor/contact_details/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/application/receipt_email_check_controller_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb
In order to minimise emails with typos or incorrect, we are going to introduce a "check and confirm" interaction right after the applicant choose if they want to receive a copy of the submitted application.
This check and confirm follows the convention of Home Office (but we use our own styling to match the rest of the application):
https://home-office-digital-patterns.herokuapp.com/patterns/confirmation-loop
This check only appears when the user entered an email, as they can leave it blank, is not mandatory. Decision tree updated for this.
[Link to story](https://mojdigital.teamwork.com/#/tasks/17103551)
=> Add check and confirm interaction for receipt email

app/controllers/backoffice/application_controller.rb, app/controllers/backoffice/dashboard_controller.rb, app/controllers/backoffice/emails_controller.rb, app/controllers/backoffice/errors_controller.rb, app/views/backoffice/dashboard/index.en.html.erb, app/views/backoffice/emails/index.en.html.erb, app/views/backoffice/errors/unhandled.en.html.erb, app/views/backoffice/shared/_menu.en.html.erb, app/views/layouts/backoffice.html.erb, config/routes.rb
Very simple (and very useless, right now, without any functionality at all) back office scaffolding, in preparation for implementing Auth0.
The back office will reside in the `/backoffice` namespace, and will provide very basic functionality to remove as much as possible the need for a developer to do some admin stuff.
All copy is placeholder.
A more streamlined layout (named `layouts/backoffice.html.erb`) has been created, based off the existing `application` layout but removing things we don't need in the backoffice.
As part of this new layout I found out some old, unused IE9 detection code. This has been removed for both layouts.
[Link to story](https://mojdigital.teamwork.com/#/tasks/17169364)
=> Create basic back office scaffolding

.env.example, app/controllers/backoffice/auth0_controller.rb, app/helpers/auth0_helper.rb, app/views/backoffice/auth0/index.en.html.erb, config/initializers/auth0.rb, config/routes.rb
This will simplify and speed up the testing and development without having to worry about the Auth0 credentials.
It is only intended for local environments, but it is disabled by default as it is encouraged to always mimic production envs even when working on localhost.
To enable, just uncomment (or set if it does not exist) the env variable: `AUTH0_BYPASS_LOCALHOST`.
=> Ability to bypass Auth0 in localhost

app/controllers/backoffice/auth0_controller.rb, config/auth0/rules/check_user_exists.js
We want to know who was trying to sign-in.
Also Sentry needs an exception object, and not two separate arguments.
=> Add extra error details

app/controllers/backoffice/emails_controller.rb, app/models/email_submission.rb, app/presenters/backoffice/failed_email.rb, app/services/reports/failed_emails_report.rb, app/views/backoffice/emails/_failure.en.html.erb, app/views/backoffice/emails/index.en.html.erb, config/routes.rb
This is a first version, subject to be changed, of the functionality to resend failed emails in the backoffice.
The idea behind this is to avoid havinf to SSH to trigger manual resend of emails that have failed due to Notify errors, connectivity issues, job failure when building the PDF, etc.
We will still receive an email notification when there is an email failure, and we will be able to trigger the resend (once some sanity check has been done in Notify) through this simple interface.
To be done / WIP:
* Some kind of audit record to know who triggered the resend (we can have this as the backoffice is behind Auth0 credentials).
* Some very basic tests. The backoffice is not tested at the moment, because it piggy-backs in existing functionality, but might be good to have some top level …
=> Initial version of backoffice resend emails page

app/models/court.rb, spec/models/court_spec.rb
We had this in the past, but was removed.
We want to reintroduce this as some new courts don't have the appropriate email addresses in place just yet, and it is better to pick the enquiries email (if any) instead of the first address of the list.
Only seek the `enquiries` word in the email address itself, not in the description or explanation.
Still if no email is found, first in the list will be picked.
=> Add court enquiries email as fallback

app/services/c100_app/court_postcode_checker.rb, features/screener.feature, spec/services/c100_app/court_postcode_checker_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/17296619)
The courts which will go live on 24/25 September are as follows.
Portsmouth = https://courttribunalfinder.service.gov.uk/courts/portsmouth-combined-court-centre
Isle of Wight = https://courttribunalfinder.service.gov.uk/courts/isle-of-wight-combined-court
Sheffield =  https://courttribunalfinder.service.gov.uk/courts/sheffield-combined-court-centre
Doncaster = https://courttribunalfinder.service.gov.uk/courts/doncaster-magistrates-court-and-family-court > missing family email address
Barnsley  = https://courttribunalfinder.service.gov.uk/courts/barnsley-law-courts
Lincoln =  https://courttribunalfinder.service.gov.uk/courts/lincoln-county-court-and-family-court
Boston = no results
York = …
=> Add new courts

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/views/application/_developer_tools.html.erb, spec/controllers/steps/screener/start_controller_spec.rb
It is now possible to answer one or more questions in the screener, and then do a bypass. These already answered questions will take precedence over the fixture data.
Also, now in the developer tools dropdown in the footer, the information about the court will appear, to quickly check where an application might be sent for a given postcode.
=> Improve the bypass functionality

app/assets/stylesheets/local/app/backoffice.scss, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/backoffice/dashboard/index.en.html.erb, app/views/backoffice/emails/_failure.en.html.erb
The table of completed applications was too crowded and a bit confusing.
Re-arranged the columns and added some space, removing not needed borders.
=> Backoffice styling improvements

app/services/reports/failed_emails_report.rb
As the service take up increase, there is also an increase in the number of emails we receive alerting us of failures in the applicant receipt email.
These failures are usually typos in the email address and nothing we can fix on our side.
In order to minimise these alerts so we only receive them when the error is genuine (or looks genuine) we are going to ignore the notify failures for the user receipt.
We still get them in the backoffice.
=> Reduce number of email alerts

app/presenters/relationships_presenter.rb, config/locales/pdf/en.yml, spec/presenters/relationships_presenter_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/17280033)
Describe what you did and why.
Add a new line between each child in the children’s relationship with parents section of the c100 pdf
It look like this currently:
has been updated to look like this:
=> Update pdf layout for children’s relationship with parents section

app/services/c100_app/court_postcode_checker.rb, spec/services/c100_app/court_postcode_checker_spec.rb
[Link to story](https://mojdigital.teamwork.com/index.cfm#/tasks/17432754)
New welsh courts which will go live near the end of October.
Caernarfon = https://courttribunalfinder.service.gov.uk/courts/caernarfon-justice-centre
Wrexham = https://courttribunalfinder.service.gov.uk/courts/wrexham-county-and-family-court
Welshpool = https://courttribunalfinder.service.gov.uk/courts/welshpool-magistrates-court
Prestatyn = https://courttribunalfinder.service.gov.uk/courts/prestatyn-justice-centre
Blackwood = https://courttribunalfinder.service.gov.uk/courts/blackwood-civil-and-family-court   > missing family email address
Pontypridd = https://courttribunalfinder.service.gov.uk/courts/pontypridd-county-court-and-family-court
Port Talbot = …
=> Add new welsh courts

Gemfile, Gemfile.lock
We had `govuk_elements_form_builder` pointing to master branch of the repo while awaiting a release of a new version.
The release is now done (https://github.com/ministryofjustice/govuk_elements_form_builder/pull/106) so we can change this to avoid nasty surprises in the future.
=> Specify version of gem to avoid surprises

app/services/c100_app/court_postcode_checker.rb
The slug for the swansea court changed from  `swansea-civil-and-family-justice-centre` to [swansea-civil-justice-centre](https://courttribunalfinder.service.gov.uk/courts/swansea-civil-justice-centre).
=> Update swansea slug

audit_courts.csv, lib/tasks/tools.rake
The `completed_applications_audit` table was created a few months after the release of the service.
Although we tried to backtrack as many applications as possible from the early days, the consequence was for some (1045) applications we couldn't reliably assign their reference code, leaving this field as `nil` in these rows.
This is not a very smart decision as the `reference_code` is the primary key and any mass update is done using this PK, which means if we want to update a bunch of records without reference code, we must use the exact timestamp which is not ideal.
Also, some of these old rows have been mistakenly re-assigned a different court, meaning the analytics are incorrect.
This one-time task will, based on an old backup, re-assign the proper court to these 1045 records, and at …
=> Add one time task to fix some rows in audit table

app/assets/javascripts/modules/password-toggle.js, app/assets/stylesheets/local/typography.scss
This show/hide functionality was relying on a `span` element, which will not get the focus when navigating with a screen reader.
Changing this `span` to a proper link `a` fix the issue.
Also, without stylesheets, will look like a proper link.
=> Fix accessibility issue with password link

db/migrate/20191114093418_add_unique_index_to_screener_answers.rb, db/schema.rb
This table can only contain unique references to C100Application. There can't be duplicates.
There have been a rare occurrence where a duplicate entry was inserted (probably some kind of race-condition difficult to replicate).
In order to avoid this from happening again, and as we did with other tables already, we are going to enforce the uniqueness of the index `c100_application_id`.
=> Ensure index uniqueness in screener_answers

.circleci/config.yml, app/models/court.rb, config/cucumber.yml, features/courts_smoke_test.feature, features/errors.feature, features/screener.feature, features/step_definitions/common.rb, features/step_definitions/smoke.rb
A very high level smoke test to ensure the slugs we use in the service are correct, with no typos, and found in Court Tribunal Finder service.
This will only run if explicitely pass the `-p smoke` flag to cucumber. Otherwise the "default" cukes will run, as it is now.
A new workflow on CircleCI will run the smoke tests automatically (currently hourly, but we will increase the frequency after we are sure it works).
**Individual commits for easier review**
=> Add an automated daily courts smoke test

app/presenters/summary/answers_group.rb, app/views/steps/completion/shared/_answers_group.html.erb, app/views/steps/completion/shared/_change_link.html.erb, config/locales/cya/en.yml
Append a visually hidden sentence to each of the `Change` links so it is more accessible to screen readers.
We might still need to tweak some of the visually hidden copy in some `Change` links to make it better.
=> Improve accessibility in CYA page

app/assets/stylesheets/local/app.scss, config/locales/cya/en.yml
There seems to be some weird issue with the CYA and some screen readers in some browsers.
In order to make sure we are using the most up to date CSS definition that might include bug fixes, we are going to use the same definition as in the new design system, only in the CYA, for now.
We might backport this to other places where we use the "old" `visually-hidden` class.
=> Use new design system visually-hidden class

app/views/about/accessibility.en.html.erb
It was missing a space after a full stop.
Also change the paragraph about the design system to actually talk about the GOV.UK Elements because this service is still using it.
=> Fix typo on accessibility statement

app/forms/steps/applicant/contact_details_form.rb, app/views/steps/applicant/contact_details/edit.html.erb, config/locales/errors/en.yml, spec/forms/steps/applicant/contact_details_form_spec.rb
But allow to enter free text as a reason in case they don't feel like disclosing this information, due to safety reasons or similar.
Basically we do the same we did in the past with the mobile number. The error message follows the same format.
=> Make the applicant contact email mandatory

app/models/court.rb, app/services/c100_app/courtfinder_api.rb, features/step_definitions/smoke.rb, spec/services/c100_app/courtfinder_api_spec.rb
Instead of using memoization of the `court_data`, we replace it with a very basic `ActiveSupport::Cache::MemoryStore` which in essence does the same but allow us to set an expiration per-key and also it is easier to test.
Also in the near future, this should be replace with a `RedisCacheStore` as otherwise it is suboptimal, having more than one instance, or loosing the cache on deploys.
=> Add a basic in-memory cache for court slugs

app/forms/steps/court_orders/details_form.rb, app/presenters/summary/html_sections/court_orders.rb, app/presenters/summary/sections/c1a_court_orders.rb, app/views/steps/court_orders/details/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, db/migrate/20191128124833_add_case_number_to_court_orders.rb, db/schema.rb, spec/forms/steps/court_orders/details_form_spec.rb, spec/presenters/summary/html_sections/court_orders_spec.rb, spec/presenters/summary/sections/c1a_court_orders_spec.rb
Based on feedback from court staff and legal advisers, we've added
a field for the case number in the section which asks about
protective orders.
Court staff will be able to locate copies of protective orders more
quickly.
This field is mandatory and do not have any format validation as each
court and even each order will have their own format.
Updated step view, form object, CYA and PDF generation.
=> Add case number field to court orders step

.env.example, Gemfile, Gemfile.lock, app/services/c100_app/courtfinder_api.rb, config/environments/development.rb, config/initializers/cache_store.rb, docker-compose.yml, spec/services/c100_app/courtfinder_api_spec.rb
CourtfinderAPI was using `MemoryStore` for a very basic cache of slugs JSON response, saving a few API requests, but, as stated in the original PR #726, it was suboptimal because we have more than one application instance (each instance having its own memory, not shared) and also, any deploys would wipe the cache.
As we've bumped the Rails version to the 5.2.x branch (PR #728) now it is very easy to just replace the `MemoryStore` with a `RedisCacheStore` which will work out much better in a multiple instances deployment like ours.
Kubernetes already provides to us an elasticache (redis) database and, in production environments, the `REDIS_URL` is exposed, so we use this, instead of the `MemoryStore` that we will continue using on dev/test envs.
Once we test this works well, we could use …
=> Replace MemoryStore with RedisCacheStore

app/forms/steps/applicant/contact_details_form.rb, app/forms/steps/respondent/contact_details_form.rb, app/presenters/summary/html_sections/people_details.rb, app/presenters/summary/sections/c1a_applicant_details.rb, app/presenters/summary/sections/c8_applicants_details.rb, app/presenters/summary/sections/people_details.rb, app/views/steps/applicant/contact_details/edit.html.erb, app/views/steps/respondent/contact_details/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, db/migrate/20191209103137_add_voicemail_consent_to_people.rb, db/schema.rb, spec/forms/steps/applicant/contact_details_form_spec.rb, spec/forms/steps/respondent/contact_details_form_spec.rb, spec/presenters/summary/html_sections/applicants_details_spec.rb, spec/presenters/summary/html_sections/respondents_details_spec.rb, spec/presenters/summary/sections/applicants_details_spec.rb, spec/presenters/summary/sections/c1a_applicant_details_spec.rb, spec/presenters/summary/sections/c8_applicants_details_spec.rb, spec/presenters/summary/sections/c8_other_parties_details_spec.rb, spec/presenters/summary/sections/other_parties_details_spec.rb, spec/presenters/summary/sections/respondents_details_spec.rb
Individual commits for more details.
In the applicant contact details, we are going to ask a new question, whether they consent the court to leave a voicemail. This is a Yes/No question.
Updated the view to add this radio, as well as reorder the fields in both, applicant and respondent, moving the email field to the top.
Also updated the CYA page and the different PDFs.
=> Add voicemail consent for the applicant

app/views/steps/abduction/previous_attempt_details/edit.html.erb, config/locales/en.yml
This is to make this text area consistent with the one in the abduction risk details step.
We make the label visually hidden, but change the copy so screen readers know what this text area is about.
=> Small copy change to previous abduction

app/models/court.rb, spec/models/court_spec.rb
We raise the priority of the explanation over the description, and remove the strict regex for the "applications" word so it can be matched anywhere.
This will fix the issue with Derby court emails being sent to an incorrect address, without introducing any change for the rest of courts.
=> Tweak email routing rules

app/controllers/backoffice/dashboard_controller.rb, app/views/backoffice/dashboard/_lookup_form.en.html.erb, app/views/backoffice/dashboard/_results_table.en.html.erb, app/views/backoffice/dashboard/lookup.en.html.erb, app/views/backoffice/shared/_menu.en.html.erb, config/routes.rb, features/screener.feature
A simple way of searching a completed application, given its reference code.
Only exact matches will be returned (in essence only one result as reference codes are unique).
Refactor the views to DRY the markup and results table.
=> Add application lookup functionality to back office

app/controllers/backoffice/emails_controller.rb, app/models/email_submissions_audit.rb, app/views/backoffice/emails/_lookup_form.en.html.erb, app/views/backoffice/emails/_results_table.en.html.erb, app/views/backoffice/emails/index.en.html.erb, app/views/backoffice/emails/lookup.en.html.erb, config/routes.rb
A simple way of searching sent emails, given the application reference code and, optionally, the email address where the application was sent.
Only exact matches will be returned.
=> Add sent emails lookup functionality to back office

app/controllers/backoffice/audit_controller.rb, app/controllers/backoffice/auth0_controller.rb, app/controllers/backoffice/users_controller.rb, app/models/backoffice_audit_record.rb, app/views/backoffice/audit/_record.en.html.erb, app/views/backoffice/audit/index.en.html.erb, app/views/backoffice/emails/lookup.en.html.erb, app/views/backoffice/shared/_menu.en.html.erb, config/routes.rb, db/migrate/20191218120550_create_backoffice_audit_records_table.rb, db/schema.rb
A DB table will hold the information of the actions performed in the back office.
As part of this first PR only logins/forbidden actions are logged.
Individual commits with more details.
=> Add back office audit records list page

app/assets/stylesheets/local/app/backoffice.scss, app/controllers/backoffice/application_controller.rb, app/controllers/backoffice/auth0_controller.rb, app/controllers/backoffice/dashboard_controller.rb, app/controllers/backoffice/emails_controller.rb, app/controllers/backoffice/users_controller.rb, app/models/backoffice_audit_record.rb, app/views/backoffice/audit/_record.en.html.erb, app/views/backoffice/audit/index.en.html.erb, app/views/backoffice/emails/_failure.en.html.erb
All actions in the back office will now produce an audit record, some of them with additional details for further analysis.
Tweaked a bit the layout of the table, and refactored the call to the `BackofficeAuditRecord.log!` method to DRY.
=> Implement more audit records in back office

app/helpers/auth0_helper.rb
If we don't have a session yet, the method `#admin_name` should just return nil, instead of blowing up.
=> Fix nil when there is no back office session yet

app/controllers/backoffice/users_controller.rb, app/views/backoffice/shared/_menu.en.html.erb, app/views/backoffice/users/_admin_user.en.html.erb, app/views/backoffice/users/index.en.html.erb, config/routes.rb
This only list the active admin users and some other details. It is not (just yet) a CRUD, maybe it will never be.
Exposed a new link in the menu bar.
=> Add new page to back office to list admin users

app/services/c100_app/applicant_decision_tree.rb, app/views/steps/application/payment/edit.html.erb, config/locales/errors/en.yml, db/migrate/20200109113022_add_unique_index_to_solicitors.rb, db/schema.rb, spec/services/c100_app/applicant_decision_tree_spec.rb
We had most of the code for the solicitor's journey commented out.
We are going to start development on this, but first, we are enabling the parts that we had completed, but we are using a feature flag so only show in local and staging environments.
Once we have this ready for release, we will change the feature flag to use the `version` attribute of the C100 Application record so new applications show the solicitor question but existing in progress, or saved applications, don't.
Copy TBD.
=> Restore old solicitor's journey, with feature flag

config/court_slugs.yml, spec/services/c100_app/court_postcode_checker_spec.rb
The old slug has been split into 2 different court tribunal pages
and thus we now have 2 new slugs.
=> Update Southend court slugs

.env.example, app/controllers/backoffice/dashboard_controller.rb, app/controllers/backoffice/emails_controller.rb, app/mailers/reports_mailer.rb, app/services/reports/failed_emails_report.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/backoffice/dashboard/_lookup_form.en.html.erb, app/views/backoffice/emails/index.en.html.erb, spec/mailers/reports_mailer_spec.rb
Previously this email was sent to a single recipient address, declared on an ENV variable.
Now that we have a functional back office, with the ability to retry these failed emails, we can send the notification to all the back office admin users so they are aware and can trigger the email resend themselves.
Still an ENV variable needs to be set in order for these emails to be sent, otherwise they will be disabled.
=> Refactor the failed emails report notification

app/assets/stylesheets/local/check_answers.scss, app/forms/steps/application/declaration_form.rb, app/models/completed_applications_audit.rb, app/presenters/summary/sections/statement_of_truth.rb, app/value_objects/user_type.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/steps/application/check_your_answers/edit.html.erb, app/views/steps/completion/shared/_statement_of_truth.pdf.erb, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, db/migrate/20200115151905_add_declaration_of_truth_attributes.rb, db/migrate/20200116142446_migrate_declaration_of_truth.rb, db/schema.rb, spec/forms/steps/application/declaration_form_spec.rb, spec/helpers/custom_form_helpers_spec.rb, spec/models/completed_applications_audit_spec.rb, spec/presenters/summary/sections/statement_of_truth_spec.rb, spec/value_objects/user_type_spec.rb
Note: individual commits for more detail, as this PR is a bit lengthy.
In preparation for solicitor's journey, we are replacing the declaration single checkbox in the Check Your Answers page, with a full name input where the signee (whether an applicant, or a solicitor) can enter their name.
If the applicant has a solicitor, they also will be able to select who is the signee (applicant or solicitor). If they don't have a solicitor (they answered NO to that question) then we don't show these radio options and default to `applicant` as the signee capacity.
Some minor updates to the PDF so we can print these new details, and also make sure it works backwards for compatibility with completed applications still in database.
=> Replace declaration checkbox with full name input

app/views/steps/application/check_your_answers/edit.html.erb
As we don't have the declaration checkbox anymore, and instead we have an input text, this will not get tracked automatically in GA.
We add the event to the form to track on submit. If the signee capacity radios are also present, these will track as well as a separate event (as before with the checkbox).
=> Track completion form submissions

app/forms/steps/application/declaration_form.rb, app/forms/steps/application/payment_form.rb, app/models/c100_application.rb, app/views/steps/application/check_your_answers/edit.html.erb, app/views/steps/application/payment/edit.html.erb, spec/forms/steps/application/declaration_form_spec.rb, spec/forms/steps/application/payment_form_spec.rb, spec/models/c100_application_spec.rb
Move from the individual form objects where we are using it to the C100Application model to DRY and because it will probably be used more times in the future in other places.
=> Refactor `has_solicitor` method

app/controllers/application_controller.rb, app/controllers/backoffice/application_controller.rb, app/controllers/concerns/security_handling.rb, app/controllers/concerns/session_handling.rb, spec/controllers/application_controller_spec.rb
Split the code dealing with the session to a separate `SessionHandling` concern.
This way we can use the much simple `SecurityHandling` in the back office too.
Current functionality is mantained.
=> Rearrange security concern

app/assets/javascripts/modules/session-timeout.js, app/controllers/backoffice/application_controller.rb, app/controllers/concerns/security_handling.rb, spec/controllers/application_controller_spec.rb
So we can easily bypass it on areas where we don't need it, like in the back office (it has its own auth mechanism, with Auth0).
=> Move the basic HTTP auth to a method

app/services/c100_app/applicant_decision_tree.rb, db/migrate/20200121092151_bump_c100_application_version_for_solicitors.rb, db/schema.rb, spec/services/c100_app/applicant_decision_tree_spec.rb
Bump the C100 Application record version from 3 to 4.
New applications created right after this migration will have version = 4 and will be shown the question 'do you have a solicitor?'
Current applications in-progress, or drafts, will maintain their version = 3 and we will not show them the new question.
Once all applications are in version >= 4, we can remove the feature-flag code.
=> Enable solicitor's journey by bumping version

app/models/completed_applications_audit.rb, app/views/backoffice/dashboard/_completion.en.html.erb, spec/models/completed_applications_audit_spec.rb
This will help when creating statistics, as some fields or questions were introduced in different versions of the application and thus it is not expected old audit records will contain all metadata fields.
As of today, current version is 4, saved applications (drafts) are in 3, and old audit records might be in any version from 1 to 3. We are not going to backdate these old audit records as would be difficult to pinpoint the exact version and it is not needed for current statistics.
=> Add the application version to the audit record

app/controllers/concerns/security_handling.rb
It turns out these headers are not longer needed as they are being set out of the box for us, and in some cases this code was duplicating some of the headers.
This code was originally carried over from Heroku where these where needed.
=> Remove unneeded headers code

Dockerfile, Gemfile, Gemfile.lock, config/initializers/wicked_pdf.rb, run.sh, worker.sh
The Dockerfiles in the repo [docker-templates](https://github.com/ministryofjustice/docker-templates) is being deprecated and it is recommended to keep Dockerfiles and docker images as lightweight and simple as possible.
In this case we are going to refactor the Dockerfile to use an alpine image and add dependencies on top.
This service is a bit special as it requires some extra dependencies in order for the PDF generation to work fine and with nice fonts.
These PDF gems had to be updated to work with the new Alpine-based image.
=> Stop using ministryofjustice/docker-templates

sidekiq.sh
It turns out we are using `sh` not `bash` and the loop syntax is different.
=> Change loop to bourne shell (sh)

app/models/user.rb, app/presenters/c8_confidentiality_presenter.rb, spec/models/user_spec.rb, spec/presenters/c8_confidentiality_presenter_spec.rb
Now that we have Sidekiq up and running we can also incorporate any Devise emails (reset password, etc.) as per instructions here:
https://github.com/heartcombo/devise#activejob-integration
Also, although unrelated, there was a pesky warning in the Sidekiq logs when generating the C8 form: `delegator does not forward private method #to_ary`
Removed this warning by implementing the missing method.
=> Send Device emails asynchronously

app/services/c100_app/draft_reminders.rb, app/services/reports/failed_emails_report.rb, run.sh, spec/services/c100_app/draft_reminders_spec.rb, worker.sh
The `daily_tasks` rake task run daily at night and can send quite a lot of emails, depending on how many draft applications are about to expire (reminders).
Up until now we didn't have a background job queue but now we have Sidekiq and can enqueue all these emails for sending later which will make the task run faster and terminate without risk of emails not being sent.
Removed the `worker.sh` script as it will be replaced with  a simpler `bin/rails daily_tasks` in the cronjob kubernetes deployment.
=> Send daily task emails asynchronously

app/mailers/notify_mailer.rb, app/services/c100_app/reminder_rule_set.rb, config/application.rb, spec/mailers/notify_mailer_spec.rb, spec/services/c100_app/reminder_rule_set_spec.rb
Symbols will raise an `ActiveJob::SerializationError: Unsupported argument type: Symbol` exception.
In the draft reminders we used as an argument to the mailer method a symbol for the name of the template. This made these reminders fail now that they are sent asynchronously.
Made so the collection of templates works with strings or symbols (indifferent access) and pass a string arg to the draft reminders method.
Also, removed the custom exception handling on `NotifyMailer` class `rescue_from Exception, with: :log_error_and_raise` because it was stopping Sidekiq from actually re-enqueue the job for retry.
=> Ensure draft reminder emails play nice when async

app/models/user.rb, spec/controllers/users/logins_controller_spec.rb, spec/models/user_spec.rb
This is a more accurate way of purging accounts because the `last_sign_in_at` is always 1 sign-in behind (except in the first sign-in where both dates are the same).
The `current_sign_in_at` gets updated in each sign-in.
=> Use `current_sign_in_at` instead of `last_sign_in_at`

app/controllers/status_controller.rb, app/services/c100_app/status.rb, spec/controllers/status_controller_spec.rb, spec/services/c100_app/status_spec.rb
Make it a bit more useful including Sidekiq checks, and also remove
the dependency we had with Court Tribunal Finder because it is just
too unreliable and we don't have any control over it so even if it
goes down, we should not consider our service unhealthy.
Still, this endpoint should not be used for kubernetes probes.
Use `ping` instead.
=> Refactor status endpoint

app/services/c100_app/online_submission_queue.rb, db/migrate/20200210092306_add_unique_index_to_email_submissions.rb, db/schema.rb, spec/services/c100_app/online_submission_queue_spec.rb
The code we previously had was making use of a thread-unsafe "find first and if not found, write to database" mechanism to check if we had an `EmailSubmission` record in order to avoid running again the code that sends these emails.
However, this mechanism is actually prone to a race condition. It’s possible that user may double-click a submit button and duplicate a HTTP request. If the timing is perfect, both select would then see no records, then try to do the INSERT.
In the end, we will end up with two rows with the same value in the database.
This has been changed to a "write first, and ignore if you can't" mechanism, where only the first thread will be able to write the record and any later try will fail with a `ActiveRecord::RecordNotUnique` exception.
Changed the …
=> Protect from emails edge case race condition

app/controllers/steps/attending_court/language_controller.rb, app/controllers/steps/attending_court_step_controller.rb, app/forms/steps/attending_court/language_form.rb, app/models/c100_application.rb, app/models/court_arrangement.rb, app/services/c100_app/attending_court_decision_tree.rb, app/views/steps/attending_court/language/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, db/migrate/20200207123819_create_court_arrangements_table.rb, db/schema.rb, spec/controllers/steps/attending_court/language_controller_spec.rb, spec/forms/steps/attending_court/language_form_spec.rb, spec/services/c100_app/attending_court_decision_tree_spec.rb
This new table will be used to create the new fields needed for the redesign of the special measures steps, beginning with the language step.
Once all the special measures steps have been migrated, we will be able to remove the old DB fields from the main `c100_applications` table.
Add language step in new `attending_court` namespace.
The main objective here will be to replicate the existing special measures steps, but in a separate namespace so they can be independent from each other and let us introduce new fields.
For a while these 2 journeys will have to cohabit together until all new applications are migrated to the new version.
We are not enabling yet in this PR the new journey.
Following PR's will introduce the changes to the CYA page and the …
=> Add new court arrangements table, starting with language

.rubocop.yml, app/presenters/summary/c100_form.rb, app/presenters/summary/c1a_form.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/attending_court.rb, app/presenters/summary/html_sections/attending_court_v2.rb, app/presenters/summary/html_sections/people_details.rb, app/presenters/summary/sections/attending_court.rb, app/presenters/summary/sections/attending_court_v2.rb, config/locales/cya/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, spec/presenters/summary/c100_form_spec.rb, spec/presenters/summary/c1a_form_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/attending_court_spec.rb, spec/presenters/summary/html_sections/attending_court_v2_spec.rb, spec/presenters/summary/sections/attending_court_spec.rb, spec/presenters/summary/sections/attending_court_v2_spec.rb
While we migrate all the applications to the new version, we must support old applications, so both blocks will continue working in parallel, but the new one will only show if we have a `court_arrangement` DB record.
=> Add new language block to CYA and PDF

app/presenters/summary/html_sections/attending_court.rb, app/presenters/summary/html_sections/attending_court_v2.rb, app/services/c100_app/application_decision_tree.rb, app/services/c100_app/attending_court_decision_tree.rb, app/views/steps/application/details/edit.html.erb, config/locales/cya/en.yml, spec/presenters/summary/html_sections/attending_court_spec.rb, spec/presenters/summary/html_sections/attending_court_v2_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/services/c100_app/attending_court_decision_tree_spec.rb
We are moving this question one step back, so it goes before the language question, instead of after, like it is now.
This will help with the reorganising of the rest of the attending court questions. In essence we maintain this question as it is, and we will not use the new table for these fields, at least for now.
The PDF order does not change.
=> Change order of the litigation capacity step

app/controllers/steps/attending_court/intermediary_controller.rb, app/forms/steps/attending_court/intermediary_form.rb, app/services/c100_app/attending_court_decision_tree.rb, app/views/steps/attending_court/intermediary/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, db/migrate/20200211152952_add_welsh_fields_to_court_arrangements.rb, db/migrate/20200211153458_add_intermediary_fields_to_court_arrangements.rb, db/schema.rb, spec/controllers/steps/attending_court/intermediary_controller_spec.rb, spec/forms/steps/attending_court/intermediary_form_spec.rb, spec/services/c100_app/attending_court_decision_tree_spec.rb, spec/support/form_validation_shared_examples.rb
As we did with language we are creating (in this case an identical) copy of the already existing `intermediary` step, but in the new namespace `AttendingCourt`, and using the DB fields from the associated table `court_arrangement`.
Some minor copy changes along the way as per design.
This is not yet wired to the main journey, but can be accessed knowing the URL.
Next PR will add the neccessary CYA and PDF changes.
Also, for future needs, a couple of fields for Welsh language have been added to the `court_arrangements` table. We are not using them at the moment.
=> Duplicate intermediary step in new namespace

app/presenters/summary/html_sections/attending_court.rb, app/presenters/summary/sections/attending_court.rb, app/services/c100_app/application_decision_tree.rb, app/views/steps/application/special_arrangements/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, spec/presenters/summary/html_sections/attending_court_spec.rb, spec/presenters/summary/sections/attending_court_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb
We are moving the special safety arrangements one step back, so it goes before the special assistance question, instead of after, like it is now.
This will help with the reorganising of the rest of the attending court questions. For now we maintain the attributes the same, but we tweak the copy. In a following PR we will redesign these steps to use the new DB table and check boxes instead of radios.
=> Change order of the special assistance step

app/presenters/summary/html_sections/attending_court_v2.rb, app/presenters/summary/sections/attending_court_v2.rb, app/services/c100_app/attending_court_decision_tree.rb, config/routes.rb, spec/presenters/summary/html_sections/attending_court_v2_spec.rb, spec/presenters/summary/sections/attending_court_v2_spec.rb, spec/services/c100_app/attending_court_decision_tree_spec.rb
As we did with language, we are adding this block, identical to the existing block but using the new attributes (from the `court_arrangements` table).
=> Add new intermediary block to CYA and PDF

app/mailers/notify_mailer.rb, app/mailers/notify_submission_mailer.rb, spec/mailers/notify_submission_mailer_spec.rb
We don't need the filter constant anymore as we are not using them. It was a leftover from a previous PR.
Also, now that we have a `declaration signee` we can use this instead of the ugliness of picking the first applicant (in case there are more than one). It is more accurate and also works fine for solicitors submitting an application for their client.
=> Remove unneeded email submission code

app/controllers/steps/attending_court/special_assistance_controller.rb, app/forms/steps/attending_court/special_assistance_form.rb, app/services/c100_app/attending_court_decision_tree.rb, app/value_objects/special_arrangements.rb, app/value_objects/special_assistance.rb, app/views/steps/attending_court/special_assistance/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, config/routes.rb, db/migrate/20200213163220_add_special_assistance_fields_v2.rb, db/schema.rb, spec/controllers/steps/attending_court/special_assistance_controller_spec.rb, spec/forms/steps/attending_court/special_assistance_form_spec.rb, spec/services/c100_app/attending_court_decision_tree_spec.rb, spec/value_objects/special_arrangements_spec.rb, spec/value_objects/special_assistance_spec.rb
This is not yet wired to the main journey, and can only be accessed by knowing the URL.
Also, CYA and PDF blocks will be added in the next PR.
=> Redesign the special assistance step with check boxes

app/services/c100_app/application_decision_tree.rb, db/migrate/20200214120733_bump_version_for_new_court_arrangements.rb, db/schema.rb, spec/services/c100_app/application_decision_tree_spec.rb
Bump the C100 Application record version from 4 to 5.
New applications created right after this migration will have version = 5 and will be shown the new attending court journey, using check boxes instead of radios for language, special arrangements and special assistance.
Current applications in-progress, or drafts, will maintain their version < 5 and will not see the new journey. They continue seeing the old, existing steps.
Once all applications are in version >= 5, we can remove the feature-flag code.
=> Enable redesigned attending court journey by bumping version

app/forms/steps/attending_court/special_assistance_form.rb, db/migrate/20200214125702_copy_litigator_capacity_into_court_arrangements.rb, db/schema.rb, spec/forms/steps/attending_court/special_assistance_form_spec.rb
So we don't have to duplicate the form objects, controllers, views, etc. as well as changes to CYA and PDF for litigator capacity questions, we are goint to take a pragmatic approach where we continue using the existing code, but copy over the values to the new database table.
When the time comes to delete the old code and attributes for the old attending court journey, it will be much easier just to start using the new table as values for existing applications will be present.
=> Prepare litigation capacity for later migration

app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/buttons.scss, app/assets/stylesheets/local/inputs.scss, app/assets/stylesheets/local/typography.scss
This will fix the extra margin added on mobile devices when using the secondary link next to the continue button, as well as the sizing of the password input on mobile devices too.
=> More small styling fixes

app/presenters/summary/html_sections/attending_court_v2.rb, app/presenters/summary/sections/attending_court_v2.rb, app/services/c100_app/application_decision_tree.rb, app/services/c100_app/attending_court_decision_tree.rb, config/locales/cya/en.yml, config/locales/pdf/en.yml, spec/presenters/summary/html_sections/attending_court_v2_spec.rb, spec/presenters/summary/sections/attending_court_v2_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/services/c100_app/attending_court_decision_tree_spec.rb
This way, litigation capacity and intermediary are together, as these steps use radio options, and then we start with the redesigned steps using check boxes.
Changed the order accordingly in the CYA page and PDF.
=> Reposition intermediary step before language step

app/presenters/summary/sections/additional_information.rb, spec/presenters/summary/sections/additional_information_spec.rb
This needs to cope with the old version of the language question, and the new version.
New version works with check boxes so we need to see if at least one, no matter which one, was selected.
Once all applications are migrated to the new version, we can cleanup the code.
=> Update PDF additional information section

app/lib/audit_helper.rb, app/models/completed_applications_audit.rb, spec/lib/audit_helper_spec.rb, spec/models/completed_applications_audit_spec.rb
This is growing too much with the addition of the special arrangements metadata.
Refactor a bit the code to split the metadata to a separate helper class.
Added a new metadata attribute (`arrangements`) to store a collection (array) of arrangement strings based on what options the applicant chose, either yes-no or check boxes.
Only for new applications using the new `court_arrangements` table. Older applications will just store an empty array.
=> Refactor completions audit log

.rubocop.yml, app/forms/concerns/arrangements_check_boxes_form.rb, app/forms/steps/attending_court/language_form.rb, app/lib/audit_helper.rb, app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/attending_court_v2.rb, app/presenters/summary/html_sections/other_court_cases.rb, app/presenters/summary/sections/additional_information.rb, app/presenters/summary/sections/attending_court_v2.rb, app/presenters/summary/sections/c1a_base_abuse_details.rb, app/value_objects/language_help.rb, app/views/steps/attending_court/language/edit.html.erb, db/migrate/20200218092658_change_language_fields.rb, db/schema.rb, spec/forms/steps/attending_court/language_form_spec.rb, spec/lib/audit_helper_spec.rb, spec/presenters/summary/html_sections/attending_court_v2_spec.rb, spec/presenters/summary/sections/additional_information_spec.rb, spec/presenters/summary/sections/attending_court_v2_spec.rb, spec/value_objects/language_help_spec.rb
Same as with `SpecialArrangementsForm` and `SpecialAssistanceForm`, for consistency.
Individual commits for more detail because a lot of things are affected by this change.
=> Refactor language form to use `ArrangementsCheckBoxesForm` concern

app/forms/steps/attending_court/special_assistance_form.rb, app/lib/audit_helper.rb, db/migrate/20200218143731_remove_litigator_fields_from_court_arrangements.rb, db/schema.rb, spec/forms/steps/attending_court/special_assistance_form_spec.rb, spec/lib/audit_helper_spec.rb
It does not make too much sense to move these fields to the `court_arrangements` table because in reality these are not arrangements.
So this is pretty much a rollout of the PR #792
Also, add back reduced litigation attr to the audit metadata.
=> Remove litigation fields from court arrangements table

app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/attending_court.rb, app/presenters/summary/html_sections/attending_court_v2.rb, app/presenters/summary/html_sections/litigation_capacity.rb, app/views/steps/application/litigation_capacity/edit.html.erb, app/views/steps/application/litigation_capacity_details/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/attending_court_spec.rb, spec/presenters/summary/html_sections/attending_court_v2_spec.rb, spec/presenters/summary/html_sections/litigation_capacity_spec.rb
This was always an anomaly. In the PDF these are separate sections so there is no reason why we had this together in the CYA.
Now these are separate sections also on the CYA. Doesn't really affect anything else, other than being visually separated.
=> Decouple litigation capacity from attending court in CYA

app/assets/stylesheets/local/pdf_summary.scss, app/presenters/relationships_presenter.rb, config/locales/pdf/en.yml, spec/presenters/relationships_presenter_spec.rb
There was unnecessary margins on paragraphs (last-of-type) and also on the relationships we were using <div> to wrap each of the relation, which was introducing a lot of spacing.
Solved by removing the <div> wrapper and instead, letting the `simple_format` format it as we want.
=> Minor styling tweaks to the PDF

config/court_slugs.yml
The family/children cases are heard in this other court, the other slug is left for crime cases instead.
=> Update Newcastle court slug

app/jobs/screener_court_refresh_job.rb, app/models/screener_answers.rb, lib/tasks/court_refresh.rake, spec/jobs/screener_court_refresh_job_spec.rb, spec/models/screener_answers_spec.rb
As we retrieve these details from CTF on the screener phase of the application, there might be cases where by the time the application gets to be submitted, the data is stale.
This only happens if CTF update the court page with a different email, or they change the slug, etc.
Should be a very rare case.
The idea is to have a rake task that can be run on demand to update stale `screener_answers` based on a search criteria (slug, email or both).
Also this will only apply to saved, not completed applications.
=> Mechanism to refresh stale CTF court data

config/sidekiq.yml
This will retry up to 10 times, or equivalent to 4h 31m total waiting time.
As most failures will come from intermitent network issues when sending emails with Notify, there is no point on retrying for longer.
If it is not fixed by the 10th retry, for example in the case of a real bug, the job moves to a dead queue and notify us by email so we can fix the bug and manually retry from the web admin.
=> Reduce sidekiq max retries

app/assets/stylesheets/local/pdf_summary.scss, app/forms/steps/attending_court/language_form.rb, app/presenters/summary/html_sections/attending_court_v2.rb, app/presenters/summary/sections/attending_court_v2.rb, app/views/steps/attending_court/language/edit.html.erb, app/views/steps/completion/shared/_multi_answer_row.html.erb, app/views/steps/completion/shared/_multi_answer_row.pdf.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, spec/forms/steps/attending_court/language_form_spec.rb, spec/presenters/summary/html_sections/attending_court_v2_spec.rb, spec/presenters/summary/sections/attending_court_v2_spec.rb
We had already these fields in the database but we were not exposing them.
Now we are going to show them in the same way we do for other language options.
Updated the form object and view, as well as CYA and PDF to show the relevant Welsh section.
Minor copy changes according to the design to accommodate this change.
=> Add Welsh option to the language step

config/locales/cya/en.yml, config/locales/pdf/en.yml
The copy&paste messed up the tab.
=> Fix locale for intermediary_help_details

app/controllers/backoffice/emails_controller.rb, app/models/concerns/application_reference.rb, app/views/backoffice/emails/_submission.en.html.erb, app/views/backoffice/emails/lookup.en.html.erb, spec/models/concerns/application_reference_spec.rb
There is a requirement to be able to resend recent emails that were successfully sent but for whatever reason, they need to be resend.
In particular, due to an IT outage, some emails where sent without error, but some courts did not receive them.
But can also happen when an applicant or a court says they've not received anything (or they deleted the email by mistake).
This expose a new functionality in the back office so, given a reference code, it is possible to trigger again the sending of emails (court or applicant) at any time, during the 28 days from the creation of the application.
=> Allow resending emails in back office, even not failed ones

app/models/c100_application.rb, app/presenters/fulfilment_error.rb, app/presenters/fulfilment_errors_presenter.rb, app/validators/application_fulfilment_validator.rb, config/locales/errors/en.yml, spec/presenters/fulfilment_error_spec.rb, spec/presenters/fulfilment_errors_presenter_spec.rb, spec/validators/application_fulfilment_validator_spec.rb
This validator will run only on completion of the application (still not wired up, that will come up in a follow-up PR) and will check some preconditions are met in order for the application to be considered "valid" and to be submitted to court. Essentially a quick sanity check.
This is not intended to be an in-deep validation of every single attribute (as that already happens at the step level, one by one as the applicant progress through the application) but more for cases where the user jumped some steps or deleted by mistake all applicants, or all respondents, etc.
Still to do in a follow-up PR the wiring to the CYA page, and the presentation of the errors using the `FulfilmentErrorsPresenter` class and the `check_your_answers/fulfilment_error` partial (not included in this PR as we …
=> Add an application fulfilment custom validator

app/controllers/sessions_controller.rb, app/forms/steps/application/declaration_form.rb, app/presenters/summary/html_presenter.rb, app/validators/application_fulfilment_validator.rb, app/views/steps/application/check_your_answers/_fulfilment_error.html.erb, app/views/steps/application/check_your_answers/_fulfilment_summary.html.erb, app/views/steps/application/check_your_answers/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, spec/forms/steps/application/declaration_form_spec.rb, spec/presenters/summary/html_presenter_spec.rb, spec/validators/application_fulfilment_validator_spec.rb
Follow-up to PR #818.
Show the errors, if any, in the CYA page. Still design is TBD so the partials are just placeholders, showing basic details about the error.
As part of this PR and to protect this new feature from being released to production before is ready, added a simple mechanism to feature-flag the validations: it will run ONLY if we are using fake court data (a fixture, like we do when ue the bypass functionality on local/staging envs).
This way, on production there is no risk of this validation being run just yet.
Note: it is possible to avoid the validations also on local/staging if you start the screener and answer at least one question, then you can use the bypass functionality (or just continue all the way to the end answering questions) and the fulfilment validator will …
=> Present fulfilment errors in CYA page

app/presenters/fulfilment_errors_presenter.rb, app/validators/application_fulfilment_validator.rb, config/locales/errors/en.yml, spec/presenters/fulfilment_errors_presenter_spec.rb, spec/validators/application_fulfilment_validator_spec.rb
Same as we did with applicants, we add validation for having at least one child and at least one respondent.
For now this will be all. We can decide to include more validations later on.
Reworked a bit the loop to retrieve the error details so it works when there is more than one, like we have now.
The final little PR after this one will be to enable this for all users (without feature-flag) to be able to release to production.
=> Add validation for children and respondents

app/assets/stylesheets/local/check_answers.scss, app/validators/application_fulfilment_validator.rb, spec/validators/application_fulfilment_validator_spec.rb
Up until now this work was behind a feature flag, but now we are going to release it to production. Removing the feature-flag code.
Also, fixed some styling issues found on smaller devices.
=> Enable fulfilment validator for all

app/forms/steps/shared/under_age_form.rb, app/views/steps/applicant/under_age/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, spec/forms/steps/shared/under_age_form_spec.rb
This commit updates the under age form to save the answer given on the form,
the answer is an acknowlegment that they understand what they need to do and
that they acknowlege they are of under age.
=> Update applicant under age form

app/services/c100_app/respondent_decision_tree.rb, spec/services/c100_app/respondent_decision_tree_spec.rb
We are rolling out an allowance for under age Participant and Respondents to be able to fill the form.
This commit is about removing the age check on the Respondent.
There will be more follow up PR's
=> remove Respondent age check

app/mailers/notify_mailer.rb, app/mailers/notify_submission_mailer.rb, app/models/applicant.rb, config/locales/en.yml, spec/mailers/notify_submission_mailer_spec.rb, spec/models/applicant_spec.rb
Expose a helper method on the `Applicants` collection to query if there is at least one applicant under age (returning true or false).
This method is later used on Notify emails, but can also be used for the confirmation pages or any other place where we need to know if the application as a whole contains at least one under age.
Send the yes/no to Notify to be able to show/hide the instructions when applicant is under age in the confirmation email.
Tweaked a bit the card payment instructions as per suggestions from content designer.
The under18s instructions are part of the Notify template.
Example of email with the under 18s code inserted (and the payment instructions tweaked):
=> Customise email copy when applicant is under age

app/lib/audit_helper.rb, app/views/backoffice/dashboard/_completion.en.html.erb, spec/lib/audit_helper_spec.rb
In order to accurately track the number of applications considered 'under age' (containing at least 1 applicant under 18s), we add this data to the audit table, as we've done with other details.
Also show this in the back office when retrieving the details of an application.
The default for old applications (lacking this data) is false as we've had the screener question all this time and didn't allow under 18s.
=> Add under age data to the audit table

db/migrate/20200317155024_remove_over18_from_screener_answers.rb, db/schema.rb, spec/models/screener_answers_spec.rb, spec/support/step_controller_shared_examples.rb
This is because there is validation on the table attributes,
if those attributes are not filled, the screener never reaches the "completion" status that is needed.
=> remove over18 attribute from screen answers

config/court_slugs.yml
Court Tribunal Finder has split the old slug into two, but only one is the court handling family cases.
Old slug does not exist anymore:
https://courttribunalfinder.service.gov.uk/courts/luton-county-court-and-family-court
This fixes the smoke errors.
=> Update Luton slug

app/assets/javascripts/modules/ga-events.js, app/assets/stylesheets/local/app.scss, app/views/about/accessibility.en.html.erb, app/views/about/contact.en.html.erb, app/views/about/cookies.en.html.erb, app/views/about/miam_exemptions.en.html.erb, app/views/about/privacy.en.html.erb, app/views/about/privacy_consent.en.html.erb, app/views/about/terms_and_conditions.en.html.erb
Migrate all pages linked to from the footer (or header like the "Report a problem" link) to the new desig system.
This is not a search and replace (sadly). It is a time consuming task because we must replace old markup with appropiate new one, as well as classes, but also use headings consistently to create a clear hierarchy throughout the service.
The headings mark up must be semantic as per guidelines here:
https://design-system.service.gov.uk/styles/typography/#headings
Also removed obsolete markup and replaced `strong` tags with either headers or proper font weight classes.
=> Migrate about pages to new design system

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/helpers/custom_form_helpers_v2.rb, app/views/layouts/govuk_template.html.erb, app/views/steps/screener/postcode/edit.html.erb, config/initializers/form_builder.rb, config/locales/en.yml, features/errors.feature, features/step_definitions/common.rb, spec/helpers/application_helper_spec.rb, spec/helpers/custom_form_helpers_spec.rb, spec/helpers/custom_form_helpers_v2_spec.rb
This is a first attempt to try to use DFE new design system form builder ([govuk_design_system_formbuilder](https://github.com/DFE-Digital/govuk_design_system_formbuilder)) to output form elements with new markup and classes.
First form migrated (children's postcode). As well as the continue buttons.
**Individual commits with more details.**
This is an alternative solution to the one tried in PR #837. I believe, it is early to say but we will be probably better using this builder as it contains all the basic elements and also revealing elements. It is yet to be seen if it will work just "out of the box" for some of our most complex forms/steps.
=> Attempt to use `govuk_design_system_formbuilder`

app/assets/stylesheets/local/typography.scss, app/views/steps/screener/done/show.en.html.erb, app/views/steps/screener/email_consent/edit.html.erb, app/views/steps/screener/error_but_continue/show.html.erb, app/views/steps/screener/no_court_found/show.en.html.erb, app/views/steps/screener/parent/edit.html.erb, app/views/steps/screener/parent_exit/show.html.erb, app/views/steps/screener/warning/show.html.erb, app/views/steps/screener/written_agreement/edit.html.erb, app/views/steps/screener/written_agreement_exit/show.html.erb, app/views/steps/shared/_screener_exit_actions.html.erb, config/locales/en.yml, features/screener.feature
Individual commits for more details.
TODO: the gem does not automatically localise the radio labels. It needs to be passed as `label: { text: 'foobar' }` which is kind of annoying.
Probably we can raise a PR to improve this.
This and other issues will be discovered as we advance with the migration.
=> Migrate screener pages and forms to new design system

Gemfile, Gemfile.lock, app/views/steps/screener/email_consent/edit.html.erb, app/views/steps/screener/parent/edit.html.erb, app/views/steps/screener/written_agreement/edit.html.erb, config/locales/en.yml, features/screener.feature
The label text for the radio options is now coming from the locales, as it used to be the case with our previous gem.
I've forked the repo and [made the improvement](https://github.com/zheileman/govuk_design_system_formbuilder/pull/1) but not yet raise a PR to the original repo until we advance enough with our migration to be sure it is working as expected and also because we might need to do the same with check boxes once we start using them.
=> Improve radios localisation (using forked gem for now)

app/views/about/terms_and_conditions.en.html.erb
There are a few services in public beta, and don't see any mention of what this
means - perhaps because services in public beta are assumed to be closer to a
'ongoing maintenance state'.
In which case there isn't really a clearly defined user need to provide info
about our internal development process.
This commit is just removing the paragraph concerning Public alpha without
replacing it with a correspondent one about public beta.
=> Removes "Public Alpha" section from T&C

lib/tasks/mutant.rake
Same as we already do with master branch.
This makes it more quick and efficient.
Mutant will however continue running on PRs as before.
=> Tweak mutant to not run on develop branch

Gemfile.lock, app/assets/stylesheets/local/app/pending_migration.scss, app/views/steps/miam/acknowledgement/edit.en.html.erb, app/views/steps/miam/child_protection_cases/edit.html.erb, config/locales/en.yml
These are the two first questions after the screener.
Note during the migration, as it advances, new issues can be found. I found the changes done to the forked gem to cope with localisations for radios was not covering all scenarios.
Some more [changes have been made](https://github.com/zheileman/govuk_design_system_formbuilder/pull/2) to the forked gem and we shall see if this covers everything we might need in this service.
From now on some steps will be quite complex so it could be we need to make some more amendments (trying as much as possible to always do this in a backwards compatible way so perhaps we can integrate these improvements in the upstream repo).
=> First two forms in journey migrated

Gemfile.lock, app/controllers/steps/attending_court/language_controller.rb, app/controllers/steps/attending_court/special_arrangements_controller.rb, app/controllers/steps/attending_court/special_assistance_controller.rb, app/forms/concerns/arrangements_check_boxes_form.rb, app/forms/steps/attending_court/language_form.rb, app/forms/steps/attending_court/special_arrangements_form.rb, app/forms/steps/attending_court/special_assistance_form.rb, app/views/steps/attending_court/intermediary/edit.html.erb, app/views/steps/attending_court/language/edit.html.erb, app/views/steps/attending_court/special_arrangements/edit.html.erb, app/views/steps/attending_court/special_assistance/edit.html.erb, config/locales/en.yml, spec/forms/steps/attending_court/language_form_spec.rb, spec/forms/steps/attending_court/special_arrangements_form_spec.rb, spec/forms/steps/attending_court/special_assistance_form_spec.rb, spec/helpers/custom_form_helpers_v2_spec.rb
I've jumped ahead to almost the end of the journey in order to migrate this whole block of 4 questions involving mostly check boxes, as this let us test the gem in this scenario, with some check boxes revealing text areas.
Dramatically simplified the `ArrangementsCheckBoxesForm` concern as instead of separate attributes for each check box, we now use a single attribute to contain the selected check boxes.
This is so it works better with the new gem too.
=> Migrate attending court steps to new design system

.gitignore, config/court_slugs.yml
The old page is no longer valid but there is a new slug for this court, so adding it to the service.
This fixes the failing smoke test.
Note: I've added to the .gitignore the `node_modules` as we are now using it (on develop branch) and could be commited by mistake when switching between branches.
=> Updated Aldershot court

app/forms/steps/screener/email_consent_form.rb, app/views/steps/miam/acknowledgement/edit.en.html.erb, app/views/steps/miam/child_protection_cases/edit.html.erb, app/views/steps/screener/email_consent/edit.html.erb, app/views/steps/screener/parent/edit.html.erb, app/views/steps/screener/written_agreement/edit.html.erb, config/court_slugs.yml, config/locales/en.yml, spec/forms/steps/screener/email_consent_form_spec.rb
Radios that reveal content should never be inline, and instead must be stacked, as per issue clarification here:
https://github.com/DFE-Digital/govuk_design_system_formbuilder/issues/104
As having mixed inline and stacked radios for Yes-No question will be negative for users, from now on we will be using only stacked radios even if they don't reveal content, so there is consistency. We could re-evaluate this decision later on if design system introduces inline revealing elements.
Some other minor amendments to comply with design system guidelines, like trying to incorporate the header into the fieldset legend where possible, and if not, provide a legend even if it is visually hidden.
For now we are not using visually hidden but in the MIAM acknowledgement I've made sure we have a legend …
=> Convert inline radios to stacked radios

app/forms/concerns/arrangements_check_boxes_form.rb, app/validators/checkbox_options_validator.rb, app/views/steps/attending_court/special_arrangements/edit.html.erb, app/views/steps/attending_court/special_assistance/edit.html.erb, config/locales/en.yml, spec/forms/steps/attending_court/language_form_spec.rb, spec/forms/steps/attending_court/special_arrangements_form_spec.rb, spec/forms/steps/attending_court/special_assistance_form_spec.rb
In the attending to court steps, after the refactor to use the new design system, it was possible to pass unknown options to the form object, by editing the html of the form (tampering with it).
This PR introduces a simple validation so all selected options are validated against the valid expected values.
Also, updated the markup of the `special_arrangements` step so the heading is part of the legend as we did with the other steps, in line with the recommended design system guidelines.
=> Ensure no tampering with checkbox options

app/helpers/application_helper.rb, app/views/entrypoint/how_long.en.html.erb, app/views/entrypoint/what_is_needed.en.html.erb, app/views/steps/miam/child_protection_info/show.en.html.erb, app/views/steps/screener/done/show.en.html.erb, app/views/steps/screener/error_but_continue/show.html.erb, app/views/steps/screener/start/show.en.html.erb, app/views/steps/screener/warning/show.html.erb, app/views/steps/shared/_screener_exit_actions.html.erb, spec/helpers/application_helper_spec.rb
This is a very common use case and we are using it in many places (more to come with the migration).
The helper will output the expected markup and will simplify if we later on need to change the classes or something as ideally there will only be one place to touch.
It tries to be smart about overriding (or not) some attributes, to cope with most common combinations, but later on we could improve it if we need more complex use-cases.
Updated already migrated pages to use this helper.
=> Add helper to create links with button shape

Gemfile.lock, app/attributes/multi_param_date.rb, app/controllers/step_controller.rb, app/forms/steps/miam/certification_date_form.rb, app/views/steps/miam/attended/edit.html.erb, app/views/steps/miam/certification/edit.html.erb, app/views/steps/miam/certification_date/edit.html.erb, config/initializers/form_builder.rb, config/locales/en.yml, spec/attributes/multi_param_date_spec.rb, spec/controllers/step_controller_spec.rb, spec/forms/steps/miam/certification_date_form_spec.rb
This PR introduces the migration of the first date element found in the application, MIAM certification date (a couple other pages have been migrated to get there but it was just radio options and copy).
For the dates previously we were using a custom date gem `gov_uk_date_fields` that had the ability not only to produce the markup but also to send parameters and process this parameters.
Now, the new gem does not provide that functionality, it only renders the view element, so anything in the backend is up to us. Also, it sends the parameter in the Rails way for multi params (appending a suffix to the parameter name).
Still we are going to leave the old gem because the steps not yet migrated will continue using it but once we've migrated all the dates in the application we can remove the …
=> Migrate first date form element (MIAM certification date)

app/views/steps/attending_court/intermediary/edit.html.erb, app/views/steps/attending_court/language/edit.html.erb, app/views/steps/attending_court/special_arrangements/edit.html.erb, app/views/steps/attending_court/special_assistance/edit.html.erb, app/views/steps/miam/acknowledgement/edit.en.html.erb, app/views/steps/miam/child_protection_cases/edit.html.erb, app/views/steps/screener/email_consent/edit.html.erb, app/views/steps/screener/parent/edit.html.erb, app/views/steps/screener/written_agreement/edit.html.erb
We do not need to set these manually now as we've defined the default configuration in `config/initializers/form_builder.rb`
For those pages where these defaults don't work we can still set the tag and size manually (like in the MIAM acknowledgement).
=> Default legend tag is h1 and size xl

Gemfile.lock, app/views/steps/miam/acknowledgement/edit.en.html.erb, app/views/steps/safety_questions/address_confidentiality/edit.html.erb, app/views/steps/safety_questions/children_abuse/edit.html.erb, app/views/steps/safety_questions/domestic_abuse/edit.html.erb, app/views/steps/safety_questions/other_abuse/edit.html.erb, app/views/steps/safety_questions/risk_of_abduction/edit.html.erb, app/views/steps/safety_questions/start/show.en.html.erb, app/views/steps/safety_questions/substance_abuse/edit.html.erb, config/locales/en.yml
These are the questions after the MIAM certification, in the `steps/safety_questions` namespace.
The abduction sub-journey and the abuse questions loop are not yet migrated. That will be in follow-up PRs.
In some of these questions, the fieldset legend is set to visually hidden to comply with accessibility recommendations in the new design system.
This happens when between the heading (H1) and the fieldset legend there is a lot of content making the heading too disconnected from the legend and thus difficult for screen readers to parse the form.
=> Migrate safety questions steps

app/attributes/checkbox_boolean.rb, app/controllers/step_controller.rb, app/forms/steps/abduction/passport_details_form.rb, app/forms/steps/abduction/previous_attempt_details_form.rb, app/views/steps/abduction/children_have_passport/edit.html.erb, app/views/steps/abduction/international/edit.html.erb, app/views/steps/abduction/passport_details/edit.html.erb, app/views/steps/abduction/previous_attempt/edit.html.erb, app/views/steps/abduction/previous_attempt_details/edit.html.erb, app/views/steps/abduction/risk_details/edit.html.erb, config/locales/en.yml, spec/attributes/checkbox_boolean_spec.rb, spec/forms/steps/abduction/previous_attempt_details_form_spec.rb
This is a sub-journey of the safety questions. If you answer YES to the abduction question, then you enter this set of questions.
Again the way we built the checkboxes originally (with the old gem) is now kicking us back, as the new gem will not POST/PUT single values like true/false but array of values like `["true"]`
In order to workaround this without having to do a big refactor, and also to maintain backwards compatibility with those steps not yet migrated, I've created a new attribute type, named `CheckboxBoolean` that essentially will extract the value from the array and use it to cast a boolean as before.
Once we've migrated all steps we should get back to these checkboxes and refactor to use the same approach we've used in the Attending Court steps (language, special arrangements, …
=> Migrate abduction journey steps

Gemfile.lock, app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/lists.scss, app/controllers/steps/miam_exemptions/domestic_controller.rb, app/forms/concerns/miam_exemptions_check_boxes_form.rb, app/forms/steps/miam_exemptions/domestic_form.rb, app/views/steps/miam_exemptions/domestic/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/locales/exemptions/en.yml, spec/forms/steps/miam_exemptions/domestic_form_spec.rb
This is a first attempt to migrate the MIAM exemptions.
It is in a working state although there is a refinement we should do at some point so if you select some exemptions inside a group (a checkbox revealing more check boxes) and then deselect the whole group and submit, the selected options inside said group should also be automatically de-selected and not saved to the database to avoid confusion to the user. **Note**: this is happening also in production, so any improvement is welcomed but not a regression per se.
In any case, other than that, I believe it is totally functional but a big refactor to the locales was needed. As well as another improvement to the gem here https://github.com/zheileman/govuk_design_system_formbuilder/pull/4
Problem with locales is, up until now we used the …
=> Migrated first page of MIAM exemptions (domestic)

app/controllers/steps/miam_exemptions/protection_controller.rb, app/forms/steps/miam_exemptions/protection_form.rb, app/views/steps/miam_exemptions/protection/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/locales/exemptions/en.yml, spec/forms/steps/miam_exemptions/protection_form_spec.rb
Same as the first page, but much simpler as there are no revealing check boxes or hint text.
In any case, with the first page the concern is now prepared to be used in the rest of pages easily.
=> Migrated second page of MIAM exemptions (protection)

app/controllers/steps/miam_exemptions/urgency_controller.rb, app/forms/steps/miam_exemptions/urgency_form.rb, app/views/steps/miam_exemptions/urgency/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/locales/exemptions/en.yml, spec/forms/steps/miam_exemptions/urgency_form_spec.rb
Same as the first page, but much simpler as there are no revealing check boxes or hint text. Like protection page.
=> Migrated third page of MIAM exemptions (urgency)

app/controllers/steps/miam_exemptions/adr_controller.rb, app/forms/steps/miam_exemptions/adr_form.rb, app/value_objects/adr_exemptions.rb, app/views/steps/miam_exemptions/adr/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/locales/exemptions/en.yml, spec/forms/steps/miam_exemptions/adr_form_spec.rb, spec/value_objects/adr_exemptions_spec.rb
After running this through our service designer, we've simplified the page so instead of 2 check boxes revealing 3 and 2 each more, now it is just a plain list of check boxes, identical to the paper form.
This let's us remove some of the ugly hint text with bullet points, and make the page simpler to read.
=> Migrate fourth page of MIAM exemptions (ADR)

app/assets/stylesheets/local/app/pending_migration.scss, app/controllers/steps/petition/orders_controller.rb, app/forms/steps/petition/orders_form.rb, app/presenters/summary/html_sections/nature_of_application.rb, app/views/steps/petition/orders/edit.html.erb, app/views/steps/petition/playback/show.html.erb, app/views/steps/petition/protection/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, spec/forms/steps/petition/orders_form_spec.rb, spec/presenters/summary/html_sections/nature_of_application_spec.rb
Migrate this step and its playback to new design system.
This is very similar to what was done for MIAM Exemptions, but it has a few particular differences so it is not worth trying to adapt the concern just for this (it has a revealing text area, for once), so I've opted for leaving the logic as it was, inside the form object itself, but updated to work with the new check boxes.
=> Migrate nature of application (petition order) view

app/assets/stylesheets/local/app.scss, app/forms/steps/children/personal_details_form.rb, app/views/steps/children/personal_details/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml
Fortunetely we've already migrated dates before so this was an easy task.
Just made sure the checkbox for "I don’t know their date of birth" was closer together to the actual date of birth input, as before, but as we can't apply classes to form element wrappers directly (`govuk-form-group`) I had to rely to the pseudo class `first-of-type` that will not work on older IE (older than 9 I believe) browser.
Not a big issue, on those browsers the checkbox will be a bit more separated from the date of birth input.
=> Migrate children personal details page

app/controllers/steps/children/orders_controller.rb, app/forms/form_attribute_methods.rb, app/forms/steps/children/orders_form.rb, app/views/steps/children/orders/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, spec/forms/steps/children/orders_form_spec.rb
This step is shown for each child and the list of checkboxes comes from the step where we ask what the applicant want to apply for, so the list is dynamic.
Complication is, the record is a child, but we are reading/writing the orders attribute in a `child_order` association (has_one).
Removed the method `selected_options` from the `FormAttributeMethods` module because we don't use it anymore in any other places.
=> Migrate children decisions step

app/services/c100_app/address_lookup_service.rb, app/views/steps/address/lookup/_applicant.html.erb, app/views/steps/address/lookup/_other_party.html.erb, app/views/steps/address/lookup/_respondent.html.erb, app/views/steps/address/lookup/edit.html.erb, app/views/steps/address/results/_no_results.en.html.erb, app/views/steps/address/results/edit.html.erb, config/locales/en.yml, spec/services/c100_app/address_lookup_service_spec.rb
These are a few views, shared between Applicant, Respondent and Other Party.
All behave the same except for some minor copy changes and links pointing to different places.
Had to add a workaround to the dropdown list as the new design system gem does not allow `include_blank: true` to include a blank item in the dropdown as before.
I've seen this is anyways not recommended as cause confusion to the user so I've done what it is recommended that is include as the first element of the dropdown the number of addresses found instead of a blank item as before.
--
=> Migrate postcode lookup to new design system

app/assets/javascripts/modules/password-toggle.js, app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/inputs.scss, app/assets/stylesheets/local/typography.scss, app/views/layouts/_flash_alert.html.erb, app/views/layouts/application.html.erb, app/views/layouts/govuk_template.html.erb, app/views/users/logins/new.html.erb, config/locales/en.yml
* Refactored flash alert and styling
The flash alert will be used in some places of the `views/users/*` due to how Devise works.
In order to make it behave more like the rest of errors, we can style and make sure the flash alert is identical to the other errors.
* Adapted the javascript to show/hide the password to work with new markup and styles
=> Migrate user sign in page

app/views/steps/abuse_concerns/details/edit.html.erb, app/views/users/logins/new.html.erb, app/views/users/passwords/edit.html.erb, app/views/users/passwords/new.html.erb, app/views/users/passwords/reset_confirmation.html.erb, app/views/users/passwords/reset_sent.html.erb, app/views/users/registrations/new.html.erb, config/locales/en.yml, config/locales/errors/en.yml
And associated confirmation pages.
Changed inputs width from `one-half` to `two-thirds` to make them slighly bigger, reserving 'one-half' for smaller inputs like reference numbers.
Also I went back to tweak some of the copy and positioning of elements in the sign in and registration pages, as per recommendations here:
https://design-system.service.gov.uk/patterns/create-accounts/
--
=> Migrate reset password page

app/assets/stylesheets/local/app.scss, app/views/layouts/_current_user_menu.html.erb
This will now show as it should.
Active link will also be marked in a different colour as per design system.
https://design-system.service.gov.uk/components/header/
=> Fix header styling

app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/buttons.scss, app/views/steps/application/receipt_email_check/show.html.erb, app/views/steps/application/submission/edit.html.erb, config/locales/en.yml
This is the step where the applicant choose to submit the application online, or print and post.
If online, the next page ask them to confirm the email address is correct, with an option to go back and change it.
Improved the styling for the button reset and cleanup other unused styles.
--
=> Migrate submission step

app/assets/stylesheets/local/app/check_answers.scss, app/presenters/summary/html_sections/children_further_information.rb, app/presenters/summary/html_sections/other_children_details.rb, app/views/steps/completion/shared/_answers_group.html.erb, app/views/steps/completion/shared/_change_link.html.erb, app/views/steps/completion/shared/_date_row.html.erb, app/views/steps/completion/shared/_free_text_row.html.erb, app/views/steps/completion/shared/_horizontal_rule.html.erb, app/views/steps/completion/shared/_multi_answer_row.html.erb, app/views/steps/completion/shared/_row.html.erb, app/views/steps/completion/shared/_section.html.erb, app/views/steps/completion/shared/_separator.html.erb, app/views/steps/petition/playback/show.html.erb, config/locales/cya/en.yml, config/locales/en.yml, spec/presenters/summary/html_sections/children_further_information_spec.rb, spec/presenters/summary/html_sections/other_children_details_spec.rb
The CYA page is composed of many small partials each producing the different sections.
Migrate all these partials to use the new design system markup and styles.
Add some custom markup for the more complicated sections so these render find on desktop but also on mobile devices.
In another follow-up PR I will do the cleaning of the old CYA styles making sure we are not using these in any other place (specially the PDF!)
As this page can be huge, adding here only a few screenshots of some sections for reference:
--
--
--
=> Migrate each individual CYA partial

app/assets/javascripts/modules/session-timeout.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/app/timeout_modal.scss, app/views/layouts/_timeout_modal.html.erb
Use as much of the new design system as possible, but we must maintain the custom styling as this modal does not have a direct equivalent in the design system.
=> Migrate timeout modal dialog

app/assets/stylesheets/local/app.scss, app/assets/stylesheets/local/app/intro_card.scss, app/views/entrypoint/how_long.en.html.erb, app/views/entrypoint/what_is_needed.en.html.erb
The previous custom styling was removed as it was not accessible and didn't follow the new design system guidelines.
We are now introducing a refactored version of the custom styling, that is accessible and still use as much as possible from the design system.
The blue cards look almost identical as before.
--
=> Refactor and migrate blue card steps

app/assets/stylesheets/local/app.scss, app/views/backoffice/shared/_flash_alert.en.html.erb, app/views/backoffice/shared/_menu.en.html.erb, app/views/layouts/backoffice.html.erb
This was refactored for the main layout but was not done in the back office layout.
However not using the same partial as the main layout as that one is for errors, and this is more for giving information.
Fixed the back office user menu as it was also done with the main user menu.
=> Restore the flash alert in the back office

app/assets/javascripts/modules/ga-events.js
These are tricky ones due to how we previously had an individual attribute for each checkbox and now we have a collection attribute for all selected ones.
However to aggregate and extract metrics in dashboards the collection will be pretty difficult to work with, so what I'm doing here is maintain the same approach we had before, but modify the attribute name so it is consistent.
More details in the code comments.
=> Fix GA check box events

app/assets/javascripts/modules/ga-events.js
Fix for build failing due to:
Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
Anyways, changing to var as we have all JS with var and feel a bit worried about changing the Uglifier settings at this point.
=> Change const with var in JS

app/forms/steps/international/resident_form.rb, app/presenters/summary/html_sections/international_element.rb, app/presenters/summary/sections/international_element.rb, app/views/steps/international/resident/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/errors/en.yml, config/locales/pdf/en.yml, db/migrate/20200511091814_restore_international_resident_details.rb, db/schema.rb, spec/forms/steps/international/resident_form_spec.rb, spec/presenters/summary/html_sections/international_element_spec.rb, spec/presenters/summary/sections/international_element_spec.rb
This PR restores a text are in the international journey that was apparently removed by mistake in the past.
It is in line with the other yes-no questions. Show this text area when selecting the YES radio option.
For reference, the PRs where this was removed are #336 and #338.
Updated the CYA and PDF to show the new details.
CYA page:
=> Add international resident details text area

app/assets/stylesheets/local/backoffice.scss, app/assets/stylesheets/local/misc.scss, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/steps/shared/_court_help.en.html.erb
Instead of hacking the govuk design system version to fit us, create an app-specific version, to use in those places where we need something different.
These so far include the back office and the completion page (court details).
Before:
After:
=> Tweak description list styles

app/views/layouts/_timeout_modal.html.erb, app/views/steps/abuse_concerns/details/edit.html.erb, app/views/steps/abuse_concerns/question/edit.html.erb, app/views/steps/alternatives/collaborative_law/edit.en.html.erb, app/views/steps/alternatives/lawyer_negotiation/edit.en.html.erb, app/views/steps/alternatives/mediation/edit.en.html.erb, app/views/steps/alternatives/negotiation_tools/edit.en.html.erb, app/views/steps/miam/consent_order_sought/show.en.html.erb, app/views/steps/miam_exemptions/shared/_exemption.html.erb, app/views/steps/petition/playback/show.html.erb, app/views/steps/shared/_kickout_survey.html.erb, config/locales/en.yml
There were some pages with unnecessary heading jumps from h1 to h3.
The class is what makes the font change its size so we don't need an h3 to make the header smaller, an h2 will do as long as it has the proper class (for example `govuk-heading-m`)
There might be other places but I think I found all of them.
We also need to do the same in some places with h4.
In addition, change a couple instances of `<p class="govuk-caption-xl">` to be a span element.
=> Change some h3 to h2

Gemfile, Gemfile.lock
In order to contribute back to upstream the modifications to the forked gem, without our service noticing, I've first created a `backup` branch containing all our changes, as `master` will be reset to upstream master.
PRs will be contributed to upstream and once all is merged in the upstream gem, we can stop using our forked version.
=> Point forked gem to backup branch

app/helpers/application_helper.rb, features/errors.feature, features/step_definitions/common.rb, spec/helpers/application_helper_spec.rb
As part of a recent cleanup, the code that sets the `Error:` prefix in the page title was removed.
This should have been caught by our feature tests, but to my surprise these were not expecting outcomes, thus never failed. I've fixed this broken cuke definitions to actually `expect` things so we are alerted if this prefix, or something similar, is removed.
=> Recover missing page title prefix functionality

app/validators/checkbox_options_validator.rb, app/views/steps/alternatives/court/edit.en.html.erb, app/views/steps/attending_court/special_arrangements/edit.html.erb, app/views/steps/attending_court/special_assistance/edit.html.erb, app/views/steps/petition/orders/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml
As per Simon accessibility audit.
Mainly: fieldset without legend in the orders page, and wrong hint position in the special arrangements pages.
=> Copy and style fixes and tweaks

app/controllers/step_controller.rb, app/controllers/steps/abduction/passport_details_controller.rb, app/controllers/steps/attending_court/language_controller.rb, app/controllers/steps/attending_court/special_arrangements_controller.rb, app/controllers/steps/attending_court/special_assistance_controller.rb, app/controllers/steps/children/orders_controller.rb, app/controllers/steps/children/residence_controller.rb, app/controllers/steps/miam_exemptions/adr_controller.rb, app/controllers/steps/miam_exemptions/domestic_controller.rb, app/controllers/steps/miam_exemptions/misc_controller.rb, app/controllers/steps/miam_exemptions/protection_controller.rb, app/controllers/steps/miam_exemptions/urgency_controller.rb, app/controllers/steps/petition/orders_controller.rb
The main use-case of the `additional_permitted_params` at the moment is to declare a permitted parameter as a collection.
This can be simplified now that all our check boxes are unified by inspecting the form object attributes and identifying the ones that are collections `Array[String]`.
=> Simplify `additional_permitted_params` for arrays

app/views/steps/attending_court/intermediary/edit.html.erb, app/views/steps/international/jurisdiction/edit.html.erb, app/views/steps/miam/exemption_claim/edit.html.erb, app/views/steps/safety_questions/substance_abuse/edit.html.erb, app/views/steps/screener/email_consent/edit.html.erb, app/views/steps/screener/warning/show.html.erb, app/views/steps/screener/written_agreement/edit.html.erb, config/locales/en.yml
Some paragraphs in some steps can be converted to hint text.
This minimise the issue of the error message not being positioned above the radios when injecting revealing form elements.
=> Change some lead paragraphs to hint text

app/assets/stylesheets/local/check_answers.scss
Not specific to IE8 but also other IE versions, so making this generic.
Other browsers render fine even with the width 100%.
=> Better handling of CYA on IE

app/models/screener_answers.rb, app/services/c100_app/screener_decision_tree.rb, config/application.rb, features/screener.feature, spec/models/screener_answers_spec.rb, spec/services/c100_app/screener_decision_tree_spec.rb
Make this feature-flag so it is easy to enable it again in the future if we need to. By default will be disabled.
Updated the `ScreenerAnswers.attributes_to_validate` so only checks the ones we absolute need, specially now that we are disabling the email consent.
=> Disable the screener email consent step

Gemfile, Gemfile.lock, app/views/steps/shared/_existing_names.html.erb, app/views/steps/shared/_new_name.html.erb, config/locales/en.yml
The new version of the gem has been released [1] and it contains all the work that we contributed back and needed for this service to work, as well as a fix for the `#govuk_fieldset` helper [2] so now we can get rid of the hardcoded markup and use the helper as intended.
[1] https://github.com/DFE-Digital/govuk_design_system_formbuilder/releases/tag/v1.1.11
[2] https://github.com/DFE-Digital/govuk_design_system_formbuilder/pull/130
=> Bump `govuk_design_system_formbuilder` gem version

app/views/about/accessibility.en.html.erb, app/views/layouts/_timeout_modal.html.erb
With the release of the new version of CAS using the new design system, some of the offences have been fixed.
Implement the copy changes suggested by content designer.
Also, bit unrelated to this but restored the timeout modal to its glorious splendor.
Before:
After:
=> Update accessibility statement page

db/migrate/20200522082810_remove_passport_possession_fields.rb, db/schema.rb
In previous PR #938 we refactor the passport possession checkboxes from individual booleans to an array of string values.
We also migrated the existing values to the array.
Now that we've released all this work, and everything is working fine, we can remove these leftover columns.
=> Remove unused passport DB fields

app/controllers/backoffice/dashboard_controller.rb, app/controllers/backoffice/emails_controller.rb, app/forms/backoffice/lookup_form.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/backoffice/dashboard/_lookup_form.en.html.erb, app/views/backoffice/dashboard/lookup.en.html.erb, app/views/backoffice/emails/_lookup_form.en.html.erb, app/views/backoffice/emails/lookup.en.html.erb, config/locales/errors/en.yml
There is some technical debt in the back office as a consequence of the rapid development back then. Still there are some missing things, TODO when time allows: back office tests.
Added a form object to hold the (currently) 2 fields we use in the back office lookup functionality: reference code, and email address.
Do some high level validation of these fields as well as some pre-processing stripping blanks to minimise errors.
=> Refactor back office forms with form object

package-lock.json, package.json
A new version has been released:
https://github.com/alphagov/govuk-frontend/releases/tag/v3.7.0
There should not be any breaking changes, and the only noticeable change is the `Back` link styling, as indicated in the changelog.
=> Bump GOV.UK Frontend v3.7.0

app/controllers/sessions_controller.rb, app/views/layouts/_developer_tools.html.erb
Speed up some common test scenarios by pre-filling some information.
In particular, the bypass to CYA will benefit from having the minimum people pre-filled (just names). Otherwise, it always fail the fullfillment validator when trying to submit.
If there are already people created when the bypass is used, the previously created people remain, will not overwrite nor create new people.
=> Improve bypass to CYA button

app/presenters/summary/html_presenter.rb, app/services/c100_app/application_decision_tree.rb, app/views/steps/application/receipt_email_check/show.html.erb, config/routes.rb, spec/presenters/summary/html_presenter_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb
Story: https://mojdigital.teamwork.com/#/tasks/20765417
Previously the page order was:
1. Special Assistance
2. Payment
3. Submission
This commit changes the page order to:
1. Special Assistance
2. Submission
3. Payment
=> Move submission before payment

Gemfile, Gemfile.lock, app/models/c100_application.rb, app/models/payment_intent.rb, config/routes.rb, db/migrate/20200605081246_create_payment_intents_table.rb, db/schema.rb, lib/tasks/mutant.rake, spec/models/c100_application_spec.rb, spec/models/payment_intent_spec.rb
This will be another neccessary piece to tie together the online payments journey.
The idea is, when an applicant finish their application (after the check your answers) we register a "payment intent" and redirects the user to an URL derived from this intent (with a nonce to avoid replay attacks).
For now, this does nothing, but in a follow-up PR, the payments controller will be created to handle the payment intent and redirect the user to the appropiate destination page (either the what next for print and post, the payment page to take card details, or the final confirmation page once paid, or for offline payment methods like HWF or cheque).
=> Create PaymentIntent model and DB table

config/locales/errors/en.yml
This is to keep consistency across other error messages, as the previous
suggested one was too long.
=> Change error message according to content designer

app/services/c100_app/attending_court_decision_tree.rb, spec/services/c100_app/attending_court_decision_tree_spec.rb
We want to know what type of submission before showing the payment type.
This change was lost during https://github.com/ministryofjustice/c100-application/pull/959
Correct order is:
- steps/attending_court/special_assistance
- steps/application/submission
- steps/application/payment
- steps/application/check_your_answers
=> Change submission type to be before payment type

app/controllers/payments_controller.rb, app/models/payment_intent.rb, app/services/c100_app/application_decision_tree.rb, app/services/c100_app/online_payments.rb, app/services/c100_app/payments_flow_control.rb, config/routes.rb, spec/controllers/payments_controller_spec.rb, spec/models/payment_intent_spec.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/services/c100_app/online_payments_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb
Individual commits for more details.
Move the payment and confirmation logic out of the decision tree into a little service object `PaymentsFlowControl` to handle the flow of the payments (or skip to confirmation if no online payment is needed).
For "offline" payments we just mark the intent as finished and skip to confirmation page. For online payments it uses the Payments API to create a payment and redirect the user to the card details page.
On returning, it handles the `#next_url` that can be either success or fail.
It also handles, for now, the feature-flagged code. Once we don't need this we can cleanup the code.
**TODO:** proper handling of errors. For now there are no specific error pages or a way to communicate to the user what went wrong and how to "fix it" or restart the …
=> Add payments flow

Gemfile.lock, app/controllers/concerns/error_handling.rb, app/controllers/errors_controller.rb, app/controllers/payments_controller.rb, app/errors/errors.rb, app/services/c100_app/payments_flow_control.rb, app/views/errors/payment_error.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/application_controller_spec.rb, spec/controllers/payments_controller_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb
This is just a high level error handling, mostly for the happy paths.
We will need some more error handling, specially if the user didn't come back to the service after a successful payment, or closed the browser in the card details page.
=> Add payments error handling

app/models/payment_intent.rb, app/services/c100_app/online_payments.rb, app/services/c100_app/payments_flow_control.rb, spec/services/c100_app/online_payments_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb
Some errors on the payment card details page can make the user re-enter the journey, but there are others that not.
For example, a user cancelling the payment, by clicking the "cancel payment" link in the card details (code `P0030`), should not make the user re-enter the payment card details, but instead, give the user our custom error page, so they can go back to change the payment method if they want.
Same for technical error issues with the payment provider (code `P0050`), there is no point in returning the user to the card details page as it will probably fail again, so better to show them our custom error and let them decide if they want to retry or change the payment method.
I've identified these 2 codes, but we could add some more, or remove some.
As part of this, I'm also sending …
=> Add some extra error handling

app/controllers/errors_controller.rb, app/controllers/status_controller.rb, spec/controllers/status_controller_spec.rb
The custom error pages we have were not setting the status code when serving html (it was working only for any other formats, like JSON).
For example, the `not found` custom error page, should go along with a `404` status code.
The `unhandled` error page, shoud go along with a `500` status code.
Also changed the status code returned by the `status` (health check) endpoint, from 503 to 500 to better indicate it is not the service (as a whole) being unavailable, as the proof is it is responding to the request, but just some part of it (like the database or redis). To avoid confusion.
=> Ensure error pages respond with appropriate status code

Gemfile.lock, app/controllers/concerns/savepoint_step.rb, app/controllers/payments_controller.rb, app/models/c100_application.rb, app/models/payment_intent.rb, app/services/c100_app/online_payments.rb, app/services/c100_app/payments_flow_control.rb, db/migrate/20200610133254_add_reminder_status_to_c100_application.rb, db/migrate/20200611113210_change_payment_intent_attributes.rb, db/schema.rb, spec/controllers/payments_controller_spec.rb, spec/models/c100_application_spec.rb, spec/models/payment_intent_spec.rb, spec/services/c100_app/online_payments_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb, spec/support/step_controller_shared_examples.rb
Individual commits for more details, as some changes required justification.
Essentially, we can simplify a lot, even remove completely some of the payment intent statuses, and thus, code around them, as now we have an application-level status `payment_in_progress`.
=> More payment status work

app/controllers/concerns/completion_step.rb, app/models/c100_application.rb, app/services/c100_app/payments_flow_control.rb, spec/models/c100_application_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb, spec/support/step_controller_shared_examples.rb
Move the logic to mark the application completed from the concern in the confirmation pages, to be an explicit method to be called after payment.
This eliminates the possibility of someone hitting (either by editing the URL or by a bookmark) the confirmation page and markin automatically the application as completed, even if it was still in the `payment_in_progress` state.
If this happens, we now show a warning error and let the user go back to the last step they completed.
=> Mark the application as completed after payment

app/controllers/sessions_controller.rb, app/models/court.rb, app/services/c100_app/online_payments.rb, spec/models/court_spec.rb, spec/services/c100_app/online_payments_spec.rb
The GBS code is necessary to facilitate HMCTS to know which court to make a credit payment.
Once the user selects their Postcode, a request is made to find the nearest Court, each court should have a GBS code, but currently not all have it, that means it can be nil (null) but the key should be present in all of them.
Story: https://mojdigital.teamwork.com/#/tasks/20809040
=> Update Court to receive gbs code

app/controllers/concerns/error_handling.rb, app/controllers/step_controller.rb, app/services/c100_app/payments_flow_control.rb, app/views/errors/payment_error.html.erb, config/locales/en.yml, spec/controllers/steps/abuse_concerns/start_controller_spec.rb, spec/controllers/steps/miam/child_protection_cases_controller_spec.rb, spec/controllers/steps/miam_exemptions/safety_playback_controller_spec.rb, spec/controllers/steps/screener/start_controller_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb, spec/support/step_controller_shared_examples.rb
If the application was left in a `payment_in_progress` status, we need to check if the payment went ahead successfully, or not, for the edge cases where the redirect from payments website failed.
This complements the automated mop-up job running periodically (to be implemented in a follow-up PR).
Essentially it means, any request to almost any url in our website, when there is a `payment_in_progress` application in the session, will trigger the `retrieve_payment` to update its status, and if successful, will just take the user directly to the confirmation page, otherwise they will see the payment error page and they can retry again.
To simplify this user-flow, I've removed for now the `OnlinePayments.non_retryable_state?` condition, as I believe it will not be that useful anymore with …
=> Handle users returning to a `payment_in_progress` application

app/jobs/payments_mop_up_job.rb, lib/tasks/mutant.rake, lib/tasks/payments_mop_up.rake, spec/jobs/payments_mop_up_job_spec.rb
This task will run periodically, triggered by a cronjob, and will scan stale pending payments in order to refresh their status and make sure we either progress the application to completed, or not.
Added all the jobs to the mutation testing for improved coverage (only when running a complete test).
=> Implement stale payments mop-up job

app/controllers/sessions_controller.rb, app/models/court.rb, spec/models/court_spec.rb
The API will not accept a `nil` value so we must be careful in case there are courts without the GBS code set.
Instead of falling back to an empty string by doing `to_s`, let's make it super explicit by using `unknown` as the code.
Updated the screener fixture to use the real GBS code for Milton Keynes.
=> Ensure we have a valid GBS code

app/services/c100_app/draft_reminders.rb, spec/services/c100_app/draft_reminders_spec.rb
We forgot to update the name of this attribute. Now it is call `reminder_status` and is a separate DB column to the previous `status`, that is not used for reminders anymore.
=> Update the attribute name for reminder statuses

app/forms/steps/application/payment_form.rb, app/presenters/valid_payments_array.rb, app/value_objects/payment_type.rb, app/views/steps/application/payment/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, spec/forms/steps/application/payment_form_spec.rb, spec/presenters/valid_payments_array_spec.rb, spec/value_objects/payment_type_spec.rb
Ensure depending which submission type the user chose, we show the available payment options for that submission method.
This PR does not include yet confirmation page instructions or email instructions. There are some other changes needed as well, to be done in follow-up PRs.
In a follow-up PR we will make sure to only show the ONLINE method on dev/staging envs, but not production. It must be maintained behind a feature flag for the time being.
=> Add new online payment radio option

app/mailers/notify_submission_mailer.rb, app/models/concerns/application_inquiry_methods.rb, app/presenters/valid_payments_array.rb, app/services/c100_app/payments_flow_control.rb, app/views/steps/shared/_payment_instructions.en.html.erb, config/locales/en.yml, config/locales/pdf/en.yml, spec/mailers/notify_submission_mailer_spec.rb, spec/models/c100_application_spec.rb, spec/presenters/valid_payments_array_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb
Now we have the new "online payment" radio option exposed, let's use this one to trigger the online payment journey, instead of using `self_payment_card` like we did until now.
Also, hide this radio option behind a feature flag so we don't show it accidentally on production just yet.
No need for signing the declaration as 'John Doe' either.
Some more copy placeholders in preparation for when we have it available.
=> Use new payment option to trigger the online journey

app/models/completed_applications_audit.rb, spec/models/completed_applications_audit_spec.rb
If the user sends two server requests quickly in succession on the check your answers page, there is a race condition where only one of the requests will be able to create the audit record.
The other request will try and fail because (on purpose) there is unique key constrain in the table.
This happens rarely and usually has no effect on the user, although depending on wich request "won" the race, they might end up with a standard error page.
In order to avoid this, instead of blowing up we will log the failure and do nothing as this is not harmful.
=> Do not propagate the exception on dup audit record

app/services/c100_app/applicant_online_submission.rb, app/views/entrypoint/v1.en.html.erb, app/views/steps/completion/confirmation/show.en.html.erb, app/views/steps/shared/_download_pdf_copy.en.html.erb, config/locales/cya/en.yml, config/locales/en.yml, spec/mailers/notify_submission_mailer_spec.rb, spec/services/c100_app/applicant_online_submission_spec.rb
Story: https://mojdigital.teamwork.com/#/tasks/20914334
We will not be attaching the application copy in the receipt email that the applicant receives (if they entered their email address, as this is optional).
They can still download the document in the confirmation page or through their user account (save&return).
The code however will very much be ready if we wanted to restore this functionality or attach any other document.
=> Do not attach the PDF to applicants confirmation email

app/jobs/payments_mop_up_job.rb, app/services/reports/failed_emails_report.rb, lib/tasks/_logger.rake, lib/tasks/court_refresh.rake, lib/tasks/daily_tasks.rake, lib/tasks/payments_mop_up.rake, spec/jobs/payments_mop_up_job_spec.rb
Instead of `puts` (in many cases having us to append the timestamp) lets use `Rails.logger.info` that automatically formats and outputs the proper timestamp.
This makes sense for rake tasks running through cronjobs so all log gets output to the STDOUT and is in one place when inspecting the logs through Kibana for example.
Also, reduced from 60 mins to 30 mins the time for a payment intent to be considered as "stale" and we start quering the payments API (every 15 mins) to check their status.
=> Improve logging in some rake tasks

app/forms/steps/applicant/has_solicitor_form.rb, app/forms/steps/application/submission_form.rb, spec/forms/steps/applicant/has_solicitor_form_spec.rb, spec/forms/steps/application/submission_form_spec.rb
Some payment types are only shown/available for online submission, or when there is a solicitor.
This PR ensures the following:
a) If the applicant answered YES to the "do you have a solicitor?" question, but later on through the edit link in the CYA they change the answer to NO, we will reset the payment as it is very likely they chose `fee account`, which is only available when there is a solicitor.
b) If the applicant changes their submission options (from online to print and post, or viceversa) we do the same and reset the payment method so we force them to select a new payment type.
=> Reset payment type when submission changes

app/controllers/errors_controller.rb
These technically are not 404 (as the page/route exists, it is just the current session to access that page is invalid).
The side effect is we are getting an increased number of alerts, as bots scanning the website will trigger plenty of these errors.
Instead of returning them as 404, let's return a 200. This does not affect users as they will continue seeing the usual error page.
=> Do not use 404 codes for invalid session errors

app/views/steps/completion/confirmation/show.en.html.erb, app/views/steps/shared/_payment_instructions.en.html.erb, config/locales/en.yml
As per content designer. This will remove the payment instructions section
in the confirmation page if the payment method was online, and tweak the
copy in the confirmation email as well.
Before we had the paragraph "The court will not be able to process your
application until payment has been received." hardcoded in the Notify email
template, but now we are pushing it from the service, only if needed.
=> Amend payment details copy

app/helpers/fees_helper.rb, app/mailers/notify_submission_mailer.rb, app/services/base_decision_tree.rb, app/services/c100_app/online_payments.rb, app/views/entrypoint/v1.en.html.erb, app/views/steps/application/payment/edit.html.erb, app/views/steps/shared/_payment_instructions.en.html.erb, config/application.rb, config/locales/en.yml, features/screener.feature, spec/helpers/fees_helper_spec.rb, spec/mailers/notify_submission_mailer_spec.rb, spec/services/c100_app/online_payments_spec.rb
Description of the fee as per content designer suggestion but we might have to change it later on based on any HMCTS feedback.
Replaced the hardcoded instances of the `£215` fee with a helper.
=> Extract hardcoded fee details to configuration

app/views/about/miam_exemptions.en.html.erb
Use more appropriate list styles for some of the lists in the MIAM exemptions page.
Before:
After:
=> Amend some lists makup and styling

app/models/c100_application.rb, spec/models/c100_application_spec.rb
There is a theoretical edge case scenario where an application older than 28 days (and thus, candidate to be purged in the automated daily maintenance task) is being updated by the user right at that very same moment.
Example: a user gets the "1 day left reminder" telling them their application is about to expire, and they decide to submit the application right before the purge kicks off over night.
This could cause the application record and data to be purged right when we need it to generate the PDF and submit the application.
Or perhaps the user just started the payment and was entering the payment details when their application was purged meaning when they are redirected back, there is no application.
Admittedly this is a very rare scenario but it is easy to protect from it by giving …
=> Add a short grace period to the applications purge

app/presenters/summary/html_presenter.rb, app/views/steps/application/check_your_answers/edit.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/pdf/en.yml, spec/presenters/summary/html_presenter_spec.rb
As per content designer suggestions.
Copy changes to the different payment methods, and the payment error page.
Also copy changes to the check your answers page, before submission:
**Print and post:**
**Submit electronically:**
**Submit electronically and pay online:**
=> More copy changes related to online payments

app/services/c100_app/online_payments.rb, spec/services/c100_app/online_payments_spec.rb
This is a harcoded string with value `C100` that will be used by HMCTS for reconciliation purposes.
This is in addition to the already present GBS code.
Ticket: https://mojdigital.teamwork.com/#/tasks/21006958
=> Add `application` to payment metadata

app/controllers/backoffice/dashboard_controller.rb, app/lib/audit_helper.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/backoffice/dashboard/_payment.en.html.erb, app/views/backoffice/dashboard/_payments_table.en.html.erb, app/views/backoffice/dashboard/_results_table.en.html.erb, app/views/backoffice/dashboard/index.en.html.erb, app/views/backoffice/dashboard/lookup.en.html.erb, spec/lib/audit_helper_spec.rb
Added the gbs code and the payment ID to the audit table when an application is completed, if paid online.
Exposed this information in the back office as might be helpful to diagnose problems in the future.
Also added a payments report table, mainly for debug purposes.
=> Add online payment details to back office

app/assets/stylesheets/local/backoffice.scss, app/views/backoffice/audit/_record.en.html.erb, app/views/backoffice/dashboard/_payment.en.html.erb, app/views/backoffice/dashboard/_payments_table.en.html.erb
Make it a bit nicer with coloured tags and only add extra details if they are interesting (on failures), not on success.
=> Styling tweaks to the payments table

Gemfile, Gemfile.lock
This will get rid of a very annoying deprecation warning in the logs as a consequence of a recent redis change:
```
`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, 
you should use it instead.
```
Removed `rubocop-rspec` gem because it is not actually in use.
=> Bump Sidekiq to 6.1.0

app/services/c100_app/payments_flow_control.rb, spec/services/c100_app/payments_flow_control_spec.rb
If the creation of the payment failes for whatever reason (maybe a connection timeout, or some weird argument is passed to the API) we don't want to be left with the `payment_in_progress` status, as it is pointless.
Revert back to `in_progress` (as the user is shown an error message) so they can retry payment or change method.
Move all the status-related "movements" to an explicit method to be easier to maintain and read.
=> Better handling of errors when creating payment

app/lib/markup_normaliser.rb, features/fixtures/README.md, features/fixtures/files/child_protection_cases.html, features/fixtures/files/child_protection_cases_with_errors.html, features/fixtures/files/miam_acknowledgement.html, features/fixtures/files/miam_acknowledgement_with_errors.html, features/fixtures/files/miam_certification_date.html, features/fixtures/files/miam_certification_date_with_errors.html, features/fixtures/files/nature_of_application.html, features/fixtures/files/nature_of_application_with_errors.html, features/fixtures/files/order_jurisdiction.html, features/fixtures/files/order_jurisdiction_with_errors.html, features/markup_smoke_tests.feature, features/step_definitions/fixtures.rb
More details in the `README.md`
These smoke tests are coupled to the actual markup generated by the form builder in the service, meaning if the page or locale change, these tests will need to be updated.
Added 5 for now, with a mixture of check boxes, radios, dates and revealing text areas.
We can easily add more, but I think with these we cover most of the combinations already. In any case this does not replace some manual testing / sanity check when updating the gem.
=> Add form builder (gem) markup smoke tests

Gemfile, Gemfile.lock, app/assets/stylesheets/local/util.scss, app/views/steps/applicant/personal_details/edit.html.erb, app/views/steps/respondent/personal_details/edit.html.erb, app/views/steps/shared/_dob_form_element.html.erb
Latest version allows to set `form_group_classes` so we can use this instead of having to wrap the element with an external div like we did before.
Reduced size of the `birthplace` text inputs to be in line with other element width sizes.
=> Bump `govuk_design_system_formbuilder`

app/mailers/notify_submission_mailer.rb, spec/mailers/notify_submission_mailer_spec.rb
We removed the PDF in the emails to the applicant some time ago, but the `link_to_pdf` was a shared personalisation param because before, both emails (court and applicant) used it. But not anymore.
Move this out of the `shared_personalisation` method and into the `application_to_court` method so it is more clear what is going on, and thus we stop sending an (empty) `link_to_pdf` param in the applicant emails.
Updated tests.
=> Make mailer documents code more clear

features/children_details.feature, features/step_definitions/common.rb
Cucumber scenario to test the steps to add a child and personal details, as well to select the orders that apply.
It also exercise the validations by provoking and fixing them to continue.
This is not a 100% coverage scenario as there are some alternative validations and also is not testing more than 1 child or the removal of existing children, but overall should be enough.
=> Add cucumber tests for children details steps

features/applicant_details.feature, features/step_definitions/common.rb, features/step_definitions/forms.rb
Cucumber scenario to test the steps to add an applicant and their personal details, as well to select the relationship to an existing child.
It also exercise the validations by provoking and fixing them to continue.
This is not a 100% coverage scenario as there are some alternative validations and also is not testing more than 1 applicant or the removal of existing applicants, but overall should be enough.
=> Add cucumber tests for applicant details steps

app/views/backoffice/dashboard/_completion.en.html.erb, app/views/backoffice/dashboard/_payment.en.html.erb, config/locales/backoffice/en.yml, config/locales/en.yml
This improve some copy that was not particularly very human-friendly (`self_payment_card ` or `solicitor`) with some more human-friendly versions using locales.
Also reduced some lengthy timestamps so they fit in one line and do not wrap.
Show the complete reference code in the payments error details, if there is an error, instead of just the firt part of the UUID so it is easy to search for the application if needed.
Before:
After:
=> Improve some copy and styling in back office tables

features/respondent_details.feature
Cucumber scenario to test the steps to add a respondent and their personal details, as well as to select the relationship and the residence to an existing child.
It also exercises the validations by provoking and fixing them to continue.
This is not a 100% coverage scenario as there are some alternative validations and also is not testing more than 1 respondent or the removal of existing respondents, but overall should be enough.
=> Add cucumber tests for respondent details steps

app/models/concerns/application_inquiry_methods.rb, app/services/c100_app/alternatives_decision_tree.rb, app/services/c100_app/miam_exemptions_decision_tree.rb, spec/models/c100_application_spec.rb, spec/services/c100_app/alternatives_decision_tree_spec.rb, spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
As well as not showing the MIAM exemptions playback pages same as we already did with child protection cases.
This is a follow-up to PR #1006
=> Consent orders will bypass alternatives to court

app/forms/steps/petition/orders_form.rb, app/presenters/petition_presenter.rb, app/value_objects/petition_order.rb, app/views/steps/petition/orders/edit.html.erb, app/views/steps/petition/playback/show.html.erb, config/locales/en.yml, spec/forms/steps/petition/orders_form_spec.rb, spec/presenters/petition_presenter_spec.rb, spec/value_objects/petition_order_spec.rb
If the application is for a consent order, then we can remove all the other orders from the nature of application and just expose a check box for Consent order (along with the other issue just in case, as it offers a free text area).
Copy still TBD.
Note, as part of a follow-up PR, the CYA and PDF will be implemented. At the moment, if you go all the way to the end, and you've selected the Consent order check box, it will blow up.
Playback:
Parent ticket: https://mojdigital.teamwork.com/#/tasks/19965720
Subtask: https://mojdigital.teamwork.com/#/tasks/21245693
=> Simplify nature of application for consent orders

app/presenters/summary/html_sections/miam_requirement.rb, app/presenters/summary/html_sections/nature_of_application.rb, app/presenters/summary/sections/miam_requirement.rb, app/presenters/summary/sections/nature_of_application.rb, config/locales/cya/en.yml, config/locales/pdf/en.yml, spec/presenters/summary/html_sections/miam_requirement_spec.rb, spec/presenters/summary/html_sections/nature_of_application_spec.rb, spec/presenters/summary/sections/miam_requirement_spec.rb, spec/presenters/summary/sections/nature_of_application_spec.rb
In the CYA this goes in the MIAM requirement section we already have.
Also ensure we show the consent order in the list of orders (nature of application) section.
Most of it was already present in the PDF.
Just ensure we show the order in the nature of application, as well as in the MIAM section.
=> Add consent order to CYA and PDF

app/mailers/notify_submission_mailer.rb, spec/mailers/notify_submission_mailer_spec.rb
Send yes/no to Notify to be able to show/hide the instructions in the confirmation email, when the application is for a consent order.
As Notify will fail if we add the variable to the template but we don't pass it, we are NOT changing the Notify template on production yet, until the day of the release of this work.
Parent ticket: https://mojdigital.teamwork.com/#/tasks/19965720
Subtask: https://mojdigital.teamwork.com/#/tasks/21212958
=> Customise applicant email for consent orders

app/views/steps/completion/confirmation/_consent_order_section.html.erb, app/views/steps/completion/confirmation/show.en.html.erb, app/views/steps/completion/what_next/_with_consent_order.html.erb, app/views/steps/completion/what_next/_without_consent_order.html.erb, app/views/steps/completion/what_next/show.en.html.erb, spec/views/steps/completion/confirmation/show.html.erb_spec.rb, spec/views/steps/completion/what_next/show.html.erb_spec.rb
We are still waiting for instructions on where to place the confirmation content on the 'digital submission' page.
After changes, it will look like this:
Story: https://mojdigital.teamwork.com/#/tasks/21212954
=> Add consent order text for online and print and post

app/services/base_decision_tree.rb, spec/services/c100_app/miam_decision_tree_spec.rb
This can happen although might be rare, if right after the release to production, an application was in the middle of answering the child protection cases (meaning the `consent_order` question was not answered as it comes before child protection cases).
Given we check the value of consent_order in the child protection cases step, a `nil` would have raised an exception.
Protect from this edge case by ensuring the call to the `#question` method always returns a GenericYesNo instance with a value, which will be 'na' in case if nils.
=> Protect from nil value in consent_order attribute

Gemfile, Gemfile.lock, app/validators/email_validator.rb, config/locales/errors/en.yml, spec/forms/steps/application/submission_form_spec.rb, spec/validators/email_validator_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21318405
The code in the gem is minimum and we can move it to our service and simplify it, reducing an external dependency and minimising the risk of this dependency being updated/changed and then our validations could break.
In fact this gem was already locked in version `< 2.0.0` because in greater version they introduced a change that didn't fit well with our validations (they made the regex much more simple thus emails like `a@b` would be valid).
I've moved the code and cleaned up to remove anything we don't need so it is just the regex.
Also as part of this I've added a very simple list of common domain typos we see frequently to try to avoid some of them. This was not part of the original gem.
For reference this is the code of the …
=> Remove dependency on `email_validator` gem

app/controllers/steps/screener/error_but_continue_controller.rb, app/mailers/notify_submission_mailer.rb, app/services/c100_app/courtfinder_api.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/steps/applicant/under_age/edit.html.erb, app/views/steps/completion/confirmation/_under_age_section.html.erb, app/views/steps/shared/_court_help.en.html.erb, spec/controllers/steps/screener/error_but_continue_controller_spec.rb, spec/services/c100_app/courtfinder_api_spec.rb, spec/views/steps/screener/error_but_continue/show.html.erb_spec.rb
As a consequence of the rubocop bump in PR #1020 a series of offences were raised, in particular, the use of `open()` to do requests in this class.
I've now fixed that by doing a big refactor and cleanup to make this class more easy to understand and maintain, with less code.
I've moved to constants many of the strings that previously were used in multiple places or were hard to find, and also made possible to customise the http request timeouts (which I've reduced from the default 60 secs to something more sensible).
Incidentally now mutant takes a lot less time in this class than before:
```
Before refactor: 135.05s
After refactor: 87.71s
```
=> Refactor the court finder API class

app/services/c100_app/courtfinder_api.rb, app/views/steps/miam_exemptions/exit_page/show.en.html.erb
After the migration to the new design system back in May, this button lost their `data-ga-category` attribute, and thus the GA tracking stopped working.
Restore the missing attribute.
Also, although unrelated, cleanup a couple of unnecessary requires.
=> Fix GA tracking in FMC postcode lookup

Gemfile.lock, package-lock.json
A new version was released. It has minor changes but some improve the accessibility.
Full list of changes here:
https://github.com/alphagov/govuk-frontend/releases/tag/v3.8.0
Also bump the `govuk_design_system_formbuilder` gem to go along the new frontend version.
Changelog here:
https://github.com/DFE-Digital/govuk_design_system_formbuilder/releases/tag/v1.2.6
No breaking changes.
=> Bump govuk frontend to 3.8.0

app/assets/stylesheets/local/util.scss, app/views/layouts/_sentry_feedback.html.erb
We've moved away from the self-hosted sentry instance, so this code needs to be updated.
It also was using a very old JS version.
I've removed as well the custom CSS as I've seen the bug is now fixed on the Sentry side.
=> Update sentry feedback code

app/services/reports/failed_emails_report.rb, app/views/backoffice/emails/index.en.html.erb
And do not show as errors very recent emails (10 minutes), as these might not have received the callback yet, due to Notify delays.
=> Clarify email failures in back office

app/models/c100_application.rb, app/services/c100_app/payments_flow_control.rb, spec/models/c100_application_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb
We had an edge case where if the application at point of submission lack some vital information used in the `CompletedApplicationsAudit` then it was giving a misleading "payment error" message.
This is because the `#confirmation_url` method (which triggers the completion and audit) raised an exception but was being captured by the rescue in the `#payment_url` method.
I've now moved the call to `confirmation_url` outside a begin-rescue so in the rare occasion it raises an exception it bubble ups and is not re-raised as a `PaymentUnexpectedError`
Also improved the overall status changes using transactions, so if either the Audit or the `create_payment` methods fail, the status is reverted to how it was automatically with a rollback.
=> Improve error handling

app/assets/stylesheets/local/check_answers.scss, app/presenters/summary/html_sections/base_children_details.rb, app/presenters/summary/sections/children_details.rb, config/locales/cya/en.yml, config/locales/pdf/en.yml, spec/presenters/summary/html_sections/children_details_spec.rb, spec/presenters/summary/html_sections/other_children_details_spec.rb, spec/presenters/summary/sections/children_details_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21392185
This PR adds the special guardianship question to the CYA and the PDF.
=> Add special guardianship question to CYA and PDF

app/services/c100_app/children_decision_tree.rb, spec/services/c100_app/children_decision_tree_spec.rb
Follow-up to PR's #1028 and #1029.
We don't want this to show on production inadvertently if we deploy, so temporarily until the non-parents work is completed, we are hiding the Special Guardianship Order question in production.
It will show in other environments, including localhost and staging.
=> Place SGO question behind feature flag

app/value_objects/relation.rb, app/views/steps/shared/_relationship_step.html.erb, config/locales/cya/en.yml, config/locales/en.yml, config/locales/pdf/en.yml, spec/forms/steps/shared/relationship_form_spec.rb, spec/value_objects/relation_spec.rb
This change adds the 'Guardian' and 'Special Guardian' options to the relationship step.
The CYA and PDF also reflects the new relationships.
Note: Need confirmation of the hint text before we can merge.
=> Add Guardian and Special Guardian options to relationship step

app/controllers/steps/permission/question_controller.rb, app/controllers/steps/permission_step_controller.rb, app/forms/steps/permission/living_order_form.rb, app/forms/steps/permission/parental_responsibility_form.rb, app/forms/steps/permission/question_form.rb, app/services/c100_app/permission_decision_tree.rb, app/views/steps/permission/question/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, db/migrate/20200806085153_add_permission_fields_to_relationship.rb, db/schema.rb, spec/controllers/steps/permission/question_controller_spec.rb, spec/forms/steps/permission/living_order_form_spec.rb, spec/forms/steps/permission/parental_responsibility_form_spec.rb, spec/services/c100_app/permission_decision_tree_spec.rb, spec/support/form_validation_shared_examples.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21392212
This is a big PR but couldn't split it in smaller chunks as all is part of the same and is required for tests to pass properly.
To be honest, more than half the lines are tests 😄 
The work is not yet finished (pending CYA, PDF, and implementing the rules to enter this journey), but all this will come in follow-up PRs.
=> Add non-parents permission questions framework

app/presenters/summary/html_sections/base_children_details.rb, app/presenters/summary/sections/children_details.rb, app/services/c100_app/children_decision_tree.rb, config/routes.rb, features/children_details.feature, features/step_definitions/forms.rb, spec/presenters/summary/html_sections/children_details_spec.rb, spec/presenters/summary/sections/children_details_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb
It now goes after the selection of orders for the child, as this way, we can skip the SGO question if the orders does not include "home" (Decide who they live with and when).
Updated tests according to this as well as CYA and PDF.
=> Change SGO question position

app/forms/steps/permission/amendment_form.rb, app/forms/steps/permission/time_order_form.rb, app/services/c100_app/permission_decision_tree.rb, config/locales/en.yml, spec/forms/steps/permission/amendment_form_spec.rb, spec/forms/steps/permission/living_order_form_spec.rb, spec/forms/steps/permission/time_order_form_spec.rb, spec/services/c100_app/permission_decision_tree_spec.rb
Task: https://mojdigital.teamwork.com/#/tasks/21392212
I've completed the next 2 questions, one question per commit.
This is because from this point onwards (ie: living_arrangements question onwards), a 'yes' answer will yield a different set of permissions required.
=> Add amendment and time order questions

app/services/base_decision_tree.rb, app/services/c100_app/applicant_decision_tree.rb, app/services/c100_app/children_decision_tree.rb, app/services/c100_app/permission_rules.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb, spec/services/c100_app/permission_rules_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21483487
This will decide if further questions are needed in order to decide
if permission is needed or not to make the application.
Rules are based on the previous answer to the SGO question, as well
as the applicant's relation to the child.
**Note**: in a follow-up PR consent orders bypass will be handled.
=> Introduce the permission rules in `ApplicantDecisionTree`

app/forms/steps/permission/consent_form.rb, app/forms/steps/permission/living_arrangement_form.rb, app/forms/steps/permission/time_order_form.rb, app/services/c100_app/permission_decision_tree.rb, config/locales/en.yml, db/migrate/20200811110454_rename_living_arrangements_to_living_arrangement.rb, db/schema.rb, spec/forms/steps/permission/consent_form_spec.rb, spec/forms/steps/permission/living_arrangement_form_spec.rb, spec/forms/steps/permission/time_order_form_spec.rb, spec/services/c100_app/permission_decision_tree_spec.rb
Task: https://mojdigital.teamwork.com/#/tasks/21392212
This PR adds the next 2 questions to the non-parents journey, living arrangement and consent.
The database has also changed, the column `living_arrangements` has been renamed to `living_arrangement` to deal with Rails' attempts to remove plurals during initialisation of constants.
I've made smaller commits to help make following the changes a little easier!
If this PR is approved, the two questions will appear as below:
=> Living arrangements and consent questions

app/forms/steps/children/orders_form.rb, app/services/c100_app/permission_rules.rb, spec/forms/steps/children/orders_form_spec.rb, spec/services/c100_app/permission_rules_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21483487
And reset the `special_guardianship_order` flag
Handle the edge case where the orders change and the previous value to the SGO question remains, which could cause some issues down the line.
Now we ensure if the orders change we always re-evaluate the question and force the user to answer it (or if we don't show it because the orders change, then it gets back to be `nil` as expected).
=> Skip non-parent questions if is a consent order

app/forms/steps/permission/amendment_form.rb, app/forms/steps/permission/consent_form.rb, app/forms/steps/permission/family_form.rb, app/forms/steps/permission/living_arrangement_form.rb, app/forms/steps/permission/living_order_form.rb, app/forms/steps/permission/local_authority_form.rb, app/forms/steps/permission/parental_responsibility_form.rb, app/forms/steps/permission/question_form.rb, app/forms/steps/permission/relative_form.rb, app/forms/steps/permission/time_order_form.rb, config/locales/en.yml, spec/forms/steps/permission/amendment_form_spec.rb, spec/forms/steps/permission/consent_form_spec.rb, spec/forms/steps/permission/family_form_spec.rb, spec/forms/steps/permission/living_arrangement_form_spec.rb, spec/forms/steps/permission/living_order_form_spec.rb, spec/forms/steps/permission/parental_responsibility_form_spec.rb, spec/forms/steps/permission/time_order_form_spec.rb
Task: https://mojdigital.teamwork.com/#/tasks/21392212
Copy changes include:
- Updating the hint text for the parental_responsibility question
- updating the wording of the amendment question
Other changes in this PR include:
- Refactoring the 9 questions so they inherit a common characteristic from the superclass
- Improve the reset mechanism of the questions
A lot of files have been changed so there are multiple commits to help with keep track of these changes.
If approved the updated question copies will look like:
=> Update questions for non-parents journey.

app/views/backoffice/dashboard/_payment.en.html.erb
If the online payment returned an error, apart from showing this error and code, we can also show what was the final payment method the user chose as in most cases they would have to select a new payment method.
If the application is still awaiting to be completed we also show this.
=> Show more detail in payments back office

app/models/relationship.rb, app/presenters/summary/html_sections/people_details.rb, config/locales/cya/en.yml, config/locales/en.yml, spec/models/relationship_spec.rb, spec/presenters/summary/html_sections/applicants_details_spec.rb, spec/presenters/summary/html_sections/other_parties_details_spec.rb, spec/presenters/summary/html_sections/respondents_details_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21498747
For each of these questions with a value (either yes or no) we have to show it in the CYA page so the user can go back an change the answer if they wish.
This repeats for each combination applicant-child as long as there is data in these attributes.
In a follow-up PR will do the PDF.
=> Add 9 permission questions to CYA

app/assets/stylesheets/local/check_answers.scss, app/models/relationship.rb, app/presenters/summary/sections/children_relationships.rb, config/locales/en.yml, config/locales/pdf/en.yml, spec/presenters/summary/sections/children_relationships_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21498747
Similar to the previous PR, but in this case we only show the qustion that was answered YES, ignoring the NO questions, and of course `nil` ones.
This repeats for each combination applicant-child as long as there is data in these attributes.
However as we know if the first attribute is `nil` the following attributes will also be `nil` we just optimise for this by only iterating through relationships that has some value in their first attribute.
=> Add permission questions to the PDF

app/assets/stylesheets/local/pdf_summary.scss, app/presenters/summary/c100_form.rb, app/presenters/summary/sections/children_relationships.rb, app/presenters/summary/sections/permission_questions.rb, config/locales/pdf/en.yml, spec/presenters/summary/c100_form_spec.rb, spec/presenters/summary/sections/children_relationships_spec.rb, spec/presenters/summary/sections/permission_questions_spec.rb
This improves upon PR #1044 by moving the permission questions into its own sub-section in the PDF right below the "Children’s relationship with parties" one, so it is a bit more clear.
Also because it is a separate section we can apply a bit of styling so the question column is much wider than the answer column (because answer can only be "Yes").
Apart from that, and to make things even more easy and clear to read, I've applied a bit of shading to the top-level section headers to separate further each of the parts of the form.
=> Move PDF permission questions into its own section

app/services/c100_app/permission_rules.rb, spec/services/c100_app/permission_rules_spec.rb
Permission (and any rules and questions derived from it) is only required for "main" children, i.e. children the application is about.
Other children that are not subject of the proceedings should not enter the 9-questions journey.
=> Permission rules do not apply to `OtherChild`

app/forms/steps/shared/relationship_form.rb, spec/forms/steps/shared/relationship_form_spec.rb
Similar to what we did for the SGO order reset in commit f45515d8045afae0158e258f50ce0581033f0d82, if the relation between the applicant and the child changes but somehow before some non-parents were answered, we make sure these are reset as a change in relationship effectivelly requires to re-evaluate the journey and decisions.
=> Reset non-parent questions if relation changes

app/controllers/steps/application/permission_sought_controller.rb, app/forms/steps/application/permission_sought_form.rb, app/views/steps/application/permission_sought/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, db/migrate/20200817145208_add_permission_sought_fields.rb, db/schema.rb, spec/controllers/steps/application/permission_sought_controller_spec.rb, spec/forms/steps/application/permission_sought_form_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21450255
Simple yes-no question as per design.
At the moment, this is not visible nor part of the journey. Once we create the follow-up step I will add these to the decision tree.
But it can be accessed directly by knowing the URL.
Added a couple of DB attributes, one is needed for this step, the other `permission_details` will be used in the follow-up step.
=> Add permission sought yes-no question

app/controllers/steps/application/permission_details_controller.rb, app/forms/steps/application/permission_details_form.rb, app/views/steps/application/permission_details/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, spec/controllers/steps/application/permission_details_controller_spec.rb, spec/forms/steps/application/permission_details_form_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21392567
Follow-up to PR #1048.
Simple details page, with a text area to enter details. Validate presence.
Made the exinsting application details, and this new permission details, more consistent by using same form labels size and removing an obsolete timeout warning text.
Still not integrated in the decision trees so it is not visible unless accessing the URL by hand.
=> Add permission to apply details step

app/services/c100_app/application_decision_tree.rb, app/services/c100_app/international_decision_tree.rb, spec/services/c100_app/application_decision_tree_spec.rb, spec/services/c100_app/international_decision_tree_spec.rb
Follow-up to PRs #1048 and #1049.
Incorporate these two questions in the main journey, right after finalising the international sub-journey.
For now, it will always show, as we are not checking the permission rules. This will be done in the next PR.
=> Add permission sought and details to main journey

app/controllers/step_controller.rb, spec/controllers/step_controller_spec.rb
This was messing a bit with some reports and statistics we have, because each time there is a navigation change (`navigation_stack` gets updated) it did a save and touched the `updated_at` magic column too.
And we tend to sort many of these report by updated_at.
The timestamp changes separately from the `navigation_stack` each time there is an attribute update, i.e. when the user is answering questions and entering details.
=> Do not touch `updated_at` on navigation updates

app/validators/email_validator.rb, spec/validators/email_validator_spec.rb
These are some mistakes users make, and although these domains exist, they are not what the user intended (domain typosquatting).
=> Add a couple more email domain typos

spec/presenters/summary/html_sections/application_reasons_spec.rb
Just a minor refactor in line with the PDF tests, so it covers all possible options (including the permission question not being asked and thus being `nil`).
=> Extend CYA permission tests

app/lib/audit_helper.rb, app/models/child.rb, app/services/c100_app/permission/application_rules.rb, app/views/backoffice/dashboard/_completion.en.html.erb, config/locales/backoffice/en.yml, config/locales/pdf/en.yml, spec/lib/audit_helper_spec.rb, spec/models/child_spec.rb, spec/services/c100_app/permission/application_rules_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21633583
This will log if the application had any children with a special guardianship order in force, and if permission was sought (or is not required, which happens if the question is not asked and thus attribute is `nil`).
It will also show this info in the back office.
Note: Even if we've not released yet non-parents, these are not breaking changes and can be released at any time.
=> Log in the audit table permission info

app/views/backoffice/dashboard/_completion.en.html.erb
I totally forgot the `default` option in the translate does not get itself translated but it outputs the raw value.
This fixes it so instead of `not_required` is shows as `Not required` :facepalm:
=> Fix i18n permission string in back office

app/services/c100_app/permission/relationship_rules.rb, spec/services/c100_app/permission/relationship_rules_spec.rb
Having a child in the application with a special guardianship order in force, automatically makes the application require permission.
Before, we were still asking the 9-questions in these cases, but with this change, we don't need to, and we assume straight away the permission will be needed.
Simplified so the `#permission_needed?` is no longer needed and is more clear what is going on.
=> Tweak permission undecided rules

app/services/base_decision_tree.rb, app/services/c100_app/applicant_decision_tree.rb, app/services/c100_app/children_decision_tree.rb, spec/services/c100_app/applicant_decision_tree_spec.rb, spec/services/c100_app/children_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21498766
Remove the code that was maintaining the non-parents hidden in production envs, as we are about to go live with this feature.
To be merged and deployed to production next week together with the other PR #1064
=> Remove the non-parents feature flag

app/presenters/valid_payments_array.rb, spec/presenters/valid_payments_array_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21709675
We are slowly rolling out new courts that accept online payments.
In this PR we add 6 more courts.
In addition, the following changes have been agreed with HMCTS business:
* Remove "pay over the phone" option for applications routed to the courts that accept online payment.
* Remove "pay over the phone" for print&post applications.
Note: to go live tomorrow.
=> Add new courts to online payments rollout

app/presenters/valid_payments_array.rb, spec/presenters/valid_payments_array_spec.rb
GOV.UK Pay has a length limit in the metadata values of 50 characters.
We use the metadata to store the name of the court where the payment was made. Unfortunately we didn't anticipate and some courts have a lengthy name, like this one, taking us over the 50 limit and getting an error when trying to create an online payment.
The name of this court is `Preston Crown Court and Family Court (Sessions House)` which is 53 chars but I've seen other courts with even 64 chars.
Temporarily disable this court. I've contacted GOV.UK Pay to raise the limit in the meantime and will be re-enabled as soon as possible.
=> Temporarily disable online payments to Preston court

app/lib/audit_helper.rb, lib/tasks/audit_relations.rake, spec/lib/audit_helper_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21737933
This is in relation to the difficulty we have to know how many fathers, mothers, etc. triggered non-parent applications (those with the `permission_sought` attribute not `nil`).
If we store an array of the relations (for example `["father", "other"]`) at least we can map this in a chart although still we will not be certain what was the trigger of the permission (but chances are 99% will be the "other" relationship).
There is a rake task to be run manually once deployed, to retroactively populate existing non-parents completed applications (there are a few, less than 20).
New ones will contain this metadata detail by default.
=> Add to audit table the applicant(s) relation to child(ren)

app/models/court.rb, app/presenters/valid_payments_array.rb, config/govuk_pay.yml, spec/models/court_spec.rb, spec/presenters/valid_payments_array_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21709675
**Online payments rollout -- batch 2**
Instead of having to add one by one all the courts that accept online payments (as these are a lot after batch 2), a blocklist is more efficient and cleaner, adding only those courts that for whatever reason can't take online payments.
Also, disallow online payments for courts without a GBS code set.
Currently we are adding the courts from batch 3 as these courts will go live next week, as well as a few courts with names taking us over the 50 chars limit on GOV.UK Pay.
Once Pay increase the limit we can removed those. And next week we will be able as well to hopefully remove the remaining ones, leaving the blocklist empty (that's the theory).
=> Rollout of online payments batch 2 courts

app/controllers/concerns/error_handling.rb, config/govuk_pay.yml, spec/controllers/application_controller_spec.rb, spec/presenters/valid_payments_array_spec.rb
As we did with other courts, this one has a name over 50 chars, and unfortunetely GOV.UK Pay have not released the increase yet, so attempts to call the API with this court name will fail with code P0102.
Add to the sentry exception the application ID if we have it to help debug wich courts are failing more easily.
=> Disable Newport court from online payments

app/services/c100_app/payments_flow_control.rb, spec/services/c100_app/payments_flow_control_spec.rb
We had this code to report payment failures (as in, users cancelling their payment, or payment card rejected) for some time while we made sure online payments were working fine.
We can now remove this info logs.
Any exception produced by the payments API will regardless be reported  to Sentry as those are important errors.
We can also see all these details and errors in the Payments transaction list.
=> Reduce level of payment debug captured in Sentry

config/govuk_pay.yml, spec/presenters/valid_payments_array_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21709675
We disabled temporarily these 5 courts as their names were over the 50 chars metadata limit.
Now Pay team have confirmed they've increased this limit:
```Custom metadata on payments can now have values that are strings of up to 100 characters (previous limit was 50)```
=> Enable Pay in courts disabled due to char limit

config/govuk_pay.yml, spec/presenters/valid_payments_array_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21709675
**Online payments rollout -- batch 3**
We just remove these 3 courts from the block list to allow them to use GOV.UK Pay.
In this batch:
- Barrow-in-Furness County Court and Family Court
- Liverpool Civil and Family Court
- York County Court and Family Court
=> Rollout of online payments - batch 3

app/models/court.rb, app/services/c100_app/courtfinder_api.rb, spec/services/c100_app/courtfinder_api_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21633615
Follow-up to PR #1080.
After the introduction of the new `Courts` DB table in the previous PR, we don't need to use the Redis cache for the court details API request, because we are now storing for up to 72h the court data in a record in the database, so it acts as a cache in effect.
I've manitained the Rails.cache configuration `config/initializers/cache_store.rb` as we might need to use it in other places. It is just a config file.
=> Remove no longer needed CTF redis cache

app/models/payment_intent.rb, app/services/c100_app/payments_flow_control.rb, config/initializers/00_extensions.rb, lib/extensions/relation_extension.rb, spec/models/payment_intent_spec.rb, spec/services/c100_app/payments_flow_control_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21915640
We've had a couple of cases (out of almost 500 successful transactions, so really edge case) where a payment was created on GOV.UK Pay twice at the (almost) same time.
**Note: payment in this context is the "attempt or intent", not the actual take of funds.**
One of these transactions usually will progress to success and funds will be taken, the other will remain "In progress" for up to 90 minutes and then time out.
Problem with this is, in our database we need to link the c100 application to the corresponding online payment, with a unique ID that Pay provides to us after the creation of each payment.
As 2 payments are created sequentially almost at the same time, only one of these transactions will "win the race" and write its …
=> Reduce race-condition edge cases in online payments

app/controllers/concerns/completion_step.rb, app/controllers/steps/applicant/under_age_controller.rb, app/lib/audit_helper.rb, app/mailers/notify_submission_mailer.rb, app/models/c100_application.rb, app/models/completed_applications_audit.rb, app/presenters/valid_payments_array.rb, app/services/c100_app/court_online_submission.rb, app/services/c100_app/online_payments.rb, app/services/c100_app/screener_decision_tree.rb, app/views/backoffice/dashboard/_completion.en.html.erb, spec/controllers/steps/applicant/under_age_controller_spec.rb, spec/lib/audit_helper_spec.rb, spec/mailers/notify_submission_mailer_spec.rb, spec/models/c100_application_spec.rb, spec/models/completed_applications_audit_spec.rb, spec/presenters/valid_payments_array_spec.rb, spec/services/c100_app/court_online_submission_spec.rb, spec/services/c100_app/online_payments_spec.rb, spec/services/c100_app/screener_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21633615
We will expose a `#court` method in the C100Application model, that will check if we have a court record in the new `courts` table, and if not, fallback to the legacy `screener_answers` table.
We can remove this method once we don't have any more records using the old table.
Changed a lot of the `screener_answers_court` references. Some remain (specifically in the developer tools bypass functionality) that will be refactored in the next PR.
=> Read court details from the new table

app/controllers/concerns/savepoint_step.rb, app/controllers/sessions_controller.rb, app/models/screener_answers.rb, app/views/layouts/_developer_tools.html.erb, config/routes.rb, features/step_definitions/common.rb, spec/controllers/steps/miam/consent_order_controller_spec.rb, spec/models/screener_answers_spec.rb, spec/support/step_controller_shared_examples.rb
Follow-up to PR #1084.
The bypass is not really a "bypass screener" anymore, but instead a "bypass postcode" as that is the only thing we have left of the screener.
Also, do not write to the old `screener_answers` table, and instead we use the new `courts` table mechanism.
=> Refactor bypass functionality

app/controllers/steps/screener/postcode_controller.rb, app/forms/steps/screener/postcode_form.rb, app/lib/audit_helper.rb, app/services/c100_app/screener_decision_tree.rb, app/views/steps/screener/postcode/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, features/screener.feature, spec/forms/steps/screener/postcode_form_spec.rb, spec/lib/audit_helper_spec.rb, spec/services/c100_app/screener_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21633615
Similar to what we did in PR #1084, we now want to start using only the new `children_postcode` DB field (which is part of the C100Application record) instead of the previous `children_postcodes` (note plural) in the old ScreenerAnswers record.
We need to maintain backwards compatibility until all applications use the new attribute.
=> Refactor `children_postcodes`

app/presenters/summary/html_presenter.rb, app/presenters/summary/html_sections/miam_requirement.rb, app/presenters/summary/html_sections/opening_questions.rb, config/locales/cya/en.yml, spec/presenters/summary/html_presenter_spec.rb, spec/presenters/summary/html_sections/miam_requirement_spec.rb, spec/presenters/summary/html_sections/opening_questions_spec.rb
These are the 2 questions we moved in the previous PR #1088 out of the MIAM group as they are not directly linked to MIAM.
They will continue working the same but just outside the MIAM requirement group.
This has been agreed and discussed with the service designer.
Before:
After:
=> Update CYA to move 2 questions out of MIAM group

app/validators/email_validator.rb, spec/validators/email_validator_spec.rb
Gmail and Hotmail are the most commonly used email domains by our users, so by making sure these adhere to the short list of valid domains for each of these providers, we can reduce a lot of failures and typos without having to create a big blocklist.
Google only has 2 (public) email domains for users, so this one is easy.
Hotmail is no longer active but existing addresses continue to work so we need to support these.
=> Improve email common typos validator

app/services/c100_app/payments_flow_control.rb, lib/tasks/mutant.rake, spec/services/c100_app/payments_flow_control_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21915640
This is an addendum to previous PR #1083 to try to reduce further the occurrences of race-conditions when creating an online payment.
Although very rare, we had, after the previous PR was released, a couple more cases where this happened.
The culprit is the fact 2 or more requests are handled in paralell, each with its own database access, and they don't see each other so the result of the creation of a `payment_intent` by process A is unknown to process B as both see no record.
By the time one of the 2 (or more) processes write to database, another could have done that already, resulting in overwriting previous data, raising a db constraint exception, etc. in a quite unpredictable way.
This PR introduces a pessimistic DB lock …
=> Add some extra measures against race conditions

app/models/c100_application.rb, config/application.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/21934280
This is a daily automated task that runs overnight and clean ups "orphaned" c100 application records. These are records that are created in the database as a consequence of entering a postcode that is either not valid, not found, or not eligible to apply.
Update the rake task to keep working as before, now that we've moved away from using the `screener_answers` DB table.
Will purge records that have the `children_postcode` present, but the `court` is nil.
=> Update `purge:orphans` rake task

app/controllers/backoffice/dashboard_controller.rb
Ordering by `updated_at` is more accurate, as a payment intent could have been created a few days ago but not completed the payment, and left to expire, but then user comes back and complete the payment (the created_at would remain the same but the updated_at will change).
This is just for the reports in the back office and do not affect anything else.
=> Change order of the payments report in back office

app/controllers/sessions_controller.rb, app/helpers/custom_form_helpers.rb
Minor tweak to get the bypass to CYA in line with the code that decides if the `save and return` button will show or not.
It shows if we've advanced at least until the `child_protection_cases`.
=> Enable save draft button on bypass to CYA

app/models/backoffice_audit_record.rb, config/application.rb, lib/tasks/daily_tasks.rake
Ticket: https://mojdigital.teamwork.com/#/tasks/22069087
Similar to other automated daily tasks, create one to clean up older than 90 days back office audit records. These are of no use and they will continue growing otherwise.
=> Add task to purge old back office audit records

app/controllers/backoffice/dashboard_controller.rb, app/models/backoffice_audit_record.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/backoffice/dashboard/_incomplete_table.en.html.erb, app/views/backoffice/dashboard/_lookup_form.en.html.erb, app/views/backoffice/dashboard/lookup.en.html.erb, config/routes.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/22084915
This is a first step towards improving the situation where some online payments are left incompleted by mistake, as the user think the pre-auth is the payment, and then their application is not submitted to court.
For saved applications it is not much of an issue as the user can resume their application and retry the payment.
But not-saved applications can't be resumed and the user might have to start over again from the beginning which is not great.
With this new functionality exposed in the back office, it is now possible to search the reference of an incomplete application and if found, will give some details.
If the online payment failed or expired (and the application was not already completed by other means) then there is a …
=> Add functionality to back office to complete applications

config/govuk_pay.yml, spec/presenters/valid_payments_array_spec.rb
This was introduced as a temporary measure while existing applications in the database refreshed their GBS code.
There is no longer a need to explicitly block these, as all the existing applications (and future ones) will have the GBS code of these courts to `nil` or `unknown` so will be automatically blocked from taking online payments.
=> Cleanup list of slugs blocked for online payments

app/views/steps/completion/shared/_change_link.html.erb
This small tweak is related to the above ticket and will allow us to track more precisely which "change" links are more frequently clicked in the CYA page.
Instead of just having an event with a "change link" label, the label now will be a bit more specific, for example: `change link: miam_certification_details`.
This will then allow us to make an informed decision on what kind of improvements we can make to return the user back to the CYA after they've changed something.
=> Track more precisely CYA change links

app/services/c100_app/courtfinder_api.rb, spec/services/c100_app/courtfinder_api_spec.rb
There seem to be some problem verifying the Ghandi certificate but as CTF might need to either update or change certificate (maybe to Let's encrypt) and that might take a while, this at least makes the API calls to CTF work again despite being a horrible workaround.
We will re-evaluate in the coming days and hopefully we can get rid of it soon.
=> Hotfix for Court Tribunal Finder invalid certificate

app/services/c100_app/courtfinder_api.rb, spec/services/c100_app/courtfinder_api_spec.rb
This reverts commit b2ad1146f3c41538c6e7b9daef199b8f05e50b49.
Problems with CTF certificate seems to have been solved now. We didn't need to release this to PROD after all.
=> Revert "Hotfix for Court Tribunal Finder invalid certificate"

app/controllers/step_controller.rb, app/services/c100_app/navigation_stack.rb, spec/controllers/step_controller_spec.rb, spec/services/c100_app/navigation_stack_spec.rb
This is the first part of a "potential" improvement to the check your answers page. Mainly a refactor at this point.
Main idea is to set a flag in the session if we detect the user accessed a page through the `change link` in the CYA. This flag will later on (in a follow-up PR) allow us to decide if we can take the user back straight to CYA.
In this PR we set the session flag but do nothing.
=> Refactor `update_navigation_stack` code into separate class

.rubocop.yml, app/controllers/step_controller.rb, app/helpers/application_helper.rb, app/services/c100_app/navigation_stack.rb, spec/controllers/step_controller_spec.rb, spec/controllers/steps/abuse_concerns/details_controller_spec.rb, spec/controllers/steps/application/details_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/services/c100_app/navigation_stack_spec.rb, spec/support/step_controller_shared_examples.rb
Follow-up to PR #1105.
This is the actual implementation of the fast-forward functionality, that started with the previous PR.
For now there is just a handful of steps that have this enabled, defined as regexp in `FAST_FORWARD_STEPS`.
Basically all the abuse concerns detail steps either for applicant or children, and the application details step.
This is mainly a proof of concept, so starting small and we will think how to scale up.
Exposed a helper method `#fast_forward_to_cya?` that can be used in the `#update_and_advance` to know if after updating a form object it can jump straight back to the CYA page, and is also used in the `#step_header` method, so we can modify the `back link` to point to the CYA as well.
I had fun with the …
=> Enable some CYA changes to fast-forward back

app/forms/steps/application/submission_form.rb, spec/forms/steps/application/submission_form_spec.rb
While doing many many rounds of tests for the previous PRs (CYA fast forward) I realised there was a scenario where the submission form would perform a `#persist!` even tho it was not strictly neccessary.
This is because in the database the `receipt_email` attribute can be nil while the form param sent is an empty string.
Tweaked the condition equality so it compares always strings even if these are empty.
=> Skip persist if submission form has not changed

app/services/c100_app/navigation_stack.rb, spec/controllers/steps/applicant/contact_details_controller_spec.rb, spec/controllers/steps/applicant/personal_details_controller_spec.rb, spec/controllers/steps/children/additional_details_controller_spec.rb, spec/controllers/steps/children/personal_details_controller_spec.rb, spec/controllers/steps/other_children/personal_details_controller_spec.rb, spec/controllers/steps/other_party/personal_details_controller_spec.rb, spec/controllers/steps/respondent/contact_details_controller_spec.rb, spec/controllers/steps/respondent/personal_details_controller_spec.rb, spec/controllers/steps/solicitor/contact_details_controller_spec.rb, spec/controllers/steps/solicitor/personal_details_controller_spec.rb
Follow-up to previous PR #1106.
Add some more steps that can safely do a fast-forward to the CYA when editing something.
More to come in next PRs but I think for now these will cover a good chunk of the potential changes a user might need to do.
It will most likely be that we can enable the fast-forward for any step with ends with `_details` so eventually we will be able to simplify a lot the regex but for now it is easier to add one at a time.
=> Add more steps to CYA fast-forward

app/controllers/steps/opening/research_consent_controller.rb, app/forms/steps/opening/research_consent_form.rb, app/services/c100_app/opening_decision_tree.rb, app/views/steps/opening/research_consent/edit.html.erb, config/application.rb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, db/migrate/20201029112416_add_research_consent_fields.rb, db/schema.rb, features/00_opening.feature, spec/controllers/steps/opening/research_consent_controller_spec.rb, spec/forms/steps/opening/research_consent_form_spec.rb, spec/services/c100_app/opening_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/22337703
In order to plan for user research and to gather participants, we are reintroducing a step we had some months ago and got removed as part of the removal of the screener.
It will show right after the postcode step, and can be disabled by setting an ENV variable `HIDE_RESEARCH_CONSENT_STEP` in case we want to stop showing this step to users.
Some copy amendments have been made but overall is pretty much the same as it was before.
=> Reintroduce the research consent step

app/views/errors/payment_error.html.erb, config/locales/en.yml
Following some concerns about users not understanding why they have a pre-auth transaction, this PR tweaks the copy as per content designer to explain a bit more.
=> Copy tweaks to the payment error page

app/controllers/steps/solicitor/address_details_controller.rb, app/forms/steps/solicitor/address_details_form.rb, app/views/steps/solicitor/address_details/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/steps/solicitor/address_details_controller_spec.rb, spec/forms/steps/solicitor/address_details_form_spec.rb
We want to refactor the solicitor's address text area into structured individual text inputs, like we did in the past for applicants, respondents, etc.
As a first step we are creating a new intermediate page step to hold the address text area, and in follow-up PRs we will remove the text are from the current (contact details) step as well as update the decision tree.
Then we can structure the data, which will need to be backwards compatible with existing and in progress applications.
I'm creating small PRs so it is easier to review but it will not be entirely functional until the next PR at least.
=> Create solicitor address details step

app/services/c100_app/opening_decision_tree.rb, app/services/c100_app/research_sampler.rb, config/application.rb, spec/services/c100_app/opening_decision_tree_spec.rb, spec/services/c100_app/research_sampler_spec.rb
We implemented over a week ago the ability to gather users's consent for user research purposes, by showing them a page where they can enter their email address.
This was present some time ago but we removed it. Now we've reintroduce it, but we are getting quite a few too much candidates and will be difficult if not impossible to really manage all of them and the list is growing every day.
As a potential improvement, instead of turning off completely the gathering of this consent, with this PR we prepare the path for, if we want, show this consent only to a percentage of the new applications.
By default at the moment is 100% meaning all applications/users are shown the consent step, but we can let's say in a week decide to reduce this to 50%, and then the consent will be shown only to a …
=> Ability to set a percentage to show/hide the research consent step

app/forms/steps/solicitor/contact_details_form.rb, app/services/c100_app/solicitor_decision_tree.rb, app/views/steps/solicitor/contact_details/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, spec/forms/steps/solicitor/contact_details_form_spec.rb, spec/services/c100_app/solicitor_decision_tree_spec.rb
Follow-up to PR #1118.
In this PR we are removing the existing text area in the contact details step, as we've now introduced this same text area in a separate "address details" step.
Update the validations and the order of the fields in the contact details form object.
Update the solicitor decision tree to introduce this new address details step, before the contact details one.
Note: still pending, in follow-up PRs, update the CYA page to be able to get back to the new address step. Also enable the fast-track.
Once we have all this refactored and up and running, we can start structuring the text area into individual fields.
=> Remove solicitor address text area from contact details step

app/presenters/summary/html_sections/solicitor_details.rb, app/presenters/summary/sections/solicitor_details.rb, config/locales/cya/en.yml, spec/controllers/steps/solicitor/address_details_controller_spec.rb, spec/presenters/summary/html_sections/solicitor_details_spec.rb, spec/presenters/summary/sections/solicitor_details_spec.rb
Continuation to previous PR #1120.
We now have a new intermediate page to enter the solicitor address details.
In this PR we add this section to the CYA too, and make the fast-forward link to work.
Remove the address from the contact details section.
Reorder the contact details in the CYA to show in the same order as in the page (email show first).
=> Add the new solicitor address step to CYA

app/models/concerns/person_with_address.rb, app/models/person.rb, app/models/solicitor.rb, db/migrate/20201112150154_add_solicitor_address_fields.rb, db/schema.rb, lib/tasks/mutant.rake, spec/models/solicitor_spec.rb
We are already using split address for applicant, respondent and other party (all inheriting from Person).
For `solicitor` model we want the same, so it makes sense to extract this concrete behaviour to a concern module `PersonWithAddress` that can be used in any model that has an address.
Refactored it a bit to make it simpler to read.
=> Prepare DB to split solicitor address

app/presenters/summary/html_sections/people_details.rb, config/locales/cya/en.yml, spec/presenters/summary/html_sections/applicants_details_spec.rb, spec/presenters/summary/html_sections/other_parties_details_spec.rb, spec/presenters/summary/html_sections/respondents_details_spec.rb
Previously the address unknown would show even if the user didn't yet entered an address at all, because we were using the flag `show: true` which indicates to always show that row even if their value is blank/nil (rendering the absense locale).
This usually is fine, but if the user for some reason did save the application for later, in the personal details of the applicant, respondent or other party, then on resuming the application the CYA would show address as 'Don't know' which is misleading.
It was easy to reproduce this behaviour on staging by using the 'Bypass to CYA' functionality.
Change this behaviour so address will show only if there is value, and 'Don't know' will show as well if there is a value.
=> Tweak the address unknown in CYA block

app/forms/address_base_form.rb, spec/forms/steps/other_party/address_details_form_spec.rb, spec/forms/steps/respondent/address_details_form_spec.rb
Small follow-up refinement to previous PR #1124.
In case some details were previously entered, when selecting the `address_unknown` checkbox, these leftovers will be reset, maintaining the DB consistency and not showing them in CYA.
=> Reset address leftovers if `address_unknown` is checked

app/controllers/steps/completion/summary_controller.rb, app/views/steps/application/check_your_answers/edit.html.erb, app/views/steps/shared/_download_pdf_copy.en.html.erb, config/locales/en.yml
Ticket: https://mojdigital.teamwork.com/#/tasks/22631863
Follow-up to PR #1127
Add a new revealing link to the `Check your answers` page to let the applicant download a draft of their application before submitting it.
The PDF will have the "draft" watermark. But other than that it will be identical to the final PDF once the applicant submits their application.
Also as part of this work, I've added th `download` attribute to the links as per:
https://www.w3schools.com/tags/att_a_download.asp
Note: copy is still TBD and to be reviewed by content designer.
=> Add button to download draft application in CYA

app/controllers/steps/miam/certification_exit_controller.rb, app/services/c100_app/miam_decision_tree.rb, app/views/steps/miam/certification_exit/show.html.erb, config/locales/en.yml, config/routes.rb, features/miam.feature, spec/controllers/steps/miam/certification_exit_controller_spec.rb, spec/services/c100_app/miam_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/22821248
As part of the changes proposed for the MIAM journey, a new kick out page needs to be added if the user answer NO to the question `Have you got a document signed by the mediator?`
Updated the decision tree and some copy.
=> Add kick out page when there is no document from mediator

app/controllers/steps/miam/mediator_exemption_controller.rb, app/forms/steps/miam/mediator_exemption_form.rb, app/views/steps/miam/mediator_exemption/edit.html.erb, config/locales/en.yml, config/locales/errors/en.yml, config/routes.rb, db/migrate/20201216130249_add_miam_mediator_exemption_field.rb, db/schema.rb, spec/controllers/steps/miam/mediator_exemption_controller_spec.rb, spec/forms/steps/miam/mediator_exemption_form_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/22821199
This PR adds the new step (yes-no question) with the controller, form object and view, as well as the new DB attribute.
It is still not linked in the decision tree and not visible, unless it is accessed directly by going to the URL.
In following PRs it will be linked to the decision tree as well as adding the new question to the CYA and the PDF.
=> Create MIAM mediator exemption yes-no step and DB attr

app/forms/steps/miam/attended_form.rb, app/forms/steps/miam/certification_form.rb, app/forms/steps/miam/mediator_exemption_form.rb, app/forms/steps/opening/child_protection_cases_form.rb, app/forms/steps/opening/consent_order_form.rb, app/services/c100_app/miam_decision_tree.rb, spec/forms/steps/miam/attended_form_spec.rb, spec/forms/steps/miam/certification_form_spec.rb, spec/forms/steps/miam/mediator_exemption_form_spec.rb, spec/forms/steps/opening/child_protection_cases_form_spec.rb, spec/forms/steps/opening/consent_order_form_spec.rb, spec/services/c100_app/miam_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/22821199
Follow-up to PR #1132
Update the decision tree (but the new step is still not showing) so the journey is still the same.
Updated several form objects to perform the correct reset of attributes when changing from yes to no, or viceversa, in order to not leave inconsistent selected options across the journey.
=> Update MIAM reset mechanism in multiple steps

app/services/c100_app/miam_decision_tree.rb, app/services/c100_app/miam_exemptions_decision_tree.rb, features/miam.feature, spec/services/c100_app/miam_decision_tree_spec.rb, spec/services/c100_app/miam_exemptions_decision_tree_spec.rb
As part of the changes proposed for the MIAM journey, we are closing the loophole where a user could continue with the application even without exemption and no attendance to MIAM.
This is in line with the paper form.
If the applicant didn't attend a MIAM, didn't have a meditor's exemption and didn't have another reason not to attend, then instead of continuing to safety concerns like now, (/steps/safety_questions/start) show a kick out page as per design.
I've confirmed that there was no need to change the copy of the existing page.
Story: https://mojdigital.teamwork.com/#/tasks/22821224
=> Show page to find a mediator when user has not attended MIAM

app/services/c100_app/abuse_concerns_decision_tree.rb, app/services/c100_app/miam_exemptions_decision_tree.rb, app/services/c100_app/safety_questions_decision_tree.rb, app/views/steps/miam_exemptions/reasons_playback/show.html.erb, features/miam.feature, spec/services/c100_app/abuse_concerns_decision_tree_spec.rb, spec/services/c100_app/miam_exemptions_decision_tree_spec.rb, spec/services/c100_app/safety_questions_decision_tree_spec.rb
Ticket: https://mojdigital.teamwork.com/#/tasks/22821224
After the applicant goes through the list of MIAM exemptions, if they don't select any, we show them the kick out page (that was done in PR #1135) but if the applicant select one or more exemptions we should show them the playback page.
This playback page used to be after the safety concerns journey but because we now don't let the user continue to this journey we need to show it before.
As a consequence a bit of refactor and simplification in other decisions tree have been made as the logic is now much more simpler.
=> Reintroduce MIAM exemptions playback and refactor

config/application.rb, features/00_opening.feature
We had this disabled via ENV variable in production environment (value 0) but the step was still showing on staging and localhost causing some confusion.
Set default value to 0 so the step is disabled everywhere for the time being. Can be changed again in the future if we want to enable the user research question.
=> Disable research consent step

app/models/solicitor.rb, db/migrate/20210108103926_remove_address_from_solicitors.rb, db/schema.rb, spec/models/solicitor_spec.rb
We don't need this anymore as we've migrated the address to structured data.
No applications are using this DB field anymore.
Removal of the attribute and unused code.
=> Cleanup of unused solicitor address DB field

.circleci/config.yml
This is neccessary as more recent versions in CircleCI starts giving errors when writing assets:
```
error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/usr/local/share/.cache/yarn/v6/npm-govuk-frontend-3.10.2-6589401e4adad1ab1dc340a18057ec88c9435a84-integrity/node_modules/govuk-frontend/README.md' -> '/usr/src/app/node_modules/govuk-frontend/README.md'".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
```
Kudos to another team who found this problem first and shared the solution:
https://mojdt.slack.com/archives/CCSD5F397/p1610108410041100
And their PR:
https://github.com/ministryofjustice/laa-court-data-ui/pull/416
=> Specify version of docker to use in CircleCI

app/presenters/summary/sections/c8_applicants_details.rb, spec/presenters/summary/sections/c8_applicants_details_spec.rb
Ticket: https://trello.com/c/tqvItimB
A request from HMCTS came in where some courts where having issues
with the positioning of the `previous addresses` (if applicant
entered any) in the C8 (when the address confidentiality is enabled).
A suggestion was made to reposition the previous addresses section
towards the bottom of the applicant contact details, separated from
the current address.
**BEFORE:**
**AFTER:**
=> Reposition C8 previous addresses section

config/locales/pdf/en.yml
Ticket: https://trello.com/c/xbDXxMyv
Just a small portion of copy removed as, after Brexit, Brussels 2 is no longer relevant to UK law.
=> Remove Brussels reference from PDF

app/models/court.rb, db/migrate/20210128095510_add_court_location_code.rb, db/schema.rb, spec/models/court_spec.rb, spec/presenters/valid_payments_array_spec.rb
Ticket: https://trello.com/c/IDdg4Kyo
As part of the centralisation work, we first need to take from CTF a piece of information we were not using before, and store it in our `Courts` DB table for later use.
In a follow-up PR we will print this code in the application PDF.
=> Store the court county location code

app/models/c100_application.rb, app/models/completed_applications_audit.rb, db/migrate/20210128153016_add_completed_at_to_c100_applications.rb, db/schema.rb, spec/models/c100_application_spec.rb, spec/models/completed_applications_audit_spec.rb
Ticket: https://trello.com/c/IDdg4Kyo
Follow-up to PR #1146.
A new requirement has been raised to also print in the PDF the completion date of the application.
We had already this date but in a separate audit table and corresponding to the last `updated_at` of the application.
In order for both tables to share the same, accurate timestamp, it is best to have a specific `completed_at` attribute stored in the c100 application itself to refer to this each time the PDF needs to be generated (when it is submitted to court, or the user downloads the PDF for example).
=> Store the application `completed_at` timestamp

app/assets/stylesheets/local/pdf_summary.scss, app/controllers/sessions_controller.rb, app/presenters/summary/c100_form.rb, app/presenters/summary/sections/processing_details.rb, config/locales/pdf/en.yml, spec/presenters/summary/c100_form_spec.rb, spec/presenters/summary/sections/processing_details_spec.rb
Ticket: https://trello.com/c/IDdg4Kyo
Follow-up to PR #1146 and #1147.
Add a new section to the PDF, at the end of the C100 form, below the statement of truth and court fee.
This new section will print the details we captured in the previous PR: the court code and name, as well as the date of completion of the application.
This is for scanning/processing purposes and not intended for the user.
For a while some applications will have the court code or the completion date missing but that's fine.
=> Add new processing details section to PDF

config/locales/en.yml
Ticket: https://trello.com/c/4JyTmiKc
Policy has confirmed that a C4 is not required.
Remove the reference to the C4 if the child’s postcode is unknown. Advise applicant to give their own postcode in these circumstances.
**Before:**
**After:**
=> Remove C4 reference in children's postcode screen

app/models/court.rb, app/services/c100_app/court_postcode_checker.rb, config/application.rb, config/court_slugs.yml, spec/models/court_spec.rb
Ticket: https://trello.com/c/ODIpiZet
This is a first step towards enabling centralisation, initially in just 5 courts, and then over the time more courts will be added to this list.
Currently this PR does not have any functionality other than create the list.
In follow-up PRs we will use this to know if a court is centralised or not and do different things based on that.
=> Create list of centralised courts

app/models/court.rb, lib/tasks/mutant.rake, spec/models/court_spec.rb
Ticket: https://trello.com/c/V23YR1mD
After some changes made to many CTF court pages, our rules are not picking correctly some of the email addresses.
In order to reduce the number of courts affected, this PR make some small tweaks to the rules so we are able to pick more accurately the correct email address.
In summary we:
1. prioritise the email address itself, looking for "keywords"
2. we change the keywords and the order, so first one is `c100`, second one is `family` and lastly is `children`
Also, in order for this to take effect more quickly, temporarily we are reducing the cache from 72 hours to just 1 hour.
=> Tweak CTF email rules

app/models/court.rb, lib/tasks/mutant.rake, spec/models/court_spec.rb
Ticket: https://trello.com/c/V23YR1mD
We reduce to 1 hour the cache in a previous PR #1153 in order for the court details in particular emails to be refreshed more quickly as some emails were incorrect due to changes in CTF.
Now all emails are correct again so we can increase the cache refresh time to the way it was before (72 hours).
=> Increase the court cache refresh time

app/models/concerns/court_contact_details.rb, app/models/court.rb, lib/tasks/mutant.rake, spec/models/concerns/court_contact_details_spec.rb, spec/models/court_spec.rb
Ticket: https://trello.com/c/ODIpiZet
Follow-up to PR #1152 to prepare the centralisation.
A bit of refactor to better organise the email and postal address methods into a separate concern that will handle the logic to know if the court is centralised or not, and return the details accordingly.
This is still not in use, as the new method `#documents_email` it is not used yet and the `#full_address` keeps returning the same address as before.
In a follow-up PR we can start enabling this.
=> Add new email and postal address for centralisation

app/models/concerns/court_contact_details.rb, app/services/c100_app/court_online_submission.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/layouts/_developer_tools.html.erb, spec/models/concerns/court_contact_details_spec.rb, spec/services/c100_app/court_online_submission_spec.rb
Ticket: https://trello.com/c/6KRa1h1M
Continuation of PR #1155.
Depending if the court is centralised or not, for online applications we submit the PDF to the central hub, or to the court email address.
For print an post applications we do the same with the postal address.
Online payments remains the same, no changes in the metadata.
In a following PR some copy changes might be needed.
=> Switch to centralised contact details

app/views/steps/completion/confirmation/_consent_order_section.html.erb, app/views/steps/completion/confirmation/_under_age_section.html.erb, app/views/steps/completion/confirmation/show.en.html.erb, app/views/steps/completion/what_next/_consent_order_section.html.erb, app/views/steps/completion/what_next/_under_age_section.html.erb, app/views/steps/completion/what_next/_with_consent_order.html.erb, app/views/steps/completion/what_next/_without_consent_order.html.erb, app/views/steps/completion/what_next/show.en.html.erb, app/views/steps/shared/_court_documents.en.html.erb, spec/views/steps/completion/confirmation/show.html.erb_spec.rb, spec/views/steps/completion/what_next/show.html.erb_spec.rb
Ticket: https://trello.com/c/6KRa1h1M
Some copy changes are needed, only in the online submission confirmation page, to indicate the user where to send documents, as centralised courts will have a different email address (and postal address).
Essentially, added a new block to the page to show this information.
Refactoring / tiding up the other completion views and partials to reduce complexity.
=> Update copy in online submissions confirmation page

app/mailers/notify_submission_mailer.rb, app/models/concerns/court_contact_details.rb, app/views/backoffice/dashboard/_completion.en.html.erb, app/views/steps/applicant/under_age/edit.html.erb, app/views/steps/shared/_court_help.en.html.erb, config/locales/en.yml, spec/mailers/notify_submission_mailer_spec.rb, spec/models/concerns/court_contact_details_spec.rb, spec/views/steps/completion/confirmation/show.html.erb_spec.rb, spec/views/steps/completion/what_next/show.html.erb_spec.rb
As part of the centralisation work, I realised there are several calls to `C100App::CourtfinderAPI.court_url` that can be simplified by using the `court` instance instead.
This makes for a more readable code but functionally it is the same.
Also, in the back office, for completed applications, retrieve the court email and the applicant email, from the `email_submissions` association to be more accurate in case a court email changes after an application has been submitted.
=> Refactor court url calls

app/mailers/notify_submission_mailer.rb, spec/mailers/notify_submission_mailer_spec.rb
Ticket: https://trello.com/c/6KRa1h1M
Propagate 2 new personalisation variables to Notify (`court_address` and `documents_email`) in order to be able to build a new "If you’re sending documents" block in the email template.
This new block is similar to the one we added to the confirmation page in PR #1157.
Note: the template in staging will be updated once this is deployed to staging, and the template in production will be updated once this is deployed to production.
=> Add centralisation contact details to confirmation email

app/views/backoffice/dashboard/_completion.en.html.erb
In the back office, completed applications, there is a section for the court and applicant's receipt addresses.
However for print and post these details are nil because the application is not submitted by email.
Make this more clear and avoid a `nil` exception because the association `email_submission` will not be present in these cases.
=> Clarify in back office print&post emails section

app/services/c100_app/online_payments.rb, spec/services/c100_app/online_payments_spec.rb
Ticket: https://trello.com/c/6KRa1h1M
Rebecca has confirmed they would prefer the email address of the central hub (what we call `documents_email`) in the online payments metadata, instead of the underlying court.
For courts that are not centralised yet, this has no effect, as the court email will be the same as before.
=> Use centralisation email address in payments metadata

app/models/court.rb, spec/models/court_spec.rb
Ticket: https://trello.com/c/8gYWiCim
This is a follow-up to PR #1153.
HMCTS has decided to add "Including C100 applications" to the explanation of all the courts we are currently aware of. Around 64 courts.
Modify our rules so we prioritise the `explanation` field when looking for keywords, in particular `c100`.
If none found, we still run a set of rules against the address itself, looking by the usual keywords as before.
Removed the rules for the `description` field as it is redundant if we look and prioritise the explanation and then the email address.
=> Prioritise explanation in CTF email list

config/court_slugs.yml, spec/models/concerns/court_contact_details_spec.rb
Ticket: https://trello.com/c/uvP2dwj3
Manchester centralisation will go live 11/03/2021.
=> Add Manchester to the centralisation pilot

app/lib/audit_helper.rb, db/migrate/20210311092612_update_centralisation_metadata.rb, db/schema.rb, spec/lib/audit_helper_spec.rb
As part of the centralisation rollout we are undergoing, some reports need to be generated to HMCTS so they know which completed applications are going to the central hub.
When there are few courts like now it can be done easily by court name, but soon there will be many more courts and generating these reports using the date and the court name is very tedious.
In order to simplify this we are adding to the metadata of any completed application a new attribute `centralised` true/false if the completed application has been for a centralised court.
This will allow to create reports much easily by just filtering by this flag.
A DB migration is needed to automate some already centralised courts in the first rollout.
=> Add centralisation metadata to the Audit table

.circleci/config.yml
Ticket: https://trello.com/c/SoDjxznK
We are handing over this service to HMCTS PET (Product Enhancement Team).
The new github team is `sustainingdevs` and this is used in the CircleCI to push/pull from the ECR repo.
=> Update CircleCI team name for HMCTS hand over

config/court_slugs.yml, spec/models/concerns/court_contact_details_spec.rb
Ticket: https://trello.com/c/FJjGm8My
The following courts are to be onboarded 23/03/2021 early morning:
- Slough
- Norwich
- Milton Keynes
- Peterborough
- Staines
- Watford
- Guildford
- Reading
- Oxford
- Luton
=> Add 10 new courts to the centralisation pilot

app/forms/steps/opening/postcode_form.rb, spec/forms/steps/opening/postcode_form_spec.rb
With the recent downtimes experienced with CTF, an edge case was discovered where, if the applicant had already entered their postcode (before CTF being down) but then they return to the postcode step when CTF is down, and click continue (no need to change the postcode) the previous assigned `court` gets wiped as we try to assign a new one, but because CTF is down we can't.
So the solution is to err on the cautious side, and do not reset the `court` attribute, because even if CTF is down but it was present from before, it can be reused, otherwise the whole application will fail to be submitted if we don't have a valid court assigned to the application.
=> Skip court reset when updating children postcode

Gemfile, Gemfile.lock
This PR adds webdrivers gem to allow new developers to get started without worrying about adding (and future management of) the webdriver for chrome.
webdrivers will automatically find and install the appropriate version of webdrivers for the installed version of chrome
=> Added webdrivers gem 

Gemfile.lock
Fixes 'Your bundle is locked to mimemagic (0.3.5), but that version could not be found'
For more background on this issue:
https://github.com/rails/rails/issues/41750
Slack conversation:
https://mojdt.slack.com/archives/C7KCVJZSQ/p1616607583045100
=> Bump mimemagic to v0.3.6

app/models/concerns/court_contact_details.rb, app/services/c100_app/courtfinder_api.rb, app/views/about/contact.en.html.erb, config/locales/en.yml, spec/mailers/notify_submission_mailer_spec.rb, spec/models/concerns/court_contact_details_spec.rb, spec/services/c100_app/courtfinder_api_spec.rb
We have been requested to change the url to:
```
https://old.courttribunalfinder.service.gov.uk
```
**Their intention is to deploy this on Monday, 22 March 2021**.
A time has been requested so that we can try our best to sync a 
deployment,
this was not given at the time of this commit.
Test will fail until endpoint is live, visit: https://old.courttribunalfinder.service.gov.uk/search/results.json?aol=Children&postcode=MK93DX
Once live, re-run the tests.
Please see card: 
https://trello.com/c/WcVTq2VV/212-cas-court-tribunal-finder-url-change
---
⚠️ **Update 31/03/2021**
FaCT team has fixed all the showstoppers found with their API (refer to ticket https://trello.com/c/Pu2yNQXa for more details) and it seems there will be no need to use the `old` CTF subdomain as that was a workaround in …
=> Replace Court Tribunal Finder endpoints with FaCT

app/presenters/summary/html_sections/nature_of_application.rb, app/views/steps/petition/orders/edit.html.erb, features/fixtures/files/nature_of_application.html, features/fixtures/files/nature_of_application_with_errors.html, spec/presenters/summary/html_sections/nature_of_application_spec.rb
Reverts ministryofjustice/c100-application#1178
We have a query with this so need to stop it getting deployed for now until it is resolved
=> Revert "RST-3299 Remove the option for 'deal with another option not listed'"

app/presenters/valid_payments_array.rb, spec/presenters/valid_payments_array_spec.rb
**JIRA**
[RST-3369](https://tools.hmcts.net/jira/browse/RST-3369)
To remove the ability for a user to pay the court fee by cheque or cash if submitting the application electronically
To remove the ability for a user to pay the court fee online if sending the application by post
=> RST 3369 Change payment type selection

Dockerfile
From recommendations here:
https://github.com/alpinelinux/docker-alpine/issues/181
https://github.com/anaynayak/aws-security-viz/commit/32930c8d4a6445ff89af1b2af9b85511dade0356
=> Update no longer supported ttf-ubuntu-font-family to ttf-freefont

.circleci/config.yml
Fix from here:
https://stackoverflow.com/questions/68243042/you-dont-have-write-permissions-for-the-usr-lib-ruby-gems-2-7-0-directory-alp
=> Upgrade docker version used to prevent permission error bug
